### ISSUE TITLE
Add `azuredevops_pipeline` Resource

### ISSUE THREAD

**Issue by juicybaba** [microsoft/terraform-provider-azuredevops#1002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

it would be nice to create pipeline based on a yml in a repo via terraform, it is annoying clicking few buttons around.
Ideally, set variable on the pipeline.

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/microsoft/azure-devops-go-api/tree/dev/azuredevops/pipelines

**Comment by Jolton** [comment]
You can already do this with the [azuredevops_build_definition](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/build_definition) resource

**Comment by juicybaba** [comment]
> You can already do this with the [azuredevops_build_definition](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/build_definition) resource

awesome! let me give it a shot.

**Comment by juicybaba** [comment]
[azuredevops_build_definition](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/build_definition) resource works perfectly, closing the feature request. @Jolton Thank you!!!
