### ISSUE TITLE
Is there any way that we can add the steps.checkout definition in the terraform script to create a pipeline

### ISSUE THREAD

**Issue by raguldevops** [microsoft/terraform-provider-azuredevops#1007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I tried to create a pipeline and unable to add the steps.checkout definition such below

checkout_submodules     = false
    fetch_depth             = "1"
    fetch_tags              = false
    git_lfs_support         = false
    label_sources           = "0"
    label_sources_format    = "\$(build.buildNumber)"
    skip_sync_source        = false

Kindly check and let me know

### New or Affected Resource(s)

* azuredevops_build_definition

### Potential Terraform Configuration

```hcl
resource "azuredevops_build_definition" "pipeline" {
  project_id = var.DEVOPS_PROJECT_ID
  name       = "${var.project}-${var.environment}"
  queue_status = enabled
  repository {
    repo_id                 = var.repo_id
    repo_type               = var.repo_type
    yml_path                = var.yml_path
    branch_name             = var.branch_name
    report_build_status     = true
  }
  }
```

### References

* #0000

**Comment by xuzhang3** [comment]
@raguldevops  you can add this configurations to the `yaml` file and use `azuredevops_build_definition` to create the pipeline based on the `yaml` file

**Comment by raguldevops** [comment]
Thanks for the suggesstions @xuzhang3 , working as expected
