### ISSUE TITLE
Unable to grant permission to all pipelines while creating the service connect for dockerregistry

### ISSUE THREAD

**Issue by raguldevops** [microsoft/terraform-provider-azuredevops#1008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to grant permission to all pipelines while creating the service connect for dockerregistry

### New or Affected Resource(s)

* azuredevops_serviceendpoint_dockerregistry

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_dockerregistry" "test_acr_SC" {
  project_id            = var.DEVOPS_PROJECT_ID
  service_endpoint_name = "SC-${var.project}${var.environment}"
  docker_registry       = "https://${azurerm_container_registry.acr.login_server}"
  docker_username       = azurerm_container_registry.acr.admin_username
  docker_password       = azurerm_container_registry.acr.admin_password
  registry_type         = "Others"
}
```

### References

* #0000

**Comment by xuzhang3** [comment]
@raguldevops  [azuredevops_pipeline_authorization](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization) can be used to to the  pipeline authorization

**Comment by raguldevops** [comment]
> @raguldevops [azuredevops_pipeline_authorization](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization) can be used to to the pipeline authorization

any sample code that i can use for the above mentioned terraform script.

**Comment by raguldevops** [comment]
@xuzhang3  if i create a service connection for docker registry manually then i can able to push the image from pipeline to acr without any issue , but if same created through terraform , i'm facing problem (auth issue) .

am i missing something in my above mentioned terraform script ?

**Comment by xuzhang3** [comment]
> > @raguldevops [azuredevops_pipeline_authorization](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization) can be used to to the pipeline authorization
> 
> any sample code that i can use for the above mentioned terraform script.

@raguldevops
Default access for all pipeline for the new service connections created by this provider will be disabled so you need update the pipeline access permission with `azuredevops_pipeline_authorization`
Allow all pipeline access:
```hcl
resource "azuredevops_pipeline_authorization" "example" {
  project_id  = azuredevops_project.example.id
  resource_id = azuredevops_serviceendpoint_dockerregistry.example.id
  type        = "endpoint"
}
```

Allow  specific pipe access:
```hcl
resource "azuredevops_pipeline_authorization" "example" {
  project_id  = azuredevops_project.example.id
  resource_id = azuredevops_serviceendpoint_dockerregistry.example.id
  type        = "endpoint"
  pipeline_id = azuredevops_build_definition.example.id

}
```

**Comment by raguldevops** [comment]
Thanks for the suggestions @xuzhang3 . code working as expected.
