### ISSUE TITLE
support for user/system managed identity (an alternative of service principal) when used in a self-hosted agent

### ISSUE THREAD

**Issue by byunru** [microsoft/terraform-provider-azuredevops#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_serviceendpoint_azurerm
azuredevops_serviceendpoint_dockerregistry
azuredevops_serviceendpoint_kubernetes

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @byunru  Can you provide more details on your requirement? I don't fully understand what you mean.

**Comment by byunru** [comment]
> Hi @byunru Can you provide more details on your requirement? I don't fully understand what you mean.
Managed identities are service principals of a special type without secrets.
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

**Comment by matt-FFFFFF** [comment]
I'd like this too and have done some digging:

@xuzhang3 FYI

In terms of the AzDo API looks like we need support for the `ManagedServiceIdentity` authentication scheme when creating the service endpoint.

We currently only support `ServicePrincipal` authentication scheme:
https://github.com/microsoft/terraform-provider-azuredevops/blob/abee538ead915f3e8b802c910ae8ca396c88ffda/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go#L75

Here's an extract from the API `/_apis/serviceendpoint/types?api-version=6.1-preview.1` method describing the ManagedServiceIdentity scheme, with the required inputs... only the tenantId is required.

```json
{
"authenticationSchemes":
  [
    {
      "inputDescriptors": [
        {
          "id": "tenantid",
          "name": "Tenant Id",
          "description": " Tenant Id of the subscription for which the MSI VM has access to",
          "type": null,
          "properties": null,
          "inputMode": "textBox",
          "isConfidential": false,
          "useInDefaultDescription": false,
          "groupName": "AuthenticationParameter",
          "valueHint": null,
          "validation": {
            "dataType": "guid",
            "isRequired": true
          }
        }
      ],
      "scheme": "ManagedServiceIdentity",
      "displayName": "Managed Identity Authentication",
      "requiresOAuth2Configuration": true,
      "dataSourceBindings": [],
      "authorizationHeaders": [],
      "clientCertificates": [],
      "properties": {
        "isVerifiable": "False"
      }
    }
  ]
}
```

**Comment by matt-FFFFFF** [comment]
Example TF config:

```terraform
resource "azuredevops_project" "project" {
  name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id                = azuredevops_project.project.id
  service_endpoint_name     = "Sample AzureRM with MSI"
  description = "Managed by Terraform"
  authentication_scheme = "ManagedServiceIdentity"
  azurerm_tenantid      = "00000000-0000-0000-0000-000000000000"
}
```

**Comment by matt-FFFFFF** [comment]
Example TF config:

```terraform
resource "azuredevops_project" "project" {
  name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id                = azuredevops_project.project.id
  service_endpoint_name     = "Sample AzureRM using managed service identity"
  description               = "Managed by Terraform"
  azurerm_spn_tenantid      = "00000000-0000-0000-0000-000000000000"
  authentication_scheme     = "ManagedServiceIdentity"
}
```

**Comment by xuzhang3** [comment]
Thank you  @matt-FFFFFF , is the `ManagedServiceIdentity` you mentioned is?
![image](https://user-images.githubusercontent.com/57888764/101140702-4b15c900-364e-11eb-8a86-612914fbea93.png)

If we are on the same thread,  I think only tenant ID is not enough here.

**Comment by matt-FFFFFF** [comment]
Hi @xuzhang3

Yes, that's the thing.

The `tenantId` is the only property required for the authentication scheme. But, you're right in that depending on scope, we also need either: `subscriptionId` and `subscriptionName`. OR `managementGroupId` and `managementGroupName`

Would be great if we could include the option to grant access to all pipelines too:

```terraform
resource "azuredevops_serviceendpoint_azurerm" "endpointazuresubscription" {
  project_id                    = azuredevops_project.project.id
  service_endpoint_name         = "Sample AzureRM using managed service identity with subscription scope"
  description                   = "Managed by Terraform"
  azurerm_tenantid              = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_id       = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_name     = "MySubscription"
  authentication_scheme         = "ManagedServiceIdentity"
  grant_access_to_all_pipelines = true
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazuremg" {
  project_id                    = azuredevops_project.project.id
  service_endpoint_name         = "Sample AzureRM using managed service identity with management group scope"
  description                   = "Managed by Terraform"
  azurerm_tenantid              = "00000000-0000-0000-0000-000000000000"
  azurerm_management_group_id   = "mymgid"
  azurerm_management_group_name = "My MG Name"
  authentication_scheme         = "ManagedServiceIdentity"
  grant_access_to_all_pipelines = true
}
```

**Comment by xuzhang3** [comment]
Hi @matt-FFFFFF  We already have `azuredevops_resource_authorization` can be used to grant resource permissions.
 https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/resource_authorization

**Comment by jaredfholgate** [comment]
@xuzhang3 The ability to create a Service Endpoint with Managed Identity would really help as would federated credentials, which is currently in preview. I think for Managed Identity we would also need to be able to supply a clientID when using a User Assigned Managed Identity, so the secret would need to be optional if using the same credentials block.

**Comment by xuzhang3** [comment]
Closing this issue #818
