### ISSUE TITLE
Cannot grant pipeline authorization for cross-project repository

### ISSUE THREAD

**Issue by Mikel-Landa** [microsoft/terraform-provider-azuredevops#1010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Azure Devops: 1.0.1
Terraform: v1.5.5

### Affected Resource(s)

* `azuredevops_pipeline_authorization`

### Terraform Configuration Files

```hcl
resource "azuredevops_pipeline_authorization" "gitops_repository" {
  project_id  = var.project_id
  resource_id = "${var.extra_projects["GitOps"].id}.${data.azuredevops_git_repository.gitops.id}"
  type        = "repository"
  pipeline_id = azuredevops_build_definition.this.id
}
```

### Actual Behavior
```
Error:  creating authorized resource: Resource id exceeds maximum length of 100.

  with azuredevops_pipeline_authorization.gitops_repository,
  on main.tf line 74, in resource "azuredevops_pipeline_authorization" "gitops_repository":
  74: resource "azuredevops_pipeline_authorization" "gitops_repository" {
```

### Steps to Reproduce

Try to reference a cross-project repository in authorization

What I see happening when I grant permission through the UI is a call to the endpoint with a body type of PipelinePermissions[], meanwhile I believe the terraform resource is calling with the resource type which should be the one throwing the error, as with the former, the resourceId goes in the url and not in the body.

I've looked at the definitions here: https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.1&tabs=HTTP#request-body

**Comment by xuzhang3** [comment]
@Mikel-Landa   this feature has been supported by #973 , will be available in the next version.

**Comment by Mikel-Landa** [comment]
Ok, great. I'll close the issue then.
Thanks.
