### ISSUE TITLE
Unable to change default_branch of azuredevops_git_repository that was originally Uninitialized

### ISSUE THREAD

**Issue by carlosjourdan** [microsoft/terraform-provider-azuredevops#1016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.7.5
on windows_amd64
\+ provider registry.terraform.io/microsoft/azuredevops v1.0.1

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
#First pass creates unitialized repository
resource "azuredevops_project" "example" {
  name               = "Example Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_git_repository" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Empty Git Repository"
  initialization {
    init_type = "Uninitialized"
  }

  lifecycle {
    ignore_changes = [
      # Ignore changes to initialization to support importing existing repositories
      # Given that a repo now exists, either imported into terraform state or created by terraform,
      # we don't care for the configuration of initialization against the existing resource
      initialization,
    ]
  }
}
```

```hcl
#Second pass, after manually initializing a repository and creating a branch named "default", tries to set it as the default branch

resource "azuredevops_project" "example" {
  name               = "Example Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_git_repository" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Empty Git Repository"
  initialization {
    init_type = "Uninitialized"
  }

  default_branch = "refs/heads/default"

  lifecycle {
    ignore_changes = [
      # Ignore changes to initialization to support importing existing repositories
      # Given that a repo now exists, either imported into terraform state or created by terraform,
      # we don't care for the configuration of initialization against the existing resource
      initialization,
    ]
  }
}
```

### Expected Behavior

The repository should have set the "default_branch" property to "ref/heads/default" after the second apply

### Actual Behavior

Error: Error converting terraform data model to AzDO project reference:  Repository 'initialization.init_type = Uninitialized', there will be no branches, 'default_branch' cannt not be set.

### Steps to Reproduce

1. `terraform apply` without the default_branch property, with init_type = "Uninitialized"
2.  manually initialize the repo and create a branch named 'default'
3.  `terraform apply` after adding the default_branch property

**Comment by xuzhang3** [comment]
@carlosjourdan  this is a tech debt that the initialization of the repo is hard coded in `azuredevops_git_repository`.  This constraint is used to prevent the default branch from being set when the repo is not initialized. Can you initialize the repository with a different initial type?

**Comment by carlosjourdan** [comment]
No. This repo is in a production environment where all the access  is done
through terraform, we have no access as project owners. If I try to change
the initialization type through the code, terraform plan says that the
resource needs to be replaced, which is unacceptable because it would
delete the entire git history.

**Comment by xuzhang3** [comment]
@carlosjourdan  I see, the second apply should not block update, this is different from the create.
