### ISSUE TITLE
Implement a Terraform data source to lookup users

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To manage permissions (ACLs) for the various security namespaces in DevOps it's vital to have a Terraform data source to lookup existing user objects.

### New or Affected Resource(s)

* data.azuredevops_user

### Potential Terraform Configuration

```hcl

resource "azuredevops_project" "main_project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  enable_tfvc        = False
  work_item_template = "Agile"
}

data "azuredevops_user" "lookup-user" {
   # Exports: id, descriptor, project_id ...
   user_name  = "jmarks@vscsi.us" # mapped to: principalName
   origin     = "aad" # Optional (!)
}

```

### References

* #84 
* https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/list?view=azure-devops-rest-5.1
* [ListUsers](https://github.com/microsoft/azure-devops-go-api/blob/b909a25cb2ee1dc19794e5e8cbdec47dbc139c82/azuredevops/graph/client.go#L63)

**Comment by tiwood** [comment]
I'm going to implement this functionality.

**Comment by tmeckel** [comment]
Implementation done in branch

https://github.com/tiwood/terraform-provider-azuredevops/tree/ds_r_user/azuredevops

**Comment by nmiodice** [comment]
I believe this is merged
