### ISSUE TITLE
Implement a Terraform data source to lookup Git repositories

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider currently only provides a way to provision Azure Git Repos, but does not allow us to reference a pre-existing repository. Having a data source for Git Repos will allow people to leverage other resources, like build definitions and repository permissions, without needing to create a new repository.

### New or Affected Resource(s)

* data.azuredevops_git_repository

### Potential Terraform Configuration

```hcl

resource "azuredevops_project" "main_project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  enable_tfvc        = False
  work_item_template = "Agile"
}

data azuredevops_git_repository "lookup-repo" {
    project_id = azuredevops_project.main_project.id
    name       = "Test Lookup Repo"
}

```

### Acceptance Criteria
 - [ ] A data source exists that allows for query of an Azure Git Repos based on the following fields:
   - [ ] `project_id` - ID of project in which the repository exists
   - [ ] `name` - name of repository
 - [ ] The `computed` fields of the resource should match the resource implementation of [Azure Git Repos](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_azure_git_repository.go). There may be an opportunity to re-use the whole resource schema!
 - [ ] Data source is validated with unit tests
 - [ ] Data source is validated with acceptance tests
 - [ ] Documentation is added in the client-facing docs 

### References

* #84 
* [Repositories - List](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/repositories/list?view=azure-devops-rest-5.1)

**Comment by nmiodice** [comment]
This will most likely be trivial after the implementation of https://github.com/microsoft/terraform-provider-azuredevops/issues/94
