### ISSUE TITLE
Azure DevOps Wiki Page

### ISSUE THREAD

**Issue by chienfuchen32** [microsoft/terraform-provider-azuredevops#1062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to design a terraform `resource` / `data` for azure DevOps wiki page like.
![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/12825790/09c061ba-7764-4487-8c38-1a023d7f8b94)

### New or Affected Resource(s)

* azuredevops_wiki_page

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "project" {
  name        = "project"
  description = "Project Description"
}

resource "azuredevops_wiki" "project_wiki" {
  name = "project.wiki"
  project_id = azuredevops_project.project.id
  type = "projectWiki"
}

resource "azuredevops_wiki_page" "page" {
  project_id = azuredevops_project.project.id
  wiki_id = azuredevops_wiki.project_wiki.id
  path = "/page"
  content = "test content"
}
```

##### Azure DevOps Wiki page documentation
* [Add and edit wiki pages](https://learn.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops&tabs=browser)
* Is [page comment](https://learn.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops), [page attachment](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops)
* should I design [wiki page git version control 1](https://learn.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser), [2](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-view-history?view=azure-devops) for this first feature request? [Go SDK Wiki](https://github.com/microsoft/azure-devops-go-api/blob/azuredevops/v7.1.0/azuredevops/wiki/models.go#L70), [Go SDK Wiki Page](https://github.com/microsoft/azure-devops-go-api/blob/azuredevops/v7.1.0/azuredevops/wiki/client.go#L205) [Go SDK git](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/v7/git/models.go#L2293), or I could simply implement page without version control at this moment as HCL described above and [az cli](https://learn.microsoft.com/en-us/azure/devops/project/wiki/manage-wikis?view=azure-devops#create-a-wiki-page)? Thanks.

* Related to Azure DevOps Wiki resource #702, #1032

**Comment by chienfuchen32** [comment]
These are some use case for the main purpose.
```tf
resource "azuredevops_project" "project" {
  name        = "project"
  description = "Project Description"
}

resource "azuredevops_wiki" "project_wiki" {
  name = "project.wiki"
  project_id = azuredevops_project.project.id
  type = "projectWiki"
}

locals {
  page = toset([
        "/page1",
        "/page2",
  ])
}
resource "azuredevops_wiki_page" "page" {
  for_each = local.page
  project_id = azuredevops_project.project.id
  wiki_id = azuredevops_wiki.project_wiki.id
  path = each.key 
  content = data.local_file.file_example.content
}

data "local_file" "file_example" {
  filename = "${path.module}/example.md"
}
```

**Comment by cveld** [comment]
I would like to create a page in the default wiki repository. I was expecting a data resource, but there doesn't seem to be one. How can I create a wiki page in an existing wiki repository?

**Comment by chienfuchen32** [comment]
Hi @cveld,

The wiki data resource is not implemented yet, I'm assuming it can be design as follow:
https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/git/data_git_repositories.go
