### ISSUE TITLE
azuredevops_team - Team Name update or Team Description Update never completing

### ISSUE THREAD

**Issue by Sharmanand** [microsoft/terraform-provider-azuredevops#1074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_team`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azuredevops_team" "this" {
  project_id  = "project-id-goes-here"
  name        = "test"
  description = "test project"
}

apply above change

change the code 
resource "azuredevops_team" "this" {
  project_id  = "project-id-goes-here"
  name        = "test"
  description = "test project again change"
}
```

### Expected Behavior
Team description should change to - test project again change

### Actual Behavior
team name and team description both blank

### Steps to Reproduce
go to azure devops portal, you will notice name and description disappear

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@Sharmanand cannot reproduce this error. Can you share your logs?

**Comment by Sharmanand** [comment]
@xuzhang3 surprise, did you tried changing the name or description of teams and terraform apply completing for you?

i dont have any logs to share its just keep saying applying modifying...

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/9371425/7460eb59-b7f5-4b52-a167-a0b0c7da8d75)

**Comment by xuzhang3** [comment]
yes, I can update both `name` and `description` at the same time.
![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/57888764/c11ae3e2-b483-4314-947a-aaa11436920a)

**Comment by xuzhang3** [comment]
@Sharmanand   you can enable the log with `export TF_LOG=TRACE` and `export TF_LOG_PATH=<log file>`
