### ISSUE TITLE
data  azuredevops_group export attribute ID field having group descriptor value

### ISSUE THREAD

**Issue by Sharmanand** [microsoft/terraform-provider-azuredevops#1077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "azuredevops_project" "example" {
  name = "Example Project"
}
```

### Panic Output

[id](https://registry.terraform.io/providers/microsoft/azuredevops/1.1.1/docs/data-sources/group#id) - The ID for this resource is the group descriptor. See below.

### Expected Behavior

it should export guid value of group id same as data source: azuredevops_groups
### Actual Behavior
currently field returns [id](https://registry.terraform.io/providers/microsoft/azuredevops/1.1.1/docs/data-sources/group#id) - The ID for this resource is the group descriptor

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@Sharmanand  the ID in `azuredevops_group`  is a randomly generated UUId, it has no meaning, it's just an ID. The descriptor can be changed to UUID but need another API call. 
https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/storage-keys/get?view=azure-devops-rest-7.1&tabs=HTTP

**Comment by Sharmanand** [comment]
@xuzhang3 it do help in lots of use case e.g. [azuredevops_branch_policy_auto_reviewers](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/branch_policy_auto_reviewers) for assigning [auto_reviewer_ids](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/branch_policy_auto_reviewers#auto_reviewer_ids)

moreover if you check [Data Source: azuredevops_groups](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/groups) it have correct export [id](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/groups#id) field. however you check [Data Source: azuredevops_group](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/group) it has duplicate value in both [id](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/group#id) & [descriptor](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/group#descriptor) descriptor.

we need to have consistency in [Data Source: azuredevops_groups](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/groups) & [Data Source: azuredevops_group](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/group) for id field

**Comment by xuzhang3** [comment]
Adding the group ID will add a  new property `group_id` to reduce the impact to existing resources, force changing the ID values will cause the resource recreated.

**Comment by Sharmanand** [comment]
hi @xuzhang3, is this new field available in upcoming release?

**Comment by xuzhang3** [comment]
@Sharmanand  yes, a new property will be added.

**Comment by Sharmanand** [comment]
@xuzhang3 any timeline ths become available?

**Comment by xuzhang3** [comment]
@Sharmanand  `v1.3.0` has been released. https://registry.terraform.io/providers/microsoft/azuredevops/1.3.0

**Comment by Sharmanand** [comment]
hi @xuzhang3 when 1.3.0 version avaialble on https://releases.hashicorp.com/terraform-provider-azuredevops/ ?

**Comment by xuzhang3** [comment]
@Sharmanand `v1.3.0` has been released https://registry.terraform.io/providers/microsoft/azuredevops/latest. Terraform registry will sync the latest release from GH, not sure why it not syncing.

> hi @xuzhang3 when 1.3.0 version avaialble on https://releases.hashicorp.com/terraform-provider-azuredevops/ ?
