### ISSUE TITLE
Implement Terraform data source to lookup projects

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To manage permissions (ACLs) for the various security namespaces in DevOps it's vital to have a Terraform data source to lookup existing projects.

### New or Affected Resource(s)

* data.azuredevops_project

### Potential Terraform Configuration

```hcl

data "azuredevops_project" "lookup_project" {
  project_name       = "Test Project"
}

```

### References

* #84 
* [Projects - List](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.1)
* [Projects - Get Project Properties](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/get%20project%20properties?view=azure-devops-rest-5.1)

**Comment by codevbus** [comment]
@nmiodice - I'd like to take this.

**Comment by nmiodice** [comment]
@codevbus Thank you! Post a PR when its ready. Please be sure to read out [contributing docs](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/docs/contributing.md) to get started.

**Comment by nmiodice** [comment]
@codevbus do you have an ETA? If you are not actively working on it I suggest we remove you as the asignee until you are able to implement, in case somebody else has bandwidth to pick it up.

**Comment by codevbus** [comment]
@nmiodice - Sorry about that! I should have something out by EoW. Apologies for the delay!

**Comment by tmeckel** [comment]
@codevbus I would really need this implementation to test the resource for groups #103 . When will the data source be ready?

**Comment by codevbus** [comment]
> @codevbus I would really need this implementation to test the resource for groups #103 . When will the data source be ready?

Apologies on this. I've finally got some clean runway to work on this again. Would EoD Wednesday be ok to deliver a finished PR?

**Comment by tmeckel** [comment]
> @codevbus I would really need this implementation to test the resource for groups #103 . When will the data source be ready?
> 
> @tmeckel @nmiodice
> Apologies on this. I've finally got some clean runway to work on this again. Would EoD Wednesday be ok to deliver a finished PR?

Hi @codevbus! Sure! Great! I was just asking, becuase I'm just in the middle of implementing the `azuredevops_group` resource #205  and it would be great having the ability to lookup projects via a data source while designing tests and examples.

**Comment by codevbus** [comment]
@tmeckel @nmiodice  - I'm afraid I'm blocking too long on this without moving the needle. 

The PR isn't where I'd want it to be... IRL-stuff is really killing my free time right now. Really sorry to have dragged this on so long but I think it's best if I hand this off.

My apologies, I'll take this as a lesson learned to be more honest with myself about time available. I appreciate your patience and hopefully I'll be able to swing back by and try again down the road if you'll have me.

**Comment by tmeckel** [comment]
@codevbus Sorry to hear that! As far as I know there's no real feasible way that I can easily take over your PR because it's bound to your branch and forked version of the repository. @nmiodice perhaps you might correct me :wink:

So my proposal would be that I copy your actual work from branch `ds-108` into our fork to give you credit on the work you did so far. I will file a new PR from our fork for this and you or @nmiodice can then close the PR you opened.

Let me know what you think.

Mentioning @tiwood for reference here.

**Comment by tmeckel** [comment]
@codevbus  I copied over you work already.

https://github.com/tiwood/terraform-provider-azuredevops/commits/ds_projects

**Comment by nmiodice** [comment]
Great! I'll close the other PR

**Comment by codevbus** [comment]
@tmeckel @nmiodice - Thanks guys. Really sorry to have blocked so long on this.

**Comment by nmiodice** [comment]
I believe this is merged
