### ISSUE TITLE
azuredevops_serviceendpoint_kubernetes crash if the parameters are empty

### ISSUE THREAD

**Issue by diegolagospagopa** [microsoft/terraform-provider-azuredevops#1084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- terraform: 1.7.3
- azure devops: 1.1.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_kubernetes`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_kubernetes" "aks_prod" {
  depends_on            = [data.azuredevops_project.project]
  project_id            = data.azuredevops_project.project.id
  service_endpoint_name = local.srv_endpoint_name_aks_prod
  apiserver_url         = module.printit_prod_secrets.values["pagopa-p-itn-prod-aks-apiserver-url"].value
  authorization_type    = "ServiceAccount"
  service_account {
    # base64 values
    token   = module.printit_prod_secrets.values["pagopa-p-itn-prod-aks-azure-devops-sa-token"].value
    ca_cert = module.printit_prod_secrets.values["pagopa-p-itn-prod-aks-azure-devops-sa-cacrt"].value
  }
}
```

### Panic Output

[`crash.log`](https://gist.github.com/diegolagospagopa/7caebcab010bf346165ef338b1fd5a99)

### Expected Behavior

Show an error message related to the fact that the service account fields are empty

### Actual Behavior

crash badly 

### Steps to Reproduce

1. create a service connection aks, with service account token and crt but the fields must be empty
2. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@diegolagospagopa   can you check the module values `module.printit_prod_secrets.values` , if this value empty then ADO would take the empty string as the input which is invalid

**Comment by diegolagospagopa** [comment]
> @diegolagospagopa can you check the module values `module.printit_prod_secrets.values` , if this value empty then ADO would take the empty string as the input which is invalid

Hi, I can confirm that the value is empty, what I wanted to say in the issue that I was not clear is that the provider does not handle the error indicating that the field is empty and cannot work correctly.

But instead it throws a panic error, which is difficult to understand.
It would be very useful to have a more speaking and managed error
