### ISSUE TITLE
`azuredevops_git_repository_file` -  error (on state refresh): Branch does not exist in the repository.

### ISSUE THREAD

**Issue by baterja** [microsoft/terraform-provider-azuredevops#1097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.9.0
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v1.1.1

### Affected Resource(s)

* `azuredevops_git_repository_file`

### Terraform Configuration Files

```hcl
# modified example to remove unnecessary complications

resource "azuredevops_git_repository_branch" "pr_template" {
  repository_id = <omitted>
  name          = "feature/PullRequestTemplate"
  ref_branch    = "refs/heads/develop"
}

resource "azuredevops_git_repository_file" "pr_template" {
  repository_id  = <omitted>
  file           = ".azuredevops/pull_request_template.md"
  content        = file("${path.module}/pull_request_template.md")
  branch         = "refs/heads/${azuredevops_git_repository_branch.pr_template.name}"
  commit_message = "Updated PR template"
}
```

### Expected Behavior

The resource should be able to handle the fact that the branch on which the file was created no longer exists when refreshing its state. I.e. by being able to refer to the branch not by its name but by pointing to the resource responsible for the branch (`azuredevops_git_repository_branch`).

### Actual Behavior

`Error: Branch "feature/PullRequestTemplate" does not exist in the <omitted> repository.`

### Steps to Reproduce

1. `terraform apply`
2. Remove the branch `feature/PullRequestTemplate`.
3. `terraform apply` again

**Comment by baterja** [comment]
Thanks @xuzhang3! Could you please release a new provider version with the fix, or is it going to be a part of a larger update batch?

**Comment by xuzhang3** [comment]
@baterja working on it. New version will coming soon.

**Comment by xuzhang3** [comment]
> Thanks @xuzhang3! Could you please release a new provider version with the fix, or is it going to be a part of a larger update batch?

@baterja Lates release `v1.2.0` https://registry.terraform.io/providers/microsoft/azuredevops/1.2.0
