### ISSUE TITLE
azuredevops_serviceendpoint_azurecr with ServicePrincipal auth is broken in v1.2.0

### ISSUE THREAD

**Issue by paleg** [microsoft/terraform-provider-azuredevops#1121]
### Terraform (and Azure DevOps Provider) Version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/microsoft/azuredevops v1.2.0

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurecr`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_azurecr" "this" {
  project_id                = "some-project"
  service_endpoint_name     = "some-name"
  resource_group            = "some-rg-name"
  azurecr_spn_tenantid      = data.azurerm_subscription.current.tenant_id
  azurecr_name              = "some-name"
  azurecr_subscription_id   = data.azurerm_subscription.current.subscription_id
  azurecr_subscription_name = data.azurerm_subscription.current.display_name
}
```

### Expected Behavior

The code above works perfectly fine with `registry.terraform.io/microsoft/azuredevops` v1.1.1, but fails with v1.2.0 with no other changes.

### Actual Behavior

with v1.2.0, apply shows changes which should not be there and fails to apply with the error:
```
  # azuredevops_serviceendpoint_azurecr.this will be updated in-place
  ~ resource "azuredevops_serviceendpoint_azurecr" "this" {
      + azurecr_spn_tenantid                   = "yyyyyy-yy-yy-yyy-yyyyyy"
        id                                     = "xxxxxxxx-xxx-x-x-xxxxx"
        # (14 unchanged attributes hidden)
    }

│ Error: Error updating service endpoint in Azure DevOps: Service connection URL change requires all the confidential parameters to be provided. Please retry operation by providing value for parameter: Service principal key.
```
### Steps to Reproduce

Create `azuredevops_serviceendpoint_azurecr` with ServicePrincipal auth using azuredevops v1.1.1 and then just update azuredevops to 1.2.0 and do `terraform apply`.

**Comment by askingcat** [comment]
I encountered this problem as well and did some debugging and git research.

The concrete bug is already fixed in the repository. @xuzhang3 fixed this one day after the release of 1.2.0 with 206c00b97cf2314ac28a0d3eb1c8d22561682d88.

The problem was that the capitalization of a parameter changed in #1105 and sometimes `tenantid` and sometimes `tenantId` was used.

The commit mentioned above fixes this for automatically created Service Principals. There are still some different casings for workload identity federation, however, so they might still have a problem.

@xuzhang3 Could you please have a look at it and consider releasing a patch?

**Comment by TheGeniesis** [comment]
I face the same issue. As a temporary workaround (I have other than azuredevops changes to approve) I added ignore_changes for this resource:

Terraform plan:
```text
  # azuredevops_serviceendpoint_azurecr.my_resource will be updated in-place
  ~ resource "azuredevops_serviceendpoint_azurecr" "my_resource" {
      + azurecr_spn_tenantid                   = "<tenant_id"
        id                                     = "<id>"
        # (14 unchanged attributes hidden)
    }
```

My change to skip the update:

```tf
resource "azuredevops_serviceendpoint_azurecr" "my_resource" {
  # ...
  lifecycle {
    ignore_changes = [
      azurecr_spn_tenantid
    ]
  }
}
```

**Comment by xuzhang3** [comment]
Case issue between `tenantid` and `tenantId`

**Comment by xuzhang3** [comment]
@askingcat  real  tenant ID returned by service is `tenatnId` which `v1.2.0` it was treated as `tenatnid`. That's why you got a diff in `v1.2.0` because tenant ID not found in the response but the TF has this configuration.
