### ISSUE TITLE
azuredevops_serviceendpoint_azurecr resource with WorkloadIdentityFederation authentication cannot be imported in v1.2.0

### ISSUE THREAD

**Issue by 04n0** [microsoft/terraform-provider-azuredevops#1124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.9.4
+ provider registry.terraform.io/microsoft/azuredevops  v1.2.0

(also tested againt latest `main` branch of `azuredevops` provider with `tenantId` fix #1115  )

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurecr `

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_azurecr" "acrnonprod" {
  project_id                             = data.terraform_remote_state.projectxyz.outputs.project_id
  resource_group                         = "acrnonprod"
  service_endpoint_name                  = "test-acr-with-wif"
  service_endpoint_authentication_scheme = "WorkloadIdentityFederation"
  azurecr_spn_tenantid                   = data.azurerm_subscription.primary.tenant_id
  azurecr_name                           = "acrnonprod"
  azurecr_subscription_id                = "abcd2348-fake-fake-fake-13337bf00000"
  azurecr_subscription_name              = "NONPROD"
  credentials {
    serviceprincipalid = "67896d9c-fake-fake-fake-fffdd77ff66f"
  }
}

import {
  to = azuredevops_serviceendpoint_azurecr.acrnonprod
  id = "34567e0b-fake-fake-fake-912ebba6dd84/1234682f-fake-fake-fake-8f16ba301402"
}
```

### Panic Output

```
panic: interface conversion: interface {} is nil, not string

goroutine 93 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointAzureCR(0xf4494bad77747ff6?, 0xc000764750, {0xc0005aa0f0?, 0xc0005b44c0?})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go:330 +0xa5a
```

Full output - https://gist.github.com/04n0/3bb8b378b55a5a284a1d91a63bd8b5a7

### Expected Behavior

When importing `azuredevops_serviceendpoint_azurecr` resource with `WorkloadIdentityFederation` authentication scheme, the Service Principal credential (`serviceprincipalkey`) [should not be read/expected](https://github.com/microsoft/terraform-provider-azuredevops/blob/611211bc3fcd6a2a684ec66218e0ed797793d889/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go#L330), just the ID (`serviceprincipalid`).

### Actual Behavior

Service Principal credential (`serviceprincipalkey`) is read even if the authentication scheme is not `ServicePrincipal` causing the provider to crash.

### Steps to Reproduce

1. Create Service Connection to Azure Container Registry with Workload Identity Federation
2. Try to import it using `import {}` or via CLI

**Comment by xuzhang3** [comment]
```log
=== RUN   TestAccServiceEndpointAzureCR_DataSource
=== PAUSE TestAccServiceEndpointAzureCR_DataSource
=== RUN   TestAccServiceEndpointAzureCR_Spn_Basic
=== PAUSE TestAccServiceEndpointAzureCR_Spn_Basic
=== RUN   TestAccServiceEndpointAzureCR_Spn_Update
=== PAUSE TestAccServiceEndpointAzureCR_Spn_Update
=== CONT  TestAccServiceEndpointAzureCR_DataSource
=== CONT  TestAccServiceEndpointAzureCR_Spn_Update
=== CONT  TestAccServiceEndpointAzureCR_Spn_Basic
--- PASS: TestAccServiceEndpointAzureCR_DataSource (90.04s)
--- PASS: TestAccServiceEndpointAzureCR_Spn_Basic (92.58s)
--- PASS: TestAccServiceEndpointAzureCR_Spn_Update (142.12s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        142.643s
```
