### ISSUE TITLE
Terraform - set Repo Policies

### ISSUE THREAD

**Issue by andrefcpimentel2** [microsoft/terraform-provider-azuredevops#113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The provider does not implement the following Repository Policies:
* Maximum path length
* Maximum file size

### New or Affected Resource(s)

* azuredevops_git_repository

### Potential Terraform Configuration

```hcl
resource azuredevops_branch_policy_file_validation {
maximum_path_length = 248

maximum_file_size = "2mb"
}
```

### References

* #0000

**Comment by racdev** [comment]
We would also like the "File path validation" policy settings to be implemented by the provider.

**Comment by racdev** [comment]
@xuzhang3 - just noticed the new azuredevops_repository_policy_file_path_pattern resource in the latest release, thanks for that.

However, our requirement is to apply the policy at project level (i.e. the "All Repositories" policies screen in the UI), but that doesnt look to be an option in the new resource (as repo is required)?

**Comment by xuzhang3** [comment]
@racdev The implemented policies are based on repository and there are  4 repository level policies not implemented. The project level policy not covered yet.

**Comment by racdev** [comment]
@xuzhang3 do you want a separate issue raising for the project level policies?

**Comment by xuzhang3** [comment]
@racdev   feel free to open another feature requirement issue

**Comment by xuzhang3** [comment]
Close this issue by #436
