### ISSUE TITLE
Support project build in debug mode

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/terraform-provider-azuredevops#113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For the debug purpose, we should have a switch to add `-gcflags="all=-N -l"` to go build. It enables us to put break points and see variables in case you do debugging on terraform when we use VSCode. I know how to do it, however, it might be better to create a new issue then go implement it. 

### Acceptance Criteria

- [ ] Existing `build.sh` script accepts command line arguments
- [ ] A new script, possibly called `build-debug.sh`, exists and calls `./scripts/build.sh` while passing these arguments: `-gcflags="all=-N -l"`

### References

https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code

**Comment by nmiodice** [comment]
Should we have a new debug-build script that uses those flags so that the "production" build uses compiler optimizations?

**Comment by TsuyoshiUshio** [comment]
It think it is a good solution!

**Comment by nmiodice** [comment]
Closed in PR #233
