### ISSUE TITLE
Provider wants to change `azuredevops_build_folder` `path` when importing

### ISSUE THREAD

**Issue by camilo-s** [microsoft/terraform-provider-azuredevops#1137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.9.4
on linux_amd64

Installed microsoft/azuredevops v1.2.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
```

### Affected Resource(s)

* `azuredevops_build_folder`

### Terraform Configuration Files

```hcl
# root module

variable "ado_project_name" {
  type        = string
}

variable "product_id" {
  type = string
}

data "azuredevops_project" "this" {
  name = var.ado_project_name
}

module "devops" {
  source = "../modules/devops"

  project_id                       = data.azuredevops_project.this.id
  product_id                       = var.product_id
}

import {
  id       = "${var.ado_project_name}/\\${var.product_id}"
  to       = module.devops.azuredevops_build_folder.this
}

import {
  id       = "${var.ado_project_name}/2160"
  to       = module.devops.azuredevops_build_definition.this["dbx"]
}

import {
  id       = "${var.ado_project_name}/2161"
  to       = module.devops.azuredevops_build_definition.this["release"]
}

# module devops

resource "azuredevops_build_folder" "this" {
  project_id = var.project_id
  path       = "\\${var.product_id}"
}

```

### Debug Output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:


  # module.devops.azuredevops_build_folder.this[0] will be updated in-place
  # (imported from "Project Name/\product-id")
  ~ resource "azuredevops_build_folder" "this" {
        id         = "\\product-id"
      ~ path       = "\\" -> "\\product-id"
        project_id = "<REDACTED>"
    }

Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

The provider correctly reads the path of the folder to be imported and is able to import it without changes to the resource, since its configuration coincides with that in the code (especially the `path` attribute)

### Actual Behavior

The provider incorrectly reads the existing folder's `path` attribute as `\\` and therefore plans to change it to `\\product-id`. I do get the folder with the correct attribute value `"path": "\\product-id"` in the response to `az pipelines folder list`

### Steps to Reproduce

1. `terraform apply`

**Comment by camilo-s** [comment]
Hello @xuzhang3, any idea when this bug fix might get released?

**Comment by xuzhang3** [comment]
@camilo-s `v1.3.0` has been released. https://registry.terraform.io/providers/microsoft/azuredevops/1.3.0
