### ISSUE TITLE
`azuredevops_git_repository` - Support enabled/disable repository

### ISSUE THREAD

**Issue by camilo-s** [microsoft/terraform-provider-azuredevops#1138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to fully manage a repository's lifecycle via Terraform, it would be good to be able to manage it's disabled status via an attribute `is_disabled`, set to false by default, mapping to the corresponding `isDisable` repository attribute in the [REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/repositories/update?view=azure-devops-rest-7.0&tabs=HTTP#disable-repository). Currently this can only be embedded in a Terraform workflow using `local-exec` providers for manually sending API requests (note that `az repos` doesn't expose this functionality either).

### New or Affected Resource(s)

* [azuredevops_git_repository](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository)

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "example" {
  name               = "Example Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_git_repository" "example" {
  project_id  = azuredevops_project.example.id
  name        = "Example Empty Git Repository"
  is_disabled = true # false by default
  initialization {
    init_type = "Clean"
  }
}
```

**Comment by xuzhang3** [comment]
@camilo-s   `disabled` already supported: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository#disabled

**Comment by camilo-s** [comment]
Thanks for your reply @xuzhang3. My understanding is that currently `disabled` is just a _computed attribute_ of `azuredevops_git_repository` as opposed to an _argument_, so the provider fetches the `isDisabled` value of the repository but doesn't allow doing any modifications to it (apologies for using the wrong description in the issue title)

That's why I get the following error when trying to set it:
```
╷
│ Error: Value for unconfigurable attribute
│ 
│   with azuredevops_git_repository.this,
│   on main.tf line 91, in resource "azuredevops_git_repository" "this":
│   91:   disabled   = true
│ 
│ Can't configure a value for "disabled": its value will be decided
│ automatically based on the result of applying this configuration.
```

**Comment by xuzhang3** [comment]
@camilo-s  manage repository `disabled` not supported yet.

**Comment by xuzhang3** [comment]
To support disable/enable, you can create another feature support issue

**Comment by camilo-s** [comment]
This was the ticket meant to request that feature 🙂

**Comment by camilo-s** [comment]
@xuzhang3 Any comment on how this issue is blocked and how we might support unblocking it?

I've tried a few workarounds to support enabling/disabling repositories with my Terraform workflow but they're rather awkward (e.g. using the [terraform_data](https://developer.hashicorp.com/terraform/language/resources/terraform-data) resource) to execute a raw REST API call to do the disabling).

Even so, the provider is unable to delete a disabled repository, so any workaround fails short of fully managing a repository''s lifecycle with Terraform. Is it possible to make this happen without going all the way into implementing support for `is_disabled` as an argument for `azuredevops_git_repository`?

**Comment by xuzhang3** [comment]
> @xuzhang3 Any comment on how this issue is blocked and how we might support unblocking it?
> 
> I've tried a few workarounds to support enabling/disabling repositories with my Terraform workflow but they're rather awkward (e.g. using the [terraform_data](https://developer.hashicorp.com/terraform/language/resources/terraform-data) resource) to execute a raw REST API call to do the disabling).
> 
> Even so, the provider is unable to delete a disabled repository, so any workaround fails short of fully managing a repository''s lifecycle with Terraform. Is it possible to make this happen without going all the way into implementing support for `is_disabled` as an argument for `azuredevops_git_repository`?


The SDK does not publish an API for `disable/enable` a repository, to manage this feature we need to handle this in the ADO provider.

**Comment by brittandeyoung** [comment]
@xuzhang3 I found that we are able to update the `isDisabled` status with a properly structured update request using the SDK. I have raised a PR to add this functionality and added the appropriate Acceptance tests in order to verify the expected behavior.
