### ISSUE TITLE
Branch policies for repository

### ISSUE THREAD

**Issue by andrefcpimentel2** [microsoft/terraform-provider-azuredevops#114]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform should have the ability to set the following branch policies :

·        Check for linked work items = Required

·        Check for comment resolution = Required

### New or Affected Resource(s)

* azuredevops_git_repository

### Potential Terraform Configuration

```hcl
 resource "azuredevops_branch_policy_wi_validation" "wi_validation" {
    require_lined_wi = true

   require_comment_resolution = true
}
```

### References

* #0000

**Comment by EliiseS** [comment]
Great idea, might be an opportunity to add them as part of some of the other branch policies, depending on the AzDO API.
