### ISSUE TITLE
Got a plan with all resources recreating.

### ISSUE THREAD

**Issue by offbeatful** [microsoft/terraform-provider-azuredevops#1165]
### Terraform (and Azure DevOps Provider) Version

Terraform 1.9.6
Azure Devops 1.2.0 and 1.3.0

### Affected Resource(s)

Pretty much every resource that uses project_id (specifically azuredevops_git_repository)

We manage DevOps using Terraform and run `apply` command using CI pipeline. Last successful run was last Monday 16th. I tried to apply new changes today and get a plan when all my resources get recreated because of project_id.

Example of what I see:
```
azuredevops_git_repository.repository must be replaced
-/+ resource "azuredevops_git_repository" "repository" {
      ~ disabled       = false -> (known after apply)
      ~ id             = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY" -> (known after apply)
      ~ is_fork        = false -> (known after apply)
        name           = "my-project"
      ~ project_id     = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" -> (known after apply) # forces replacement
      ~ remote_url     = "https://company@dev.azure.com/company/projects/_git/my-project" -> (known after apply)
      ~ size           = 7016497 -> (known after apply)
      ~ ssh_url        = "git@ssh.dev.azure.com:v3/company/projects/my-projects" -> (known after apply)
      ~ url            = "https://dev.azure.com/company/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/_apis/git/repositoriesYYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY" -> (known after apply)
      ~ web_url        = "https://dev.azure.com/company/projects/_git/my-project" -> (known after apply)
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }
```

Has something changed on a backend/api?

This is a blocking issue for us.

**Comment by offbeatful** [comment]
`terraform plan -refresh=false` works as expected. If `-refresh=false` is not specified most resources gets recreated.

**Comment by xuzhang3** [comment]
@offbeatful  Changes to `project_id` caused the repository to be recreated, this is by design not a bug.

**Comment by offbeatful** [comment]
@xuzhang3 that is obvious. However project hasn’t changed. A week ago everything was working with standard plan/apply commands. Right now only when I disable state refresh.

I checked project Id in the state and using az cli - they match. 

My assumption that something might ve broken on the API side (project id is not returned or different?)

**Comment by xuzhang3** [comment]
@offbeatful  Nothing changed of this resource recently. Does this project been recreated?

**Comment by offbeatful** [comment]
All resources are intact (because I have several prevent destroy checks), but plan suggests to recreate all of them. Adding ‘-refresh=false’ solves the issue. This is my temporary solution but my guess is that this is not intended as plan must take into account refreshed state. 

If DevOpsAPI returns inconsistent data then refreshed state is not valid. Is there a place to report that on DevOps side?

Just to sum up:
- with ‘-refresh=false’ there no changes to infra
- with default behavior (just running ‘terraform plan’) the plan suggests to recreate every resource that depends on project_id

**Comment by xuzhang3** [comment]
This is strange, will the `.state` file be updated by others?

**Comment by offbeatful** [comment]
Ok, I figured it out. It seems the Project's process was changed outside of terraform. However it is not clear why that forces everything to be recreated.
