### ISSUE TITLE
github serviceendpoint token cannot be updated

### ISSUE THREAD

**Issue by seqdan** [microsoft/terraform-provider-azuredevops#117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v0.12.25
+ provider.azuredevops v0.0.1
```

### Affected Resource(s)

* `azuredevops_serviceendpoint_github`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_project" "myproject" {
	project_name = "My Project"
	description = "Interesting project"
	work_item_template = "Basic"
}

resource "azuredevops_serviceendpoint_github" "se1" {
	project_id = azuredevops_project.myproject.id
	service_endpoint_name = "testendpoint1"
	auth_personal {
		personal_access_token = "aaa[...]aaa"
	}
}
```

### Expected Behavior

When I run `terraform apply` with different personal access tokens, I would expect terraform to create the service endpoint during the first run, and to update the token during the second run.

### Actual Behavior

The service endpoint is correctly created during the first run. After an update of the token, the second run fails with:

```
Error: Error updating service endpoint in Azure DevOps: Github Apps can not be updated must match imported values exactly
```

### Steps to Reproduce

1. `terraform apply`
2. change personal access token value
3. `terraform apply`

### Important Factoids

* I have tried to set the "description" to an empty value, and to not set a description. Same result in both cases. This is, because the documentation (https://www.terraform.io/docs/providers/azuredevops/r/serviceendpoint_github.html) states it must be set to empty, explicitly, but I had issues with empty values during creation of the service connection.
* I can easily change the token manually in the Azure DevOps GUI.
* The documentation also indicates I cannot create "github apps" via terraform. I am confused. I want to create a service endpoint with a personal access token. Why does this qualify as an "app"?

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @seqdan Thanks for opening this issue. Looks like a service API breaking change , need more investigation. Similar issue #73

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.

**Comment by abindg** [comment]
Is this resolved ? I am having a similar issue . I am using an existing service connection and importing it into my terraform state using azure devops . But when it goes to apply stage , it creates the following error :

Error updating service endpoint in Azure DevOps: Github Apps can not be updated must match imported values exactly

**Comment by xuzhang3** [comment]
@abindg Where did you  import the  GH connection from? `Project settings -> Pipelines -> Service Connections` or `Project settings -> Boards -> GitHub connections`, if from `Project settings -> Boards -> GitHub connections`, then cannot be updated.

**Comment by abindg** [comment]
@xuzhang3 

Thank for the reply . I have resolved this issue I think. 

I am running a terraform manifest through azure devops pipeline , which after creating other resources , creates another azure devops pipeline in the same project . That was having problem as there was a conflict with the original github Service endpoint that was used to check in the terraform repo . 

I had to import the Github enndpoint into my terraform state and then used that same endpoint to build the next pipeline difinition . It worked.
