### ISSUE TITLE
tofu init throws an error 'authentication signature from unknown issuer'

### ISSUE THREAD

**Issue by kkuchcinski** [microsoft/terraform-provider-azuredevops#1170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

OpenTofu v1.8.2
on darwin_arm64
provider: microsoft/azuredevops v1.3.0
### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.5.7"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=4.0"
    }
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=1.3.0"
    }
  }
}

```

### Debug Output

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 4.0.0"...
- Finding microsoft/azuredevops versions matching ">= 1.3.0"...
- Installing hashicorp/azurerm v4.3.0...
- Installed hashicorp/azurerm v4.3.0 (signed, key ID 0C0AF313E5FD9F80)
- Installing microsoft/azuredevops v1.3.0...

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/
╷
│ Error: Failed to install provider
│ 
│ Error while installing microsoft/azuredevops v1.3.0: the provider is not signed with a valid signing key; please contact the provider author (authentication signature from unknown issuer)

### Expected Behavior

tofu init finishes successfully

### Actual Behavior

tofu init failed

### Steps to Reproduce

1. `tofu init`

### Important Factoids

it was working with such configuration till Friday 20.09.2024 with following comment:
```
- Installing microsoft/azuredevops v1.3.0...
- Installed microsoft/azuredevops v1.3.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

### References

* #0000

**Comment by xuzhang3** [comment]
@kkuchcinski  ADO provider is not released to the TOFU registry

**Comment by kkuchcinski** [comment]
@xuzhang3 based on information on OpenTofu registry it is https://search.opentofu.org/provider/microsoft/azuredevops/latest

nevertheless the issue has been resolved in https://github.com/opentofu/opentofu/issues/2014
