### ISSUE TITLE
Add support for immediate expiry to azuredevops_branch_policy_build_validation

### ISSUE THREAD

**Issue by markwragg** [microsoft/terraform-provider-azuredevops#1171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There doesn't appear to be any way to set the build expiration option "Immediately when `<branch>` is updated" via `azuredevops_branch_policy_build_validation`: 

![image](https://github.com/user-attachments/assets/2c1f1f83-1646-4c3d-8edc-f7ab62386a1f)

Setting valid_duration to 0 is equivalent to setting "never expire". The best you can do at the moment is set it to expire after 1 minute.

### New or Affected Resource(s)

* azuredevops_branch_policy_build_validation

### Potential Terraform Configuration

I would have expected `valid_duration = 0` to expire immediately, with it perhaps supporting `valid_duration = -1` if you want it to never expire. I guess if you don't want this to be a breaking change then `valid_duration = -1` could be expire immediately, or a new `expire_immediately = true` setting could perhaps be added.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by xuzhang3** [comment]
@markwragg  you can set the immediate expiry via:
```hcl
    queue_on_source_update_only = false
    valid_duration      = 0
```

**Comment by markwragg** [comment]
This works thanks!
