### ISSUE TITLE
Creash when using data source azuredevops_serviceendpoint_azurecr

### ISSUE THREAD

**Issue by skarum** [microsoft/terraform-provider-azuredevops#1179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `data azuredevops_serviceendpoint_azurecr`

### Terraform Configuration Files

```hcl
data "azuredevops_project" "this" {
  name = "projectname"
}

data "azuredevops_serviceendpoint_azurecr" "acr" {
  project_id          = data.azuredevops_project.this.id
  service_endpoint_name = "endpoint-name"
}
```

### Debug Output

https://gist.github.com/skarum/3bb1502b668fde24fd438979ecbb83b7

### Expected Behavior

Get the id of the service connectin

### Actual Behavior

Plan crashes

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I'm connecting to Azure DevOps with a PAT that have full access to service connections in that project - and I'm a project administrator.

![image](https://github.com/user-attachments/assets/e2e85f94-5970-4977-b27f-c5c7c54821ba)

I can add permissions to the service connection using an hardcoded service connection id.

Result is the same when using `service_endpoint_id` (with the id) and using `service_endpoint_name` (with the name)

**Comment by xuzhang3** [comment]
@skarum   can you help check that the the import resource is the ACR service connection?  The scope in this service connection should in format of 
`/subscriptions/<sub ID>/resourceGroups/<RG name>/providers/Microsoft.ContainerRegistry/registries/<Container register name>` but it is not there in your scenario, so I guess it is not an Azure resource

**Comment by skarum** [comment]
You are right! I knew it was a connection to ACR, but had not checked how it was setup.

Turns out it was setup as "Others" in Docker Registry type

![Image](https://github.com/user-attachments/assets/44875da6-92fb-4f0a-877c-86894c87b6c9)

Sorry about the confusion.
