### ISSUE TITLE
Error import repository in Azure DevOps: Request returned status: 400 Bad Request

### ISSUE THREAD

**Issue by jrowecdw** [microsoft/terraform-provider-azuredevops#1191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform 1.9.7 x64
hashicorp/azurerm v4.5.0
microsoft/azuredevops v1.3.0

### Affected Resource(s)

Azure DevOps repository. Importing repositories between projects in the same organisation. 

azuredevops_git_repository
azuredevops_serviceendpoint_generic_git

### Terraform Configuration Files
```
data "azuredevops_project" "deploy" {
  name = "deploy"
}


resource "azuredevops_serviceendpoint_generic_git" "deployShared" {
  project_id              =  data.azuredevops_project.deploy.id
  repository_url        = "https://dev.azure.com/<EXAMPLE>/deploy/_git/shared"
  # username           = "username"
  password               = "<redacted>"
  service_endpoint_name = "Example Generic Git"
  description            = "Managed by Terraform"
}

resource "azuredevops_git_repository" "example" {
  project_id = azuredevops_project.example.id
  name       = "example-import"
  initialization {
    init_type = "Import"  # Initialize by importing an existing repository
    source_type = "Git"
    source_url = "https://dev.azure.com/<EXAMPLE>/deploy/_git/shared"  
   # service_connection_id = azuredevops_serviceendpoint_generic_git.deployShared.id
  }
}
)
```

Have valid PAT token, have tried this too but same error persists. Empty repository called 'example-import' is created but never populated. Same credentials via the portal work. 

### Expected Behavior

Import succesful of repository from existing project to new project. 

### Actual Behavior

```
╷
│ Error: Error import repository in Azure DevOps: Request returned status: 400 Bad Request 
│ 
│   with module.customers.azuredevops_git_repository.example,
│   on customers/honda.tf line 56, in resource "azuredevops_git_repository" "example":
│   56: resource "azuredevops_git_repository" "example" {
│ 
╵
```

1. Create source project with repo and files you wish to copy. Create destination project and use the code above to try and import the parent repo into the new repo. 
2. Terraform plan/apply as normal. 

### Important Factoids

Using via Azure DevOps with PAT which has full org access. Can create other projects fine no issue.

**Comment by xuzhang3** [comment]
This is because the repository you need to import is confidential and you need to send uname/pwd or service connection to access the repository. Also, ADO should check the request before importing

**Comment by jrowecdw** [comment]
Ive attempted prefixing the URL with the PAT (which makes no difference) I can do this via git commands so I am happy authentication is fine. Do you have an example of how this should work with PAT authentication ?

**Comment by xuzhang3** [comment]
@jrowecdw Set the password to PAT and leave the username empty.

**Comment by xuzhang3** [comment]
I'm trying to add an API that can be used to validate requests before importing a repository, and this API is not included in the SDK

**Comment by xuzhang3** [comment]
Adding this precheck is a little tricky, the precheck request requires uname/pwd, but this is handled by the service connection. We cannot get the uname/pwd directly from the service connection. 
As a tip, when you try to import a private repository, you can treat a 400 Bad Request as an authorization failure because the service doesn't return any useful information, authorization failure could be the underlying error.
