### ISSUE TITLE
Support for gitlab serviceendpoint

### ISSUE THREAD

**Issue by MrLuje** [microsoft/terraform-provider-azuredevops#1235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for `gitlab` serviceendpoint

![Image](https://github.com/user-attachments/assets/56939d28-f481-4d38-9c94-a73b1ba7d3eb)

Thanks

**Comment by xuzhang3** [comment]
@MrLuje  Is this a GitLab service connection that needs to be supported: https://marketplace.visualstudio.com/items?itemName=onlyutkarsh.gitlab-integration?

**Comment by MrLuje** [comment]
> @MrLuje  Is this a GitLab service connection that needs to be supported: https://marketplace.visualstudio.com/items?itemName=onlyutkarsh.gitlab-integration?

Ah sorry... I didn't notice it was a marketplace integration
I guess we are out of scope for this one :)

**Comment by xuzhang3** [comment]
@MrLuje  marketplace service connections also supported by ADO

**Comment by MrLuje** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/632075?s=64&amp;u=14c880cec8d24d1680bb2b5c6ee45afa1b391dfa&amp;v=4">@MrLuje](https://github.com/MrLuje) marketplace service connections also supported by ADO

There is already one for that ? do you have an example ?

**Comment by xuzhang3** [comment]
@MrLuje A lot. https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_runpipeline
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_octopusdeploy
