### ISSUE TITLE
Terraform Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by rkgaddipati** [microsoft/terraform-provider-azuredevops#1236]
I encountered an issue with the Azure DevOps provider when applying changes to security role assignments. The provider produced an unexpected new value, indicating that the root object was present but now absent. This issue occurred across multiple modules and domains.

Error Messages:

When applying changes to
module.domains["Project_Name"].module.ado_groups.azuredevops_securityrole_assignment.overrider_group_environment_admin_privileges,
provider "provider[\"registry.terraform.io/microsoft/azuredevops\"]"
produced an unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's
own issue tracker.

https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/securityrole_assignment -- Trying to apply this resource block

Expected Behavior:

The provider should apply the changes without producing inconsistent results.

Actual Behavior:

The provider produced an unexpected new value, indicating that the root object was present but now absent.

**Comment by xuzhang3** [comment]
@rkgaddipati  What authorization to use to run the ADO provider and what permissions to grant it.

**Comment by rkgaddipati** [comment]
we are using the PAT token to access the ADO, and it has the admin privileges. We are trying to add an existing group to the environments inside the ADO pipelines under security tab with Administrator privileges.

provider version used for "azuredevops" ">= 1.3.0"

**Comment by xuzhang3** [comment]
@rkgaddipati this seems to be an PAT/User permission issue. The ADO service will sometimes return 200 if the PAT does not have permissions.

**Comment by rkgaddipati** [comment]
![Image](https://github.com/user-attachments/assets/eab8bc6c-ceb1-428b-b567-b1f67216986c)
![Image](https://github.com/user-attachments/assets/dff21a34-ddcd-40ef-9b17-db70d6005103)
![Image](https://github.com/user-attachments/assets/1a80210e-41ce-4f06-8e0f-df1618560dfc)

it has admin privileges on the ADO, and pretty sure it is not related to permissions

**Comment by drdamour** [comment]
@xuzhang3 i'm getting this too.  we use PAT as well.  key troubleshooting point to consider, a subsequent rerun succeeds.  so this is NOT a permissions issue, seems to be a race condition.

It's failing often (but not always) in terraform applies where we create the group and then assign that group a role in the same apply.  Even a few seconds later a rerun succeeds.

the security role being added  in this case is for a service connection at the collection level.
```
resource "azuredevops_securityrole_assignment" "example" {
  # value sniffed following https://bw861987.medium.com/azure-devops-terraform-change-serviceconnection-and-environment-permissions-for-a-project-a0d59bfa2da1
  # saw it as "distributedtask.collection.serviceendpointrole" in the url
  # but it keeps coming back in the body as "distributedtask.serviceendpointrole" so guessing AzDO made a synonym for it or something...going with this since it works
  scope       = "distributedtask.serviceendpointrole"
  resource_id = "collection_${var.service_connection.id}"
  identity_id = azuredevops_group.group.origin_id
  # i wish there was a more granular role that was just secret rotation...but there is not so we'll give em admin
  role_name   = "Administrator"
}
```

**Comment by xuzhang3** [comment]
Fixed in #1255

**Comment by itssravya** [comment]
@xuzhang3 
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: timeout while waiting for state to become 'succeed, failed' (last state: 'syncing', timeout: 10m0s)
│ 
│   with module.azure-devops.azuredevops_securityrole_assignment.library[0],
│   on modules/adoproject/main.tf line 117, in resource "azuredevops_securityrole_assignment" "library":
│  117: resource "azuredevops_securityrole_assignment" "library" {


Currently its getting timeout after **1.6** release

**Comment by xuzhang3** [comment]
> [@xuzhang3](https://github.com/xuzhang3) ##[error]Terraform command 'apply' failed with exit code '1'. ##[error]╷ │ Error: timeout while waiting for state to become 'succeed, failed' (last state: 'syncing', timeout: 10m0s) │ │ with module.azure-devops.azuredevops_securityrole_assignment.library[0], │ on modules/adoproject/main.tf line 117, in resource "azuredevops_securityrole_assignment" "library": │ 117: resource "azuredevops_securityrole_assignment" "library" {
> 
> Currently its getting timeout after **1.6** release

The purpose of the retry added in v1.6 is to ensure the final consistency of the role assignment. According to feedback, the API may return cached results during the entire stage.  Extending the retry interval may fix this issue.
