### ISSUE TITLE
Wrong logic for returning service endpoint's project when validateServiceEndpoint is called

### ISSUE THREAD

**Issue by xxbarsey-tieto** [microsoft/terraform-provider-azuredevops#1248]
Logic for finding project to which service endpoint belong to is currently buggy as it just return whatever is the first element in projects list. This logic is fine when creating the endpoint as when you create the service endpoint it belong to a specific project only. But later if you share that service endpoint with other projects, **ServiceEndpointProjectReferences** property will contain a list of all project where that service connection is shared to, including the parent project where it is created and the list order is random. So returning the first element of that array as the parent project is wrong.

For calling get endpoint of the Rest API it is required to pass the project ID, so I don't see any point to try to get that project ID from the service endpoint body later with this flowed logic.

```
func validateServiceEndpoint(clients *client.AggregatedClient, endpoint *serviceendpoint.ServiceEndpoint, serviceEndpointID *string, retryTimeout time.Duration) error {
    ...
    Project:    converter.String((*endpoint.ServiceEndpointProjectReferences)[0].ProjectReference.Id.String()),
    ...
}
```

**Comment by xuzhang3** [comment]
@yuri-tieto The project info from `ServiceEndpointProjectReferences` is generated from t he `project_id` based on the HCL script.  The `(*endpoint.ServiceEndpointProjectReferences)[0].ProjectReference.Id` is the `project_id`. But this is a bit ambiguous compared to the service response, which may have multiple projects in `ServiceEndpointProjectReferences`, and the first project may not be the one that owns this service connection(`isShared=true`).

**Comment by xuzhang3** [comment]
Change the logic a bit to make it more readable
