### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by ahmedBedairC** [microsoft/terraform-provider-azuredevops#1251]
### **Environment Details**

- Terraform Version: 1.10.0 (on Windows)
- Azure DevOps Provider Version: registry.terraform.io/microsoft/azuredevops v1.4.0

### **Scenario**

I am using Terraform to create and configure Azure DevOps resources. The configuration includes:

- Azure DevOps Project creation
- Azure DevOps Environment creation
- Service Connections setup
- Security Role Assignments using azuredevops_securityrole_assignment

While all other resources are created successfully, the azuredevops_securityrole_assignment resource fails to create the required security role assignments during the first run of terraform apply. The error indicates an inconsistent result.

### **Error Message**
`Error: Provider produced inconsistent result after apply

When applying changes to module.ado_provisioning.azuredevops_securityrole_assignment.deploy_app_01_role_assignment["staging"], provider
"provider[\"registry.terraform.io/microsoft/azuredevops\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
`

### **Steps to Reproduce**

1. Run terraform apply with the configuration below.
2. Observe that the first apply fails with an "inconsistent result" error.
3. Run terraform apply again.
4. The missing resources are created successfully.

### **Terraform Configuration Files**
```
resource "azuredevops_securityrole_assignment" "deploy_application_runners_role_assignment" {
  for_each = local.env_deploy_application_runners

  scope       = "distributedtask.environmentreferencerole"
  resource_id = format("%s_%s", data.azuredevops_project.project.id, each.value)
  identity_id = local.groups["deploy_application_runners"]
  role_name   = "User"
}

locals {
  env_deploy_application_runners = {
    development = azuredevops_environment.development.id
    quality     = azuredevops_environment.app_quality.id
    staging     = azuredevops_environment.staging.id
    production  = azuredevops_environment.chp_app_production.id
  }

  groups = {
    deploy_application_runners = azuredevops_group.deploy_app_runners.origin_id
    deploy_content_runners     = azuredevops_group.deploy_content_run.origin_id
  }
}
```
### **Problem**
The azuredevops_securityrole_assignment resource fails with an inconsistent result error on the first run of terraform apply. However:

- All other resources (projects, environments, and service connections) are created successfully.
- Running terraform apply a second time creates the missing security role assignments without issues.

### **Expected Behavior**
All resources, including azuredevops_securityrole_assignment, should be created successfully on the first terraform apply run.

**Comment by MrWrzosek** [comment]
I got the exact same error. During the first apply I get an error, but when I check the infrastructure I see that the role has nevertheless been assigned. The second apply no longer throws an error, but I only do it to complete the state with the missing resource.

Terraform 1.9, AzureDevOps Provider 1.4.0
