### ISSUE TITLE
Document for Provider users

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/terraform-provider-azuredevops#128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Documentation for Users might helpful for the users.  **More discussion is required**. Feel free to leave comment.  My current idea is having the same structure as Terraform Azure Providers

* [Terraform Azure Provider website](https://www.terraform.io/docs/providers/azurerm/index.html)
* [Terraform Azure Provider documentation](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/website/docs)

They are auto generated website, however, we don't need it just Markdown is fine. However, Keep the same structure might helpful to terraform users. The structure is:

* Guides
* Data Sources
* Resources

For Guides, it is free format. For Data Sources, Resources, it will have: 

* title
* Example Usage
* Argument Reference
* Attribute Reference
* Import (Resources only) 

### New or Affected Resource(s)

No

### Potential Terraform Configuration

No

### References

Already put it on above

**Comment by nmiodice** [comment]
- Re-scope to:
  - cover only azure repos update code
  - write story for other resources
  - document the documentation approach in our contributing guidelines
