### ISSUE TITLE
Create Azure Devops Organization

### ISSUE THREAD

**Issue by polanfong** [microsoft/terraform-provider-azuredevops#129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a feature to create an Azure DevOps Organization via Terraform.
Apologies if this is already available. All I could find was creating via ARM template (see https://tobiasfenster.io/automating-organization-and-project-creation-in-azure-devops). That seems to be using an outdated resource type though ("Microsoft.VisualStudio/account").

### New or Affected Resource(s)

Azure DevOps Organization

### Potential Terraform Configuration

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
  subscription_id = "xxxxxxxxxxxxxxxxx"
}

resource "azuredevops_org" "org" {
  org_name = "Contoso"
  location = "eastus"
  resource_group_name = "..."
}
```

**Comment by xuzhang3** [comment]
Hi @polanfong  Thanks for opening this issue. ADO provider is aimed at provision resources within Azure DevOps organization.  We have no plan to support create organizations and another reason is API is not exposed by the service side.

**Comment by polanfong** [comment]
ok thanks @xuzhang3

**Comment by madi-parloa** [comment]
What about modifying settings of an existing Azure DevOps Organization? Managing policies, permissions, etc. ?

**Comment by xuzhang3** [comment]
@madi-parloa  Some of the resource are support both project level and ORG level permission management. Take `azuredevops_feed_permission` as example. this resource grant the permissions based on the group, the group can be project group or ORG group. Current policy resources focuses on the project level, Could you elaborate on what kind of policy you want?
