### ISSUE TITLE
Implement project - Update

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#13]
The project resource has no implementation for "Update" resulting in a `terraform apply` to not work correctly if a project needs to change.

# Acceptance Criteria
 - [x] Executing `terraform apply` should update a terraform managed project in AzDO
 - [x] Unit tests are written, if needed
 - [x] Acceptance test is implemented - https://www.terraform.io/docs/extend/testing/acceptance-tests/testcase.html

**Comment by TsuyoshiUshio** [comment]
Please assign it to me.  :) I can't move the task of the Kanban board.
