### ISSUE TITLE
resource_authorization documentation page is missing navigation pane.

### ISSUE THREAD

**Issue by DamonStamper** [microsoft/terraform-provider-azuredevops#132]
When visiting https://www.terraform.io/docs/providers/azuredevops/r/resource_authorization.html the navigation pane on the left side of the browser doesn't show up. Browsing other resources (https://www.terraform.io/docs/providers/azuredevops/r/variable_group.html) shows the pane without issue.

Chrome version 83.0.4103.116 (Official Build) (64-bit)

**Comment by xuzhang3** [comment]
Hi @DamonStamper  Thanks for your feedback, This is issue has been fix at #13 . Since we have not released the new version, the document won't updated.
