### ISSUE TITLE
Include lint check in lint-check-go.sh script

### ISSUE THREAD

**Issue by ThePhen** [microsoft/terraform-provider-azuredevops#138]
As a developer, I want my build to fail when I include source code files that do not pass basic linting. Furthermore, i want the existing lint check scripts to *actually lint check my files!*

### Acceptance Criteria
 - [x] `golint -set_exit_status ./...` is executed whenever `./scripts/lint-check-go.sh` is run. If any lit errors are found, the script should produce a non-zero exit status. This should fail the CICD lint check phase.
 - [x] A friendly error telling you what to do in order to fix your files should be emitted to the terminal so that people debugging the build can fix issues. **Note: the default output of running `golint -set_exit_status ./...` may be sufficient!**
 - [x] Any existing linting errors should be fixed as a part of this change

**Comment by nmiodice** [comment]
Done in #199
