### ISSUE TITLE
Link secrets from an Azure key vault as variables

### ISSUE THREAD

**Issue by straylight** [microsoft/terraform-provider-azuredevops#139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Was hoping we could add the ability to specify Azure Subscription and Key Vault Name in which the variable group can pull from.

### New or Affected Resource(s)

* azuredevops_variable_group

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "project" {
  project_name = "Test Project"
}

resource "azuredevops_variable_group" "variablegroup" {
  project_id   = azuredevops_project.project.id
  name         = "Test Variable Group"
  description  = "Test Variable Group Description"
  allow_access = true

  key_vault = {
    subscription_id = "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
    name = "mykeyvault"
  }

  variable {
    name  = "key"
    value = "value"
  }

  variable {
    name      = "Account Password"
    value     = "p@ssword123"
    is_secret = true
  }
}
```

### References

* #0000

**Comment by DamonStamper** [comment]
I believe that this feature is planned. https://github.com/terraform-providers/terraform-provider-azuredevops/issues/138#issuecomment-670392497

**Comment by straylight** [comment]
> I believe that this feature is planned. [#138 (comment)](https://github.com/terraform-providers/terraform-provider-azuredevops/issues/138#issuecomment-670392497)

I read that issue and failed to see that comment for some reason, thank you for linking that.

Closing this as its already being worked on.
