### ISSUE TITLE
[Feature request] Add support for extensions

### ISSUE THREAD

**Issue by DamonStamper** [microsoft/terraform-provider-azuredevops#141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Azure DevOps extensions. For example I'd like to define a SonarCloud (SonarSource.sonarcloud) extension.

### New or Affected Resource(s)

* azuredevops_extension

**Comment by xuzhang3** [comment]
Hi @DamonStamper  This is duplicate with #140 . Service connections are have the same API configuration template.
