### ISSUE TITLE
After creating a new project in Terraform, there is unexpectedly a new repository in the project

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
```
$ terraform -version
Terraform v0.12.4
```

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "project" {
  project_name       = var.project_name
  description        = "A project to track super awesome things."
  visibility         = "private"
  work_item_template = "Agile"
}
```

### Expected Behavior

New project (and *only* a new project) is created in the org

### Actual Behavior

New project AND new repo created in the org

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is behavior driven by the `QueueCreateProject` API. The fix will be to use the repo Delete API to remove the newly created repo.

**Comment by beatcracker** [comment]
I'm not sure how you'll be able to do that, since one can't remove the last repo in the project:
```none
VERBOSE: DELETE https://dev.azure.com/foobar/_apis/git/repositories/28cde1ef-af14-4f37-8a6d-3b069ab52bce?api-version=5.1-preview with 0-byte payload
WARNING: An error occurred: The remote server returned an error: (500) Internal Server Error.
WARNING: There must always be at least one repository per Team Project.
```

- https://stackoverflow.com/questions/34946400/visual-studio-team-services-delete-repository
- https://github.com/MicrosoftDocs/vsts-docs/issues/3540
- https://developercommunity.visualstudio.com/content/problem/91852/cannot-delet-git-repo.html

**Comment by nmiodice** [comment]
Closing as this is ADO behavior, not related to the implementation of this provider.
