### ISSUE TITLE
Add support for committing files to "azuredevops_git_repository"

### ISSUE THREAD

**Issue by TechnologyAnimal** [microsoft/terraform-provider-azuredevops#154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After creating a new repository, I want to be able to commit files from my local filesystem to a remote git repository.

### New or Affected Resource(s)

* azuredevops_git_repository_file

### Potential Terraform Configuration

```hcl
resource "azuredevops_git_repository_file" "gitignore" {
  repository = "example"
  file       = ".gitignore"
  content    = "**/*.tfstate"
}
```

### References
[https://www.terraform.io/docs/providers/github/r/repository_file.html](https://www.terraform.io/docs/providers/github/r/repository_file.html)

**Comment by xuzhang3** [comment]
Hi @TechnologyAnimal  You can use the Terraform Provisioner [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html) . I will put this new feature request in our backlog.

**Comment by xuzhang3** [comment]
Closing this issue. Duplicate with #23
