### ISSUE TITLE
Support path filters in azuredevops_branch_policy_build_validation resource

### ISSUE THREAD

**Issue by cmielke** [microsoft/terraform-provider-azuredevops#155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a DevOps engineer I want to configure the path filter on a build validation branch policy so that I can trigger the build validation policy only when certain files in my repo are changed.

### New or Affected Resource(s)

* azuredevops_branch_policy_build_validation

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_build_validation" "p" {
  project_id = azuredevops_project.p.id

  enabled  = true
  blocking = true

  settings {
    display_name        = "Don't break the build!"
    build_definition_id = azuredevops_build_definition.b.id
    valid_duration      = 720
    path_filter             = "/somefolder/*;!/somefolder/tests/*"

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = azuredevops_git_repository.r.default_branch
      match_type     = "Exact"
    }

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = "refs/heads/releases"
      match_type     = "Prefix"
    }
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#path-filters

**Comment by xuzhang3** [comment]
Hi @cmielke  This feature has been implemented. But not released.  You can find the `filename_patterns` in [build policy](https://github.com/terraform-providers/terraform-provider-azuredevops/blob/master/website/docs/r/branch_policy_build_validation.html.markdown) :

**Comment by cmielke** [comment]
That looks great. Thanks @xuzhang3!

**Comment by xuzhang3** [comment]
Closing this issue. Feel free reopen it if you have questions.
