### ISSUE TITLE
Can not create PR triggers in build definitions on TfsGit type repos

### ISSUE THREAD

**Issue by kjoconnor** [microsoft/terraform-provider-azuredevops#158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
```
kevin@pc pipelines % terraform -v
Terraform v0.12.29
provider.azuredevops v0.0.1
```

### Affected Resource(s)

* `azuredevops_build_definition`

### Terraform Configuration Files

```hcl
data azuredevops_git_repositories terraform {
  project_id = data.azuredevops_project.myproject.id
  name       = "terraform"
}

resource azuredevops_build_definition terraform {
  project_id = data.azuredevops_project.myproject.id
  name       = "Terraform Pipeline"
  path       = "\\Pipelines"

  ci_trigger {
    use_yaml = true
  }

  pull_request_trigger {
    use_yaml       = true
    initial_branch = "master"
    forks {
      enabled       = true
      share_secrets = true
    }
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = data.azuredevops_git_repositories.terraform.id
    branch_name = "master"
    yml_path    = "azure-pipelines.yml"
  }
}
```

### Expected Behavior

I expect to be able to create this build definition, it seems like PR triggers are supported according to the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers).

### Actual Behavior

```shell
azuredevops_build_definition.terraform: Creating...

Error: error creating resource Build Definition: The trigger type PullRequest is not valid for the TfsGit repository type.

  on terraform.tf line 14, in resource "azuredevops_build_definition" "terraform":
  14: resource azuredevops_build_definition terraform {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nope.

**Comment by kjoconnor** [comment]
I see this now on [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#pr-trigger), I'm guessing that's why this is:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/731233/90476660-f4649d80-e0f7-11ea-8501-b4c2c3e9cf24.png">

Are you able to manage build validation with this provider yet? Thanks!

**Comment by xuzhang3** [comment]
Hi @kjoconnor  You can use `azuredevops_branch_policy_build_validation` to create the PR triggers for `TfsGit` type repo.
Config example:
```hcl
resource "azuredevops_project" "p" {
  project_name = "Sample Project"
}

resource "azuredevops_git_repository" "r" {
  project_id = azuredevops_project.p.id
  name       = "Sample Repo"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_build_definition" "b" {
  project_id = azuredevops_project.p.id
  name       = "Sample Build Definition"

  repository {
    repo_type = "TfsGit"
    repo_id   = azuredevops_git_repository.r.id
    yml_path  = "azure-pipelines.yml"
  }
}

resource "azuredevops_branch_policy_build_validation" "p" {
  project_id = azuredevops_project.p.id

  enabled  = true
  blocking = true

  settings {
    display_name        = "Don't break the build!"
    build_definition_id = azuredevops_build_definition.b.id
    valid_duration      = 720
    filename_patterns =  [
      "/WebApp/*",
      "!/WebApp/Tests/*",
      "*.cs"
    ]

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = azuredevops_git_repository.r.default_branch
      match_type     = "Exact"
    }

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = "refs/heads/releases"
      match_type     = "Prefix"
    }
  }
}
```

**Comment by kjoconnor** [comment]
Thanks! One note, it looks like `filename_patterns` isn't valid, is that coming in a future version? I've verified on the docs and by running it and getting an error that it doesn't work.

https://www.terraform.io/docs/providers/azuredevops/r/branch_policy_build_validation.html

**Comment by kjoconnor** [comment]
I see it is: https://github.com/paultyng/terraform-provider-azuredevops/issues/62

Thanks! Closing this one.
