### ISSUE TITLE
`default_branch` attribute missing on azuredevops_git_repositories data source

### ISSUE THREAD

**Issue by kjoconnor** [microsoft/terraform-provider-azuredevops#159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
kevin@pc pipelines % terraform -v
Terraform v0.12.29
provider.azuredevops v0.0.1
```

### Affected Resource(s)

* [`azuredevops_git_repositories`](https://www.terraform.io/docs/providers/azuredevops/d/data_git_repositories.html#default_branch)

### Terraform Configuration Files

```hcl
data azuredevops_git_repositories terraform {
  project_id = data.azuredevops_project.myproject.id
  name       = "terraform"
}

resource azuredevops_build_definition terraform {
  project_id = data.azuredevops_project.myproject.id
  name       = "Terraform Pipeline"
  path       = "\\Pipelines"

  ci_trigger {
    use_yaml = true
  }

  pull_request_trigger {
    use_yaml       = true
    initial_branch = data.azuredevops_git_repositories.terraform.default_branch
    forks {
      enabled       = true
      share_secrets = true
    }
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = data.azuredevops_git_repositories.terraform.id
    branch_name = data.azuredevops_git_repositories.terraform.default_branch
    yml_path    = "azure-pipelines.yml"
  }
}

```

### Expected Behavior

The `branch_name` attribute should be pulled from the `azuredevops_git_repositories` data source and should be fine to use in the build definition resource.

### Actual Behavior

```
Error: Unsupported attribute

  on terraform.tf line 25, in resource "azuredevops_build_definition" "terraform":
  25:     initial_branch = data.azuredevops_git_repositories.terraform.default_branch

This object has no argument, nested block, or exported attribute named
"default_branch".
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None.

**Comment by xuzhang3** [comment]
Hi @kjoconnor  You need replace the `azuredevops_git_repositories`  with `azuredevops_git_repository`. `azuredevops_git_repositories` will get all of the repos within the project.

**Comment by kjoconnor** [comment]
Thanks @xuzhang3, but it doesn't look like `azuredevops_git_repository` is a valid data source.

```
Error: Invalid data source

  on terraform.tf line 5, in data "azuredevops_git_repository" "terraform":
   5: data azuredevops_git_repository terraform {

The provider provider.azuredevops does not support data source
"azuredevops_git_repository".
```

It isn't listed as a data source on the docs either, just `azuredevops_git_repositories`.

**Comment by xuzhang3** [comment]
@kjoconnor  My mistake. `azuredevops_git_repository ` not releaseed yet. You can use the `azuredevops_git_repositories`  get the repository `default_branch` .
Example config:
```
data azuredevops_project project {
  project_name = "my project"
}



data azuredevops_git_repositories terraform {
  project_id = data.azuredevops_project.project.id
  name       = "my project"
}

 output "brachname_" {
  value = data.azuredevops_git_repositories.terraform.repositories[0].default_branch
}
```

**Comment by kjoconnor** [comment]
Thanks!
