### ISSUE TITLE
Microsoft / HashiCorp ownership

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/terraform-provider-azuredevops#160]
The repository has been moving around a couple of times lately. Can you please clarify to the community of users & contributors who is considered to be the owner of this repository and who will be maintaining this provider?

**Comment by xuzhang3** [comment]
Hi @sdebruyn  This repo will be moved to http://github.com/microsoft  and Microsoft will maintain this provider.

**Comment by hashitop** [comment]
@sdebruyn for now, it is still OK to report issues on this repo?

**Comment by xuzhang3** [comment]
@sdebruyn @hashitop   You still can report issues on this repo.

**Comment by exocom** [comment]
@xuzhang3 when exactly is the move going to happen? I've just opened a PR to terraform/terraform-provider-azuredevops  and do not want to have to repeat this work if possible.

**Comment by xuzhang3** [comment]
@exocom  I can't give the exact time when this transfer will finished. There's some policy issues when move back to MS GH.  You can submit your PR to this repo.
