### ISSUE TITLE
Implement new resource "ACR Service Endpoint"

### ISSUE THREAD

**Issue by ThePhen** [microsoft/terraform-provider-azuredevops#162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by mattdot** [comment]
@nmiodice is this still blocked or would it be possible to create now?

**Comment by nmiodice** [comment]
@mattdot this is no longer blocked. There is a core component that you can use to simplify the creation of service endpoints located [here](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/crud/serviceendpoint/crud_service_endpoint.go)

Examples:
- [AzureRM](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_azurerm.go)
- [DockerHub](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_dockerhub.go)
- [BitBucket](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_bitbucket.go)

**Comment by nmiodice** [comment]
If you'd like, I can assign this to you if you have plans to implement

**Comment by mattdot** [comment]
After looking into it a little more, what we actually need is an “other docker repository” service connection.  I’ll create a feature request for that one and submit a pr in the next couple days.

**Comment by xuzhang3** [comment]
Closing this issue due to #304

**Comment by nmiodice** [comment]
Re-opening - 304 was for docker registry connections. There is another type - ACR - which does not require a username/password

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#33
