### ISSUE TITLE
[Feature Request] Add project_id as alternative attribute for project data source

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/terraform-provider-azuredevops#162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When you want to import a project using the data source, you have to specify the project name. In my case I don't have the project name, but I have its ID. It would be useful to be able supply the project_id and let it compute all the other variables (one of which being the name) for me.

### New or Affected Resource(s)
* `data azuredevops_project `

### Potential Terraform Configuration
```hcl
data "azuredevops_project" "p_name" {
  project_name = "some_project_name"
}

output "project_computed_id" {
  value = data.azuredevops_project.p_name.id
}

data "azuredevops_project" "p_id" {
  project_id = "12345"
}

output "project_computed_name" {
  value = data.azuredevops_project.p_id.project_name
}
```

**Comment by EliiseS** [comment]
I've added `project_id` field in PR #163
