### ISSUE TITLE
Implement "sweeper" to cleanup orphaned acceptance test resources

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#164]
In the likely case that an acceptance tests fails during a developer SDLC cycle it will be common for resources provisioned during acceptance tests to not be properly cleaned up. There are a number of reasons why this can happen, and they are discussed here: https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html.

These resources may cost money and clutter our cloud resources, so they should be cleaned up after each run of the acceptance test.

### Acceptance Criteria
 - [ ] A sweeper - described [here](https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html) is implemented. Nearly every named resource for this project will be provisioned into an AzDO project, so the sweeper can clean up projects provisioned from the acceptance tests.
 - [ ] The sweeper should run after every acceptance test

**Note: All resources -- including projects -- that have a name should be using a common prefix, which is [defined here](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/provider_test.go#L104). This can be used to filter for testing resources**

**Note: DO NOT DELETE ALL PROJECTS... FILTER BY PREFIX!**

### Relevant documentation
 - https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html

**Comment by ThePhen** [comment]
@KeithJRome @nmiodice ... if you get desperate and just want to clean an org's `test-acc` projeccts, I've been using this to help me keep my org clean by-hand:

```bash
az devops project list \
| jq -r '.[]|select(.name|contains("test-acc"))|.id' \
|xargs -l -- az devops project delete --yes --id
```

**Comment by nmiodice** [comment]
@cgriggs01 I don't see the `make sweep` target in the Makefile. Are these docs up to date?

https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html

**Comment by cgriggs01** [comment]
Hi @nmiodice, 

It looks like this is not used on must of the provider today. The Azurerm provider uses Dalek instead. 

I've let the team know and they will look at updated this documentation. 

Best,
Chris

**Comment by nmiodice** [comment]
Closing with no plans to fix
