### ISSUE TITLE
Error 'rpc error: code = Unavailable desc = transport is closing' when creating multiple repos for a project

### ISSUE THREAD

**Issue by skinamdar** [microsoft/terraform-provider-azuredevops#164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
variable "AZDO_ORG_SERVICE_URL" {
  type = string
}

variable "AZDO_PERSONAL_ACCESS_TOKEN" {
  type = string
}

provider "azuredevops" {
  version = ">= 0.0.1"
  org_service_url       = var.AZDO_ORG_SERVICE_URL
  personal_access_token = var.AZDO_PERSONAL_ACCESS_TOKEN
}

resource "azuredevops_project" "project1" {
  project_name          = "mock-project1"
  description           = "Test provisioning of mock-project1"
}

resource "azuredevops_git_repository" "base" {
  project_id = azuredevops_project.project1.id
  name       = "Base"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_git_repository" "repo1" {
  project_id = azuredevops_project.project1.id
  name       = "Repo1"
  parent_repository_id  = azuredevops_git_repository.base.id
}
```

### Debug Output

https://gist.github.com/skinamdar/fec43858218154e7049d5b9bde03e064

### Expected Behavior

Repo and project should have provisioned without any errors. 

### Actual Behavior

Terraform crashed 
```

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

1. `terraform plan && terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @skinamdar  This is a know issues, you need add the `initialization` configuration for your second repo configure.
```
resource "azuredevops_git_repository" "repo1" {
  project_id = azuredevops_project.project1.id
  name       = "Repo1"
  parent_repository_id  = azuredevops_git_repository.base.id
  initialization {
    init_type = "Clean"
  }
}
```

**Comment by skinamdar** [comment]
Thanks for the update @xuzhang3 , I'm able to initialize it now. Does that mean when ```parent_repository_id``` is included in the block, that ```initialization``` is ignored and there just for config compatibility purposes?

**Comment by xuzhang3** [comment]
@skinamdar `initialization` won't be ignored and in the next release will be changed to required
