### ISSUE TITLE
Error messages should all provide added context and follow the same general pattern

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#165]
### Description

The project currently does not handle error messaging in a consistent way, so it is difficult to know why some errors are happening due to a lack of consistent context. 

Examples:
 - https://github.com/microsoft/terraform-provider-azuredevops/blob/1b7b3a0fa389a4004c319b5a9fc7c40758663689/azuredevops/resource_azure_git_repository.go#L99
 - https://github.com/microsoft/terraform-provider-azuredevops/blob/1b7b3a0fa389a4004c319b5a9fc7c40758663689/azuredevops/resource_build_definition.go#L83

### Acceptance Criteria
 - [ ] All errors returned from top level functions in the provider -- `create`, `read`, `update`, and `delete` functions -- should follow the same high level structure that includes enough information for somebody to reasonably understand where the error occurred and what they might do to fix it

### Some Ideas for structure of errors - feel free to improve on these
One idea would be to use the following structure: `"unable to <ACTION> due to <REASON>. <ADDED CONTEXT>`

**API failure**: `"Unable to add member to group due to failure in ListMemberships API: 404 NOT FOUND"` - the `404 NOT FOUND` would be the data contained from the error returned by the AzDO SDK and is the result of formatting the error like so: `%+v`

**Data Validation Error**: `"Unable to query for project due to invalid UUID format`

**Comment by EliiseS** [comment]
@nmiodice 

I've found that on deletes we sometimes return a nil for an empty string, while other times we try to convert it into an UUID. Which approach should be used? 

``` go
func resourceUserEntitlementDelete(d *schema.ResourceData, m interface{}) error {
	if d.Id() == "" {
		return nil
	}
	userEntitlementID := d.Id()
	id, err := uuid.Parse(userEntitlementID)
	if err != nil {
		return fmt.Errorf("Error parsing UserEntitlement ID. UserEntitlementID: %s. %v", userEntitlementID, err)
	}
```

vs

``` go
func deleteProject(clients *aggregatedClient, id string, timeoutSeconds time.Duration) error {
	uuid, err := uuid.Parse(id)
	if err != nil {
		return fmt.Errorf("Invalid project UUID: %s", id)
	}
```
