### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by josh-barker** [microsoft/terraform-provider-azuredevops#170]
Hi,

I'm looking forward to using the new resources and features.

I'm wondering when is the next release expected?
How frequently do you think the releases will come out?

Cheers!

**Comment by xuzhang3** [comment]
Hi @josh-barker  Sorry for the inconvenient that we cannot release the new version due to the GPG keys.  As I know that we will get GPG keys at the  second half of the October and regular release will be every three weeks.

**Comment by josh-barker** [comment]
Hi @xuzhang3 

No worries. Thanks for the quick response!

**Comment by josh-barker-coles** [comment]
Hi @xuzhang3, just following up on the release. When will 0.0.2 to be released?


Cheers

**Comment by xuzhang3** [comment]
@josh-barker-coles @josh-barker
 Hi guys,  v0.1.0 has been released. https://registry.terraform.io/providers/microsoft/azuredevops/latest
