### ISSUE TITLE
Replying to https://github.com/hashicorp/terraform/issues/890#issuecomment-547461675

### ISSUE THREAD

**Issue by dikhan** [microsoft/terraform-provider-azuredevops#186]
Hi @nmiodice ,

Sorry for reaching out through an issue/question but could not find any other way to reply to your question on https://github.com/hashicorp/terraform/issues/890#issuecomment-547461675 since the terraform bot closed the issue. I replied to you via email, but I wasn't sure whether you got my reply, so pasting it here just in case:

> Hi Nicholas,
> 
> I am glad you found that useful. In regards to mocking updates, unfortunately I have not run into the need to mock the HasChange behaviour since the [OpenAPI Terraform Plugin](https://github.com/dikhan/terraform-provider-openapi) compares the local updated properties with the remote ones (making a GET call to the API to retrieve the remote state instead of using HasChange which compares the updated values with the ones in the state file). Anyways, you may be able to mock that up by using terraform.InstanceState and terraform.InstanceDiff. It's a bit convoluted, but I am not aware of any other way to simulate the HasChange, and also that's how the terraform folks seem to be doing it in their tests too. I put together a simple test to show how that would work:

````
func TestTestHasChange(t *testing.T) {
   r := &schema.Resource{
      Schema: map[string]*schema.Schema{
         "member": &schema.Schema{
            Type:     schema.TypeString,
            Optional: true,
         },
      },
   }

   r.Update = func(d *schema.ResourceData, m interface{}) error {
      if !d.HasChange("member") {
         return nil
      }
      old, new := d.GetChange("member")
      fmt.Printf("members value changed - old: %s, new: %s", old, new)
      d.Set("member", new)
      return nil
   }

   s := &terraform.InstanceState{
      ID: "member",
      Attributes: map[string]string{
         "member": "someValue",
      },
   }

   d := &terraform.InstanceDiff{
      Attributes: map[string]*terraform.ResourceAttrDiff{
         "member": &terraform.ResourceAttrDiff{
            New: "someUpdatedValue",
         },
      },
   }

   actual, err := r.Apply(s, d, nil)
   if err != nil {
      t.Fatalf("err: %s", err)
   }

   expected := &terraform.InstanceState{
      ID: "member",
      Attributes: map[string]string{
         "id":  "member",
         "member": "someUpdatedValue",
      },
   }

   if !reflect.DeepEqual(actual, expected) {
      t.Fatalf("bad: %#v", actual)
   }
}
````
> You can also take a look at the terraform test here: https://github.com/hashicorp/terraform/blob/master/helper/schema/resource_test.go#L450

Feel free to close off this issue once you have read it. Hope this helps.

Dani

**Comment by nmiodice** [comment]
Many thanks for the reply @dikhan!
