### ISSUE TITLE
data user origin_id doesn't work

### ISSUE THREAD

**Issue by poligraph** [microsoft/terraform-provider-azuredevops#186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

terraform -v
Terraform v0.12.28
provider.azuredevops v0.0.1

### Affected Resource(s)

* `azuredevops_users`

### Terraform Configuration Files

```
data "azuredevops_users" "user" {
  principal_name = "user@domain.com"
}

output "user" {
  value = data.azuredevops_users.user.principal_name
}

output "user_origin" {
  value = data.azuredevops_users.user.origin
}

output "user_origin_id" {
  value = data.azuredevops_users.user.origin_id
}
```

### Expected Behavior

following outputs should be displayed
user
user_origin
user_origin_id
### Actual Behavior

shows only one output
user = user@domain.com

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@poligraph   User detail information is wrapped in `azuredevops_users.user.users`
Potential output:
```
user = {
  "id" = "xxxxx"
  "principal_name" = "user@domain.com"
  "users" = [
    {
      "descriptor" = "descriptor"
      "display_name" = "user name"
      "mail_address" = "user@domian.com"
      "origin" = "aad"
      "origin_id" = "xxx-xxx-xxx-xxx-xxx-"
      "principal_name" = "user@domain.com"
    },
  ]
}
```

**Comment by poligraph** [comment]
@xuzhang3 thanks for answer I was able to get this output, but data structure is a set and seems the only wat to access is by `  value = tolist(data.azuredevops_users.user.users)[0].descriptor`

is it any possibility to change type to access without to list conversion? ideally something like this
`value = data.azuredevops_users.user.users.descriptor`

thanks.

**Comment by xuzhang3** [comment]
@poligraph   Users return from service API is a list, change list to a  object may result in meta data loss.

**Comment by xuzhang3** [comment]
Closing this issue, feel free to reopen if you have questions.
