### ISSUE TITLE
Feature: Artifactory Service Endpoint

### ISSUE THREAD

**Issue by josh-barker** [microsoft/terraform-provider-azuredevops#194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I'd like to configure an Artifactory Service Endpoint in AzureDevops

### New or Affected Resource(s)

* azuredevops_serviceendpoint_artifactory

### Potential Terraform Configuration

```hcl
// user credentials
resource "azuredevops_serviceendpoint_artifactory" "example_1" {
  project_id = azuredevops_project.project.id

  url = "https://some.artifactory.instance.com"

  user {
    username = "xxxx"
    password = "xxxx"
  }

  service_endpoint_name = "example-artifactory-1"
  description           = "example-1"
}

// token
resource "azuredevops_serviceendpoint_artifactory" "example_2" {
  project_id = azuredevops_project.project.id

  url = "https://some.artifactory.instance.com"

  token {
    access_token = "xxxx"
  }

  service_endpoint_name = "example-artifactory-2"
  description           = "example-2"
}
```

**Comment by birchb1024** [comment]
I'm starting on this today.

**Comment by xuzhang3** [comment]
Close issue.  Jfrog Artifactory service endpoint #256  has been supported in v0.1.2
