### ISSUE TITLE
[Feature Request]: SonarQube Service Endpoint

### ISSUE THREAD

**Issue by josh-barker** [microsoft/terraform-provider-azuredevops#195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I'd like to configure a SonarQube Service Endpoint in AzureDevops

### New or Affected Resource(s)

* azuredevops_serviceendpoint_sonarqube

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_sonarqube" "example" {
  project_id = azuredevops_project.project.id

  url   = "https://sonarqube.instance.com"
  token = "xxx"

  service_endpoint_name = "example-sonarqube-1"
  description           = "example-1"
}
```

**Comment by birchb1024** [comment]
The code in our fork did work today. Needs more testing. We also need the 'all projects' flag. 
This is in progress.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
