### ISSUE TITLE
Publish new release to Terraform Registry

### ISSUE THREAD

**Issue by simongottschlag** [microsoft/terraform-provider-azuredevops#197]
Hi!

Are there any plans on doing a new release of this provider and are you looking into publishing it to the Terraform registry?

We have to build the code ourselves and store the binaries in GIT right now, would be really great if we could use a release from you instead.

Thank you!

Best regards,
Simon

**Comment by mxrss2** [comment]
Agreed if not in the registry can you please just publish released builds as artifacts in releases. It seems like its not clear what the release cadence is -- I am not even sure what version the provider is on.

**Comment by xuzhang3** [comment]
@simongottschlag @mxrss2  Sorry for the inconvenient that we cannot release the new version due to the GPG keys. As I know that we will get GPG keys in the late October.  Next release  the provider will be released to Terraform registry.

**Comment by simongottschlag** [comment]
@xuzhang3 any updates? We don't want to contribute anything before we know this is the repository that will be releasing the provider and that we know new releases can be made.

**Comment by xuzhang3** [comment]
@simongottschlag  We just get GPG key from the security team last few days and we are trying set up the release task.  The ADO provider will be released and I can guarantee that.

**Comment by simongottschlag** [comment]
@xuzhang3 do you need any assistance setting up the release task for the Terraform registry? I would gladly help out.

**Comment by xuzhang3** [comment]
@simongottschlag  I have setup a release pipeline https://github.com/microsoft/terraform-provider-azuredevops/pull/213, current issue is the GPG sign not working correct and this is an internal security service.

**Comment by xuzhang3** [comment]
It would be apricate if you can your help release the ADO provider, but file sign is an internal service, I'm afraid you may not be able to get involved.

**Comment by simongottschlag** [comment]
@xuzhang3 ah! You can't use GitHub Actions to do this instead?

Terraform documentation: https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-

Example: https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.github/workflows/release.yml

**Comment by xuzhang3** [comment]
@simongottschlag The security sign does not  support `GitHub action`.

**Comment by simongottschlag** [comment]
> @simongottschlag The security sign does not  support `GitHub action`.

@xuzhang3 ok! This means we need to wait for Microsoft to resolve this internally before we can release this provider?

**Comment by xuzhang3** [comment]
@simongottschlag  YES. The  release will coming soon as the only thing blocked us now is the internal sign issue.

**Comment by simongottschlag** [comment]
@xuzhang3 any updates? We've been waiting for quite a while now and will have to start doing this ourselves if nothing happens.

**Comment by xuzhang3** [comment]
@simongottschlag Sorry for the inconvenient. The code sign onboard request still in processing.

**Comment by simongottschlag** [comment]
@xuzhang3 do you have any estimate for when it will be ready? 👍

**Comment by xuzhang3** [comment]
> @xuzhang3 do you have any estimate for when it will be ready? 👍

As far as I know, 3 days ~ 7 days, I cannot give an accurate time. 😞

**Comment by simongottschlag** [comment]
@xuzhang3 I saw https://github.com/microsoft/terraform-provider-azuredevops/pull/224 beeing merged. Crossing my fingers it works :)

**Comment by xuzhang3** [comment]
@simongottschlag  If everything goes well,   new version will be released today.

**Comment by simongottschlag** [comment]
@xuzhang3 that is the best news I've read this week 👍

**Comment by sennerholm** [comment]
Super!

Another question, where is the doc going to show up? Is it at:
https://www.terraform.io/docs/providers/azuredevops/index.html or on: https://registry.terraform.io/search/providers?q=azure%20devops

Or some other place?

Sincerely
Mikael

**Comment by xuzhang3** [comment]
@sennerholm  The docs will be at https://registry.terraform.io/search/providers?q=azure%20devops

**Comment by simongottschlag** [comment]
@xuzhang3 any info regarding getting it on Terraform Registry?

**Comment by xuzhang3** [comment]
@simongottschlag Microsoft   GPG signature cannot verified  by Terraform, I need change the signature format.

**Comment by simongottschlag** [comment]
@xuzhang3 ah, that's unfortunate. I can't see the script used to sign, have you verified that it's the following?

gpg --detach-sign terraform-provider-{NAME}_{VERSION}_SHA256SUMS

**Comment by xuzhang3** [comment]
@simongottschlag  The GPG signature used here is supported by MS internal service.  Integrated in the release pipeline, not in the script.

**Comment by simongottschlag** [comment]
@xuzhang3 ah, that's too bad. What's the plan forward?

Sorry for pushing this all day, every day, but we really need to make Azure DevOps a native part of Terraform for multiple projects and would of course prefer it being released from here instead of a third party fork.

**Comment by xuzhang3** [comment]
@simongottschlag  I'm contacting this with code sign service team if they can return the file in the format required by Terraform . Otherwise I need change the file format by myself to meet the Terraform publish criteria.

**Comment by simongottschlag** [comment]
@xuzhang3 is it possible to convert it manually? That seems like a reasonable way of handling it until it can be automated, just to make sure we can do some new releases. 👍

**Comment by simongottschlag** [comment]
@xuzhang3 I've forked the repo and published the provider using our GPG for now: https://registry.terraform.io/providers/XenitAB/azuredevops/latest

We need the PR #225 and can't wait for it any longer.

I'll remove the fork when you've made a successful release and merged the PR.

**Comment by xuzhang3** [comment]
@simongottschlag @sennerholm     ADO provider v0.1.0 has release to Terraform provider.  
https://registry.terraform.io/providers/microsoft/azuredevops/latest
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs

Configure example:
```
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = "=0.1.0"
    }
  }
}
```

**Comment by simongottschlag** [comment]
@xuzhang3 congratulations!!! 😁🎉👍 Thank you 😁
