### ISSUE TITLE
Project Feature missing from navigation

### ISSUE THREAD

**Issue by straubt1** [microsoft/terraform-provider-azuredevops#2]
### Documentation issue

The resource `azuredevops_project_features` is missing in the left navigation bar.

### Terraform (and Azure DevOps Provider) Version

n/a

### Affected Resource(s)

* `azuredevops_project_features`

### References

* [azuredevops_project_features direct link](https://www.terraform.io/docs/providers/azuredevops/r/project_features.html)

<img width="278" alt="image" src="https://user-images.githubusercontent.com/8408833/85229104-8298fd80-b3ad-11ea-8e75-c416f2485331.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xuzhang3** [comment]
Close this issue, feel free to reopen it if anyone have questions.
