### ISSUE TITLE
How to use a predefined yaml

### ISSUE THREAD

**Issue by defaultbr** [microsoft/terraform-provider-azuredevops#20]
Hello guys, 

Is there any way to populate the linked .yml?

My situation, i'm using this:

```

resource "azuredevops_git_repository" "r" {
  project_id = azuredevops_project.project.id
  name       = "provision-automation-do-not-delete"
  initialization {
    init_type = "Clean"
  }

}

resource "azuredevops_build_definition" "b2" {
  project_id = azuredevops_project.project.id
  name       = "Criar um novo projeto"

  repository {
    repo_type = "TfsGit"
    repo_id   = azuredevops_git_repository.r.id
    yml_path  = "create-new-project.yml"
  }
}
```

but the create-new-project.yml is not created in the repository and there is no way to provide the content of it, what im trying to do now is to output the repository info

```
resource "local_file" "foo" {
    content     = tostring(jsonencode(azuredevops_git_repository.r))
    filename = "${path.module}/repository.json"
}
```

and trying to setup the repository, git clone, git push etc... is there any other way to do that?

**Comment by xuzhang3** [comment]
Hi @defaultbr  By default, ADO provider won't commit any  files at repo creation. You need create the real `create-new-project.yml` and submit to the repo you just create. ADO provider only create the pipeline template.
If you want to commit files after the new repo created, you can use the [Terraform provisioners](https://www.terraform.io/docs/provisioners/index.html). You may config your [SSH key](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page) too.
