### ISSUE TITLE
Add acceptance tests for VariableGroup

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer, I want to have variableGroups covered by acceptance tests.

This story is blocked by https://github.com/microsoft/terraform-provider-azuredevops/issues/170 and https://github.com/microsoft/terraform-provider-azuredevops/issues/171

### References

* Design: https://github.com/microsoft/terraform-provider-azuredevops/issues/21

**Comment by nmiodice** [comment]
These are accepted
