### ISSUE TITLE
Project Import Fails

### ISSUE THREAD

**Issue by MattMencel** [microsoft/terraform-provider-azuredevops#201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
terraform version
Terraform v0.13.4
+ provider foo/com/azuredevops v0.0.1
+ provider registry.terraform.io/hashicorp/azurerm v2.30.0
```

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "operations" {
  name        = "Operations"
}

```

### Debug Output

https://gist.github.com/MattMencel/ec654b2d93a2bf392b28807b056461f6

### Expected Behavior

Import Project

### Actual Behavior

```
Acquiring state lock. This may take a few moments...
azuredevops_project.operations: Importing from ID "Operations"...
azuredevops_project.operations: Import prepared!
  Prepared azuredevops_project for import
azuredevops_project.operations: Refreshing state... [id=Operations]

Error: Error looking up project with ID Operations and Name 
```

### Steps to Reproduce

1. `terraform import azuredevops_project.operations Operations`

**Comment by xuzhang3** [comment]
@MattMencel I test your configuration and  it works. From the logs, I can get the information that the provider cannot read the project.  Does your PAT have the permission to read the project?

**Comment by MattMencel** [comment]
Ah, you are correct. I was using a secret someone else had placed in KeyVault, assuming it was the PAT. It wasn't.

Thanks for pointing me in the right direction.

**Comment by xuzhang3** [comment]
Close this issue, feel free to reopen it if you have questions.
