### ISSUE TITLE
Agent Pool - Azure virtual machine scale set

### ISSUE THREAD

**Issue by aleqsss** [microsoft/terraform-provider-azuredevops#204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The 'Azure virtual machine scale set' pool type of agent pools, inside of Azure DevOps, has now been released and is publicly available, since the (what I can see) version 6.0 of the Azure DevOps REST API. This makes me think that it would be suitable to be able to configure such, from this provider. 

As you can see in the documentation, it now implementes the [TaskAgentPoolOptions](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/add?view=azure-devops-rest-6.0#taskagentpooloptions) definition which allows you to specify, amongst others, the **elasticPool** property.

### New or Affected Resource(s)

Affected Resources:
* azuredevops_agent_pool

Affected Data Sources:
* azuredevops_agent_pool
* azuredevops_agent_pools

### References
From what I can see, this provider is using the [azure-devops-go-api](https://github.com/microsoft/azure-devops-go-api) which, at the time of writing, doesn't implement the **elasticPool** / [TaskAgentPoolOptions](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/add?view=azure-devops-rest-6.0#taskagentpooloptions). Because of this I've created the following issue in that repository: 

* [Add new taskagent resource functionality #90](https://github.com/microsoft/azure-devops-go-api/issues/90)

**Comment by aleqsss** [comment]
I'm interested in working/contributing on this issue, but I'm impeded because as of my understanding, the [azure-devops-go-api](https://github.com/microsoft/azure-devops-go-api) is using an internal tool/code generator to generate the SDK.

**Comment by simongottschlag** [comment]
@xuzhang3 would it be possible for you to ask internally at Microsoft what the plans are for the updated SDK?

@aleqsss has been waiting for a reply for quite some time and would be great to understand what the plans are.

I created the following more than a week ago and still nothing: https://github.com/microsoft/azure-devops-go-api/issues/93

Thank you 😊

**Comment by xuzhang3** [comment]
@simongottschlag  Sure, I will update the information when I got response from service team.

**Comment by aleqsss** [comment]
Thank you for your input, @simongottschlag and @xuzhang3.

Unfortunately I haven't received any feedback whatsoever, on the [Add new taskagent resource functionality #90](https://github.com/microsoft/azure-devops-go-api/issues/90) issue/feature request. So an information update in regards of the plans of updating that SDK, would be highly appreciated @xuzhang3. Thank you for investigating this internally.

**Comment by aleqsss** [comment]
@xuzhang3 were you able to get any response from the service team?

Thank you! 🙂

**Comment by xuzhang3** [comment]
Hi @aleqsss We have some internal progress, I will update it here if there is any update.

**Comment by aleqsss** [comment]
Thank you @xuzhang3, I appreciate that!

**Comment by stefanes** [comment]
@xuzhang3 Any update on the internal progress you mentioned?

**Comment by xuzhang3** [comment]
@stefanes   I get some repsonse internal that v6.x will be released but do not have the timeline

**Comment by aleqsss** [comment]
@xuzhang3, any updates in regards of the timeline? 🙂

**Comment by danielpof** [comment]
> Thank you for your input, @simongottschlag and @xuzhang3.
> 
> Unfortunately I haven't received any feedback whatsoever, on the [Add new taskagent resource functionality #90](https://github.com/microsoft/azure-devops-go-api/issues/90) issue/feature request. So an information update in regards of the plans of updating that SDK, would be highly appreciated @xuzhang3. Thank you for investigating this internally.

Wouldn't they be using [AutoREST](https://github.com/Azure/autorest) like the [Azure SDK](https://devblogs.microsoft.com/azure-sdk/code-generation-with-autorest/)?

**Comment by mvanderlyn27** [comment]
Any update on the v6.x release?

**Comment by xuzhang3** [comment]
No good news,  the SDK repo is in low activity.  A workaround I thinking is embed the new features as a patch in this repo and handle the sdk  ourselves.  DevOps swagger:  https://github.com/MicrosoftDocs/vsts-rest-api-specs

**Comment by ramsateesh** [comment]
Is this coming up anytime soon ? Needed this like yesterday.

**Comment by aleqsss** [comment]
> > Thank you for your input, @simongottschlag and @xuzhang3.
> > Unfortunately I haven't received any feedback whatsoever, on the [Add new taskagent resource functionality #90](https://github.com/microsoft/azure-devops-go-api/issues/90) issue/feature request. So an information update in regards of the plans of updating that SDK, would be highly appreciated @xuzhang3. Thank you for investigating this internally.
> 
> Wouldn't they be using [AutoREST](https://github.com/Azure/autorest) like the [Azure SDK](https://devblogs.microsoft.com/azure-sdk/code-generation-with-autorest/)?

If you look at the filed issue https://github.com/microsoft/azure-devops-go-api/issues/90 (mentioned in this issue description) you can see that it seems like they are using some internal tool for generating this. 🙂

**Comment by aleqsss** [comment]
@xuzhang3 take a look at [this issue (#93)](https://github.com/microsoft/azure-devops-go-api/issues/93) (more specifically [this](https://github.com/microsoft/azure-devops-go-api/issues/93#issuecomment-901113724) and [this](https://github.com/microsoft/azure-devops-go-api/issues/93#issuecomment-904912783) post) in the azure-devops-go-api.

It seems like they've started the work with updating the SDK to 6.0 and 6.1. 🎉
So hopefully it won't be necessary with a workaround where we need to handle the SDK ourselves.

When this is done, it also enables the possibility to add functionality for the other missing parts of version 6.0 and 6.1, to this Azure DevOps Terraform provider, which to be honest would be most welcome. 🙂

> No good news, the SDK repo is in low activity. A workaround I thinking is embed the new features as a patch in this repo and handle the sdk ourselves. DevOps swagger: https://github.com/MicrosoftDocs/vsts-rest-api-specs

**Comment by xuzhang3** [comment]
Hi @aleqsss  thanks for ping me out here. we have noticed this issue,  after v6 and v6.1 SDK released, I will update the go.mod and `vendor` files.

**Comment by gabrielmccoll-rlg** [comment]
@nechvatalp Just to make you aware that @xuzhang3 was planning on updating here too so I'm hoping it's in your remit. Thank you !

**Comment by DevOpsBoondoggles** [comment]
[VMSS_agent.zip](https://github.com/microsoft/terraform-provider-azuredevops/files/7491175/VMSS_agent.zip)

Just in case this is useful to anyone else, the work around I managed to get was using the rest api and powershell and some null resources. the attached zip has two scripts, one for remove and one for adding the agent pool , along with a tf showing example of how used.

**Comment by gabrielmccoll-rlg** [comment]
also I think it needs 6.1 for this as Elastic Pools create doesn't seem to exist in 6.0 ?https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools/create?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-6.0

**Comment by xuzhang3** [comment]
@gabrielmccoll-rlg seems the `elastic pool` APIs  only available in preview APIs

**Comment by DevOpsBoondoggles** [comment]
> @gabrielmccoll-rlg seems the `elastic pool` APIs  only available in preview APIs

Yeah that's a shame. I notice it does mention elastic pools on the create pool api for 6.0 as a pooltype I think it was but no indication of how to use it.

**Comment by tmeckel** [comment]
@xuzhang3 @nechvatalp pushed the v6.0 API into `azure-devops-go-api` https://github.com/microsoft/azure-devops-go-api/pull/110 The v6.0 API contains the API definition and corresponding models for the `Elastic Pool Agents` which utilizes Azure Virtual Machine Scale Sets. What are the major steps to migrate the DevOps provider to use the v6.0 API? After that someone could implement resources and data sources to support `Elastic Pool Agents`.

**Comment by DevOpsBoondoggles** [comment]
> @xuzhang3 @nechvatalp pushed the v6.0 API into `azure-devops-go-api` https://github.com/microsoft/azure-devops-go-api/pull/110 The v6.0 API contains the API definition and corresponding models for the `Elastic Pool Agents` which utilizes Azure Virtual Machine Scale Sets. What are the major steps to migrate the DevOps provider to use the v6.0 API? After that someone could implement resources and data sources to support `Elastic Pool Agents`.

Sounds good. Am not sure you you do that with the v6 api. It was simple with the v6.1 so if there's an example of doing it with 6 that be great

**Comment by tmeckel** [comment]
I tried a quick upgrade of the provider to the v6 API. I expected some issue but surprisingly the new v6 API lacks some models, which, for my understanding, should not be the case .

**Example:**
![image](https://user-images.githubusercontent.com/14177833/144235483-037e2c88-1bbf-45c7-a793-5abab32d61eb.png)
 
@nechvatalp is there something wrong with the generation process? 

I checked the OpenAPI specification v6 for Git and the GitChange model is defined in the JSON File

https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/8284433147b306c76d642da782c58b6cdea8f5ad/specification/git/6.0/git.json#L11069

@xuzhang3

**Comment by nechvatalp** [comment]
@tmeckel yes, seems like problem with the generation.

I will look at it and try to fix it.

**Comment by DevOpsBoondoggles** [comment]
@tmeckel  @nechvatalp  thanks very much for keeping us updated on this and the other thread too

**Comment by nechvatalp** [comment]
@tmeckel I updated the generation tool and regenerated the clients, lot more models are present now. Hopefully, nothing is missing this time. Thanks for spotting the issue.

**Comment by tmeckel** [comment]
@nechvatalp great news 🤙🏼 I'll give it a try tomorrow!

**Comment by tmeckel** [comment]
@nechvatalp these are the issues that are left after you re-created the v6 API

```go
# github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/memberentitlementmanagement
azuredevops/internal/service/memberentitlementmanagement/resource_user_entitlement.go:330:60: clients.MemberEntitleManagementClient.GetUserEntitlements undefined (type memberentitlementmanagement.Client has no field or method GetUserEntitlements)
azuredevops/internal/service/memberentitlementmanagement/resource_user_entitlement.go:330:94: undefined: memberentitlementmanagement.GetUserEntitlementsArgs
# github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint
azuredevops/internal/service/serviceendpoint/commons.go:255:4: unknown field 'Project' in struct literal of type serviceendpoint.CreateServiceEndpointArgs
azuredevops/internal/service/serviceendpoint/commons.go:293:4: unknown field 'Project' in struct literal of type serviceendpoint.UpdateServiceEndpointArgs
azuredevops/internal/service/serviceendpoint/commons.go:304:4: unknown field 'Project' in struct literal of type serviceendpoint.DeleteServiceEndpointArgs
# github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent
azuredevops/internal/service/taskagent/resource_variable_group.go:303:4: unknown field 'Group' in struct literal of type taskagent.AddVariableGroupArgs
azuredevops/internal/service/taskagent/resource_variable_group.go:304:4: unknown field 'Project' in struct literal of type taskagent.AddVariableGroupArgs
azuredevops/internal/service/taskagent/resource_variable_group.go:314:4: unknown field 'Project' in struct literal of type taskagent.UpdateVariableGroupArgs
azuredevops/internal/service/taskagent/resource_variable_group.go:316:4: unknown field 'Group' in struct literal of type taskagent.UpdateVariableGroupArgs
azuredevops/internal/service/taskagent/resource_variable_group.go:327:4: unknown field 'Project' in struct literal of type taskagent.DeleteVariableGroupArgs
```

Looks great for the second attempt to do a major API upgrade :-)

I'm not sure if those issues are a result of the API has been changed or the generation process has still a bug. 
Do you have any information on this?

@xuzhang3 I'll file a draft PR for tracking the upgrade to the v6 API :-)

**Comment by nechvatalp** [comment]
@tmeckel I briefly looked at it, most of the issues seem to be changes in the APIs.

For the GetUserEntitlements this is present in [5.1 documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/get-user-entitlements?view=azure-devops-rest-5.1) but not in [6.0](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/get-user-entitlements?view=azure-devops-rest-5.1&viewFallbackFrom=azure-devops-rest-6.0). This doesn't seem intentional though, the API is there just not picked up by our generator not sure why, will need to investigate it a bit more.

For the service endpoints, the API changed in [6.0](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-6.0) and no longer uses `Project` attribute like [5.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-5.1) used to.

For the task agent stuff, `Group` got renamed to `VariableGroupParameters` as for the `Project` it seems like it got removed from the API similarly like with the service endpoints. [5.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/add?view=azure-devops-rest-5.1) vs [6.0](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/add?view=azure-devops-rest-6.0)

**Comment by tmeckel** [comment]
@nechvatalp Thanks that you took the time to look through the issues I reported. Highly appreciated!

My takeaways:

1. We will change the code for the `variable groups` and the `service endpoints` to match the changes in the v6.0 API
2. We will wait for your further investigations about the change for  `clients.MemberEntitleManagementClient.GetUserEntitlements`.  Any indication about the time frame here?

**Comment by tmeckel** [comment]
@nechvatalp I changed the code for `variable groups` and the `service endpoints`, whereas I've to admit that I don't think, that the new code for the `service endpoints` will work in the first place, because it's a huge change that the `project` parameter is removed from the `CreateServiceEndpoint` function and replaced by a `serviceendpoint.ServiceEndpointProjectReference`. Well as far as I understood the API 😁 

Now waiting for your results about `clients.MemberEntitleManagementClient.GetUserEntitlements`.

**Comment by nechvatalp** [comment]
@tmeckel Looked into it and the `GetUserEntitlements` was superseeded by [SearchUserEntitlements](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/search-user-entitlements?view=azure-devops-rest-6.0) in 6.0 I would recommend adopting that.

**Comment by tmeckel** [comment]
@nechvatalp I replaced the problematic code with something completely different which utilizes the `Identities` API. Which is even faster.

**Comment by tmeckel** [comment]
Any issues about migrating to v6 API can be found in the corresponding PR #494

**Comment by tmeckel** [comment]
@nechvatalp I checked if the v6 api contains the endpoints to create elastic pool agents, but sadly enough that isn't the case. So @gabrielmccoll (@gabrielmccoll-rlg) was right with comment https://github.com/microsoft/terraform-provider-azuredevops/issues/204#issuecomment-962959946 that at least v6.1 of the DevOps API is required to manage elastic pool agents.

So what are the plans with the GO API? Will there be support for v6.1 or will be the next step v7? And will v7 include everything of v6.1? And when will v6.1 or v7 be available?

**Comment by DevOpsBoondoggles** [comment]
> @nechvatalp I checked if the v6 api contains the endpoints to create elastic pool agents, but sadly enough that isn't the case. So @gabrielmccoll (@gabrielmccoll-rlg) was right with comment https://github.com/microsoft/terraform-provider-azuredevops/issues/204#issuecomment-962959946 that at least v6.1 of the DevOps API is required to manage elastic pool agents.
> 
> 
> 
> So what are the plans with the GO API? Will there be support for v6.1 or will be the next step v7? And will v7 include everything of v6.1? And when will v6.1 or v7 be available?

Thanks for this 
I believe I checked and the api was not in 7.0 for elastic pools. Just 6.1. Which is weird but not unusual for msoft tbh. Many of the azurerm apis seem to just jump from preview to preview.

**Comment by nechvatalp** [comment]
@tmeckel @gabrielmccoll The plan is to release new GO version with each new major ADO release. Next API version will be 7.0 coming with AzureDevOps 2022 early next year. I won't be releasing 6.1.

The elastic polls apis will be in the 7.0 release, all apis which are currently 6.1 should be in 7.0.

**Comment by tmeckel** [comment]
@nechvatalp Good to hear that at least we have something like a roadmap 👍🏼 and that `7.0` will contain cumulatively all changes `>6.0` is good to hear too 😀 Hopefully "... _early next year_" does not mean Q2 2022 🤣

**Comment by tmahncke-lhind** [comment]
@nechvatalp do you have an idea about a timeline? Is there any way this can be supported or is access to the internal code required in order to generate the new objects?

We are currently working around the issue manually, but since we have quite a few Azure DevOps VMSS agent pools in use this would be quite a help.

**Comment by xuzhang3** [comment]
@tmahncke-lhind  VMSS API is not available in v6 SDK. A workaround for this is to use  [terraform  local-exec ](https://www.terraform.io/language/resources/provisioners/local-exec) with `azure cli ` or `powershel`

**Comment by DevOpsBoondoggles** [comment]
@tmeckel @nechvatalp heya just wondering if there's any progress towards v7

**Comment by tmeckel** [comment]
@gabrielmccoll seems nobody is working on the Azure DevOps Go SDK and as long as version 7.1 is not supported the provider can't support creating elastic agent pools.

**Comment by DevOpsBoondoggles** [comment]
> @gabrielmccoll seems nobody is working on the Azure DevOps Go SDK and as long as version 7.1 is not supported the provider can't support creating elastic agent pools.
> 
> 

Dang. At times like this I wish I knew Go. Or proper developing.

**Comment by aristosvo** [comment]
Please vote on this issue: https://developercommunity.visualstudio.com/t/Update-of-the-Go-SDK-to-include-new-feat/10186787

**Comment by SSKLCP** [comment]
[7.1 is now released!](https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv7.1.0)

**Comment by aleqsss** [comment]
Finally, thank you for noticing this @SSKLCP! 👍

@xuzhang3 and @tmeckel, hint hint... 😁

**Comment by PLsergent** [comment]
Hi!
With this new version, can we hope for an integration within the provider? 😄

**Comment by keithfree** [comment]
~90 days later...still hoping :)

**Comment by DevOpsBoondoggles** [comment]
Yesssss ! Good job @xuzhang3 !

**Comment by yirmio** [comment]
Thanks!
