### ISSUE TITLE
Branch Policy Minimum Reviewers Additional Settings

### ISSUE THREAD

**Issue by birchb1024** [microsoft/terraform-provider-azuredevops#206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We want to add more settings to the Minimum Reviewers resource. From the REST API they are:

                "allowDownvotes"
                "resetOnSourcePush"
                "requireVoteOnLastIteration"
                "resetRejectionsOnSourcePush"
                "blockLastPusherVote"

### New or Affected Resource(s)

* azuredevops_branch_policy_min_reviewers

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_min_reviewers" "p" {
  project_id = azuredevops_project.p.id

settings {
  last_pusher_cannot_approve = true
  allow_completion_with_rejects_or_waits = true
  on_push_reset_approved_votes = true
  on_push_reset_all_votes = true
  on_last_iteration_require_vote = true
}
```

### References

* [Azure Devops API Documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/?view=azure-devops-rest-6.0)
* [Azure Devops User Documentation](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)

#### Example Settings from the API (since settings are not documented):

```JSON
        {
            "createdBy": {
                "displayName": "Bill Birch",
                "url": "https://spsprodeau1.vssps.visualstudio.com/redactedredacted"
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/billbirchredactedredacted"
                    }
                },
                "id": "redacted-redacted",
                "uniqueName": "bill.birch@coles.com.au",
                "imageUrl": "https://dev.azure.com/billbirch/redactedredacted",
                "descriptor": "redactedredacted"
            },
            "createdDate": "2020-10-15T08:21:46.5683546Z",
            "isEnabled": true,
            "isBlocking": true,
            "isDeleted": false,
            "settings": {
                "minimumApproverCount": 10,
                "creatorVoteCounts": true,
                "allowDownvotes": true,
                "resetOnSourcePush": true,
                "requireVoteOnLastIteration": false,
                "resetRejectionsOnSourcePush": false,
                "blockLastPusherVote": true,
                "scope": [
                    {
                        "refName": "refs/heads/master",
                        "matchKind": "Exact",
                        "repositoryId": null
                    }
                ]
            },
            "isEnterpriseManaged": false,
            "_links": {
                "self": {
                    "href": "https://dev.azure.com/billbirch/redactedredacted/_apis/policy/configurations/11"
                },
                "policyType": {
                    "href": "https://dev.azure.com/billbirch/redactedredacted/_apis/policy/types/fa4e907d-c16b-4a4c-9dfa-4906e5d171dd"
                }
            },
            "revision": 12,
            "id": 11,
            "url": "https://dev.azure.com/billbirch/redactedredacted/_apis/policy/configurations/11",
            "type": {
                "id": "fa4e907d-c16b-4a4c-9dfa-4906e5d171dd",
                "url": "https://dev.azure.com/billbirch/redactedredacted/_apis/policy/types/fa4e907d-c16b-4a4c-9dfa-4906e5d171dd",
                "displayName": "Minimum number of reviewers"
            }
        }
```
```

**Comment by birchb1024** [comment]
I have started working on this one. Our Fork is here: https://github.com/colesgroup/terraform-provider-azuredevops

**Comment by nvmathure** [comment]
Are you still working on this feature? I need it for my integration. Please let me know how can I contribute to the work you have already started.

**Comment by birchb1024** [comment]
Yes, I have to push up a PR today

Bill

**Comment by birchb1024** [comment]
I'll push to our fork and let you know.

**Comment by birchb1024** [comment]
Hi,

please see PR #255.

Regards,
Bill

**Comment by xuzhang3** [comment]
Close this issue , feature request  has been implemented and merged.
