### ISSUE TITLE
Error: Value cannot be null.

### ISSUE THREAD

**Issue by dhjensen** [microsoft/terraform-provider-azuredevops#207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

* Terraform v0.13.4

### Affected Resource(s)

* azuredevops_build_definition

### Terraform Configuration Files

```hcl
resource "azuredevops_build_definition" "helloworldbuild" {
  project_id = data.azuredevops_project.webpage.id
  name       = "HelloWorld build pipeline"
  #path       = "\\ExampleFolder"

  ci_trigger {
    use_yaml = true
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = data.azuredevops_git_repositories.helloworld.repositories[0].id
    branch_name = data.azuredevops_git_repositories.helloworld.repositories[0].default_branch
    yml_path    = "azure-pipelines.yml"
  }

  variable {
    name  = "runAllStages" 
    
  }

}
```

### Expected Behavior

Since the documentation states that value is optional I exspect it to create a pipeline variable with no consern about the value.

### Actual Behavior

azuredevops_build_definition.helloworldbuild: Modifying... [id=5]

Error: Value cannot be null.
Parameter name: definition.Variables.Variable.Value

  on azuredevops.tf line 31, in resource "azuredevops_build_definition" "helloworldbuild":
  31: resource "azuredevops_build_definition" "helloworldbuild" {

### Steps to Reproduce

1. `terraform apply`
2. Yes
3. boom

### References

* #0000

**Comment by xuzhang3** [comment]
@dhjensen  Thanks for your feedback. This should be a bug in reading variable default value.   Suggest config the values manually .  I will add more constraints for the variables and update the document. constraints

**Comment by dhjensen** [comment]
> @dhjensen Thanks for your feedback. This should be a bug in reading variable default value. Suggest config the values manually . I will add more constraints for the variables and update the document. constraints

@xuzhang3 If I do as you suggest and specify the "values" / "variables" manually this resource will destroy them on subsequent `terraform apply` runs
The best workaround I have been able to find is to configure an empty variable in a variable group. But even in that case it will overide any values I add to the variable  on subsequent runs.

**Comment by xuzhang3** [comment]
@dhjensen Can you share your new TF script?  Before execute `terraform apply`, you can  use `terraform plan` to track the difference.

**Comment by xuzhang3** [comment]
> > @dhjensen Thanks for your feedback. This should be a bug in reading variable default value. Suggest config the values manually . I will add more constraints for the variables and update the document. constraints
> 
> @xuzhang3 If I do as you suggest and specify the "values" / "variables" manually this resource will destroy them on subsequent `terraform apply` runs
> The best workaround I have been able to find is to configure an empty variable in a variable group. But even in that case it will overide any values I add to the variable on subsequent runs.

@dhjensen   This is Terraform's behavior.   Variable objects in  ADO provider are defined as `Set`,  when object property changed,  Terraform will treat the old object no longer  existed.

**Comment by dhjensen** [comment]
> @dhjensen Can you share your new TF script? Before execute `terraform apply`, you can use `terraform plan` to track the difference.

I'm not sure which code you wanted, this is what I ended up doing.:
```
resource "azuredevops_build_definition" "helloworldbuild" {
  project_id = data.azuredevops_project.webpage.id
  name       = "HelloWorld build pipeline"
  #path       = "\\ExampleFolder"

  ci_trigger {
    use_yaml = true
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = data.azuredevops_git_repositories.helloworld.repositories[0].id
    branch_name = data.azuredevops_git_repositories.helloworld.repositories[0].default_branch
    yml_path    = "azure-pipelines.yml"
  }

  variable {
    name        = "runAllStages"
    value       = "False"
  }

}
```

**Comment by dhjensen** [comment]
> > > @dhjensen Thanks for your feedback. This should be a bug in reading variable default value. Suggest config the values manually . I will add more constraints for the variables and update the document. constraints
> > 
> > 
> > @xuzhang3 If I do as you suggest and specify the "values" / "variables" manually this resource will destroy them on subsequent `terraform apply` runs
> > The best workaround I have been able to find is to configure an empty variable in a variable group. But even in that case it will overide any values I add to the variable on subsequent runs.
> 
> @dhjensen This is Terraform's behavior. Variable objects in ADO provider are defined as `Set`, when object property changed, Terraform will treat the old object no longer existed.

I will have to take your word for it.
However it would be nice for it to only "care" about the existance of the variables. Would be nice to be able to just specify variables with no values. Add value later without triggering terraform changes when it keeps the empty variable state.

**Comment by dhjensen** [comment]
@xuzhang3 I no longer use these resources so I cannot give any more feedback on the matter. You can close this issue if there is confirmation of a fix?

**Comment by xuzhang3** [comment]
Close this issue,  feel free to open another issue if you have questions.
