### ISSUE TITLE
Design: Support AzDO Variable Groups

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#21]
As a developer I want to provision a pipeline that can consume variables from a variable group. This story is a design story to figure out how to do that!

# Acceptance criteria
- [x] Investigate how to provision variable groups. Values should be able to be marked as a secret.
- [x] Investigate how to link variables with build definitions
- [x] Document schema for variable group in this issue as a comment.
- [x] Review schema and implementation plan with team through GitHub comments
- [x] After review, write implementation stories. Each story should contain all information needed to implement the feature. Each feature should take about 1-2 days to implement and should include the relevant unit/acceptance tests/documentation.

# Notes from a long time ago. Not well thought through... Please feel free to ignore these!

The terraform template could model the variable group as follows
```terraform
resource "azuredevops_variable_group" "my_variable_group" {
  name = "my-variable-group"
  description = "my variable group description"
  allow_access = true
  variable {
    name = "my-variable-1-name"
    value = "my-variable-1-value"
    is_secret = true
  }
  variable {
    name = "my-variable-2-name"
    value = "my-variable-2-value"
    is_secret = true
  }
}
```

The AzDo api only exposes a resource for variable group. The variable group resource expects the variables within to be provided as part of the payload. Therefore, the variables should be provided within the variable group resource in the terraform template

**Comment by TsuyoshiUshio** [comment]
Hi @nmiodice 

I had some research for the API. Also, I need to discuss something about this. 
Any comment is welcome.
# User Interface

![Screen Shot 2019-10-29 at 12 08 59 PM](https://user-images.githubusercontent.com/1390976/67808597-35e66800-fa54-11e9-80ae-aa77f66d79a8.png)


# Example Usage

## Plain Variables group (The first implementation)

```hcl
resource "azuredevops_variable_group" "my_variable_group" {
      project_id = azuredevops_project.id    // Required
      name = "my-variable-group"  
      description = "my variable group description"
      allow_access  = "true"
      variables {
            key  = "key1"
            value = "value1"
            is_secret = true
      }
      variables {
             key = "key2"
             value = "value2"
     }
}
```

## With KeyVault reference (The second implementation)

After that, we can implement Azure KeyVault integration. at that time, 

```hcl
resource "azuredevops_variable_group" "my_variable_group" {
      project_id = azuredevops_project.id    // Required
      service_endpoint_id = azuredevops_service_endpoint.id  // It requires service principal service end point
      vault = "avault"
      name = "my-variable-group"  
      description = "my variable group description"
      type = "AzureKeyVault"     // Default is "Vsts"
      allow_access  = "true"
      variables {
            key  = "key1"
            value = "value1"
            is_secret = true
      }
      variables {
             key = "key2"
             is_secret = true
             is_vault = true
     }
}
```

# Discussion Topic 

This resource requires two APIs. To create a Variables Group, it has "variables group" API listed below. However, to "allow access to all pipeline", it requires, "authorized project resources" API. 
This is totally different API. However, for the convenience and simplicity of the authorized project resources API, I choose to call two APIs in this resource.  However, any suggestion is welcome.

# API

## [Variable groups](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/add?view=azure-devops-rest-5.1)

This request create a Variables Group. However, not include access_allow. 

* [Go SDK](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/taskagent/client.go#L39)

### Sample Request

POST  https://dev.azure.com/<ORG_NAME>/<PROJECT_ID>/_apis/distributedtask/variablegroups?api-version=5.1-preview.1

BODY
```son
{
  "variables": {
    "key1": {
      "value": "value1"
    },
    "key2": {
      "value": "value2",
      "isSecret": true
    }
  },
  "type": "Vsts",
  "name": "TestVariableGroup1",
  "description": "A test variable group"
}
```

RESPONSE

```json
{
    "variables": {
        "key1": {
            "value": "value1"
        },
        "key2": {
            "value": null,
            "isSecret": true
        }
    },
    "id": 6,
    "type": "Vsts",
    "name": "TestVariableGroup1",
    "description": "A test variable group",
    "createdBy": {
        "displayName": null,
        "id": "2b673dea-9d3b-4ee4-b3fb-c84f7bab27b7"
    },
    "createdOn": "2019-10-29T19:07:08.9666667Z",
    "modifiedBy": {
        "displayName": null,
        "id": "2b673dea-9d3b-4ee4-b3fb-c84f7bab27b7"
    },
    "modifiedOn": "2019-10-29T19:07:08.9666667Z",
    "isShared": false,
    "variableGroupProjectReferences": [
        {
            "projectReference": {
                "id": "<PROJECT_ID>",
                "name": "Test Project"
            },
            "name": "TestVariableGroup1",
            "description": "A test variable group"
        }
    ]
}
```

## [Authorized Project Resource](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/authorizedresources/authorize%20project%20resources?view=azure-devops-rest-5.1#definitionresourcereference)

This API authorized something to some resources. In this Terraform resource, we use this to allow access to all pipeline which you can see it on the screen shot.

* [GO SDK Client](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/build/client.go#L395)
*[GO SDK Models](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/build/models.go#L1226)

### Sample Request

PATCH //dev.azure.com/<ORG_NAME>/<PROJECT_ID>/_apis/build/authorizedresources?api-version=5.1-preview.1

Body

```json
[
    {
        "authorized": true,
        "id": 6,
        "name": "TestVariableGroup1",
        "type": "variablegroup"
    }
]
```

Response

```json
{
    "count": 2,
    "value": [
        {
            "name": "Private Testing Agents",
            "type": "queue",
            "id": "298",
            "authorized": true
        },
        {
            "type": "variablegroup",
            "id": "6",
            "authorized": true
        }
    ]
}
```

# Additional Example

The example for creating Variable Groups with KeyVault configuration. Under the hood, it create a service principal automatically, and set it as service connection. In case of terraform, we can configure it after creating service_connection with service principal, then use the id to configure this. 
This is the example is captured by chrome on AzureDevOps. 

POST https://6packdevops.visualstudio.com/_apis/distributedtask/variablegroups

Body 

```json
{
    "description": "",
    "name": "KeyVault Link",
    "providerData": {
        "serviceEndpointId": "ed6a8047-922b-4378-b74b-50087580757c",
        "vault": "tsushivault",
        "lastRefreshedOn": "2019-10-30T08:37:16.484Z"
    },
    "type": "AzureKeyVault",
    "variables": {
        "hello": {
            "isSecret": true,
            "value": "",
            "enabled": true,
            "contentType": "",
            "expires": null
        }
    },
    "variableGroupProjectReferences": [
        {
            "description": "",
            "name": "KeyVault Link",
            "projectReference": {
                "id": "<PROJECT_ID>",
                "name": ""
            }
        }
    ]
}

```

**Comment by TsuyoshiUshio** [comment]
# Stories 

* Implement new resource "azuredevops_variable_group"
* Add KeyVault reference feature for VariableGroups Resource

 In case, you want to split Authorized Project Resource, 
* Implement new resource azuredevops_authorized_project_resource

However, the API is too abstract.  So for the usability, to implement it inside of the azuredevops_variables_group might be fine, IMO.

**Comment by nmiodice** [comment]
Great work! Thx for the investigation.

Some comments/questions:
 - What needs to change for the `azuredevops_build_definition` resource in order to consume these variable groups? The API reference is [located here](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/definitions/create?view=azure-devops-rest-5.0#variablegroup). I imagine that we can support it by taking a list of variable group IDs... For example:

```hcl
resource "azuredevops_variable_group" "group1" {
    ...
}
resource "azuredevops_variable_group" "group2" {
    ...
}
resource "azuredevops_build_definition" "build" {
    ...
    variable_groups = azuredevops_variable_group.*.id
}
```

 - Can you provide a more concrete schema that includes default values, accepted values, and which values will have `ForceNew := true` set? Which ones do we support `UPDATE` for?

 - I think that its OK to include the pipeline authorization in this resource -- I agree, it is too abstract to be useful in isolation, and belongs inside the variable_group resource

 - I like your approach with regards to using the `service_principal_id` rather than creating it under the hood. This makes a lot of sense!

 - It may make sense to put the Key Vault metadata into its own property -- `keyvault` or something -- with all the fields that logically tie to the Key Vault. That way you can infer if the KeyVault configuration is needed based on whether or not the property exists, and you can leverage more of Terraform's schema validation by saying that the top level is optional, but if its supplied, then the lower level attributes are required

**Comment by TsuyoshiUshio** [comment]
# Build definition 

I tried the API, Your recommendation is right. It just requires id and it looks required. In this case, variables_groups is  like below, it is an array of the object. 

```
    "variableGroups": [
        {
            "id": 6
        }
    ],
```

I just don't know the notation of following. Is it works? If works? I'll take your advice. :)

```
resource "azuredevops_variable_group" "group1" {
    ...
}
resource "azuredevops_variable_group" "group2" {
    ...
}
resource "azuredevops_build_definition" "build" {
    ...
    variable_groups = azuredevops_variable_group.*.id
}
```
# Schema definition. 

I'll update the comment. 

# KeyVault metadata
It is the part of the VariableGroupProviderData, However, it doesn't expose the spec, when I observed via chrome, it only has service_endpoint and vault (keyvault name) and RefleshedOn. However, your suggestion might be right. currently only name needed however make it inside of keyvault object. I'll update the comment. 
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/add?view=azure-devops-rest-5.1#variablegroupproviderdata

**Comment by TsuyoshiUshio** [comment]
Hi @nmiodice 
I answered your comment and update the definition. Thank you for your great advice. I took all of them and experiment if it works.

**Comment by TsuyoshiUshio** [comment]
@nmiodice 
Awesome! I love your idea! I'll take it! It simplify it and gain the ability to validation.
