### ISSUE TITLE
Add support for Github Enterprise service connection

### ISSUE THREAD

**Issue by veyu** [microsoft/terraform-provider-azuredevops#210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a user I would like to create Github Enterprise service connection. It could be done by modifying currently existing `azuredevops_serviceendpoint_github` or by creating new resource `azuredevops_serviceendpoint_github_enterprise`.

### New or Affected Resource(s)

Modify
* azuredevops_serviceendpoint_github

or create new 

* azuredevops_serviceendpoint_github_enterprise

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_github" "serviceendpoint_gh_1" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "Sample GithHub Enterprise Personal Access Token"

  auth_personal {
    server_url = "https://github.mydomain.com/"
    # Also can be set with AZDO_GITHUB_SERVICE_CONNECTION_PAT environment variable
    personal_access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

**Comment by xuzhang3** [comment]
Close this issue for resource has been implemented.

**Comment by AdamSir2** [comment]
@xuzhang3 AZDO_GITHUB_SERVICE_CONNECTION_PAT doesn't seem to be working for me - any ideas if this has changed?

**Comment by xuzhang3** [comment]
@AdamSir2 How your export your ENVs? This config still working.

**Comment by AzySir** [comment]
@xuzhang3  can confidently confirm this does not work from OS X - unless the error message is not relevant which is very windowsesque.

I am running this as `export AZDO_GITHUB_SERVICE_CONNECTION_PAT=gh_<hash_here>`

**Comment by AzySir** [comment]
I will try to run this in a docker container for testing purposes
