### ISSUE TITLE
work_item_template shouldn't destroy your project 

### ISSUE THREAD

**Issue by HarleyB123** [microsoft/terraform-provider-azuredevops#211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When changing the work_item_template, i've noticed that it destroys the project and creates a new one with the desired work_item_template. This nearly caught me out before, as it destroyed my project and all the code within it! (Thankfully we could restore)

### New or Affected Resource(s)

* azuredevops_project

### Potential Terraform Configuration

Would be the same as it currently is, except Terraform doesn't destroy the project 😄

**Comment by xuzhang3** [comment]
@HarleyB123  Project process can be changed in organization properties configuration page. This is an organization level configure and cannot be changed at project level. Also current projects API does not support change project processes [Projects API](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/processes?view=azure-devops-rest-6.0),  I think current provider behavior is correct.

**Comment by HarleyB123** [comment]
Hey @xuzhang3 - Thanks for this! 

Looking at the API documentation I agree, it would be impossible to cater for this need without there first being a change in the API itself.

Whilst slightly difficult to appreciate or understand from a users view (as I just want to change a projects process and retain all board items - the only way to do this after creating a project is to import it to the state), the current provider behaviour is indeed correct
