### ISSUE TITLE
[Bug] - terraform apply with azuredevops_resource_authorization resource

### ISSUE THREAD

**Issue by rasanjaya85** [microsoft/terraform-provider-azuredevops#215]
Error: Provider produced inconsistent result after apply

When applying changes to
azuredevops_resource_authorization.auth_iam_cloud_connection, provider
"registry.terraform.io/-/azuredevops" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by xuzhang3** [comment]
@rasanjaya85 Can you share your TF config or error details?

**Comment by petersonsbuild** [comment]
I'm getting the same error:

```
Error: Provider produced inconsistent result after apply

When applying changes to azuredevops_resource_authorization.projectb_auth,
provider "registry.terraform.io/microsoft/azuredevops" produced an unexpected
new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Here is my configuration:

```
data "azuredevops_project" "projecta" {
  name = "ProjectA"
}

data "azuredevops_project" "projectb" {
  name = "ProjectB"
}

resource "azuredevops_agent_pool" "fargate_pool" {
  name           = "FargatePool"
  auto_provision = false
}

resource "azuredevops_agent_queue" "fargate_queue" {
  project_id    = data.azuredevops_projecta.project.id
  agent_pool_id = azuredevops_agent_pool.fargate_pool.id
}

resource "azuredevops_resource_authorization" "projecta_auth" {
  project_id  = data.azuredevops_project.projecta.id
  resource_id = azuredevops_agent_queue.fargate_queue.id
  type        = "queue"
  authorized  = true
}  

resource "azuredevops_resource_authorization" "projectb_auth" {
  project_id  = data.azuredevops_project.projectb.id
  resource_id = azuredevops_agent_queue.fargate_queue.id
  type        = "queue"
  authorized  = true
}
```
It appears that when I attempt to do cross-account-authorization I get this error.

**Comment by xuzhang3** [comment]
@plbenpeterson In DevOps, organization agent pool and project agent pool are different. `projectb_auth` reference to an agent pool  exist in `projecta`. You need create an agent pool for `projectb` then  you can  then you can do the authorization.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
