### ISSUE TITLE
Check the PR with GitHub Action

### ISSUE THREAD

**Issue by mikaelkrief** [microsoft/terraform-provider-azuredevops#220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Use GitHub Action instead Azure Pipelines for check PR.

==> My PR for implement this , will be done asap.

**Comment by mikaelkrief** [comment]
@nmiodice , at the requirement of this GitHub action workflow you need to create secrets in the GitHub Settings of the repository like as in the following image:

![image](https://user-images.githubusercontent.com/2725302/70794900-03dc5b80-1d9f-11ea-85b1-d2effbe2ad7c.png)

**Comment by mikaelkrief** [comment]
PR #222

**Comment by nmiodice** [comment]
Closing based on the following limitation of GH secrets:
```
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```

source: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#using-encrypted-secrets-in-a-workflow
