### ISSUE TITLE
Support Kubernetes as service endpoint type

### ISSUE THREAD

**Issue by saidst** [microsoft/terraform-provider-azuredevops#221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ADO provides *service connections / service endpoints for Kubernetes Clusters*.
These allow for the encapsulation of environment-specific access credentials from environment-independent code like e.g. an Azure Pipelines.

Currently, there is standard solution for automating CRUD-operations on such a service connection available. When using the REST-API provided by ADO in conjunction with terraform/ansible one faces two levels of abstraction which is ugly.  
terraform provides a high level whereas the REST-API has still quite some low-level semantics. 
Also, many users still create these service connections manually through the GUI.

Thus, we suggest to implement a terraform resource for managing ADO's Kubernetes service connections.

**Use Cases**
*Provisioning of Azure Kubernetes Service (AKS)*
A prominent example for utilising this resource in CI/CD-processes is the *provisioning of AKS*. 
After deployment of AKS through terraform, a service connection / environment needs to be created prior to e.g. being able to deploy k8s-resources through Azure Pipeline's *Kubernetes*-Task.  
Currently, there is no standard-solution provided by ADO. This is problematic if you want to automate E2E-Deployment of an environment: from AKS up to Pods. 
This terraform-resource could satisfy this need.

### New or Affected Resource(s)

* azuredevops_serviceendpoint_kubernetes

#### Azure subscription-based credentials
```hcl
resource "azuredevops_serviceendpoint_kubernetes" "aks_endpoint" {
  project_id            = "phoenix-project"
  service_endpoint_name = "dev1-kubernetes"
  apiserver_url = "https://my-aks-709b2401.hcp.westeurope.azmk8s.io"
 
  authorization_type = "AzureSubscription"
  azure_subscription  {
    azure_environment = "AzureCloud"
    cluster_name = "my aks"
    subscription_id = "6fe632ae-367b-4ec7-b157-639175dd5055"
    subscription_name = "my-subscription"
    tenant_id = "6fe632ae-367b-4ec7-b157-639175dd5055" 
    resourceGroup_id = "ddb7a2d9-31a4-435c-965b-a6107c9e1c3e"
    namespace = "default"
  }
}
```

#### Service Account-based credentials
```hcl
resource "azuredevops_serviceendpoint_kubernetes" "aks_endpoint" {
  project_id            = "phoenix-project"
  service_endpoint_name = "dev1-kubernetes"
  apiserver_url = "https://my-aks-709b2401.hcp.westeurope.azmk8s.io"
 
  authorization_type = "ServiceAccount"
  service_account {
    token = "bXktYXBw"
    ca_cert = "Mzk1MjgkdmRnN0pi"
  }
}
```

#### Kubeconfig-based credentials
```hcl
resource "azuredevops_serviceendpoint_kubernetes" "aks_endpoint" {
  project_id            = "phoenix-project"
  service_endpoint_name = "dev1-kubernetes"
  apiserver_url = "https://my-aks-709b2401.hcp.westeurope.azmk8s.io"
 
  authorization_type = "Kubeconfig"
  kubeconfig {
    accept_untrusted_certs = true
    kube_config = <<EOT
     --- 
     apiVersion: v1 
     clusters:
     - cluster:
     certificate-authority-data:
     <more yaml here>
      ...
    EOT
  }
}
```

### References

n/a

**Comment by saidst** [comment]
I want to work on this.

Besides CLA, what is your process of designing a feature?

**Comment by Jyoti492** [comment]
@saidst I also want to use this feature . Did you get any reply when this will be developed ?
I would like to help if required.

**Comment by saidst** [comment]
I have not received any response so far.
However, I've done first private, prototype implementations.

**Comment by nmiodice** [comment]
Hi, sorry for the delay. I have bad filters on my inbox and missed this!

Regarding the design proposal, can you please provide me with an example API post for configuring such an endpoint? Also, have you looked at the existing service connection resources? They will abstract quite a bit of the implementation logic away to make your implementation easier @saidst @Jyoti492

**Comment by saidst** [comment]
I've seen your abstractions. They speed things up.
Based on them, I've done a very basic test-implementation for a certain subtype of the kubernetes endpoint: [resource_serviceendpoint_kubernetes.go](https://github.com/saidst/terraform-provider-azuredevops/blob/feature/kubernetes-serviceendpoint/azuredevops/resource_serviceendpoint_kubernetes.go)

To what do you refer with *example API post* ?  
If you mean the JSON-Structure, please see this:
```
{
    "authorization": {
        "parameters": {
            "azureEnvironment": "AzureCloud",
            "azureTenantId": "<ID>",
            "serviceAccountCertificate": null
        },
        "scheme": "Kubernetes"
    },
    "data": {
        "authorizationType": "AzureSubscription",
        "azureSubscriptionId": “<ID>“,
        "azureSubscriptionName": “<NAME>“,
        "clusterId": “<ARM Resource ID>“,
        "namespace": "default"
    },
    "name": "my-serviceconnection",
    "type": "kubernetes",
    "url": “<URL TO K8S APISERVER>“
}
```

**Comment by Jyoti492** [comment]
@nmiodice any update please ?

**Comment by Jyoti492** [comment]
@saidst : have you started working on it and do you know the expected delivery time ?

**Comment by saidst** [comment]
Not (officially). I try to stick to the contribution guidelines. According to them, the anticipated new features first needs to be accepted and second be assigned to someone.

Also, I figured, that we need to invest further efforts into the semantics of the resource prior to implementation.

**Comment by saidst** [comment]
@nmiodice: have you had the chance to take a look on the latest comments?
We would like to work on this piece.

**Comment by nmiodice** [comment]
@saidst sorry for the delay here -- I have been in and out of the office as I prepare for my wedding next week. Needless to say things have been a *little* crazy on my end.

I apologize for the delay and think that your approach makes a lot of sense. I'll go ahead and assign this story to you and you can feel free to post a PR when you have an implementation that works.

**Note** I'll be unable to pay much attention to the PRs over the next 2 weeks off as I'll be out of office during the week of my wedding (and a few days after). Expect delays!

**Comment by saidst** [comment]
Updated semantics of resource. See initial post.

**Comment by nmiodice** [comment]
@saidst any ETA on a PR?

**Comment by saidst** [comment]
We are almost there. Expect to open the PR today/tomorrow.
Will rebase onto master now and see which suprises I encounter.

**Comment by mcmcghee** [comment]
This would almost complete our automation via terraform and would be a killer feature! Right now we have to do this manually and prevents us from doing automated destroy and create jobs.

**Comment by saidst** [comment]
The PR is already open. We need to figure with Microsoft how to proceed on it. There seems to be parallel development going on, which needs to be synced.

**Comment by nmiodice** [comment]
@saidst @mcmcghee 

There are pending merge conflicts in the PR and also the build is not passing! Please fix and we can get this in :)

https://github.com/microsoft/terraform-provider-azuredevops/pull/236

**Comment by saidst** [comment]
We are on it.

Can you give us read-access to your Azure Pipelines in order to see the build logs? 

Linting seem so fail.

**Comment by nmiodice** [comment]
Let me deep dive on this a little bit today to see whether or not I can grant access without giving away access to some sensitive internal-only information

**Comment by tmeckel** [comment]
@nmiodice I had a quick check about the same issue in another project ... problem is, well as far as I understood the AzDO docs: you cannot grant access to people from an public project in GitHub because there's no "everyone" or "read" role, that is assigned to an account for a public project while accessing a connected resource in AzDO. For a private GitHub project you've no issue at all, because you can assign rights in AzDO based on the group (role) memberships in GitHub.

**Comment by nmiodice** [comment]
@tmeckel did you find any creative workarounds?

**Comment by nmiodice** [comment]
I'm reaching out to Azure DevOps experts in my org to look in depth on my end.

**Comment by saidst** [comment]
Thanks for your support. I am confident to sort things without that read-access. However, for mid-term, I think we need it.

**Comment by tmeckel** [comment]
> 
> 
> @tmeckel did you find any creative workarounds?

No, unfortunately not, although I must admit that I didn't really have time to fully analyze the problem and find a solution.

**Comment by nmiodice** [comment]
This feature is now merged

**Comment by tmeckel** [comment]
@nmiodice Can this be closed now?

**Comment by nmiodice** [comment]
Oops... I thought I closed it :)
