### ISSUE TITLE
Resource for bitbucket connection

### ISSUE THREAD

**Issue by ssala7** [microsoft/terraform-provider-azuredevops#223]
We have repository in bitbucket and In azure DevOps we can create service connection with bitbucket We would like to do the same using terraform please provide an resource for azuredevops_bitbucket_repository

**Comment by jonasbark** [comment]
https://github.com/microsoft/terraform-provider-azuredevops/issues/219

**Comment by nmiodice** [comment]
Closed by https://github.com/microsoft/terraform-provider-azuredevops/pull/260
