### ISSUE TITLE
Resource for regular git repositories service endpoint

### ISSUE THREAD

**Issue by amnk** [microsoft/terraform-provider-azuredevops#229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_serviceendpoint_git

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "project" {
  project_name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_git" "git" {
  project_id             = azuredevops_project.project.id
  service_endpoint_name  = "yet_another_git_repo"
  description = "Endpoint for another git repo"
    
  git_repository_url = "https://<my.private.server>"
  git_username = "xxx"
  git_password = "xxx"
}
```

**Comment by xuzhang3** [comment]
@amnk you can find github service endpoint document here [link](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/serviceendpoint_github.html.markdown)
