### ISSUE TITLE
Support for Git files

### ISSUE THREAD

**Issue by logachev** [microsoft/terraform-provider-azuredevops#23]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would be great to be able to control files in Git repositories from Terraform.

Similar to github provider: https://www.terraform.io/docs/providers/github/r/repository_file.html

### New or Affected Resource(s)

`azuredevops_repository_file`

### Potential Terraform Configuration

```hcl
resource "azuredevops_repository_file" "gitignore" {
  repository_id = "example"
  file       = ".gitignore"
  content    = "**/*.tfstate"
}
```

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @logachev , Thanks for open this issue. Relate APIs [COMMIT](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20push%20commits?view=azure-devops-rest-5.1) [PUSH](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-5.1)
If you want push or commit files now . You can use [Terraform provisioners](https://www.terraform.io/docs/provisioners/index.html)  instead.

**Comment by phillebaba** [comment]
Is there any progress on this? I would also like to have this feature in the same way that GitHub does it.
https://www.terraform.io/docs/providers/github/r/repository_file.html

**Comment by xuzhang3** [comment]
@phillebaba  This feature is our backlog and don't have a start date.

**Comment by rdalbuquerque** [comment]
This would be very helpful when generating repos with template files. We are doing it with forks now, not ideal.
