### ISSUE TITLE
Project data source not working

### ISSUE THREAD

**Issue by amarkulis** [microsoft/terraform-provider-azuredevops#232]
Since the provider has moved to Microsoft the data project source doesn't work as documented:

Error:
__Error: Unsupported argument

  on AZR-FOUNDATION.tf line 2, in data "azuredevops_project" "foundation":
   2:   project_name = "PCET-AZR-NEW"

An argument named "project_name" is not expected here.__

Code:

`data "azuredevops_project" "foundation" {
  project_name = "PCET-AZR-NEW"
}
`

**Comment by xuzhang3** [comment]
@amarkulis This is a breaking change in `v0.1.0`.  We renamed the project name from `project_name` to `name`. You can find it in the [change log](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/CHANGELOG.md)

**Comment by amarkulis** [comment]
@xuzhang3 This migration has been really painful I was able to use this module last week and now everything on https://www.terraform.io/docs/providers/azuredevops/index.html is totally wrong.

**Comment by xuzhang3** [comment]
@amarkulis  https://www.terraform.io/docs/providers/azuredevops/index.html will be deprecated.  Azure DevOps provider has been moved to Terraform registry  https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/project

**Comment by lukerosser** [comment]
I've had the same problem - it should be made clearer that documentation is deprecated.

It also wasn't obvious that the provider location had moved. No mention of it in the release notes.

**Comment by xuzhang3** [comment]
@lukerosser @amarkulis   I have update the release note. It's our mistake not to mention that the the document has been moved to the new location.

**Comment by lukerosser** [comment]
Thanks @xuzhang3 - the "about" section on the repository is still using the wrong documentation link too.

**Comment by xuzhang3** [comment]
@lukerosser    I create a new PR to fix the document link issue.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
