### ISSUE TITLE
PROVIDER_VERSION.txt still 0.0.1 ?

### ISSUE THREAD

**Issue by birchb1024** [microsoft/terraform-provider-azuredevops#233]
On master branch this file has contents '0.0.1' 

Is that correct?

**Comment by xuzhang3** [comment]
@birchb1024  This  file is used for `scripts/build.sh, scripts/local-install.sh` etc.   The provider release version is based on tags.

**Comment by xuzhang3** [comment]
Close this issue, feel free to reopen it if you have questions.
