### ISSUE TITLE
Error: Failed to instantiate provider "azuredevops" to obtain schema: fork/exec

### ISSUE THREAD

**Issue by derhally** [microsoft/terraform-provider-azuredevops#242]
Today we started getting the following error during terraform plan

```
Error: Failed to instantiate provider "azuredevops" to obtain schema: fork/exec /home/atlantis/.atlantis/repos/****/services/86/default/environments/test/.terraform/plugins/linux_amd64/terraform-provider-azuredevops_v0.1.0: no such file or directory
```

This was not an issue with 0.0.1 .

We are using terraform 0.12.29

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

0.1.0

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version               = ">= 0.0.1"
  org_service_url       = ***
  personal_access_token = ***
}
```

### Expected Behavior

terraform plan should work with azure devops provider

### Actual Behavior

terraform fails to use the 0.1.0 provider

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We are running inside of a container based on alpine:3.12

### References

* #0000

**Comment by jakobyte1024** [comment]
Can confirm. Same problem for me. Terraform 0.13.5 running with official TF docker image. Workaround `version = "<0.1.0"`

**Comment by xuzhang3** [comment]
@derhally  `azuredevops` has been move to Terraform registry  and the plugin path has been changed by Terraform .Recommend not to set the plugin path in your script, Terraform can handle the plugin path  itself. If you specific the plugin location in your script file, you need change the path.
**Example**:
For v0.0.1, plugin path :`.terraform\plugins\windows_amd64`
For v0.1.0, plugin path :`.terraform\plugins\registry.terraform.io\microsoft\azuredevops\0.1.0\windows_amd64`

If you want use v0.1.0 with Terraform v0.12.x, you need some extra configuration. 
```
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}
```

**Comment by derhally** [comment]
The new provider config is not supported by terraform 0.12 and it even warms you about that.  The issue is reproducible even with terraform 0.13.

I don't have issue with any other providers.

Did you try reproducing it?

**Comment by SBiesinger** [comment]
Can confirm this problem persists on the official TF 0.14 docker image

**Comment by xuzhang3** [comment]
> The new provider config is not supported by terraform 0.12 and it even warms you about that. The issue is reproducible even with terraform 0.13.
> 
> I don't have issue with any other providers.
> 
> Did you try reproducing it?

@derhally @SBiesinger ADO provider is a different with other provider,   ADO released the first version v0.0.1 as Hashicorp official provider then we moved the repo back to Microsoft and released the v0.1.0 to Terraform registry.
Provider local plugins path  released via Terraform registry has bee changed, For example: 
```
old provider local path:  `.terraform\plugins\windows_amd64` 
registry plugin local path `.terraform\plugins\registry.terraform.io\microsoft\azuredevops\0.1.0\windows_amd64`.
```

**Hashicorp has helped sync the v0.1.0  from registry to the old provider release repo**.  You should be able use the v0.1.0 without any extra configuration now. But you will get a warning message:
![image](https://user-images.githubusercontent.com/57888764/101118193-91a1fe00-3623-11eb-8f52-9229866b2d47.png)

When you upgrade the Terraform from v0.12.x to v0.13.x,  you can use the help command `0.13upgrade` help upgrade the 0.12.x script to 0.13.x compatible script https://www.terraform.io/docs/commands/0.13upgrade.html.

**Comment by SBiesinger** [comment]
Hi @xuzhang3,

first of all, thanks for taking the time to support us on this issue. We are aware that the provider path has changed. The configuration on my side is so:

```
terraform {  
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
    }
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"      
    }
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
  required_version = ">= 0.13"
}
```

However, running on the official TF Docker image (tested on 0.13, 0.13.5 and 0.14), we get the following output:

```
Failed to instantiate provider "registry.terraform.io/microsoft/azuredevops"
to obtain schema: fork/exec
.terraform/providers/registry.terraform.io/microsoft/azuredevops/0.1.0/linux_amd64/terraform-provider-azuredevops_v0.1.0:
no such file or directory
```

We can see the plugin is indeed found by looking at this line, which appears during Terraform init:

```
- Installing microsoft/azuredevops v0.1.0...
- Installed microsoft/azuredevops v0.1.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
```

While searching for a solution, I came across [this ](https://github.com/Mastercard/terraform-provider-restapi/issues/65) issue in another Terraform provider, which seems to be a similar problem. Could the issues be related?

Once again thanks for the support,
SBiesinger

**Comment by xuzhang3** [comment]
Hi @SBiesinger  I see, we need more investigation.

**Comment by xuzhang3** [comment]
@derhally  @derhally @SBiesinger  Provider not found should be fixed in v0.1.1. https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v0.1.1

**Comment by xuzhang3** [comment]
Close this issue,  feel free to open another issue if you have questions.

**Comment by biswaranjanb** [comment]
What was the fix done @xuzhang3

**Comment by xuzhang3** [comment]
@biswaranjanb   Can you specific your question? Are you  still cannot initialization ADO provider in docker?
