### ISSUE TITLE
Integrate Terraform Provider Linter

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#243]
### Community Note

* Please vote on this issue by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this
  request
* Please do not leave "+1" or "me too" comments, they generate extra noise for
  issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

### Description

As a maintainer I want to onboard the Azure DevOps Terraform provider to the
HashCorp partner program, so that the provider could be automatically downloaded
from the Terraform provider infrastructure and doesn't have be manually compiled
and installed by the user.

HashiCorp reviewed the current status of the implementation of the provider and
project layout and provided the results in issue #241.

This issue tracks the implementation status of the requirement to utilize the
[Terraform Provider Linter](https://github.com/bflad/tfproviderlint) during
development of the Azure DevOps Provider.

###  Acceptance Criteria

* [ ] The Terraform Provider Linter is integrated in the build infrastructure of
  the project
* [ ] The documentation in docs/contributing.md is changed accordingly

### References

* #241

**Comment by nmiodice** [comment]
### Some notes/questions while I work through the linting issues

- I don't see this integrated into any other provider's CI process. Is this intended to help with development, or should it be baked into the `Makefile` called out in #244 and #241 ?
- The following lint checks are triggering, but I believe they are safe to be ignored:
  - `.../azuredevops/utils/tfhelper/tfhelper.go:72:8: R001: ResourceData.Set() key argument should be string literal` - This is a part of a generic helper that makes a common operation -- storing a secret into the TF state file in a way that enables "did it change?" logic without storing the actual secret -- possible to be shared across multiple resources. For that reason, the `key` in the call to `set()` is intentionally dynamic.

**Comment by nmiodice** [comment]
PR 1 of ?: https://github.com/microsoft/terraform-provider-azuredevops/pull/251

**Comment by nmiodice** [comment]
@xuzhang3 would you like to take this as well? I unassigned myself from the issue. Please advise if you should take it or if I should.
