### ISSUE TITLE
Service Endpoint AzureRM: Verification Fails With Invalid Key

### ISSUE THREAD

**Issue by Flaniga3** [microsoft/terraform-provider-azuredevops#245]
Affected resource:
`azuredevops_serviceendpoint_azurerm`

Terraform Version: 0.12.20

Provider version: built from master on November 20th, 2020

Resource configuration:
```
resource "azuredevops_serviceendpoint_azurerm" "service_connection_primary" {
  project_id                       = <REDACTED>
  service_endpoint_name = "<REDACTED>"
  description                     = "Created and managed via Terraform"
  credentials {
    serviceprincipalid   = azuread_service_principal.spn_primary.application_id
    serviceprincipalkey = random_password.pass_primary.result
  }
  azurerm_spn_tenantid          = <REDACTED>
  azurerm_subscription_id       = <REDACTED>
  azurerm_subscription_name = <REDACTED>
}

resource "azuredevops_serviceendpoint_azurerm" "service_connection_secondary" {
  project_id                       = <REDACTED>
  service_endpoint_name = "<REDACTED>"
  description                     = "Created and managed via Terraform"
  credentials {
    serviceprincipalid    = azuread_service_principal.spn_secondary.application_id
    serviceprincipalkey = random_password.pass_secondary.result
  }
  azurerm_spn_tenantid          = <REDACTED>
  azurerm_subscription_id       = <REDACTED>
  azurerm_subscription_name = <REDACTED>
}
```

Expected Behavior:
I should be able to view the service connection in Azure DevOps and verify it.

Actual Behavior:
I attempt to verify the service connection in Azure DevOps and verification fails with "invalid key". This key works when authenticating via command line, and via all other forms of authentication. When I copy and paste a copy the key from a secure location into the service connection, verification succeeds.

Steps to reproduce:
Pass a random_password.result from a valid random password resource to any azuredevops_serviceendpoint_azurerm while providing all other valid information. Attempt a verification of the service connection in the azure devops UI.

**Comment by xuzhang3** [comment]
@Flaniga3 I cannot reproduce your error, I can create the AzureRM service connection and verify success. Can you check whether the AzuerRM configurations used in the TF schema is correct? 
My test result:
![image](https://user-images.githubusercontent.com/57888764/101126429-6ecd1500-3636-11eb-905a-7da436e03bb8.png)

**Comment by Flaniga3** [comment]
Not sure what was wrong, but I cleared out the created service connections and allowed them to be recreated. Suddenly everything is working. Could have had something to do with the fact that they had to be updated a couple times before I finally got them correct. A fresh creation from the configuration I posted fixed it.

**Comment by pijemcolu** [comment]
There's definitely a bug lurking somewhere there. I am currently seeing the same issue after updating the service connection left and right. Will re-create the service connection for now.
