### ISSUE TITLE
Use Mozilla Public License 2.0

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#245]
### Community Note

* Please vote on this issue by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this
  request
* Please do not leave "+1" or "me too" comments, they generate extra noise for
  issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

### Description

As a maintainer I want to onboard the Azure DevOps Terraform provider to the
HashCorp partner program, so that the provider could be automatically downloaded
from the Terraform provider infrastructure and doesn't have be manually compiled
and installed by the user.

HashiCorp reviewed the current status of the implementation of the provider and
project layout and provided the results in issue #241.

This issue tracks the implementation status of the requirement that the Azure
DevOps Provider is licensed under the [Mozilla Public License
2.0](https://www.mozilla.org/en-US/MPL/2.0/). The required license file can be
copied from
[LICENSE](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/LICENSE).

###  Acceptance Criteria

* [ ] The repository contains a file `LICENSE`  which contains the Mozilla Public License
2.0

### References

* #241

**Comment by xuzhang3** [comment]
In accordance with Microsoft policy, the MIT license will continue to be used in this repository.  Hasicorp will manage the license issue after migrate to there repository
