### ISSUE TITLE
Adopt GitFlow process

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#248]
### Community Note

* Please vote on this issue by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this
  request
* Please do not leave "+1" or "me too" comments, they generate extra noise for
  issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

### Description

The repository should adopt the [`GitFlow`](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow to provide an easy way to create new releases of the provider and have a standard way to keep the required changelog as requested in #247.

###  Acceptance Criteria

* [ ] The branches inside the repository are organized according to the [GitFlow
  process](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
* [ ] A standard operating procedure is documented how repository maintainers
  create releases, maintain the `CHANGELOG.md`file and create new releases to
  the `master` branch. Sample: https://github.com/PowerShell/DscResources/blob/master/Maintainers.md#rules

### References

* #241
* #247

**Comment by tmeckel** [comment]
Okay ... this issue has been closed without any further comment. Pretty surprising, because without a branch that collects incoming pull requests and other contributions from the team, a REAL (serious) release management, including changelog maintenance, will not be possible.

There are enough examples from other Microsoft projects (like SharePoint PnP, or the DSC Team) that adopted a workflow like `git flow`. But merging all work on the master is not an ideal approach from my point of view. 

@nmiodice your thoughts on this?

**Comment by nmiodice** [comment]
@xuzhang3 can you provide clarity on why this was closed?

**Comment by xuzhang3** [comment]
@nmiodice @tmecke Sorry for I closed this issue without any comments.  
As this provider will be migrated to Terraform official provider repository and Terraform workflow does not follow the "git flow", normally they merge the new PRs directly to the master.

**Comment by nmiodice** [comment]
Based on the updated description, I'll go ahead and close this. You can re-open if you'd like to continue the discussion.
