### ISSUE TITLE
Terraform plan has changes

### ISSUE THREAD

**Issue by zoemac11** [microsoft/terraform-provider-azuredevops#248]
Looking to use the TERRAFORM_PLAN_HAS_CHANGES variable but looks like it is setting it true even when there are no changes made in plan

Using terraform 12.29

![image](https://user-images.githubusercontent.com/41298038/101467398-2cf3e580-393a-11eb-9718-32a6de0ff5af.png)

![image](https://user-images.githubusercontent.com/41298038/101467413-2f563f80-393a-11eb-9e93-004974c85130.png)

**Comment by xuzhang3** [comment]
Hi @zoemac11  `TERRAFORM_PLAN_HAS_CHANGES` is not a Terraform configuration.

**Comment by favoretti** [comment]
This is from Terraform extension to AzDO, not for you guys :) Feel free to close.
