### ISSUE TITLE
Adding AAD groups to Azure DevOps project groups

### ISSUE THREAD

**Issue by jorgemarti** [microsoft/terraform-provider-azuredevops#249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unless I'm mistaken, the `azuredevops_group_membership` resource is able to add AAD **users** to Azure DevOps groups, but it still doesn't work with groups (either _security_ or _Office 365_ groups). As normally we grant access to new projects based on groups, it would be a much appreciated feature.

### New or Affected Resource(s)

* azuredevops_group_membership
* azuredevops_group_entitlement

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "project" {
  project_name = "Test Project"
}

resource "azuredevops_group_entitlement" "group" {
    principal_name = "foo_group@contoso.com"
}

data "azuredevops_group" "group" {
  project_id = azuredevops_project.project.id
  name       = "Build Administrators"
}

resource "azuredevops_group_membership" "membership" {
  group = data.azuredevops_group.group.descriptor
  members = [
    azuredevops_group_entitlement.group.descriptor
  ]
}
```

### References

* #74

**Comment by tmeckel** [comment]
@jorgemarti perhaps the current documentation for [`azuredevops_group_membership`](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/group_membership.html.markdown) is a bit misleading,
but you can add groups as `members` already as well, if you retrieve the subject descriptor of the group with the [`azuredevops_group`](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/d/data_group.html.markdown#data-source-azuredevops_group) data source, as you already described it in the issue.

To create a new DevOps group which is linked to an AAD group use the `azuredevops_group` resource and use the `origin_id` parameter,  where the `origin_id` must contain the `objectid` of the group inside Azure AD Tenant which is linked to the Azure DevOps organization. You can then use the `descriptor` property to add the new group as member of another DevOps group like `Build Administrators`

**Comment by jorgemarti** [comment]
@tmeckel many thanks, I was able to test it, and even with `mail` instead of `origin_id` it works.

**Comment by tmeckel** [comment]
@jorgemarti  glad it worked for you!
