### ISSUE TITLE
Create an Azure DevOps project with default configuration?

### ISSUE THREAD

**Issue by sheeeng** [microsoft/terraform-provider-azuredevops#250]
I would like to contribute to implement this feature as soon as possible.

Could someone guide me?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by nmiodice** [comment]
Can you expand on what you mean by `with default configuration`?

**Comment by sheeeng** [comment]
Sorry that I did not clarify it earlier. Creating an Azure DevOps project with given default configuration as shown in the Azure Dashboard. For example,  default private visibility and using default Agile work_item_template.

**Comment by tmeckel** [comment]
@sheeeng we already have a resource `azuredevops_project` which creates Azure DevOps projects:

https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/project.html.markdown

In addition we're planning to provide a resource `azuredevops_project_features` to manage features for projects

https://github.com/tiwood/terraform-provider-azuredevops/issues/5

So as @nmiodice already asked: can you describe in more detail what do you mean with _Create an Azure DevOps project with default configuration_ and what are you missing from the current provider implementation?

**Comment by sheeeng** [comment]
Thank you for the further clarification. I have misunderstood something. I will close this issue.
