### ISSUE TITLE
Enable/disable Azure DevOps services? E.g. Enable Pipelines, Disable Boards & Repos, etc.

### ISSUE THREAD

**Issue by sheeeng** [microsoft/terraform-provider-azuredevops#253]
Can we enable[1] "Pipelines" and "Artifacts" but disable[1] "Boards", "Repos" and "Test Plans" in Azure DevOps project using this Terraform provider?

[1] https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-services?view=azure-devops

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by sheeeng** [comment]
For example, this request can be done using the Azure DevOps portal. I wonder whether we can do the same with this Terraform provider.

[![Image](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/media/services/set-service-visibility.png?view=azure-devops)](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-services?view=azure-devops)

**Comment by tmeckel** [comment]
https://github.com/tiwood/terraform-provider-azuredevops/issues/5

**Comment by tmeckel** [comment]
@nmiodice I started the implementation https://github.com/tiwood/terraform-provider-azuredevops/tree/r_project_features  can you assign me the issue please 😁

**Comment by nmiodice** [comment]
@tmeckel done, and thank you!
