### ISSUE TITLE
Checks missed due to case-insensitive validation

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```bash
Terraform v0.12.16
+ provider.azuredevops v0.0.1
```

### Affected Resource(s)

All resources that use string validation that is later then revalidated for checks in a case sensitive way.

### Terraform Configuration Files

```hcl
resource "azuredevops_git_repository" "repo" {
  project_id = local.project_id
  name       = "Infrastructure Repository"
  initialization {
    init_type  = "import"
  }
}
```

### Expected Behavior

Incorrect casing should either be an validation error or always result in the same error message.

### Actual Behavior

Depending on if the init_type  is written in lowercase or uppercase, the error message received is different, but never a validation error.

### Steps to Reproduce

The error message received if 'import' is written with lowercase
```bash
Error: Error creating resource Build Definition: TF400898: An Internal Error Occurred. Activity Id: 6568d230-7c3e-4cb9-b6b0-6193e2da8969.

  on azdo.tf line 113, in resource "azuredevops_build_definition" "build":
 113: resource "azuredevops_build_definition" "build" {
```

The error message received if 'Import' is written with uppercase:
```bash
Error: Error converting terraform data model to AzDO project reference: Initialization strategy not implemented: Import

  on azdo.tf line 104, in resource "azuredevops_git_repository" "repo":
 104: resource "azuredevops_git_repository" "repo" {
```

### Important Factoids

This issue affects all resources that uses case insensitive string validation and performs further checks in a case sensitive way.

For example, here the line 343 will only be executed for uppercased 'Clean' input, while for lowercase the if will be skipped.
![image](https://user-images.githubusercontent.com/12761692/78171190-06e18180-744c-11ea-8937-b6f58af71728.png)

**Comment by tmeckel** [comment]
There are many places inside the code of the provider where the equal operator is used to compare strings instead of `string.EqualFold`. All string comparisons should be verified if the must be replaced by using `string.EqualFold`

**Comment by nmiodice** [comment]
@tmeckel do you know of any good linters to check this in an automated way?

**Comment by nmiodice** [comment]
This is fixed in #269 but I'd like to keep this open for a little bit to see if we can incorporate a lint check. cc @xuzhang3 @EliiseS

**Comment by tmeckel** [comment]
> 
> 
> @tmeckel do you know of any good linters to check this in an automated way?

Perhaps [go-critic](https://github.com/go-critic/go-critic) is worth a try. There's already a [check](https://go-critic.github.io/overview#equalFold-ref) about string comparison done with `EqualFold` or with the normal `==` operator.

**Comment by EliiseS** [comment]
@tmeckel That only checks for `strings.ToLower(x) == strings.ToLower(y)`, but we want a check for `x == "x"`

**Comment by tmeckel** [comment]
Well a linter can't save you from your own stupidity 😁 but perhaps we shouldn't overcomplicate the situation here. 

I totally agree with you that a perfect solution can't be possible or would create to much effort but I think when we could apply a linter like go-critic and check for the normal `x == "y"` we are good to go for 80% percent of the time.

**Comment by tmeckel** [comment]
@nmiodice @EliiseS found another candidate for Linting purposes https://github.com/quasilyte/go-ruleguard ... best of with this tool ... it's dynamically extensible

**Comment by nmiodice** [comment]
cc @cgriggs01 can we integrate tooling like the suggestion from @tmeckel once we move to a HC repo?

**Comment by cgriggs01** [comment]
Hi @nmiodice, 

I don't see any issue with using this tooling for development of the provider. 

Thanks for asking
