### ISSUE TITLE
Unable to compile using GNUmake

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

build infrastructure

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

After starting the build process with `make build` the provider should be installed locally.

### Actual Behavior

The build process stopped because the `gofmtcheck.sh` script is not executable.

![image](https://user-images.githubusercontent.com/14177833/78471096-d68d3200-772e-11ea-87d5-93784747af81.png)

### Steps to Reproduce

1. clone git repository of provider
2. Start build with `make build`

### Important Factoids

N/A

### References

* #252 introduced the new build system via GNUmake

**Comment by xuzhang3** [comment]
I don't know which user group your account is in.  
```shell
chmod -R 777 ./gofmtcheck.sh
```
should fix this

**Comment by tmeckel** [comment]
@xuzhang3 the execute permission must be checked into GIT

https://www.jerriepelser.com/blog/execute-permissions-with-git/

**Comment by xuzhang3** [comment]
> @xuzhang3 the execute permission must be checked into GIT
> 
> https://www.jerriepelser.com/blog/execute-permissions-with-git/

I create a new PR #265  to fix this issue

**Comment by tmeckel** [comment]
Works as expected now after PR #265 has been merged
