### ISSUE TITLE
Error: VS403284: Invalid operation when trying to set AGILETOOLS permissions on project

### ISSUE THREAD

**Issue by pondichys** [microsoft/terraform-provider-azuredevops#260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.14.3
+ provider registry.terraform.io/microsoft/azuredevops v0.1.0

### Affected Resource(s)

* `azuredevops_project_permissions`

### Terraform Configuration Files

```hcl
variable "azdevops_limited_admin_group_permissions" {
  type=map(any)
  default = {
    GENERIC_READ = "Allow"
    GENERIC_WRITE = "Deny"
    DELETE = "Allow"
    PUBLISH_TEST_RESULTS = "Allow"
    ADMINISTER_BUILD = "Allow"
    START_BUILD = "Allow"
    EDIT_BUILD_STATUS = "Allow"
    UPDATE_BUILD = "Allow"
    DELETE_TEST_RESULTS = "Allow"
    VIEW_TEST_RESULTS = "Allow"
    MANAGE_TEST_ENVIRONMENTS = "Allow"
    MANAGE_TEST_CONFIGURATIONS = "Allow"
    WORK_ITEM_DELETE = "Allow"
    WORK_ITEM_MOVE = "Deny"
    WORK_ITEM_PERMANENTLY_DELETE = "Allow"
    RENAME = "Deny"
    MANAGE_PROPERTIES = "Allow"
    # MANAGE_SYSTEM_PROPERTIES = "Allow"
    # BYPASS_PROPERTY_CACHE = "Allow"
    BYPASS_RULES = "Allow"
    SUPPRESS_NOTIFICATIONS = "Allow"
    UPDATE_VISIBILITY = "Deny"
    CHANGE_PROCESS = "Deny"
    AGILETOOLS_BACKLOG = "Allow"
    AGILETOOLS_PLANS = "Allow"
  }
}
resource "azuredevops_project" "tf-project" {
  name               = "Terraform-Test"
  description        = "Terraform-Test Project Description"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

# Set the project features available
resource "azuredevops_project_features" "tf-project-features" {
  project_id = azuredevops_project.tf-project.id
  features   = var.azdevops_project_features
}

# Create a limited project admins group
resource "azuredevops_group" "tf-group" {
  scope        = azuredevops_project.tf-project.id
  display_name = "Limited Administrators"
  description  = "Members of this group have the same authroziations as Project Administrators group except Edit Project settings."
}

# Set permissions for the limited project admins group
resource "azuredevops_project_permissions" "tf-project-perm" {
  project_id  = azuredevops_project.tf-project.id
  principal   = azuredevops_group.tf-group.id
  permissions = var.azdevops_limited_admin_group_permissions
}
```

### Debug Output

I do not provide a DEBUG log as it does not seem to be an issue in the provider code but rather a limitation of Azure Devops. I can do so if really needed.

### Panic Output

No panic output

### Expected Behavior

We should be able to set project permissions as stated in the documentation.

### Actual Behavior

AGILETOOLS_BACKLOG and AGILETOOLS_PLANS are documented but produce error and there is no indication to what they exactly refer to.

Received error

```
VS403284: Invalid operation. Unable to set bits '51118080' in security namespace '52d39943-cb85-4d7f-8fa8-c6baac873819' as it is reserved by the system.

  on main.tf line 51, in resource "azuredevops_project_permissions" "tf-project-perm":
  51: resource "azuredevops_project_permissions" "tf-project-perm" {
```

### Steps to Reproduce

1. use `azuredevops_project_permissions`resource to assign permissions AGILETOOLS_BACKLOG and/or AGILETOOLS_PLANS.
2. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by xuzhang3** [comment]
Hi @pondichys  The user group is set the scope to project but you try grant the `agile` permissions which can not be managed by project namespace.

**Comment by pondichys** [comment]
Thanks for the answer.
