### ISSUE TITLE
Is there a binary available for release version v0.1.0?

### ISSUE THREAD

**Issue by ttpp8794** [microsoft/terraform-provider-azuredevops#264]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by xuzhang3** [comment]
We are migrating the plugin to the official Terraform repository.  Version v0.0.1 is coming soon.

**Comment by ttpp8794** [comment]
@xuzhang3 Thank you for your response. Any ETA on this plugin available in official Terraform repository?

**Comment by rmaziarka** [comment]
Before that, could you provide the plugin? There is no information on how long it will take so the file could be valuable for the time being.

**Comment by xuzhang3** [comment]
> Before that, could you provide the plugin file? There is no information on how long it will take so the file could be valuable for the time being.

You can build a binary file in three steps. 
  1. Install golang
  2. Checkout terraform-provide-azuredevops source code
  3. Go to project root directory and run the command "go build -gcflags="-N -l" -o terraform-provider-azuredevops". You will find the "terraform-provider-azuredevops" file in project root directory
If you run terraform in a Windows environment, you may need to add the file suffix ".exe".

**Comment by xuzhang3** [comment]
> @xuzhang3 Thank you for your response. Any ETA on this plugin available in official Terraform repository?

Not sure when this plugin will available in official Terraform repository. Currently they are reviewing the code.

**Comment by nmiodice** [comment]
Based on the update here - https://github.com/microsoft/terraform-provider-azuredevops/issues/241 - its safe to close this in favor of the official CI approach.
