### ISSUE TITLE
azuredevops_resource_authorization Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by DanSibbernsen** [microsoft/terraform-provider-azuredevops#266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.0

### Affected Resource(s)

* `azuredevops_resource_authorization`

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "main" {
  name                = "${var.registry_name}${terraform.workspace}"
  resource_group_name = var.resource_group
  location            = var.location
  sku                 = "Basic"

  tags = merge(var.base_tags, {
      Enviroment  = terraform.workspace
      Role        = "container-registry"
    })
}

data "azurerm_subscription" "main" {}

resource "azuredevops_serviceendpoint_azurecr" "main" {
    project_id                = "azurecr"
    service_endpoint_name     = "acr-docker-registry-${terraform.workspace}"
    resource_group            = var.resource_group
    azurecr_spn_tenantid      = azurerm_container_registry.main.id
    azurecr_name              = azurerm_container_registry.main.name
    azurecr_subscription_id   = data.azurerm_subscription.main.subscription_id
    azurecr_subscription_name = data.azurerm_subscription.main.display_name
    description               = "description"
}

resource "azuredevops_resource_authorization" "main" {
  project_id  = azuredevops_serviceendpoint_azurecr.main.project_id
  resource_id = azuredevops_serviceendpoint_azurecr.main.id
  authorized  = true
}
```

### Debug Output

[Gist](https://gist.github.com/DanSibbernsen/2c146ef6588b05442dba296386d6e289)

### Expected Behavior

Terraform applies changes to the Azure Container Registry's service connection to "Grant access permissions to all pipelines"  

### Actual Behavior

Received error linked above. Service connection is created but permissions are not granted.

### Steps to Reproduce

1. `terraform apply`

### References

* #145 
* #215

**Comment by xuzhang3** [comment]
Hi @DanSibbernsen  This because the resource you try to authorize not ready.  Wait 1 or 2 mins should working.

**Comment by DanSibbernsen** [comment]
> Hi @DanSibbernsen This because the resource you try to authorize not ready. Wait 1 or 2 mins should working.

Hi @xuzhang3, I put in a time_sleep blocker like so:
```
# This is to work around an issue with azuredevops_resource_authorization
# The service connection resource is not ready when we get to
# so the recommendation is to wait 2 minutes until it's ready
# This resource will destroy (potentially immediately) after null_resource.next
resource "null_resource" "previous" {}

resource "time_sleep" "wait_120_seconds" {
  depends_on = [null_resource.previous]
  create_duration = "300s"
}

# This resource will create (potentially immediately) after null_resource.previous
resource "azuredevops_resource_authorization" "main" {
  depends_on = [azuredevops_serviceendpoint_azurecr.main, time_sleep.wait_120_seconds]
  project_id  = azuredevops_serviceendpoint_azurecr.main.project_id
  resource_id = azuredevops_serviceendpoint_azurecr.main.id
  authorized  = true
}
```

I set it for 5 minutes and I'm still getting the same error. Any other tips?

**Comment by DanSibbernsen** [comment]
Ah, I think I found my issue. The PAT I assigned to AZDO_PERSONAL_ACCESS_TOKEN doesn't have access rights to modify service connections of this type. Will confirm when I have a PAT that has those permissions. Though it's a bit weird that I could create the service connection but not be able to alter it, so maybe that's a bug?

**Comment by xuzhang3** [comment]
Checked with service team that this is not a bug.  I will follow up whether ADO can handle the resource state and maybe we can add a retry logic for the resource before resource ready.

**Comment by DanSibbernsen** [comment]
Thanks @xuzhang3, your advice helped me resolve my problem! I had a few issues:
1. azurecr_spn_tenantid was wrong (populating it with the wrong value)
2. the delay between the azuredevops_serviceendpoint_azurecr that you mentioned

After getting both of those working, I can now create Azure Container Registry Service Connections with access to all pipelines. Here is my example code:

```
resource "azurerm_container_registry" "main" {
  name                = "testContainerRegistryUniqueName"
  resource_group_name = "tstate"
  location            = "eastus2"
  sku                 = "Basic"
}

data "azurerm_client_config" "main" {
}

data "azurerm_subscription" "main" {}

data "azuredevops_project" "main" {
  name = "test"
}

resource "azuredevops_serviceendpoint_azurecr" "main" {
    project_id                = data.azuredevops_project.main.id
    service_endpoint_name     = "test-1234"
    resource_group            = "tstate"
    azurecr_spn_tenantid      = data.azurerm_client_config.main.tenant_id
    azurecr_name              = azurerm_container_registry.main.name
    azurecr_subscription_id   = data.azurerm_subscription.main.subscription_id
    azurecr_subscription_name = data.azurerm_subscription.main.display_name
    description               = "test"
}

# This is to work around an issue with azuredevops_resource_authorization
# The service connection resource is not ready immediately
# so the recommendation is to wait 20 seconds until it's ready
resource "time_sleep" "wait_20_seconds" {
  depends_on = [azuredevops_serviceendpoint_azurecr.main]
  create_duration = "20s"
}

resource "azuredevops_resource_authorization" "main" {
  depends_on = [time_sleep.wait_20_seconds]
  project_id = data.azuredevops_project.main.id
  resource_id = azuredevops_serviceendpoint_azurecr.main.id
  authorized = true
}
```
