### ISSUE TITLE
Exclude _test.go files from SonarQube checks

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#267]
Can we exclude the test files (`_test.go`) from the SonarQube checks?

![image](https://user-images.githubusercontent.com/14177833/79264552-0e197e00-7e95-11ea-82a0-b16649f65149.png)

![image](https://user-images.githubusercontent.com/14177833/79264617-28535c00-7e95-11ea-9932-5f8fef43374b.png)

**Comment by nmiodice** [comment]
I'd prefer to delay this until we move to HashiCorp CI as I dont think we'll have that issue there.

**Comment by tmeckel** [comment]
@nmiodice I'm not sure if Hashicorp is using Sonarcloud at all.. if not ... would be a pitty. I'm not even sure about all the internals on the onboarding process for the provider with Hashicorp but if it's designed like the process with the providers at Pulumi as a maintainer you (can) push changes from your "working" repo to the maintained corporate repo and thus your're free to use any code quality assurance products you like. If it's the same way here with Hashicorp I'd recommend keep developing here in this repo and configuring Sonarcloud as we need it. Your thoughts?

**Comment by nmiodice** [comment]
@tmeckel the primary development work will be done in the HC repo.

FYI I've set the exclusion policies like so. Hopefully it helps.

![image](https://user-images.githubusercontent.com/2497673/80985434-d7c88200-8df4-11ea-82cc-2516cd1746de.png)

![image](https://user-images.githubusercontent.com/2497673/80985485-e747cb00-8df4-11ea-8b93-a55694737062.png)

**Comment by nmiodice** [comment]
I believe this is now complete -- lets re-open if it becomes an issue or if there are any improvements that can be made.
