### ISSUE TITLE
azure: malformed storage account key: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by techiechap** [microsoft/terraform-provider-azuredevops#268]
If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.
--->

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

<Terraform 0.12.3 & 0.12.20  >

### Affected Resource(s)

<C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe>

* `azuredevops_win2016-2017`

### Terraform Configuration Files

terraform {

backend "azurerm" {

storage_account_name =  `"__terraformstorageaccount__"`

container_name = "terraform"

key = "terraform.tfstate"

access_key ` "__storagekey__"`

}
}
provider "azurerm" {
features {}
}

```hcl
Piple line fails at initialization, 
```

### Panic Output

<Nope>

### Expected Behavior

<https://gist.github.com/techiechap/11b888c1470a12cb1bd6cc456a1317a6>

### Actual Behavior

<https://gist.github.com/techiechap/11b888c1470a12cb1bd6cc456a1317a6>

### Steps to Reproduce

1. `Create Az Repo
2.  Define CI & CD
3. Add Az CLI, Az PS, Replace Tokens, terraform install (0.12.3 or 0.12.20), terraform init, terraform plan terraform apply task in Microsoft hosted 2016-27, ubuntu 18 agent`
4. create variables to store tf state in azure storage, as mentioned in terraform config above.

### Important Factoids
`
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?

[Azure Devops Lab ](https://azuredevopslabs.com/labs/vstsextend/terraform/)

[Terraform](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6454)

[DeveloperCommunityVisualStudio](https://developercommunity.visualstudio.com/content/problem/986435/cicd-pipeline-terraform-tf-state.html)'

* #0000

**Comment by tiwood** [comment]
It seems like you have issues with your `azurerm` backend config. This is the `azuredevops` provider repository and has nothing to do with the `azurerm` backend config.

Backend related stuff goes here: https://github.com/hashicorp/terraform/issues

**Comment by techiechap** [comment]
@tiwood  yep,  i had to rewrote the inline ps script to store the storage key, i think copy pasting the script was an issue  we can close the issue,
