### ISSUE TITLE
Service Connection for Azure China and ablity to select management group

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#27]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/379
Originally created by @anikm1987 on *Tue, 30 Jun 2020 11:21:13 GMT*

---
Hi,
Currently I am not able to find any option to set azurm_enviornment while creating service connection which is kind of restricting me to use it for Azure China cloud.

Also in service azuredevops_serviceendpoint_azurerm, there is no option to provide management group as an option.

Is this planned for future release?

Thanks
Aniket

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/379#issuecomment-652165118
Originally created by @xuzhang3 on *Wed, 01 Jul 2020 03:24:46 GMT*

---
Hi @anikm1987, We have migrate this repo to [terraform-provider-azuredevops](https://github.com/terraform-providers/terraform-provider-azuredevops)
1. In AzureRM service connection, `Environment` is not supported yet. We will add this in the future.  
2. What management group do mean? [Membership resource](https://www.terraform.io/docs/providers/azuredevops/r/group_membership.html) may help you.

**Comment by CaptainStealthy** [comment]
@EliiseS @xuzhang3 Is there a chance that the `azuredevops_serviceendpoint_azurerm` resource could be updated to support management groups? This is going to become a problem for us very soon :(

**Comment by mblaschke** [comment]
bump

**Comment by aellwein** [comment]
This feature is still needed :-)

**Comment by aellwein** [comment]
bump

**Comment by aellwein** [comment]
TWIMC: i've created [this pull request](https://github.com/microsoft/terraform-provider-azuredevops/pull/699) to support AzureRM service endpoint creation with "environment" parameter (AzureCloud, AzureChinaCloud are supported). In the meantime, you can try my own provider fork: https://registry.terraform.io/providers/aellwein/azuredevops/latest

With the version 0.3.0 on, it supports AzureRM service endpoint for AzureChinaCloud.

**Comment by xuzhang3** [comment]
Closing this issue via #699
