### ISSUE TITLE
terraform-plugin-sdk v2 roadmap?

### ISSUE THREAD

**Issue by birchb1024** [microsoft/terraform-provider-azuredevops#272]
Currently the provider uses v1.13.1 of the terraform-plugin-sdk. There is a version 2 of the plugin SDK from Hashi (github.com/hashicorp/terraform-plugin-sdk/v2) which has a lot of changes. See [v2 upgrade guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html.) 

Do you have a plan to upgrade to the new plugin SDK? Is there any planned date for a new version?

**Comment by xuzhang3** [comment]
Hi @birchb1024  We have  no plans to upgrade to v2, currently v1 can cover our requirement, but we can investigate what we can benefit from v2. Regular release will be per three weeks. Due to bug fix and feature requirement, we may change the release cycle.
