### ISSUE TITLE
azuredevops_serviceendpoint_azurerm sets empty password, when changed

### ISSUE THREAD

**Issue by rmaziarka** [microsoft/terraform-provider-azuredevops#273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- terraform - v0.12.24
- azuredevops - v.0.0.1

### Affected Resource(s)

- `azuredevops_serviceendpoint_azurerm`

* `azuredevops_XXXXX`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_azurerm" "azure_devops" {
  project_id                = local.azure_devops_project_id
  service_endpoint_name     = var.service_endpoint_name
  azurerm_spn_clientid      = azuread_application.azure_devops.application_id
  azurerm_spn_clientsecret  = random_password.azure_devops.result
  azurerm_spn_tenantid      = data.azurerm_client_config.default.tenant_id
  azurerm_subscription_id   = data.azurerm_client_config.default.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.default.display_name
  azurerm_scope             = azurerm_resource_group.default.id
  description               = "service connection"
}
```

### Apply output
```hcl
Terraform will perform the following actions:

  # module.azure.azuredevops_serviceendpoint_azurerm.azure_devops will be updated in-place
  ~ resource "azuredevops_serviceendpoint_azurerm" "azure_devops" {
        authorization                 = {
            "scheme" = "ServicePrincipal"
        }
        azurerm_scope                 = "/subscriptions/...."
        azurerm_spn_clientid          = "4d3be64f-..."
        azurerm_spn_clientsecret_hash = (sensitive value)
        azurerm_spn_tenantid          = "e05e12bb-..."
        azurerm_subscription_id       = "b45490cd-...."
        azurerm_subscription_name     = "RadSoft"
      ~ description                   = "description" -> "description 1"
        id                            = "82868062-..."
        project_id                    = "debac8f1-..."
        service_endpoint_name         = "service-connection"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

The client secret is preserved after changes.

### Actual Behavior

The client secret is set to empty after changes.

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. change description
3. `terraform apply -auto-approve`

### Additional info
In terraform state I have empty `azurerm_spn_clientsecret`
```json
"attributes": {
    "authorization": {
        "scheme": "ServicePrincipal"
    },
    "azurerm_scope": "/subscriptions/....",
    "azurerm_spn_clientid": "4d3be64f-...",
    "azurerm_spn_clientsecret": "",
    "azurerm_spn_clientsecret_hash": "$2a$04...",
    "azurerm_spn_tenantid": "e05e12bb-...",
    "azurerm_subscription_id": "b45490cd-....",
    "azurerm_subscription_name": "SubscriptionName",
    "description": "description",
    "id": "82868062-...",
    "project_id": "debac8f1-...",
    "service_endpoint_name": "service-connection"
}
```

**Comment by nmiodice** [comment]
@rmaziarka this is intentional. Instead of storing the password in plain-text, we store a `bcrypt`'d value and use that to identify if the value in the configuration has actually changed.

Is this causing any issues with your plan/apply?

**Comment by tiwood** [comment]
We had an issue where some users changed the name of the service connection, which caused an in-place upgrade and resulted in an service connection without password.

**Comment by nmiodice** [comment]
Ah, thats not good! I see, this makes sense to implement. I will have a go at it this week.

**Comment by nmiodice** [comment]
Fix: https://github.com/microsoft/terraform-provider-azuredevops/pull/296

**Comment by nmiodice** [comment]
This should be fixed so I'll go ahead and close the issue. If you find other related issues, please do not hesitate to re-open or create a new bug!
