### ISSUE TITLE
azuredevops_variable_group - Not Respecting State

### ISSUE THREAD

**Issue by midacts** [microsoft/terraform-provider-azuredevops#275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- Terraform v0.12.24
- provider.azuredevops v0.0.1
  - I had to build from source today and i named it version 0.0.1

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
resource "azuredevops_variable_group" "test" {
  project_id   = "xxx"
  name         = "Test9001"
  description  = "Test Variable Group Description"
  allow_access = false

  variable {
    name  = "test9001"
    value = "youcanseeme"
  }

  variable {
    name      = "super secret"
    value     = "p@ssword123"
    is_secret = true
  }
}
```

### Expected Behavior

terraform apply - applies the config
terraform plan - shows everything is applied

### Actual Behavior

terraform apply - works

terraform plan - shows the secret resource needs to be removed and readded

```text
Terraform will perform the following actions:

  # azuredevops_variable_group.test will be updated in-place
  ~ resource "azuredevops_variable_group" "test" {
        allow_access = false
        description  = "Test Variable Group Description"
        id           = "11"
        name         = "Test9001"
        project_id   = "xxx"

        variable {
            is_secret = false
            name      = "test9001"
            value     = "youcanseeme"
        }
      - variable {
          - is_secret = true -> null
          - name      = "super secret" -> null
        }
      + variable {
          + is_secret = true
          + name      = "super secret"
          + value     = "p@ssword123"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by nmiodice** [comment]
I admit, this is not perfect. I don't see a way to fix it without making it possible for Terraform to keep this value up-to-date, though. This comes down to the Azure DevOps API not returning the value of variables marked as a `secret`.

As an example, if we fix this issue (which will involve storing the secret value to the TF state) then if it is ever changed outside of Terraform, it will be impossible to determine that it has changed. This is due to the fact that the updated value will never be returned from the API.

So to me it seems that we have 2 options:

- Always update secrets (the current approach)
- Only create secrets, and then never update them


*Example API response for secret variable*
```
{
  "variables": {
    "foo": {
      "value": null,
      "isSecret": true
    }
  },
...}
```

**Comment by midacts** [comment]
I would assume it would need to be stored in Terraform state and just be marked as sensitive when terraform plan is run.
Like you said, otherwise Terraform does not know the value to verify if anything needs to change.

I'd be curious how other providers deal with similar issues.

**Comment by tiwood** [comment]
I‘ll say we should set ForceNew on the value property, that way the variable will only be (re)created when the value is changed (state diff).

Always updating resources + showing a plan is against Terraform Provider patterns afaik.

**Comment by nmiodice** [comment]
I'll try to have a go at fixing this tomorrow

**Comment by nmiodice** [comment]
https://github.com/microsoft/terraform-provider-azuredevops/pull/291/files

**Comment by nmiodice** [comment]
Merged! This should be fixed :)
