### ISSUE TITLE
azuredevops_projects - Problems Referencing Attriutes

### ISSUE THREAD

**Issue by midacts** [microsoft/terraform-provider-azuredevops#276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- Terraform v0.12.24
- provider.azuredevops v0.0.1
  - I build this using today's source code and named it v0.0.1

### Affected Resource(s)

* `azuredevops_projects`

### Terraform Configuration Files

```hcl
data "azuredevops_projects" "muh-project" {
  project_name = "muh project"
}

output "project_id" {
  value = "${data.azuredevops_projects.muh-project.projects.*.project_id}"
}

output "project_name" {
  value = "${data.azuredevops_projects.muh-project.projects.*.name}"
}

resource "azuredevops_variable_group" "test" {
  project_id   = data.azuredevops_projects.muh-project.projects.*[0].project_id
  name         = "Test9001"
  description  = "Test Variable Group Description"
  allow_access = false

  variable {
    name  = "test9001"
    value = "xxx"
  }
```

#### Option 1: Using Only `.`

```text
Error: Unsupported attribute

  on iam.tf line 62, in resource "azuredevops_variable_group" "test":
  62:   project_id   = "${data.azuredevops_projects.muh-bucket.projects.project_id}"

This value does not have any attributes.
```

#### Option 2: Using `.*.`

```text
Error: Incorrect attribute value type

  on main.tf line 62, in resource "azuredevops_variable_group" "test":
  62:   project_id   = "${data.azuredevops_projects.muh-bucket.projects.*.project_id}"
    |----------------
    | data.azuredevops_projects.muh-bucket.projects is set of object with 1 element

Inappropriate value for attribute "project_id": string required.
```

### Expected Behavior

I would expect to use:

`data.azuredevops_projects.muh-bucket.projects.project_id`

and reference the one project I want to reference.

After reading the documentation, it looks like the intent may be to use this data source for all projects?

It would probably be better for this to be one project, and not multiple.

### Actual Behavior

This works. I've never had to use this anywhere else in Terraform

`data.azuredevops_projects.muh-bucket.projects.*[0].project_id`

### Steps to Reproduce

1. `terraform apply`

**Comment by midacts** [comment]
Maybe it is how it is intended to be used?

It took me a little while to figure it out so maybe updating the variable groups documentation showing how to use it.
Or making the project data source only work with one project.

BTW - really glad this project exists. I was super excited when I stumbled across it today.

**Comment by tiwood** [comment]
@midacts, can you please check if `data.azuredevops_projects.muh-bucket.projects[0].project_id` works for you? This should be the correct syntax IMO.

**Comment by midacts** [comment]
I forgot to mention trying that.
It doesn't work either.

```text
Error: Invalid index

  on main.tf line 64, in resource "azuredevops_variable_group" "test":
  64:   project_id   = data.azuredevops_projects.muh-bucket.projects[0].project_id

This value does not have any indices.
```

**Comment by tmeckel** [comment]
@midacts 

Create a map and access the project by name afterwards 

```hcl
data "azuredevops_projects" "muh-project" {
  project_name = "muh project"
}

locals {
  project_map = {
    for project in data.azuredevops_projects.muh-project.projects : project["name"] => project
  }
}

resource "azuredevops_variable_group" "test" {
  project_id   = local.project_map["muh project"].project_id
  name         = "Test9001"
  description  = "Test Variable Group Description"
  allow_access = false

  variable {
    name  = "test9001"
    value = "xxx"
  }
```

**Comment by midacts** [comment]
That would work.
Along with `projects.*[0].project_id`.

It's just kind of a janky way of using it.

**Comment by nmiodice** [comment]
@xuzhang3 @tmeckel what are your thoughts on another data provider `azuredevops_project` (note the omission of the final `s`), to pick out a single project only?

**Comment by tmeckel** [comment]
@nmiodice @xuzhang3  easy to do and actually I though about the same. We should have a single data source and multi result data source . So people can chose the type of the data source according to their demand. 

I was always happy with the multi result data source, because that gives you the possibility to apply permissions for all projects with minimal HCL code by using `for_each` or `count`. But I can the use case for a single value data source as well.

**Comment by nmiodice** [comment]
Implemented here - https://github.com/microsoft/terraform-provider-azuredevops/pull/284

**Comment by nmiodice** [comment]
You were not joking, @tmeckel - the implementation is just 13 lines of code. The tests is exactly 4x that.

And of course the changes to the `vendor` directory are... staggering :D

**Comment by midacts** [comment]
Thanks for implementing this.
I'm still learning golang, but I'd like to one do be able to contribute.

**Comment by nmiodice** [comment]
@midacts we'll always welcome OSS contributions :)

I believe this ticket can be closed -- please let us know if the new `azuredevops_project` is still difficult to use and we can revisit

**Comment by tmeckel** [comment]
> You were not joking, @tmeckel - the implementation is just 13 lines of code. The tests are exactly 4x that.

@nmiodice  Yep... well designed code always pays off 😁 
 
> 
> And of course the changes to the `vendor` directory are... staggering :D

As I said already to @EliiseS , we urgently need a way to deal with PRs that contain changes to the vendor directory or include new components in `go.mod`.  I think we can't allow people to simply make arbitrary changes to the components which are used inside the provider.  This could end in an hard to maintain and unstable product.

**Comment by nmiodice** [comment]
@tmeckel can you elaborate on your point?

**Comment by xuzhang3** [comment]
I think update  ```vendor``` should be fine, as this files are dependencies files defined in the ```go.mod``` file. We can control the update of ```go.mod```.

**Comment by nmiodice** [comment]
I tend to agree @xuzhang3, but I'm interested to learn about @tmeckel 's concern.

Is the concern that the `vendor` directory may not actually match what is in `go.mod`, perhaps leading to the ability for potentially malicious injections into the project? Or is the concern purely about managing dependencies?

**Comment by nmiodice** [comment]
@tmeckel can you please open an issue with your concern regarding the dependency management? I want to give this issue the right attention, but I don't think this is the right issue for it.

**Comment by tmeckel** [comment]
@nmiodice there you go => #311 have fun reading it.
