### ISSUE TITLE
ACR docker registry login server should be lower case

### ISSUE THREAD

**Issue by whiskeysierra** [microsoft/terraform-provider-azuredevops#277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.1
```

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurecr`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azuredevops_serviceendpoint_azurecr" "default" {
  service_endpoint_name     = "acr-${var.realm.name}-${var.realm.stage}"
  project_id                = var.project.id
  resource_group            = azurerm_container_registry.default.resource_group_name
  azurecr_spn_tenantid      = data.azurerm_client_config.current.tenant_id
  azurecr_name              = azurerm_container_registry.default.name
  azurecr_subscription_id   = data.azurerm_subscription.current.subscription_id
  azurecr_subscription_name = data.azurerm_subscription.current.display_name
}
```

The ACR is named `acrbosGA`.

### Expected Behavior

login server supplied to DevOps API should be `acrbosga.azurecr.io`.

### Actual Behavior

login server supplied to DevOps API is `acrbosGA.azurecr.io`.

https://github.com/microsoft/terraform-provider-azuredevops/blob/51c2e734c629913a1d6692f4921de90b6936959e/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go#L43

When doing `az acr login --name acrbosGA` the CLI will issue a warning because of case-sensitivity:

> Uppercase characters are detected in the registry name. When using its server url in docker commands, to avoid authentication errors, use all lowercase.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
Close this issue, has been fixed in v0.1.2.
