### ISSUE TITLE
Github service connection for Github enterprise

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#28]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/378
Originally created by @anikm1987 on *Tue, 30 Jun 2020 11:17:10 GMT*

---
Hi,
I was trying to create service connection for GITHUB enterprise but unable to find any option to provide server url.
Is this feature planned?
Is there any other way I can do that.
Thanks

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/378#issuecomment-652161551
Originally created by @xuzhang3 on *Wed, 01 Jul 2020 03:11:57 GMT*

---
Hi @anikm1987, `github_enterprise_service_connection` is in our future plan.  You can create the GITHUB service connection in the traditional way(use portal).
We have migrate this repo to [terraform-provider-azuredevops](https://github.com/terraform-providers/terraform-provider-azuredevops)

**Comment by hpomorski** [comment]
Do we have any update on that issue? It would be very nice to automate the process of setting whole DevOps projects by using seed jobs and it's one of the blockers.
