### ISSUE TITLE
git_repository default_branch

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/terraform-provider-azuredevops#283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Be able to set the default_branch for git_repository

Currently when  a git repo is created, you can see the atribute for default_branch but are unable to set it

### New or Affected Resource(s)

* azuredevops_XXXXX
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository

### Potential Terraform Configuration

```hcl
resource "azuredevops_git_repository" "repo" {
  project_id = azuredevops_project.project.id
  name       = "Sample Empty Git Repository"
  initialization {
    init_type = "Clean"
   default_branch = "refs/heads/main"
  }
}
```

**Comment by xuzhang3** [comment]
Hi @FernandoMiguel  you can set the `azuredevops_git_repository.default_branch`, it  is configurable. But you should ensure that the branch existed otherwise ADO won't be able to create this resource.

**Comment by FernandoMiguel** [comment]
>But you should ensure that the branch existed otherwise ADO won't be able to create this resource.
the all point of this resource is to create a repo.
in that moment no branches exist.
the idea is for it to create one with the name we choose, and not default to "master"

**Comment by FernandoMiguel** [comment]
https://github.com/jamiemccrindle/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/git/resource_git_repository.go#L71
says it is computed.
can we override that in terraform?

**Comment by FernandoMiguel** [comment]
tested and working.
the docs need to be updated

**Comment by xuzhang3** [comment]
Hi @FernandoMiguel  `default_branch` can  override by Terraform.   Service will set a default value if this parameter is not set, so this configuration is `Computed`.
