### ISSUE TITLE
Error creating service endpoint in Azure DevOps: Authorization parameter 'AccessToken' must be supplied to complete OAuth flow

### ISSUE THREAD

**Issue by hassan-wow** [microsoft/terraform-provider-azuredevops#286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.10
+ provider.azuredevops v0.0.1

terraform-provider-azuredevops-0.1.0

### Affected Resource(s)

resource_serviceendpoint_github.go

### Terraform Configuration Files

```hcl
provider "azuredevops" {
personal_access_token = var.azdo_token
org_service_url = var.azdo_org_service_url
}
resource "azuredevops_project" "project" {
project_name = var.azdo_project_name
description = var.azdo_project_desc
version_control = "Git"
work_item_template = "Agile"
visibility = "private"
}
resource "azuredevops_serviceendpoint_github" "oauth" {
count = "${var.enabled_repo_conn == "true" ? 1 : 0}"
project_id = azuredevops_project.project.id
service_endpoint_name = var.github_service_endpoint_name
auth_oath {
oauth_configuration_id = var.oauth_configuration_id
}
}
```

### Expected Behavior

Successful creation of github service connection using oAuth

### Actual Behavior

Service connections to Github can be created using PAT but not using oAuth

1. Running terraform apply throws the error
Error creating service endpoint in Azure DevOps: Authorization parameter 'AccessToken' must be supplied to complete OAuth flow

- Create an oAuth connection in Azure DevOps Organisation settings
- use its configurationid in your main.tf with the following schema 

 auth_oath {
    oauth_configuration_id = var.oauth_configuration_id
  }

Run plan and apply, throws AccessToken error

Note a side issue : auth_oath is mistyped in the provider source code, as per the documentation this should be auth_oauth.

**Comment by nmiodice** [comment]
@hassan-wow this is a known limitation of the underlying API that we are using and is described in  [the documentation](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/serviceendpoint_github.html.markdown#argument-reference).

From the docs:
**NOTE: Github OAuth flow can not be performed via terraform. You must create this on Azure DevOps and then import it.**

I'll close this as there is no issue here. Please re-open if you'd like to discuss further.
