### ISSUE TITLE
"The policy configuration ... does not exist."

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/terraform-provider-azuredevops#288]
After adding / updating branch policies, we seem to be stuck with this error:

```yaml
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azuredevops_branch_policy_min_reviewers.branch_policy_min_reviewers["azuredevops"] will be updated in-place
  ~ resource "azuredevops_branch_policy_min_reviewers" "branch_policy_min_reviewers" {
        id         = "14"
        # (3 unchanged attributes hidden)

      ~ settings {
          ~ reviewer_count     = 1 -> 2
            # (1 unchanged attribute hidden)

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azuredevops_branch_policy_min_reviewers.branch_policy_min_reviewers["azuredevops"]: Modifying... [id=14]

Error: Error updating policy in Azure DevOps: The policy configuration with ID '14' and revision '4' does not exist.

  on git_repository.tf line 21, in resource "azuredevops_branch_policy_min_reviewers" "branch_policy_min_reviewers":
  21: resource "azuredevops_branch_policy_min_reviewers" "branch_policy_min_reviewers" {
```

no idea how to resolve it

**Comment by xuzhang3** [comment]
@FernandoMiguel Can you provide the operation steps? Seems you fixed the policy ID to 14,  but this policy has been deleted, have  you modify  the policies in web portal?

**Comment by FernandoMiguel** [comment]
>  have  you modify  the policies in web portal? 
Yes. As we experiment with the various options, we are testing the ideal settings, both via web, and then coding them into terraform. 

I'm not familiar with policy IDs. 
But we would love to learn better how to handle this. 
As even some other team member can at some point in the future do a similar change and our pipelines should handle this gracefully.

**Comment by xuzhang3** [comment]
Hi @FernandoMiguel  Normally terraform will auto get/get the ID when you try create/update the policy. But if you modify the policy out of terrrfrom won't be able detect the changes.  Terraform manage the resource based on the `.tfstate` file and service responses.
For example: 
1. Create the policy with terraform.
2. Delete the policy from portal.
3. Change TF configures and apply,  terraform will use the policy ID found in the `.tfstate` file but this policy has been deleted. When the change request send to service, service won't  find the policy and will return an error message.

**Comment by xuzhang3** [comment]
The issue will be closed, if you have any questions, please feel free to open it.

**Comment by billbirchatcoles** [comment]
This looks like a duplicate of issue:#112. 

Here's my comment, also duplicated:

We have this issue, I believe this is a provider defect. Here's why:
Terraform did  refresh the state file as part of the plan step, and it **found** 3876:
```
module.product_team[0].azuredevops_branch_policy_auto_reviewers.devops: Refreshing state... [id=3876]
module.product_team[0].azuredevops_branch_policy_auto_reviewers.azure: Refreshing state... [id=3877]

  # module.product_team[0].azuredevops_branch_policy_auto_reviewers.azure will be updated in-place
  ~ resource "azuredevops_branch_policy_auto_reviewers" "azure" {
      ~ blocking   = false -> true
```
then in the Apply step it errored:
```
module.product_team[0].azuredevops_branch_policy_auto_reviewers.devops: Modifying... [id=3876]
module.product_team[0].azuredevops_branch_policy_auto_reviewers.azure: Modifying... [id=3877]
module.product_team[0].azuredevops_branch_policy_auto_reviewers.azure: Modifications complete after 0s [id=3877]
module.product_team[0].azuredevops_group_membership.queue: Modifying... [id=*]
module.product_team[0].azuredevops_group_membership.queue: Still modifying... [id=*, 10s elapsed]
module.product_team[0].azuredevops_group_membership.queue: Modifications complete after 17s [id=*]

Error: Error updating policy in Azure DevOps: The policy configuration with ID '3876' and revision '3' does not exist.

  on ../modules/product_team/main.tf line 157, in resource "azuredevops_branch_policy_auto_reviewers" "devops":
 157: resource "azuredevops_branch_policy_auto_reviewers" "devops" {

```
When I looked at [the API](https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/update?view=azure-devops-rest-5.1) it requires the "revision" attribute. 

So it appears _to me_ that the provider does not record the revision in the state file as part of the ID. Where is the provider getting the revision number from????

My hunch is that when a user changes the policy via the UI, the revision is changed and whatever the provider is sending is not matched in the update REST transaction.

I await your responses with keen interest!
