### ISSUE TITLE
Are there plans to enable roll out of a new organization using this provider

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/terraform-provider-azuredevops#290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We currently create new azure devops organizations and projects using (unofficial/unsupported?) ARM template resources. It would be cool if it was possible to do this using terraform instead.

### New or Affected Resource(s)

* azuredevops_org

**Comment by nmiodice** [comment]
I don't believe that there exists a public API that we can use to create an organization. I'll happily be proven wrong, though, as I think that would be awesome!

ADO APIs:

https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/get%20variable%20groups%20by%20id?view=azure-devops-rest-5.1#security

**Comment by nmiodice** [comment]
cc @xuzhang3

**Comment by Mobrockers** [comment]
Correct, there is no azure devops API. However it is possible to create an azure devops organization (and project) by submitting the following arm template to the azure RM deployment API endpoint:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "accountName": {
      "type": "string",
      "metadata": {
        "description": "The name of the Visual Studio Team Services account, if it doesn't exist it will be created."
      }
    },
    "projectName": {
      "type": "string",
      "metadata": {
        "description": "The name of the Visual Studio Team Services project."
      }
    },
    "processTemplateId": {
      "type": "string",
      "defaultValue": "6B724908-EF14-45CF-84F8-768B5384DA45",
      "allowedValues": [
        "6B724908-EF14-45CF-84F8-768B5384DA45",
        "ADCC42AB-9882-485E-A3ED-7678F01F66BC",
        "27450541-8E31-4150-9947-DC59F998FC01"
      ],
      "metadata": {
        "description": "Scrum: 6B724908-EF14-45CF-84F8-768B5384DA45 / Agile: ADCC42AB-9882-485E-A3ED-7678F01F66BC / CMMI: 27450541-8E31-4150-9947-DC59F998FC01"
      }
    },
    "versionControlOption": {
      "type": "string",
      "defaultValue": "Git",
      "allowedValues": [
        "Git",
        "Tfvc"
      ],
      "metadata": {
        "description": "The version control of the Visual Studio Team Services project's source code: Git or Tfvc."
      }
    },
    "location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location for all resources."
      }
    }
  },
  "variables": {},
  "resources": [
    {
      "name": "[parameters('accountName')]",
      "type": "microsoft.visualstudio/account",
      "location": "[parameters('location')]",
      "apiVersion": "2014-02-26",
      "properties": {
        "operationType": "Create",
        "accountName": "[parameters('accountName')]"
      },
      "resources": [
        {
          "name": "[parameters('projectName')]",
          "type": "project",
          "location": "[parameters('location')]",
          "apiVersion": "2014-02-26",
          "dependsOn": [
            "[concat('microsoft.visualstudio/account/', parameters('accountName'))]"
          ],
          "properties": {
            "ProcessTemplateId": "[parameters('processTemplateId')]",
            "VersionControlOption": "[parameters('versionControlOption')]"
          }
        }
      ]
    }
  ]
}

```

The template definition is here: https://schema.management.azure.com/schemas/2014-02-26/microsoft.visualstudio.json#/resourceDefinitions/account

**Comment by tmeckel** [comment]
Maybe this sounds a bit ridiculous 😀 BUT if there's an ARM endpoint (template) for this, the resource should be implemented in the [AzureRM Terraform provider](https://github.com/terraform-providers/terraform-provider-azurerm)

**Comment by nmiodice** [comment]
@tmeckel I agree -- this seems like a better fit for https://github.com/terraform-providers/terraform-provider-azurerm. I didn't realize you could do that with ARM. 


*Note*: A less-than-ideal solution if you need this ASAP would be to deploy it using this resource - https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html.

**Comment by tmeckel** [comment]
@tiwood any idea how much effort it would be to add support for creating AzDO organizations into the Terraform AzureRM provider?

**Comment by tiwood** [comment]
@tmeckel, I'll look into it today, but I don't really think that you can do that (anymore?) with the Azure API. AFAIK the orgs only show up if you link them to your AAD and/or a subscription for billing.

**Comment by nmiodice** [comment]
I'm going to close this as we have no plans to implement this feature.
