### ISSUE TITLE
Add Agent_Pool data source support

### ISSUE THREAD

**Issue by LaurentLesle** [microsoft/terraform-provider-azuredevops#293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by nmiodice** [comment]
@LaurentLesle can you expand on the use case for this feature? When do you need to reference a property of an agent pool, other than its name (which you'd need for the data source).

**Comment by LaurentLesle** [comment]
I have some situations when the agent pools are already provisioned at the organization level and I want to use the data source to check if the agent pool already exist and skip the creation of the agent pool.

something like that

```hcl
data "azuredevops_agent_pool" "pool1" {
  name = "name of the pool"
}

resource "azuredevops_agent_pool" "pool" {
  count = data.azuredevops_agent_pool.pool1.0 == null ? [1] : [0]
    name = var.pool_name
    auto_provision = false
}
```

**Comment by nmiodice** [comment]
@EliiseS are you working on this? If so, please assign to yourself

**Comment by EliiseS** [comment]
Right, I didn't see this one. I have also assigned myself to the other one: https://github.com/microsoft/terraform-provider-azuredevops/issues/300

But I think it I misunderstood the other one, because I thought it was about getting an agent pool too.
