### ISSUE TITLE
Unable to create "Key Vault linked" Variable groups due to invalid AzureRM service connection

### ISSUE THREAD

**Issue by tiwood** [microsoft/terraform-provider-azuredevops#294]
If I try to create a new variable group, which I want to link to an Azure Key Vault, I'm getting the following error message in Azure DevOps (Portal UI):

```text
Failed to query service connection API: 'https://management.azure.com/subscriptions/providers/Microsoft.KeyVault/vaults?api-version=2016-10-01'. Status Code: 'NotFound', Response from server: '{"error":{"code":"SubscriptionNotFound","message":"The subscription 'providers' could not be found."}}'
```

This only happens for Service Connections created with `azuredevops_serviceendpoint_azurerm`. You can see that the URI is malformed and `missing the actual subscription id`.

It seems the issue is caused by two capital `S` inside the `data` block:

This works (manually created):
```json
{
  "data": {
    "subscriptionId": "123",
    "subscriptionName": "123",
    "environment": "AzureCloud",
    "scopeLevel": "Subscription",
    "creationMode": "Manual"
  }
}
```

This throws the error:
```json
{
  "data": {
    "SubscriptionId": "123",
    "SubscriptionName": "123",
    "environment": "AzureCloud",
    "scopeLevel": "Subscription",
    "creationMode": "Manual"
  }
}
```

I'll create a PR today to fix this.

**Comment by EliiseS** [comment]
This is fixed by PR: https://github.com/microsoft/terraform-provider-azuredevops/pull/277
