### ISSUE TITLE
Git import does not respect default branch of source repo

### ISSUE THREAD

**Issue by matt-FFFFFF** [microsoft/terraform-provider-azuredevops#297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```text
Terraform v0.14.6
+ provider registry.terraform.io/microsoft/azuredevops v0.1.2
```

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
resource "azuredevops_git_repository" "importedrepo" {
  project_id = azuredevops_project.p.id
  name       = "importedrepo"
  initialization {
    init_type   = "Import"
    source_type = "Git"
    source_url  = var.source_repo_url
  }
}
```

### Debug Output

https://gist.github.com/matt-FFFFFF/5477885f7ba3c12bc26c487faafecf60

### Panic Output

n/a

### Expected Behavior

Git repo is imported and the default branch remains as set in the source repo

### Actual Behavior

Git repo is imported and the default branch is not the same as the source repo

### Steps to Reproduce

1. `terraform apply`

### References

Possibly related? 

* #282

**Comment by xuzhang3** [comment]
Hi @matt-FFFFFF Do you mean import repo should use the default branch setting like `refs/heads/master` or  custom the default branch?

**Comment by matt-FFFFFF** [comment]
When I import a repo that has multiple branches, the default branch of the source repository is not respected.

E.g Source repo branches (on GH):

- main [default]
- prod
- canary

Once imported into AzDO using the above, it looks like this

- main
- prod
- canary [default]

**Comment by xuzhang3** [comment]
Hi @matt-FFFFFF   I did some research, this is the default behavior of Azure DevOps. `import` can be used to import repository from Azure DevOps git repo, GitHub repo etc.

**Comment by xuzhang3** [comment]
The issue will be closed, if you have any questions, please feel free to open it.
