### ISSUE TITLE
Implement new resource "Docker Registry Service Connection"

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-azuredevops#297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a service connection to connect to a docker registry other than docker hub.  This can be used to connect to ACR with admin access or another docker registry.

### New or Affected Resource(s)

* azuredevops_serviceconnection_dockerregistry

### Potential Terraform Configuration

```hcl
# Example using ACR, but should work with any docker registry that accepts username and password
data "azurerm_container_registry" "dockerregistry" {
  name                           = "acrregistry"
  resource_group_name = "samplerg"
}

# Create a new service connection for accessing docker registry
resource "azuredevops_serviceendpoint_dockerregistry" "dockerregistry_serviceconnection" {
  service_endpoint_name = data.azurerm_container_registry.dockerregistry.name
  docker_registry = "https://${data.azurerm_container_registry.dockerregistry.login_server}/v1"
  docker_username = data.azurerm_container_registry.dockerregistry.admin_username
  docker_password = data.azurerm_container_registry.dockerregistry.admin_password
  docker_email = ""
  project_id = var.devops_project.id
}
```

### References

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg

* #161

**Comment by mattdot** [comment]
@nmiodice please assign me to this one.

**Comment by nmiodice** [comment]
@mattdot I'm curious -- will this resource be for an arbitrary docker registry that uses username/pass to authenticate? If so, perhaps [resource_serviceendpoint_dockerhub](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_dockerhub.go) can be extended by:
- Adding a new field called `registry_endpoint`
- Having `registry_endpoint` default to `https://index.docker.io/v1/`

If you are trying to implement one that uses a service principal to access ACR, though, it will need to be a new resource.
