### ISSUE TITLE
Create a new agent queue to connect a project to an agent pool

### ISSUE THREAD

**Issue by LaurentLesle** [microsoft/terraform-provider-azuredevops#300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When an agent pool is created with the azuredevops_agent_pool it is created at the organization level. It is also possible to have existing organizations with agent pools created before.

### New or Affected Resource(s)

This feature request is to import an existing agent_pool into a devops project:

```hcl
data "azuredevops_agent_pool" "pool" {
  name = "agent pool name"
}

data "azuredevops_projects" "project" {
    project_name = "project name"
}

# Set the project_id and agent_pool_id import an org level agent pool into a project
resource "azuredevops_agent_pool" "pool" {
  project_id = data.azuredevops_projects.project.projects.*.project_id[0]
  agent_pool_id = data.azuredevops_agent_pool.pool.id
  grant_to_all_pipelines = true
}

```

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by nmiodice** [comment]
Based on your description, it sounds like what you really want is an `azuredevops_agent_queue` resource, which is described by this [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/queues/add?view=azure-devops-rest-5.1):

```
resource "azuredevops_agent_queue" "q" {
  project_id             = ...
  agent_pool_id          = ...
  grant_to_all_pipelines = true|false
}
```

Can you confirm?

**Comment by LaurentLesle** [comment]
Correct. Let me adjust the name of the issue

**Comment by EliiseS** [comment]
I'm working on adding agent pool and agent pools data

**Comment by EliiseS** [comment]
I'm working on adding the data right now, so I'll free this ticket up incase someone else has bandwidth to add this before I will.

**Comment by nmiodice** [comment]
WIP branch - https://github.com/microsoft/terraform-provider-azuredevops/tree/niiodice/agent-pool-queue

**Comment by nmiodice** [comment]
PR posted. cc @LaurentLesle

**Comment by nmiodice** [comment]
@LaurentLesle this feature has been merged!
