### ISSUE TITLE
typos in error message

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/terraform-provider-azuredevops#303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.46.1
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/time v0.6.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.2

### Affected Resource(s)

* `azuredevops_variable_group`

### Debug Output
Error: Expanding variable group resource data: Failed to get the Azure Key **valut** secrets.Code: forbidden, error **messge**:

**Comment by FernandoMiguel** [comment]
https://github.com/microsoft/terraform-provider-azuredevops/blob/33b33401b4539cd9ef245155e3cb8ca5fdd247ed/azuredevops/internal/service/taskagent/resource_variable_group.go#L429
https://github.com/microsoft/terraform-provider-azuredevops/blob/33b33401b4539cd9ef245155e3cb8ca5fdd247ed/azuredevops/internal/service/taskagent/resource_variable_group.go#L451
and other places

**Comment by xuzhang3** [comment]
Hi @FernandoMiguel   This is an open source project, you can submit a PR to  fix this issues.
