### ISSUE TITLE
Add support for settings -> scope -> match_type = DefaultBranch

### ISSUE THREAD

**Issue by esciara** [microsoft/terraform-provider-azuredevops#305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the REST API supports the `DefaultBranch` value for `matchKind`:

```json
  {
    "createdBy": {
      ...
    },
    ...
    "settings": {
      "allowDownvotes": false,
      "blockLastPusherVote": false,
      "creatorVoteCounts": true,
      "minimumApproverCount": 2,
      "requireVoteOnLastIteration": true,
      "resetOnSourcePush": false,
      "resetRejectionsOnSourcePush": false,
      "scope": [
        {
          "matchKind": "DefaultBranch",
          "refName": null,
          "repositoryId": null
        }
      ]
    },
    "type": {
      ...
    },
    ...
  }
```
It should be possible to set it:
```hcl
resource "azuredevops_branch_policy_min_reviewers" "p" {
  ...
  settings {
    ...
    scope {
      match_type     = "DefaultBranch"
    }
  }
}
```
But currently, the only values supported are `Exact` and `Prefix`.

### New or Affected Resource(s)

* azuredevops_branch_policy_min_reviewers

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_min_reviewers" "one" {
  project_id = local.project_id

  enabled  = true
  blocking = true

  settings {
    reviewer_count     = 2

    scope {
      match_type     = "DefaultBranch"
    }
  }
}
```

### References

The values of `matchKind` are not documented in the [API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/create?view=azure-devops-rest-5.1) as the `settings` are defined as a json object.

**Comment by ariciputi** [comment]
Hi,
I had the same issue today and I landed here. AFAICU there is a PR open for this, but it got stuck somehow. How can I help to make this done?

**Comment by wetwicky** [comment]
Hi,
I also had the same issue but with the resource 'azuredevops_branch_policy_status_check'.
 we would requires the same fix for match_type
```hcl
resource "azuredevops_branch_policy_status_check" "p" {
  ...
  settings {
    ...
    scope {
      match_type     = "DefaultBranch"
    }
  }
}
```
