### ISSUE TITLE
In azuredevops providers the azuredevops_users data source do not export list, but set.

### ISSUE THREAD

**Issue by giovanni-fontanel-overit** [microsoft/terraform-provider-azuredevops#308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```hcl
terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = "1.2.1"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.26"
    }
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
```

### Affected Resource(s)

* `azuredevops_azuredevops_users`

### Terraform Configuration Files

```hcl
#Load single user by using it's principal name
data "azuredevops_users" "user_project_administrator" {
  principal_name = "user@company.com"
}
output "output_user_project_administrator" {
  value = data.azuredevops_users.user_project_administrator.users[0].description
}
```

### Debug Output

```hcl
Error: Invalid index

  on common/main.tf line 25, in output "output_user_project_administrator":
  25:   value = data.azuredevops_users.user_project_administrator.users[0]

This value does not have any indices.
```

### Expected Behavior

Should be returned a list, with only one element, accessible with data.azuredevops_users.user_project_administrator.users[0] syntax.

### Actual Behavior

Return a set. In fact, if we write this code:

```hcl
#Load single user by using it's principal name
data "azuredevops_users" "user_project_administrator" {
  principal_name = "user@company.com"
}
output "output_user_project_administrator" {
  value = tolist(data.azuredevops_users.user_project_administrator.users)
}
output "my_user" {
  value = output_user_project_administrator[0].descriptor
  description = "My user is:"
}
```
the output is correct:

```hcl
Changes to Outputs:
  + my_user = "aad.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

### Steps to Reproduce

use my snippet code inside your code and run terraform apply.

**Comment by xuzhang3** [comment]
The origin design return users in set type, need more investigation if we can change the user type from set to list.

**Comment by giovanni-fontanel-overit** [comment]
Hi,
thank you for your reply. I can suppose that the bug is an incorrect or incomplete documentation. [This](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/users#attributes-reference) documentation say:

> The following attributes are exported:
> users - A **list** of existing users
> 

Is more correct to say:

> The following attributes are exported:
> users - A **set** of existing users
> 

?

Or 

> The following attributes are exported:
> users - A **set** of existing users for count=1 and a **list** of existing users for count>1
> 

?

I'm sure that you could provide a better description that I'm suggesting ( sorry, I'm not an editor :) )

**Comment by xuzhang3** [comment]
Hi @gfontanelwork I would prefer `users - A set of existing users`

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
