### ISSUE TITLE
Managing changes for go.mod and the vendor directory

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#311]
Handling changes to go.mod and the vendor directory is a critical point in maintaining the provider code space. The importance stems from the following points

1.	Indiscriminate incorporation of changes to the go.mod file and thus the used packages of a go application can lead to bloating the generated executable. Even if go is very clever in only compiling and linking used code from packages, new packages will only enlarge the code base and the final executable, especially when users introduce new packages when they don’t evaluate in beforehand, if the functionality already exists in present packages.

2.	Indiscriminate incorporation of changes to the go.mod file will increase the likelihood of errors. It’s a characteristic of defensive programming to limit the external dependencies, because external dependencies are not subject to the test procedures of the using project and thus errors are not (actively) detectable by the project but only be noticed by monitoring the used packages about fixes and updates. Even the provider isn’t that vulnerable to errors in other packages because it doesn’t provide a callable service that might be get hijacked, maintainers might be forced to create new releases only because errors in used packages and not by own fixes and improving the functionality.

3.	Changes to the vendor directory, included in pull requests, might overwrite already incorporated fixes from the used packages. Typically it’s hard to evaluate changes to the vendor directory because of its sheer mass and thus this will make it likely that fixes to package code, which already has been merged, will be overwritten by erroneous code which will lead to one or more regressions in the provider executable.  Which will require the maintainers to create a new release.

4.	The go.mod and vendor directory might get out of sync. If there’s no step in the PR evaluation process (which could be an automatic step), which always ensures that go.mod and the vendor directory are in sync, it will provoke errors during compilation of the provider code base. Furthermore forcibly ensuring the synchronicity of go.mod and the vendor directory, usually by using `go mod tidy` followed by `go mod vendor`, will likely change the vendor directory which might introduce unwanted changes, whose effects are already described in 3.

The following counter measures seem to be valuable in tackling the above mentioned issue areas: 
1.	Extend the PR template with a question about if the submitter introduced a new package into go.mod. If this is the case the submitter should justify its decision in using the package and that he or she searched through the already used packages for the same or similar functionality and found no matching counterpart.

2.	Maintainers must have a close look on changes to the vendor directory so that unwanted changes from PRs will overwrite bug fixed code with old (erroneous) code. 

3.	Aside the usage of Sonarcloud, to ensure and increase code quality, Whitesource (Bolt) should be integrated to the build pipeline to automatically detected vulnerabilities or issues with colliding licenses in used packages.

**Comment by nmiodice** [comment]
Thanks for the writeup @tmeckel - I think that this is a worthwhile pursuit. A questions to help me learn a bit more...

> Changes to the vendor directory, included in pull requests, might overwrite already incorporated fixes from the used packages

Are you referring to changes manually made to files that reside in `vendor/`, or changes that have been made in the packages and incorporated into the `vendor/` directory via `go mod vendor`?

**Comment by tmeckel** [comment]
@nmiodice Ha! Same question @EliiseS had yesterday ... Hold on I'll copy my answer from LinkedIn 😁 

> With manually I mean using 'go mod vendor'. The issue is you can do a 'go mod vendor' change the vendor directory and not committing the go.mod in conjunction with those changes. So you end up with a discrepancy between go.mod and the vendor directory.

And well of course you can inadvertently or intentionally manually incorporate changes to the vendor directory. Me and @tiwood are using this approach to fix the nasty error in the DevOps Go API, which prevents us from rolling out support for permission related feature in the provider. 

This particular use case might emphasize the problems you can run in with what I described in (3). You applied a (temporary) patch to the vendor directory to circumvent some error from a used (external) package. But someone might overwrite your patch by a PR. Okay, one could argue that this approach (changing files in the vendor directory) is (really?) bad practice. But hey, sometimes the end justifies the means.

**Comment by xuzhang3** [comment]
I think we should submit in a separate PR when we need update `go.mod` file. In this way , if one user update vendor files through `go mod vendor && go mod tidy`, another user won't be able to overwrite the vendor files already used.

**Comment by tmeckel** [comment]
@xuzhang3 this could be a possibility as well. Perhaps we should ask someone from Hashicorp how they handle changes around `go.mod` and the `vendor` directory. Megan Marsh (@SwampDragons) comes to my mind for example, because she's maintaining [Packer](https://github.com/hashicorp/packer) for Hashicorp. And perhaps, in the end, I might over emphasize the importance and potential hazards which comes with changes to `go.mod` and the `vendor` directory.

**Comment by xuzhang3** [comment]
@tmeckel
Hashicorp handle `go.mod` update in separate PR.

**Comment by SwampDragons** [comment]
Hi! Thanks for pinging me. It's definitely a sticky problem and doesn't have a perfect answer. But here's a basic outline of how Packer approaches dependency management.

To address #1:  When possible, we try to live by "A little copying is better than a little dependency." (https://go-proverbs.github.io/).

Even with that guidelines, Packer is huge because of all the different APIs and use cases we have to support. I will say that when I first started maintaining Packer I was a lot more concerned about updating dependencies, but one nice thing about golang being statically compiled is that if there are any big breaking changes we generally find out when we try to build before anything gets committed. At the end of the day our philosophy is that a binary being a little bloated is probably not the end of the world. 

For #2: We generally do not update dependencies "just because" a new release of that dependency has come out, instead opting to keep things as static as possible unless we need an upstream change. We tend to prioritize well-maintained third party packages, especially those that are either very widely used in the community or those that are backed by an actual company, since those are probably less likely to be susceptible to hijacking or malicious changes. 

To solve #3 and #4: In Packer, we have a Makefile command that runs during our branch tests; it checks to make sure that the mod file and vendor directory match, and CI fails if they don't match. Code is here:

https://github.com/hashicorp/packer/blob/master/Makefile#L158-L163

Hope this helps guide your decisionmaking a bit!

**Comment by tmeckel** [comment]
@SwampDragons  Megan, thank you very much for your detailed contribution and I knew why I wanted your opinion on the topic here in the discussion!

@nmiodice, @xuzhang3 from my point of view, we definitely should incorporate the Makefile command Megan mentioned in her answer as soon as possible. Regarding to the other answers we should define a process in a short time frame, how we want to handle changes to `go.mod` and `vendor` here at the provider, so that we can communicate these decisions to potential contributors via the [contribution guidelines](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/docs/contributing.md) as well.

**Comment by xuzhang3** [comment]
@tmeckel  @nmiodice
I can update the `Makefile`.  Also I will update `ci.yml` file too,  current pipeline builds are not using `Makefile` commands

**Comment by EliiseS** [comment]
@xuzhang3 I believe nick was looking into using the make file commands in CI yesterday, but I'm not sure how far he got

**Comment by nmiodice** [comment]
Not very far @EliiseS

**Comment by xuzhang3** [comment]
> Not very far @EliiseS. I was investigating using the Makefile to install the provider and run `terraform validate` against the example TF we have. I got frustrated and did something else, instead haha!

I have a branch working on this feature too and nearly finished it.

**Comment by nmiodice** [comment]
I've gone ahead and integrated the vendor checks into the CI - see the linked PR. Note, I ended up using the following:

```bash
check-vendor-vs-mod: ## Check that go modules and vendored code are on par
	@echo "==> Checking that go modules and vendored dependencies match..."
	go mod vendor
	@if [[ `git status --porcelain vendor` ]]; then \
		echo "ERROR: vendor dir is not on par with go modules definition." && \
		exit 1; \
	fi
```

This is slightly different than the example shared by @SwampDragons - I found that by using the `git diff` approach it would not catch *new* files (i.e., an added dependency) as changes caused by *new* dependencies were not staged changes, and therefore not picked up by `git diff`. 

cc @tmeckel

**Comment by tmeckel** [comment]
@nmiodice great catch to use `git status` to detect new files in the vendor branch as well!! Like it! Perhaps @SwampDragons will adapt your solution in Packer 😁

**Comment by nmiodice** [comment]
If I’m not mistaken, I believe this issue can be closed. Feel free to re-open if I’ve missed anything here.

**Comment by tmeckel** [comment]
@nmiodice  With #343 we ensure that `vendor` and `go.mod` are in sync. But what's the process around introducing new packages in `go.mod`?

**Comment by nmiodice** [comment]
I've tried to elaborate on that here, @tmeckel: https://github.com/microsoft/terraform-provider-azuredevops/blob/master/docs/contributing.md#8-post-a-pr

were you thinking something more explicit?

**Comment by tmeckel** [comment]
@nmiodice oh I'm sorry Nick! I simply overlooked this. Good wording! Although as a German I would prefer a checklist, of course. Naaaa ... just kidding! 😁 So IMHO because all objectives of this issue has been achieved, you were right to close it! 👍

**Comment by nmiodice** [comment]
Hah!! That made me chuckle :). I’ll go ahead and close this out. Not a bad way to start my Friday!

**Comment by tmeckel** [comment]
@nmiodice just stumbled upon this
go-mod-outdated: A Tool to Find Outdated Dependencies - https://t.co/pjIksbrYhN
