### ISSUE TITLE
Adding AD group as a member of Azure DevOps group with Terraform

### ISSUE THREAD

**Issue by jacky-ni** [microsoft/terraform-provider-azuredevops#313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For adding a member to a group in Azure DevOps with Terraform, I use `azuredevops_group_membership`, however, I cannot find a way to add an AD group as a member in the Azure DevOps group with Terraform.

In the DevOps GUI, I can add an AD group via project setting -> permissions -> select a group -> members -> Add, and search the wanted group. However, I cannot find a way to do so with Terraform.

### Desired solution
It is desired that in the `azuredevops_group_membership`, the name of an AD group can also be used as the `principle_name`

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
}

resource "azuredevops_project" "terraform_experimental" {
  name               = var.project_name
  description        = var.description
}

resource "azuredevops_user_entitlement" "user1" {
  principal_name = "jackyni@outlook.com" # Here, I would like to use an AD group name, such as 'euw-team1-core'
}

data "azuredevops_group" "terraform_experimental_readers" {
  project_id = azuredevops_project.terraform_experimental.id
  name       = "Readers"
}

resource "azuredevops_group_membership" "reader_membership" {
  group = data.azuredevops_group.terraform_experimental_readers.descriptor
  members = [
    azuredevops_user_entitlement.user1.descriptor
  ]
}

```

**Comment by josh-barker-coles** [comment]
Hi @jacky-ni,

Is this what you're trying to do - https://github.com/microsoft/terraform-provider-azuredevops/issues/51#issuecomment-759217529

Perhaps the documentation / examples could be updated?

/cc @xuzhang3

**Comment by jacky-ni** [comment]
Hi @josh-barker-coles 

Thanks a lot for your solution, I tried it and it works well.
It seems that I am missing the step that transfers the aad ID to Azdo group descriptor...
Great solution!
