### ISSUE TITLE
Variable group created. But getting 401 Unauthorized error (PAT permissions :Variable Groups: Read, Create, & Manage)

### ISSUE THREAD

**Issue by nimmyarjith** [microsoft/terraform-provider-azuredevops#314]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v0.12.29
azuredevops 0.1.2.

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
terraform {
required_version = ">= 0.11"
  required_providers {
	azurerm = "~> 2.20"
    azuredevops = {
      #source = "microsoft/azuredevops"
      version = ">= 0.0.1"          
    }
  }
}
provider "azuredevops" {
   personal_access_token = "<token>"
   org_service_url       = "https://dev.azure.com/organization" 
}
data "azuredevops_project" "adoproject" {
  name = "ProjectName"
}
resource "azuredevops_variable_group" "vg" {
  project_id   = data.azuredevops_project.adoproject.id
  name         = "auto-test-variable-set"
  description  = "Test Variable Group Description"
  allow_access = false

  variable {
    name  = "key"
    value = "value"
  }  
}

output "varid" {
  value = azuredevops_variable_group.vg.id
}
```

### Debug Output

Error: Error creating definitionResourceReference Azure DevOps object: Request returned status: 401 Unauthorized
![image](https://user-images.githubusercontent.com/75978295/109500459-3f149880-7ad1-11eb-8248-b08c0ad0e5c8.png)

### Expected Behavior

Variable group should be created in ADO without any terraform output errors.

### Actual Behavior

**Variable group is getting created. But getting  401 Unauthorized in terraform**

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The PAT token  have the following permission as per the terraform documentation
**Variable Groups: Read, Create, & Manage**

**Comment by xuzhang3** [comment]
Hi @nimmyarjith  Variable group is configured under a project and project need read the template configurations. So you should grant at least the following permissions: `Project:  read`, `Work Items: Read` and `Variable Groups: Read, create, & manage `

**Comment by nimmyarjith** [comment]
Hi @xuzhang3 Thank you for your response. We have also tried with the read permissions on project, workitem and something more. It did not work actually. But our concern is that TF is creating the variable groups. If it was a permission issue, it should not create the variable group itself. But it is creating it. But returning error. Any more suggestions please

**Comment by xuzhang3** [comment]
Hi @nimmyarjith  The root issue here is `azuredevops_variable_group` can grant the access permission to pipelines 
![image](https://user-images.githubusercontent.com/57888764/110060548-0f9baf80-7da1-11eb-86a8-19d1417fc113.png)
This permission managed by `Tokens` or `Token Administration`. I would suggest you grant the access with `azuredevops_resource_authorization` though `azuredevops_variable_group` can also set the access permission for piplines.

**Comment by nimmyarjith** [comment]
Hi @xuzhang3  Thanks for your reply. Sorry i did not get that point. Because we are setting allow_access = false in our code

**Comment by xuzhang3** [comment]
`azuredevops_variable_group` will try set to the access flag for pipelines and this permission is managed by `Tokens` and `Token Administration`

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.

**Comment by stewartadam** [comment]
@xuzhang3 are these documented anywhere? It seems like this information would be key to have on the respective doc pages, e.g. https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/variable_group

**Comment by xuzhang3** [comment]
@stewartadam All the documents are at https://github.com/microsoft/terraform-provider-azuredevops/tree/master/website/docs
The variable group document: https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/variable_group.html.markdown

**Comment by stewartadam** [comment]
I think those the resource doc pages may need a pass from someone familiar with the inner workings of this provider to update the required permissions - for example the page linked for Variable Groups mentions "PAT Permissions required: Variable Groups: Read, Create, & Manage" which based on the discussion above now seems to require:

* Projects: read
* Work Items: Read
* Variable Groups: Read, create, & manage
* Tokens: Token Administration

**Comment by cmayomsft** [comment]
Please reopen this issue. I am also getting 401's when trying to create a Variable Group using a PAT with Variable Groups: Read, Create, & Manage scope. The feature is confusing (why do I need more scopes?) and docs are incorrect (doesn't prescribe the scopes I do need).

But, it is also failing when I use the scopes suggested in this issue.

I was only able to get this working when I added Build - Read and Execute.

So, it worked with the following PAT scopes:
* Build - Read & execute
* Project and Team - Read
* Tokens - Read and manage
* Token Administration - Read and manage
* Work Items - Read
* Variable Groups - Read, Create, & Manage

Please reopen.

**Comment by ceesios** [comment]
please reopen. I have tested with all of the documented PAT scopes and also with every scope available and I am unable to get rid of the 401 error with v0.2.0.

**Comment by xuzhang3** [comment]
@ceesios  Latest changes not released yet, if you need this features, you can build a private package by yourself with:
```
linux/mac:
go build -gcflags="-N -l" -o terraform-provider-azurerm
windows:
go build -gcflags="-N -l" -o terraform-provider-azurerm.exe
```
