### ISSUE TITLE
Investigate potential issue configuring build for GitHub repos

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#314]
**Note**: This issue was reported on Gitter. This issue reflects the investigation into any possible bugs, but there was not much information on reproducing the stated error

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
$ terraform -v
Terraform v0.12.24
```

### Affected Resource(s)

* `azuredevops_build_definition`

### Terraform Configuration Files

```hcl
TBD
```

### Debug Output

```
TBD
```

### Panic Output

```
TBD
```

### Expected Behavior

The terraform apply should not fail

### Actual Behavior

From the Gitter thread:
> using this new provider to build github connected build definitions has caused TF Cloud to crash as well as spit out very generic errors of the provider

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This was reported on Gitter and needs investigation

### References

https://gitter.im/terraform-provider-azuredevops/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by nmiodice** [comment]
@lachie-white can you provide the configuration you used that fails? I have the following configuration that applies without any error agains the latest master

> note: the build itself will fail because I have not set any environment vars..., but the TF apply seems to work w/o issues

```hcl
resource "azuredevops_project" "project" {
  project_name       = "Nick Test Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_github" "serviceendpoint" {
  project_id             = azuredevops_project.project.id
  service_endpoint_name  = "Sample GithHub Personal Access Token"
    
  # Set using the `AZDO_GITHUB_SERVICE_CONNECTION_PAT` environment variable
  auth_personal {
  }
}

resource "azuredevops_build_definition" "nightly_build" {
  project_id      = azuredevops_project.project.id
  agent_pool_name = "Hosted Ubuntu 1604"
  name            = "Nightly Build"

  repository {
    repo_type             = "GitHub"
    repo_id               = "microsoft/terraform-provider-azuredevops"
    repo_name             = "microsoft/terraform-provider-azuredevops"
    branch_name           = "master"
    yml_path              = ".azdo/azure-pipeline-nightly.yml"
    service_connection_id = azuredevops_serviceendpoint_github.serviceendpoint.id
  }
}
```

**Comment by lachie-white** [comment]
Thanks for opening this issue @nmiodice, This could just come down to many documentation errors but either way its good to solve.

Firstly, within the Usage Example of the Readme, `repo_id` is not mentioned anywhere so following that will lead users to an issue straight away. It is also not within any of the other examples e.g. https://github.com/microsoft/terraform-provider-azuredevops/blob/master/examples/github-based-cicd-simple/main.tf

As you can see in your example it now just leads to duplicated information as `repo_id` and `repo_name` are the same for Github's repository link.

`repo_id` is also excepted as an empty string, which is odd for a required field. 

I believe the terraform crash was occurring when going back and forth between changing properties in many applies within the repository block, not able to re-create this as of today.

Code i was using:
```
resource "azuredevops_build_definition" "build" {
  project_id      = azuredevops_project.project.id
  agent_pool_name = "Hosted Ubuntu 1604"
  name            = "Infra_Build"
  path            = "\\"

  repository {
    repo_id               = ""
    repo_type             = "GitHub"
    repo_name             = "GitOpsDemo/gitopsdemoinfra"
    branch_name           = "master"
    yml_path              = ".azdo/azure-pipelines.yaml"
    service_connection_id = azuredevops_serviceendpoint_github.github_service_connection.id
  }
}
```

**Comment by nmiodice** [comment]
Ok! This is good context. I'd like to mull on the right approach here for a bit. I'll report back when I have some quiet time to work through it.

**Comment by nmiodice** [comment]
@lachie-white I went ahead and removed the redundant field in this PR https://github.com/microsoft/terraform-provider-azuredevops/pull/321

**Comment by nmiodice** [comment]
Closing as the docs have been fixed and redundant field removed
