### ISSUE TITLE
Verify that all documentation is up to date

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

The documentation should be up to date

### References

https://gitter.im/terraform-provider-azuredevops/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by lachie-white** [comment]
Not sure if these all belong here but:

- ```repo_id``` is not mentioned anywhere in the documentation.
- Example is out of date and no longer works.
https://github.com/microsoft/terraform-provider-azuredevops/blob/master/examples/github-based-cicd-simple/main.tf
- Delete Resource Authorizations (Such as Github Service Connection Authorization) at the same time as a project deletion fails with an error (re-running the plan corrects this):
```
Terraform v0.12.24
Initializing plugins and modules...
2020/05/14 15:34:06 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/4df8ee1acd
azuredevops_resource_authorization.azurerm_auth: Destroying... [id=accf6120-a493-4dfe-bae7-3e79885374c7]
azuredevops_resource_authorization.github_auth: Destroying... [id=f8f1776b-7e21-4432-8da0-b1f94e249ab8]
azuredevops_build_definition.build: Destroying... [id=16]
azuredevops_resource_authorization.github_auth: Destruction complete after 1s
azuredevops_build_definition.build: Destruction complete after 1s
azuredevops_serviceendpoint_github.github_service_connection: Destroying... [id=f8f1776b-7e21-4432-8da0-b1f94e249ab8]
azuredevops_serviceendpoint_github.github_service_connection: Destruction complete after 1s

Error: error deleting authorized resource: no project resources have been authorized
```
- I think there has been a spelling mistake in the documentation or the code for this resource: https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/serviceendpoint_github.html.markdown
The documentation and examples refer to an ```auth_oauth``` however, one doesn't exist and looking within the GO code there is only mention of ```auth_oath```
- I found my self digging around the website pages a lot: https://github.com/microsoft/terraform-provider-azuredevops/tree/master/website/docs/r as these seemed to have the best / most up to date documentation on the resources but feel these should be maybe easier to find. (Understanding that when this provider is published in the TF Registry it will be)
-

**Comment by erickascic** [comment]
the README.md references azuredevops_azure_git_repository instead of azuredevops_git_repository

**Comment by nmiodice** [comment]
Keep the feedback coming! I have a branch where I am working through fixing these

https://github.com/microsoft/terraform-provider-azuredevops/tree/niiodice/docs-update

**Comment by nmiodice** [comment]
I've created a [PR](https://github.com/microsoft/terraform-provider-azuredevops/pull/320) to address the following:
 - Validate all sample `*.tf` files
 - Validate all documentation for resources - includes documenting `repo_id` field
 - Validate all documentation for data sources
 - Fix `azuredevops_azure_git_repository` issue in main `README.md`
 - Fix typo for `auth_oath`
 - Explicitly link to website docs from the main `README.md`

I'll need to investigate the following:
 - Delete Resource Authorizations (Such as Github Service Connection Authorization) at the same time as a project - @lachie-white can you share your Terraform code that reproduces this issue?
 - Investigate if we can prefer ONE of `repo_id` or `repo_name`

**Comment by lachie-white** [comment]
@nmiodice :

If you build the below (sub in the correct PAT's) then try to remove it all in one step the error occurs.


```
resource "azuredevops_project" "project" {
  project_name       = "AzDO Project Name"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_build_definition" "build" {
  project_id      = azuredevops_project.project.id
  agent_pool_name = "Hosted Ubuntu 1604"
  name            = "Infra_Build"
  path            = "\\"

  repository {
    repo_id               = ""
    repo_type             = "GitHub"
    repo_name             = "GitOpsDemo/gitopsdemoinfra"
    branch_name           = "master"
    yml_path              = ".azdo/azure-pipelines.yaml"
    service_connection_id = azuredevops_serviceendpoint_github.github_service_connection.id
  }
}

resource "azuredevops_serviceendpoint_github" "github_service_connection" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "GitHub_Service_Connection"
  auth_personal {
    personal_access_token = "xxxxxxxxxxxxxxxxxxxxx"
  }
}

resource "azuredevops_resource_authorization" "github_auth" {
  project_id  = azuredevops_project.project.id
  resource_id = azuredevops_serviceendpoint_github.github_service_connection.id
  authorized  = true
}

resource "azuredevops_serviceendpoint_azurerm" "azure_service_connection" {
  project_id                = azuredevops_project.project.id
  service_endpoint_name     = "Azure_Service_Connection"
  azurerm_spn_tenantid      = "xxxxxxxxxxxxxxxxxxxxx"
  azurerm_subscription_id   = "xxxxxxxxxxxxxxxxxxxxx"
  azurerm_subscription_name = "Subscription_Name"
  credentials {
    serviceprincipalid  = "xxxxxxxxxxxxxxxxxxxxx"
    serviceprincipalkey = "xxxxxxxxxxxxxxxxxxxxx"
  }
}

resource "azuredevops_resource_authorization" "azurerm_auth" {
  project_id  = azuredevops_project.project.id
  resource_id = azuredevops_serviceendpoint_azurerm.azure_service_connection.id
  authorized  = true
}
```

**Comment by nmiodice** [comment]
Reproducing and found the issue. Implementing the fix today

**Comment by nmiodice** [comment]
I believe all of the items here are closed out. @lachie-white can you confirm? If so, we can consider this issue closed!

**Comment by lachie-white** [comment]
LGTM! Awesome work, I can't wait till this is in the registry and ready to be used!
