### ISSUE TITLE
Cloning README Instructions Are Unclear

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/terraform-provider-azuredevops#316]
### Affected Resource(s)

* README.md

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Cloning into the GOPATH

### Actual Behavior

You clone into the GOPATH but the instructions are very strange.

```
$ mkdir -p $GOPATH/src/github.com/terraform-providers/terraform-provider-azuredevops; cd $GOPATH/src/github.com/terraform-providers/terraform-provider-azuredevops
$ git clone git@github.com:terraform-providers/terraform-provider-azuredevops.git
$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-azuredevops.git
```

### Steps to Reproduce

1. `mkdir` will make a directory called `src/github.com/terraform-providers/terraform-provider-azuredevops` in the GOPATH
2. ... Which we then `cd` into.
3. And then we clone, which would make another directory beneath our current one: 
```
~/go/src/github.com/terraform-providers/terraform-provider-azuredevops/terraform-provider-azuredevops
```
4. And then there is a line saying to `cd` into a `.git`. 

#### Suggestions:

I've forked the repo and can handle these suggestions as needed.

* Split the `;` line into two for better readability. Long lines in code-formatted sections is not the best IMO
* Have `mkdir` make the top-level folder only, ie `mkdir $GOPATH/src/github.com/terraform-providers/`
* `cd` into the top-level, _then_ clone

Goal: Just to make this read more easily, look more unified.

### Important Factoids

n/a

### References

n/a

**Comment by xuzhang3** [comment]
@mindlessroman
Sorry this REAMME.md file misleading you. This file was prepared for migrate this provider to Terrform official repository,  some path or rep path had been changed to a place not exist. I will change this file or you can help update this file.     

I will change this introduce looks like:
```sh
$ mkdir -p $GOPATH/src/github.com/terraform-providers && cd $GOPATH/src/github.com/terraform-providers
$ git clone git@github.com:microsoft/terraform-provider-azuredevops.git
$ cd terraform-provider-azuredevops
```

**Comment by mindlessroman** [comment]
Perfect!!!

**Comment by mindlessroman** [comment]
Just made the PR #317 if you want to review @xuzhang3

**Comment by nmiodice** [comment]
Merged, so I'll close this issue. Thanks @mindlessroman !
