### ISSUE TITLE
A provider named "azuredevops" could not be found in the Terraform Registry.

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/terraform-provider-azuredevops#325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- `Terraform v0.12.25`
- `provider azuredevops 0.1.2`

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I would like to use the `azuredevops` provider in my Terraform template but when running `terraform init` I got the error that this provider doesn't exit in the Terraform registry. Am I missing anything? I'm not sure to see anything in this GH repo about how to get this working?

### Actual Behavior

```
sudo terraform init
Initializing the backend...
Initializing provider plugins...
- Checking for available provider plugins...
Provider "azuredevops" not available for installation.
A provider named "azuredevops" could not be found in the Terraform Registry.
This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.
In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64
Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
Error: no provider exists with the given name
```

### Steps to Reproduce

1. `terraform init`

### Important Factoids

N/A

### References

N/A

**Comment by nmiodice** [comment]
Hi @mathieu-benoit - The instructions (for now) to use this provider can be found [here](https://github.com/microsoft/terraform-provider-azuredevops#developing-the-provider). You'll need to run `./scripts/build.sh && ./scripts/local-install.sh` to side-load it into your local plugins folder. Then your `init` should work without issue.

You can follow along with [this issue](https://github.com/microsoft/terraform-provider-azuredevops/issues/241) to better understand where this provider is in the [Provider Partner Program](https://www.terraform.io/guides/terraform-provider-development-program.html) process. The long term goal is to be able to download this from the HC registry.

**Comment by mathieu-benoit** [comment]
Ok got it, go to know, thanks. Do you think having a section in the main README.md which call out "how to install this tf provider"?

**Comment by nmiodice** [comment]
I do indeed, however, part of https://github.com/microsoft/terraform-provider-azuredevops/issues/241 is migrating to what the steps *should/will* be and so we made a decision to remove them for the time being.

If this process is delayed we can add them back in.

**Comment by seqdan** [comment]
I had the same issue as @mathieu_benoit : It took me a while to figure out how to install and use the provider. Maybe something very simple like https://github.com/microsoft/terraform-provider-azuredevops/pull/331 would help.
