### ISSUE TITLE
May I know the whitelist of domain when downloading this provider?

### ISSUE THREAD

**Issue by cc93691810** [microsoft/terraform-provider-azuredevops#327]
When downloading and installing this provider, we got the below error. May I know the whitelist of the domain so that we can add them into our firewall rules.

![image](https://user-images.githubusercontent.com/43203994/111126371-96c10280-85ad-11eb-9ba9-3d300bd9b4d6.png)

**Comment by xuzhang3** [comment]
Hi @cc93691810  ADO provider is released at https://registry.terraform.io/providers/microsoft/azuredevops/latest

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
