### ISSUE TITLE
Unable to download Microsoft's Official Terraform Provider for Azure DevOps

### ISSUE THREAD

**Issue by nimmyarjith** [microsoft/terraform-provider-azuredevops#329]
Hi All,

We get error while initializing the azuredevops provider.

We use Octopus as a deployment tool. The tentacle agent is in a controlled environment, protected by firewall. The terraform code is running from there. Initially we were getting error

**"https://github.com/microsoft/terraform-provider-azuredevops/releases/download/v0.1.2/terraform-provider-azuredevops_0.1.2_SHA256SUMS": 
An existing connection was forcibly closed by the remote host. Error: Failed to install providers**

We opened the FW for domain https://github.com

But now it is failing while downloading from **"https://github-releases.githubusercontent.com/....."**

So it is coming as a series

Could you please help us to get the full domain list to be whitelisted for using azuredevops provider

Thanks in advance

**Comment by xuzhang3** [comment]
Hi @nimmyarjith  ADO is released at https://registry.terraform.io/providers/microsoft/azuredevops/latest. So I think you need add `https://registry.terraform.io` to your FW.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another issue if you have questions.
