### ISSUE TITLE
Implement new resource "ACR Service Endpoint"

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#33]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162
Originally created by @ThePhen on *Tue, 29 Oct 2019 20:12:43 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-624858756
Originally created by @mattdot on *Wed, 06 May 2020 19:59:37 GMT*

---
@nmiodice is this still blocked or would it be possible to create now?

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-624864896
Originally created by @nmiodice on *Wed, 06 May 2020 20:12:15 GMT*

---
If you'd like, I can assign this to you if you have plans to implement

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-547986799
Originally created by @nmiodice on *Wed, 30 Oct 2019 16:13:47 GMT*

---
Blocked on https://github.com/microsoft/terraform-provider-azuredevops/issues/160

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-625059250
Originally created by @mattdot on *Thu, 07 May 2020 06:35:15 GMT*

---
After looking into it a little more, what we actually need is an “other docker repository” service connection.  I’ll create a feature request for that one and submit a pr in the next couple days.

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-624864272
Originally created by @nmiodice on *Wed, 06 May 2020 20:11:00 GMT*

---
@mattdot this is no longer blocked. There is a core component that you can use to simplify the creation of service endpoints located [here](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/crud/serviceendpoint/crud_service_endpoint.go)

Examples:
- [AzureRM](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_azurerm.go)
- [DockerHub](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_dockerhub.go)
- [BitBucket](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_bitbucket.go)

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-639359693
Originally created by @xuzhang3 on *Fri, 05 Jun 2020 09:14:00 GMT*

---
Closing this issue due to #304

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/162#issuecomment-639726455
Originally created by @nmiodice on *Fri, 05 Jun 2020 19:10:23 GMT*

---
Re-opening - 304 was for docker registry connections. There is another type - ACR - which does not require a username/password

**Comment by beandrad** [comment]
I'd like to work on this issue.

**Comment by xuzhang3** [comment]
Close this issue due to https://github.com/microsoft/terraform-provider-azuredevops/pull/119.
