### ISSUE TITLE
How to add GitHub Enterprise Server service connection using provider

### ISSUE THREAD

**Issue by jpiecuch** [microsoft/terraform-provider-azuredevops#331]
Hello folks,

is there a way to create GitHub Enterprise Server service connection using provider or this functionality is not yet available? I went through documentation https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_github and couldn't find any information about this.

**Comment by xuzhang3** [comment]
Hi @jpiecuch  GitHub Enterprise Server service connection  is not yet available. #210  is tracking on this resource.

**Comment by jpiecuch** [comment]
Thank you for quick answer!
