### ISSUE TITLE
Support darwin/arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by julie-ng** [microsoft/terraform-provider-azuredevops#332]
I am running Terraform on a new Apple mac with the m1 chip and while most terraform providers, including azurerm have been updated to run on arm architecture, the `microsoft/azuredevops` provider does not work.

### Terraform (and Azure DevOps Provider) Version

| Software | Version |
|:--|:--|
| Terraform CLI | 0.14.7 |
| azuredevops Provider | 0.1.2 |

### Expected Behavior

Terraform is successfully initialized.

### Actual Behavior

```
Error: Incompatible provider version

Provider registry.terraform.io/microsoft/azuredevops v0.1.2 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

### Steps to Reproduce

I am using this repo [azure/devops-governance](https://github.com/azure/devops-governance), which works fine on my other computer and in CI/CD builds.

```
$ terraform init -backend-config=azure.conf
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Finding hashicorp/azuread versions matching "1.4.0"...
- Finding microsoft/azuredevops versions matching ">= 0.1.0"...
- Finding hashicorp/azurerm versions matching ">= 2.50.0, 2.51.0"...
- Installing hashicorp/azurerm v2.51.0...
- Installed hashicorp/azurerm v2.51.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/azuread v1.4.0...
- Installed hashicorp/azuread v1.4.0 (signed by HashiCorp)

Error: Incompatible provider version

Provider registry.terraform.io/microsoft/azuredevops v0.1.2 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

### References

Most other Terraform providers have since updated their binaries to work with m1 macs. See:
https://github.com/hashicorp/terraform/issues/27257

**Comment by xuzhang3** [comment]
Hi @julie-ng  Thanks for your feedback.  ADO is built based on GO v1.14. We need upgrade the golang from v1.14 to v1.16 to support Apple Silicon.

**Comment by julie-ng** [comment]
Thanks @xuzhang3 for the response. Any idea on the timeline for this? March? April?

**Comment by xuzhang3** [comment]
Hi @julie-ng   v0.1.3 support darwin/arm64

**Comment by xuzhang3** [comment]
Close  this issue, feel free to open another issue if you have questions.
