### ISSUE TITLE
Login with Service Principal instead of PAT

### ISSUE THREAD

**Issue by carlosjourdan** [microsoft/terraform-provider-azuredevops#335]
How can I login with Service Principal instead of using Personnal Access Tokens when running terraform commands? 

I'm trying to build an Azure Devops project that will be used to manage terraform files and deploy other Azure Devops projects. The idea is to have a git repository with .tf files, and a pipeline that will execute terraform apply. But in order to do that, I need to have persistent credentials, not PATs.

**Comment by nmiodice** [comment]
@carlosjourdan can you elaborate on why a PAT is not sufficient for your use case? Can you provide a link to the documentation that describes, in detail, the authentication strategy you want to use?

**Comment by carlosjourdan** [comment]
Looking into the [docs](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops) I found out that "The Azure DevOps API doesn't support non-interactive service access via service principals."

So I guess there's nothing to be done here unless that changes.

Thanks anyway.
