### ISSUE TITLE
`ci_trigger` and `pull_request_trigger` blocks cause error for build definitions

### ISSUE THREAD

**Issue by edwardwu-servian** [microsoft/terraform-provider-azuredevops#336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
```
terraform -v
Terraform v0.12.24
```
Azure DevOps Provider version 0.1.2

### Affected Resource(s)

* azuredevops_build_definition
https://github.com/microsoft/terraform-provider-azuredevops/blob/bee91ffa72f2ef5581a91b83940e9f5087f64dd8/azuredevops/resource_build_definition.go#L135

### Terraform Configuration Files

```hcl
resource "azuredevops_build_definition" "module" {
  project_id = var.project_id
  name       = var.pipeline_name

  ci_trigger {
    use_yaml = true
  }

  pull_request_trigger {
    use_yaml = true

    forks {
      enabled       = false
      share_secrets = false
    }
  }

  repository {
    repo_name             = var.repo_name
    repo_type             = var.repo_type
    service_connection_id = var.service_connection_id
    yml_path              = var.pipeline_yaml_file_path
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Thank you for making this provider available! It's great!

We are using Bitbucket repo and expecting to use this provider to create Azure DevOps pipeline. `azuredevops_build_definition` should be able to create that without requiring `repo_id` when `repo_type` is `Bitbucket` - we are not expecting a `repo_id` since the repository is not managed by Azure DevOps.

### Actual Behavior

`terraform plan` reports "missing required argument" error.
```
Error: Missing required argument

  on main.tf line 29, in resource "azuredevops_build_definition" "module":
  29:   repository {

The argument "repo_id" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

https://github.com/microsoft/terraform-provider-azuredevops/pull/321
* #0000

**Comment by nmiodice** [comment]
I'm not a bitbucket expert so I may be messing up the terms here, but the `repo_id` in this case, and for GitHub, will look like the following (using this repo as an example): `microsoft/terraform-provider-azuredevops`. So it is `<org>/<repo>`.

**Comment by nmiodice** [comment]
I've clarified this in https://github.com/microsoft/terraform-provider-azuredevops/pull/338

**Comment by edwardwu-servian** [comment]
Thank you for getting back so fast!

`repo_id = var.repo_name` does work. However, I had to remove `ci_trigger` block and `pull_request_trigger` during `terraform apply`. Including either of these blocks resulted in a failure. Please refer to below as an example.

### Terraform Configuration Files
```hcl
resource "azuredevops_build_definition" "module" {
  project_id = var.project_id
  name       = var.pipeline_name

  ci_trigger {
    use_yaml = true
  }

  repository {
    repo_name             = var.repo_name
    repo_id               = var.repo_name
    repo_type             = var.repo_type
    branch_name           = var.branch_name
    service_connection_id = var.service_connection_id
    yml_path              = var.pipeline_yaml_file_path
  }
}
```
 
### Debug Output

https://gist.github.com/edwardwu-servian/bc395317b04d453ff3252d693198a997

**Comment by xuzhang3** [comment]
@edwardwu-servian
Looks like it is a bug when create `build_definition ` with `bitbucket ` repos. I can reproduce your error , but not sure what's wrong .I will follow up this issue.

**Comment by nmiodice** [comment]
That sounds good to me @xuzhang3. I renamed the issue to increase clarity, but i'll leave the real work to you :)

**Comment by xuzhang3** [comment]
I try communicate this issue with service team,  bad luck, no helpful information. They suggest open a report for customer support team. [report link](https://developercommunity.visualstudio.com/content/problem/1062011/can-not-create-a-build-definition-with-bitbucket-a.html)

**Comment by edwardwu-servian** [comment]
> I try communicate this issue with service team, bad luck, no helpful information. They suggest open a report for customer support team. [report link](https://developercommunity.visualstudio.com/content/problem/1062011/can-not-create-a-build-definition-with-bitbucket-a.html)

So the behavior without `ci_trigger` and `pull_request_trigger` is that the pipeline is still created with trigger - they are just not enabled (overriden). 
Interestingly, the same yaml could create a pipeline from the Azure DevOps frontend with triggers enabled. I wonder if there's any issues related to this in the REST API
 
![image](https://user-images.githubusercontent.com/65932538/83594716-4a1eb480-a5a3-11ea-9e99-3c37d556940e.png)
