### ISSUE TITLE
Hide secret variable from plan

### ISSUE THREAD

**Issue by carlosjourdan** [microsoft/terraform-provider-azuredevops#337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the "value" property of a variable inside a variable group is not marked as sensitve, and will appear in the plan output despite of the "is_secret" property.

I don't have any experience developing terraform providers, and I don't know if you can dinamically set the sensitivity of one property based on another property. If that's possible, toggling the sensitivity of the "value" property based on the "is_scret" property would resolve this issue. 

If this type of dynamic masking is not possible, I propose creating a property named "secret_value" that would be a shorthand for setting the value and marking the variable as secret in Azure Devops. This "secret_value" property can be marked as sensitive on the provider, and the issue would also be solved.

### Potential Terraform Configuration

```hcl
resource "azuredevops_variable_group" "vg" {
  project_id   = azuredevops_project.project.id
  name         = "Sample VG 1"
  description  = "A sample variable group."
  allow_access = true

  variable {
    name      = "this_secret_is_seen_on_plan"
    value     = "value1"
    is_secret = true
  }

  variable {
    name      = "this_secret_could_be_hidden_from_plan"
    secret_value     = "value1"
  }

}

```

**Comment by nmiodice** [comment]
@xuzhang3 I think the same strategy can be used with the `azuredevops_build_definition` resource, as it consumes variables that may be secrets as well.

Personally, I like the approach to have a `secret_value` (or `secret`) field and remove the `is_secret` flag, as the value cannot be marked as sensitive in the schema dynamically. 

This would bea breaking change, though. What do you think @xuzhang3 ?

**Comment by carlosjourdan** [comment]
Although it's a breaking change, I think it makes sense from a security perspective. I was linking the variable to a password that is generated on a predecessor task. In the first run this didn't catch my attention, as it was marked to be set after the run. But then I went on to change another variable on the same group and the plan showed the secret even though I wasn't touching it. I think this can be a silent problem for many people.
________________________________

**Comment by xuzhang3** [comment]
> @xuzhang3 I think the same strategy can be used with the `azuredevops_build_definition` resource, as it consumes variables that may be secrets as well.
> 
> Personally, I like the approach to have a `secret_value` (or `secret`) field and remove the `is_secret` flag, as the value cannot be marked as sensitive in the schema dynamically.
> 
> This would bea breaking change, though. What do you think @xuzhang3 ?

@nmiodice I think we can keep the `is_secret`, this can inform the user that if they want config a secret value or not.
Config without `is_secret`:
```
"value": {
    Type:         schema.TypeString,
	Required:     true,
	ValidateFunc: validate.NoEmptyStrings,
	ConflictsWith: []string{"secret_val"},
},
"secret_val": {
	Type:         schema.TypeString,
	Required:     true,
	ValidateFunc: validate.NoEmptyStrings,
	ConflictsWith: []string{"value"},
},
```

**Comment by xuzhang3** [comment]
> @xuzhang3 I think the same strategy can be used with the `azuredevops_build_definition` resource, as it consumes variables that may be secrets as well.
> 
> Personally, I like the approach to have a `secret_value` (or `secret`) field and remove the `is_secret` flag, as the value cannot be marked as sensitive in the schema dynamically.
> 
> This would bea breaking change, though. What do you think @xuzhang3 ?

@nmiodice Agree with your idea, remove `is_secret` and  add new filed `secret_val`.
