### ISSUE TITLE
feat: service endpoint for azure devops / tfs

### ISSUE THREAD

**Issue by dmccaffery** [microsoft/terraform-provider-azuredevops#339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a service endpoint to register cross-organisation service connections (for referencing things like azure pipelines templates).

### New or Affected Resource(s)

* azuredevops_serviceendpoint_azuredevops

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_azuredevops" {
  project_id = "XXXX"
  service_endpoint_name = "Sample AzureDevOps"
  description = "Managed by Terraform"
  auth_personal {
    personal_access_token = "Some Token"
  }
  connection_url = "https://dev.azure.com/sample-org"
  grant_all_pipelines = true
}
```

### References

API: https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-6.0

**Comment by arnonearth** [comment]
I had the same use case of sharing repositories between organizations which requires an external TFS service connection. So I forked and wrote a resource for private use a few months ago.

I have recently finished writing tests and docs. I will open a pull request for this issue.
