### ISSUE TITLE
Terraform 0.13 -  Add registry sourced provider support

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#34]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/363
Originally created by @arnaudlh on *Fri, 05 Jun 2020 01:41:28 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Terraform 0.13 currently in beta adds support for registry sourced provider as per [this link](https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/).
As a [user](https://github.com/azure/caf-terraform-landingzones) of the terraform-provider-azuredevops, we'd love TF0.13 day 0 support for this feature, so that we can dynamically pull your provider. 

### New or Affected Resource(s)

* none

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    terraform-provider-azuredevops = {
        source = "registry.terraform.io/microsoft/terraform-provider-azuredevops"
        version = "x.y.0"
    }
  }
}
```

### References

* #0000

**Comment by xuzhang3** [comment]
Close this issue.  ADO provider has been released to Terraform registry 
  https://registry.terraform.io/providers/microsoft/azuredevops/latest
