### ISSUE TITLE
PROVIDER_VERSION is hardcoded  with version 0.0.1 and not got updated by version tag

### ISSUE THREAD

**Issue by eissko** [microsoft/terraform-provider-azuredevops#341]
Hello MSFT,
we had been struggling with aztfmod/rover which consumes azuredevops provider here in Dockerfile (https://github.com/aztfmod/rover/blob/1e1c15cb3c78c79c83acdb2d7341f6258bad3476/Dockerfile#L42). 

It took a lot of time to debug. When we attached to the container - every azuredevops provider having in it is name suffix 0.0.1 regardless the version commit/tag version used - in fact it is the value which is hard-coded in file PROVIDER_VERSION (https://github.com/microsoft/terraform-provider-azuredevops/blob/439d35adfe7cb0266177e7301b325a5fa0670a22/PROVIDER_VERSION.txt#L1)

Would you consider update the CI/CD with correct version in every release/ master branch with proper tag? It could help to avoid inconsistency.

Of course we can overwrite file PROVIDER_VERSION.TXT before running build.sh with correct version. Better would be if correct version is already on place.

Thank you
Peter

**Comment by nmiodice** [comment]
@eissko, can you help me understand the pain this is causing within the dockerized context? The `PROVIDER_VERSION.txt` strategy is not in-line with our long term versioning goal (we hope to snap to the strategy used by other TF providers) and so I'd like to better understand so we can align on the right path forward.

**Comment by eissko** [comment]
not big pain for me. as I mentioned above - another project also led by ms team using you build.sh to compile the provider. hence the provider artifact in that docker build always end-up with same name even it is different version.

using this part of code:

`function compile() {
  NAME=$(cat "$PROVIDER_NAME_FILE")
  VERSION=$(cat "$PROVIDER_VERSION_FILE")

  BUILD_ARTIFACT="terraform-provider-${NAME}_v${VERSION}"`

So wouldn't be better when you create new tag on master as release, e.g. 2.1.2 , update the file with this tag? instead of having always 0.0.1

**Comment by xuzhang3** [comment]
@eissko ADO provider release with `goreleaser` , [you can find the release here](https://github.com/microsoft/terraform-provider-azuredevops/releases). We already release new version with tag.
