### ISSUE TITLE
Teams support

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

maybe i'm missing it, but how do i define a team?  Seems to have some realtionship with a group, but obv has more config options.  not really sure how it would work if it would reference a group...i'd think yes and membership would be in the group not the team.

### New or Affected Resource(s)

* azuredevops_team

### Potential Terraform Configuration

```hcl
resource "azuredevops_group" "example" {
  scope        = azuredevops_project.opsys.id
  display_name = "Example"
  description  = <<-EOF
    Example

    Managed by TF
  EOF

  members = [
    local.example_user.descriptor
  ]
}


resource "azuredevops_team" "example" {
  group = azuredevops_group.example

  backlog_levels = [
     "epics",
     "features",
     "stories"
  ]

  working_days = [
    "monday",
    "tuesday",
    etc...
  ]

  bugs_management = "requirements" #or tasks or none

  iteration_default = "/what/ever/"

  iteration_backlog = "/what/ever/"


   area_default = "/whatever/area/"

    administrators = [
        local.example_user.descriptor
    ]      
}
```

something for team_iteration and team_area as separate resources too at a later time

**Comment by xuzhang3** [comment]
Hi @drdamour  Teams and group similar but different. You refer this post: https://developercommunity.visualstudio.com/t/what-is-the-difference-between-team-and-security-g/534380

Teams API: https://docs.microsoft.com/en-us/rest/api/azure/devops/core/teams?view=azure-devops-rest-5.1

**Comment by drdamour** [comment]
looks like team create doesn't take a group...which is too bad since it makes one for you.  so pretty much have to copy some of the basic attributes from group and then expose a group as an attribute for the team to be used in all the security/membership stuff i'd guess.

**Comment by tmeckel** [comment]
@drdamour Teams support is on it's way with #121 

For configuring backlog (levels), areas, bug management and capacity management (work days etc) we do need additional resources I think. What's you opinion in this @xuzhang3?

**Comment by tmeckel** [comment]
Related: #394

**Comment by drdamour** [comment]
@tmeckel / @xuzhang3 taking this for a spin and it seems to be stuck in a creating loop forever

**Comment by drdamour** [comment]
so more info after testing...def seems like this is hanging, tried locally on windows and on a linux azdo build agent both hung forever (well i waited 25 minutes)

```
Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7
```

and

```
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7
```

**Comment by xuzhang3** [comment]
@dramour  Can you share your TF script and error log?

**Comment by dmccaffery** [comment]
@xuzhang3 : we are seeing the same thing (never ending loop) when trying to change the description:

```terraform
resource "azuredevops_team" "governance" {
  project_id  = azuredevops_project.project.id
  name        = "Governance"
  description = "Represents the current members of the governance committee."
}

```

```text
azuredevops_team.governance: Modifying... [id=2cedcbee-cd47-406d-96e6-d2a0e56119c4]
2021-10-31T19:16:37.439Z [DEBUG] provider.terraform-provider-azuredevops_v0.1.7: 2021/10/31 19:16:37 [DEBUG] Waiting for state to become: [Synched]
2021-10-31T19:16:42.579Z [DEBUG] provider.terraform-provider-azuredevops_v0.1.7: 2021/10/31 19:16:42 [TRACE] Waiting 5s before next try
azuredevops_team.governance: Still modifying... [id=2cedcbee-cd47-406d-96e6-d2a0e56119c4, 10s elapsed]
2021-10-31T19:16:47.722Z [DEBUG] provider.terraform-provider-azuredevops_v0.1.7: 2021/10/31 19:16:47 [TRACE] Waiting 10s before next try
```

**Comment by dmccaffery** [comment]
@xuzhang3  -- I think I figured it out -- its related to an import when a description exists whereby the import fails to pull in the description. This seems to create an apply that cycles forever waiting for some kind of a state change.

**Comment by drdamour** [comment]
@xuzhang3 the most basic apply cauesed it
```
resource "azuredevops_team" "app_delivery" {
  project_id = azuredevops_project.opsys.id
  name       = "App Delivery"

  description  = "description"
```

i can CONFIRM what @dmccaffery said...if i do NOT have a description, then it works fine...it's if i have a description it just hangs forever

**Comment by drdamour** [comment]
there's just something really messed up with the description, it does actually set it, it's def there, but apply keeps thikning it needs to add it everytime
![image](https://user-images.githubusercontent.com/1514496/140393246-5a411f91-82e7-4935-bb49-205e2f4e2c82.png)

**Comment by drdamour** [comment]
also this model still doesn't make a lot of sense...when you create a team, it also creates a group...if i want to layer one team in another i really need a handle to the group. 

one way to fix this is to have the team export a group attribute that would mirror the attributes https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group#attributes-reference

**Comment by roryprimrose** [comment]
@drdamour I had to create a Terraform module to help wrap this up.

```
terraform {
  required_version = ">= 1.0.0" # Terraform Version
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}

variable "project" {
  type = object(
    {
      id   = string,
      name = string
    }
  )
}

variable "team" {
  type = object(
    {
      name        = string,
      description = string
    }
  )
}

resource "azuredevops_team" "team" {
  project_id  = var.project.id
  name        = var.team.name
  description = var.team.description
}

data "azuredevops_group" "project_teams" {
  project_id = var.project.id
  name       = azuredevops_team.team.name
}

output "project_name" {
  value = var.project.name
}

output "project_id" {
  value = var.project.id
}

output "team_name" {
  value = azuredevops_team.team.name
}

output "team_id" {
  value = azuredevops_team.team.id
}

output "group_id" {
  value = data.azuredevops_group.project_teams.id
}

output "principal_name" {
  value = format("[%s]\\%s", var.project.name, azuredevops_team.team.name)
}

output "descriptor" {
  value = data.azuredevops_group.project_teams.descriptor
}

output "display_name" {
  value = azuredevops_team.team.name
}
```

**Comment by drdamour** [comment]
Bleh

**Comment by drdamour** [comment]
@xuzhang3  this is still an issue in 0.2.0.  The team is created and the description is set, but the apply phase never exists

**Comment by xuzhang3** [comment]
@drdamour  What your description is like , service will remove the spaces but the provider not, which result in a retry loop  up to 60 mins.

**Comment by drdamour** [comment]
@xuzhang3 yeah its a multiline heredoc.but i thought i tried a single line too.  I will try that and report back…either way feels like bug to me

**Comment by drdamour** [comment]
@xuzhang3 and we still need the group desriptor added to attributes so we can nest team group in another group

**Comment by xuzhang3** [comment]
@drdamour   description cannot start or end with spaces

**Comment by drdamour** [comment]
@xuzhang3 any plans to get the group id exposed on the team resource.  using the data hack described in https://github.com/microsoft/terraform-provider-azuredevops/issues/343#issuecomment-961461592 causes weird issues when the team itself changes .

need the group id to grant things like area and iteration permissions.

**Comment by drdamour** [comment]
closing this and opening #820 for the group_id attribute feature
