### ISSUE TITLE
Default git repo

### ISSUE THREAD

**Issue by carlosjourdan** [microsoft/terraform-provider-azuredevops#346]
Is it possible to create an AZDO Project without a default repo? If not, how can I declare and manage the default repo created when I declare an azuredevops_project resource? For instance, how can I define branching policies for the default git repository?

The only way I was able to do this so far was to do a terraform init to set the repo ID, but this won't make it into the production pipeline that I'm trying to build.

**Comment by KeithJRome** [comment]
AZDO Projects always include a default repo. You can see this behavior if you manually create a project in the portal as well.

**Comment by nmiodice** [comment]
@carlosjourdan - I recommend using the date resource for [git repos](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/d/data_git_repositories.html.markdown)

This will load all, but will allow you to filter on the name. We do not yet have one that loads a specific git repo, but it will be simple to implement. Would you like to see this feature? cc @xuzhang3

**Comment by xuzhang3** [comment]
@carlosjourdan 
You can refer the created  `repo` with [data_git_repositories](https://github.com/microsoft/terraform-provider-azuredevops/tree/master/website/docs/d). 
An HCL config example :
```hcl
resource "azuredevops_project" "project" {
  project_name       = "Sample Project"
  visibility         = "public"
  work_item_template = "Agile"
}

data "azuredevops_git_repositories" "repos" {
  project_id     = azuredevops_project.project.id
}

output "git_repos_name"{
  value = data.azuredevops_git_repositories.repos.repositories.0.name
}

output "git_repos_url"{
  value = data.azuredevops_git_repositories.repos.repositories.0.url
}

output "git_repos_ssh_url"{
  value = data.azuredevops_git_repositories.repos.repositories.0.ssh_url
}

output "git_repos_web_url"{
  value = data.azuredevops_git_repositories.repos.repositories.0.web_url
}
```

**Comment by tmeckel** [comment]
Well this only will work when the Project is initially created and no other Git Repos are created. As far as I remember there's no flag which indicates the default Git Repo for a project. The only way, to some extend, to find the "default Git Repository" is to use the name of the (created) project as the name of the Git Repository in question.

**Comment by carlosjourdan** [comment]
Thank you all for the tips. Apparently the data_git_repositories with filtering will suffice.

I'm very new to Terraform, so there's still a lot of room to cover. But I was able to accomplish a lot in the past few days, in many ways thanks to this project. I was able to provision a devops project that includes the terraform source code and a pipeline to apply it. So, after the inital apply, all future evolution is concentrated arround pull requests and automated pipelines. The great thing about this is being able to enforce strict governance without adding too much friction.

If this goes forward as planned, we will probably have to learn how to develop providers to close a few gaps in our current infrastructure, and maybe we can tackle a couple of work items here as a way to learn the ropes.

Thanks again for all the help.

**Comment by nmiodice** [comment]
@carlosjourdan you may want to take a peek at this piece of Terraform code, which automates AzDO in a similar way you are describing:

https://github.com/microsoft/cobalt/tree/master/infra/templates/ado-bootstrap-iac-pipeline

**Comment by nmiodice** [comment]
I'll go ahead and close this issue, but feel free to re-open if you have any questions. We are always happy to lend a hand!

**Comment by carlosjourdan** [comment]
Wow, this cobalt project is almost exactly what I have built! I guess it was still worth going through this process to get the hang of how terraform works.

Now I'm trying to modularize it to scenarios where some projects have multiple repos and pipelines. I just need to set up the proper permissions for the main bootstrap service principal so that it can create other service principals.

Thanks a lot @nmiodice , this will certainly help.

**Comment by nmiodice** [comment]
I am a core contributor for that project as well - happy to help you on your journey if you have any questions that come up!
