### ISSUE TITLE
How to link existing agent pool to the project ?

### ISSUE THREAD

**Issue by krishrocks1904** [microsoft/terraform-provider-azuredevops#348]
![image](https://user-images.githubusercontent.com/67486994/112832668-8de02e80-908d-11eb-9b8a-5bfb0f9ad79a.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @krishrocks1904   Currently agent pool cannot be reused by `azuredevops_agent_pool`.

**Comment by richardgavel** [comment]
I thought this is what azuredevops_agent_queue is for?

https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/agent_queue

**Comment by krishrocks1904** [comment]
thanks @richardgavel this works as expected.
closing the issue now
