### ISSUE TITLE
`id` output from Agent Pool is not a UUID valid for authorization

### ISSUE THREAD

**Issue by edwardwu-servian** [microsoft/terraform-provider-azuredevops#350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
```
terraform -v
Terraform v0.12.24
```
`Azure DevOps provider v0.1.2`

### Affected Resource(s)

* `azuredevops_agent_pool`
* `azuredevops_resource_authorization`

### Terraform Configuration Files

```hcl
resource "azuredevops_agent_pool" "module" {
  name           = "Dev Pool"
  auto_provision = true
  pool_type      = "automation"
}

resource "azuredevops_resource_authorization" "module" {
  project_id  = azuredevops_project.module.id
  resource_id = azuredevops_agent_pool.module.id
  authorized  = true
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Agent pool created and authorized for the project

### Actual Behavior

Received error "Error: expected "resource_id" to be a valid UUID, got 11". 

Terraform state as below:
```
"resources": [
    {
      "mode": "managed",
      "type": "azuredevops_agent_pool",
      "name": "module",
      "provider": "provider.azuredevops",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "auto_provision": true,
            "id": "11",
            "name": "Dev Pool",
            "pool_type": "automation"
          }
        }
      ]
    }
  ]
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

* #0000

**Comment by xuzhang3** [comment]
@edwardwu-servian
Currently `azuredevops_resource_authorization` only support service connection resources. [You can find document here](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/resource_authorization.html.markdown)

**Comment by edwardwu-servian** [comment]
Ah thanks, closing this one

**Comment by nmiodice** [comment]
@edwardwu-servian - this behavior will be more flexible once this PR is merged, by the way:

https://github.com/microsoft/terraform-provider-azuredevops/pull/332

**Comment by edwardwu-servian** [comment]
> @edwardwu-servian - this behavior will be more flexible once this PR is merged, by the way:
> 
> #332

Thanks for letting me know!
