### ISSUE TITLE
Variables as a seperate resource

### ISSUE THREAD

**Issue by carlosjourdan** [microsoft/terraform-provider-azuredevops#351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today the azuredevops_variable_group has to manage all variables in the vg. If a variable exists in the vg that is not listed in the resource, the terraform plan will include its deletion .

I think it would be useful to declare variables as a separate resource, allowing for greater decoupling and modularization. If this happens, we would need to change the behaviour of the azuredevops_variable_group so that it does not delete a variable that was never part of its state.

To understand where this is coming from, I'm trying to expand the ideas from the [cobalt ado-bootstrap-iac-pipeline project](https://github.com/microsoft/cobalt/tree/master/infra/templates/ado-bootstrap-iac-pipeline), creating modules for code re-use. 

The structure I have in mind would have three kinds of modules: project, app and app_resource.

```
project
+-- app1
|   +-- app_resource1
|   +-- app_resource2
+-- app2
|   +-- app_resource1
```

The project module would create the basic logic from the cobalt example, with the terraform pipeline and bootstrap agent.

Each app module would define a repo, pipeline, environments and variable groups related to a specific application.

An app_resource_xxx module could be used to add resources to an app, like a database, a storage account, etc. 

Each app_resource_xxx module would need to create the resource, and populate the variable groups with the necessary data (e.g. connection strings, resource uris, etc). In order to do this, I would need to receive the vg id, and add a variable to it, without disrupting the variables that would be defined in other modules.

This is what a terraform plan could look like
```hcl

module "some_project"{
  source="my_project_module",
  name="Some project"
}

module "some_app"{
  source="my_app_module"
  name="Some app"
  project_id = module.some_project.id
  environments = ["dev","stage","prod"]
}

module "some_database"{
  source="my_app_resource_sql_database_module"
  database_args="..."
  environments = module.some_app.environments #this structured output would include a variable group id for each environment
}

```

### New or Affected Resource(s)

* azuredevops_variable_group 
* azuredevops_variable

### Potential Terraform Configuration

```hcl
resource "azuredevops_variable_group" "variable_group" {
  project_id   = ...
  name         = ...
  description  = ...

  variable { 
      name = "Var1"    
      value = "This variable would be managed with the variable group"
  }  
}

resource "azuredevops_variable" "variable"{
  variable_group_id = azuredevops_variable_group.variable_group.id
  name="Var2"
  value ="This variable would be managed independently"
}
```

**Comment by nmiodice** [comment]
@carlosjourdan we had initially thought about this as the implementation strategy but decided against it because it makes managing a variable group extremely difficult, if not impossible. This is due to the following:

* The variable definition/entity itself includes the keys/values of each of the variables in that group
* Secret values are not returned from the API

Based on this, its not possible to manage variables independently.

My recommendation is to use `outputs` for your modules, and then collect them into the variables that are needed for your variable group. This should lead to a more composable set of modules, since they won't need to assume anything about the devops environment in which they live.

An example, using fictional modules:

```hcl
module "service_principal" {
   ...
}

module "super_secret_stuff" {
   ...
}

resource "azuredevops_variable_group" "vg" {
    variable {
        name = "foo"
        value = module.service_principal.id
    }
    variable {
        name = "foo"
        is_secret = true
        value = module.super_secret_stuff.mykey
    }
}
```

**Comment by nmiodice** [comment]
Closing with no plans to fix
