### ISSUE TITLE
Refactor resource implementation to mirror the AzDO API areas

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on the design in https://github.com/microsoft/terraform-provider-azuredevops/issues/324, we need to refactor the package structure for the resources to mirror the area paths for the Azure DevOps API

### New or Affected Resource(s)

* N/A

### Potential Terraform Configuration

* N/A

### References

* https://github.com/microsoft/terraform-provider-azuredevops/issues/324

**Comment by nmiodice** [comment]
I'll wait until https://github.com/microsoft/terraform-provider-azuredevops/pull/348 is merged. My branch has this implemented but it depends on that PR being merged - https://github.com/microsoft/terraform-provider-azuredevops/tree/niiodice/move-resources

**Comment by xuzhang3** [comment]
Close this issue as #356 has been merged
