### ISSUE TITLE
Add support for managing Status Check policies

### ISSUE THREAD

**Issue by ajhall** [microsoft/terraform-provider-azuredevops#352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to use Terraform to manage branch policies that require a status posted via the PR Status API, as documented here: https://docs.microsoft.com/en-us/azure/devops/repos/git/pr-status-policy?view=azure-devops

### New or Affected Resource(s)

* azuredevops_branch_policy_status (new)

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_status" "p" {
  project_id = azuredevops_project.p.id

  enabled  = true
  blocking = true

  settings {
    status_name                 = "my-status"
    status_genre                = "my-genre"
    default_display_name        = "My status check policy"
    author_id                   = null
    invalidate_on_source_update = true
    policy_applicability        = null
    author_id                   = null

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = azuredevops_git_repository.r.default_branch
      match_type     = "Exact"
    }
  }
}
```

### References

* https://github.com/Azure/azure-devops-cli-extension/issues/1040
* https://docs.microsoft.com/en-us/azure/devops/repos/git/pr-status-policy?view=azure-devops
* https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations?view=azure-devops-rest-6.0

**Comment by xuzhang3** [comment]
Released in v0.1.5,  close this issue. Feel free to open another issue if you have questions.
