### ISSUE TITLE
`azuredevops_git_repository` resource cannot parse "Import" 'import_type'

### ISSUE THREAD

**Issue by AgileCloudInstitute** [microsoft/terraform-provider-azuredevops#353]
There seems to be a bug which stops the `azuredevops_git_repository` resource from being able to recognize the "Import" value for `import_type`.  
  
`azuredevops_git_repository`  is not able to import a repository.  
  
Here is the log output when the error is being thrown:  
  
    [0m[1mazuredevops_git_repository.repository: Creating...[0m[0m
    [31m
    [1m[31mError: [0m[0m[1mError expanding repository resource data: Initialization strategy not implemented: Import[0m
    [0m  on azuredevops.tf line 12, in resource "azuredevops_git_repository" "repository":
      12: resource "azuredevops_git_repository" "repository" [4m{[0m
    [0m
    [0m[0m
    ##[error]Bash exited with code '1'.
  
Here is the code section involved (note that the actual github repo and account are valid when run, but have been redacted here):  
    
    resource "azuredevops_project" "project" {
      project_name       = "Sample Project"
      visibility         = "private"
      version_control    = "Git"
      work_item_template = "Agile"
    }
  
    resource "azuredevops_git_repository" "repository" {
      project_id = azuredevops_project.project.id
      name       = "my-simple-repo"
      initialization {
        init_type = "Import"
        source_type = "GitHub"
        source_url = "https://github.com/account-name/public-repo-name.git"
      }
    }
  
The commands that were used to install the azdo terraform plugin indicate the version being used, and are as follows:  
  
    mkdir terraform.d
    mkdir terraform.d/plugins
    mkdir terraform.d/plugins/linux_amd64
    wget https://github.com/microsoft/terraform-provider-azuredevops/releases/download/v0.1.2/terraform-provider-azuredevops_linux_amd64.tar.gz
    tar -xf terraform-provider-azuredevops_linux_amd64.tar.gz -C terraform.d/plugins/linux_amd64

I have been reviewing the resource's source code [at this link](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_git_repository.go), and I cannot see where the problem is because the source code seems to show "Import" as an option.  
  
>**Is there a bug elsewhere in the control flow through which strings pass during runtime?**

**Comment by xuzhang3** [comment]
@AgileCloudInstitute`import` is not yet supported. Sorry the documentation misled you
cc @nmiodice

**Comment by xuzhang3** [comment]
Relate issue #98

**Comment by AgileCloudInstitute** [comment]
Can you please suggest an automated alternative to import code from another outside git repo into a an Azure git repo created using `azuredevops_git_repository`, at the time of creation?   
  
Perhaps a terraform output variable for the newly created Azure git repo would be fed into a separate script in another language?  
  
A link to a working example and explanation would be ideal.  
  
This must be a very common use case, especially for organizations migrating their code into Azure DevOps from other vendors.

**Comment by xuzhang3** [comment]
@nmiodice   Do you know any workaround for this issue?

**Comment by mxrss2** [comment]
you could just use a provisioner block to git push a sample repo into the repository. 


Look up provisioners block in the terraform documentation @AgileCloudInstitute.

**Comment by xuzhang3** [comment]
closing this issue due to #373

**Comment by AgileCloudInstitute** [comment]
@mxrss2   @xuzhang3   How do you suggest getting credentials through the provisioner block that you suggest?  When we add a provisioner block inside the `azuredevops_git_repository` declaration, Terraform prompts for a manual input of password for the repo.  There is no mention of how to set a repo password in this `azdo provider` documentation for `azuredevops_git_repository`, and we cannot leave this as a manual step.  

>**Please be very specific in showing how you suggest users do automated importation of code into newly created `azuredevops_git_repository` instances.**  

This must be a widely needed use case because every user will need to import existing code in order to use Azure git repositories, and because your documentation gives the impression that you already support this without complicated workarounds.

**Comment by mxrss2** [comment]
@AgileCloudInstitute 

Your just pushing a git repo, a simple shell script can import the repo. If you want to pull from a cloned url you just use NetRC or SSH keys to authenticate to the repo. 

The item that @xuzhang3 mentions is a different ask, its not an import and `import` is a really bad name to use. because of this confusion. These tickets are asking different questions. One is to support the import attribute in a git_repo the issue refrenced is to import an existing git_repository resource. Meaning I want to terraform a repo that already exists -- you cant do that without importing the state of the existing resource. 

To your point, they should remove the attribute if its not ready to use. It does make it seem like it supports it when it does not. Also, the name import should be changed to something that isn't confusing with terraform parlance. 

Such as maybe i dont know template_repository
.

**Comment by AgileCloudInstitute** [comment]
@mxrss2    @xuzhang3    @nmiodice   
  
>**What specific syntax do you suggest to get an SSH key to use inside the provisioner which will push the code into the newly created repo?**  
  
Here is the code we are using now:  
    
    resource "azuredevops_git_repository" "repository" {
        project_id = azuredevops_project.project.id
        name       = "my-simple-repo"
        initialization {
          init_type = "Clean"
        }
        provisioner "local-exec" {
            command = "git remote set-url origin ${azuredevops_git_repository.repository.ssh_url} && git push -u origin --all"
            working_dir = "C:\\path\\to\\local\\checked-out\\copy-of\\git-repo\\" 
        }  
    }
  
The problem we are encountering is that the `git push` command is triggering a request for credentials that are not available.  
  
>**How do we associate ssh keys with the newly defined repo and then use the correct public key from the Terraform code?**

**Comment by mxrss2** [comment]
@AgileCloudInstitute 

Are you doing this through a container to do the push? Does it work when you run this locally?

```
resource "azuredevops_git_repository" "repository" {
    project_id = azuredevops_project.project.id
    name       = "my-simple-repo"
    initialization {
      init_type = "Clean"
    }

    provisioner "local-exec" {
        command = "git remote set-url origin ${azuredevops_git_repository.repository.ssh_url} && git push -u origin --all"
        working_dir = "C:\\path\\to\\local\\checked-out\\copy-of\\git-repo\\" 
    }  
}
```
You are using a local provisioner. You will need to source the key using ssh-key-agent or use .netrc

NetRC (https://ec.haxx.se/usingcurl/usingcurl-netrc)
SSH-Agent (https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)

I usually do my work inside a linux container to keep this just linux (it makes things easier, you can then just add the ssh-agent and then source a key from your system.

a simple script like so would work

```
#!/bin/sh
eval $(ssh-agent -s)
ssh-add ~/.ssh/id_rsa
git remote set-url origin ${azuredevops_git_repository.repository.ssh_url} && git push -u origin --al

```

You will need to tweak it to work but i would start with something like that. You could additionally just do a pull from a remote repo and then do a remote origin add ${azure_repo}

If your going to dynamic source the repo url you will need to use template() or use bash arguments.

**Comment by AgileCloudInstitute** [comment]
@mxrss2   @xuzhang3  @nmiodice 

We need to authenticate using a personal access token due to the way that secrets are designed to flow through the system in which this will run.  

>**_What specific syntax would we use in order to `push` to the newly created git repo using a personal access token?_**    
  
We are currently getting the following error message:     
  
    (local-exec): fatal: No such URL found: https://MyOrganization@dev.azure.com/MyOrganization/MyProject/_git/MyRepo
  
When we run the current generation code, which is as follows:     
    
    resource "azuredevops_git_repository" "repository" {
      project_id = azuredevops_project.project.id
      name       = "my-simple-repo"
      initialization {
        init_type = "Clean"
      }
      provisioner "local-exec" {
        command = "ls -al && B64_PAT=$(echo \"pat:$AZ_PAT\" | base64) && git remote set-url origin http.extraHeader=\"Authorization: Bearer $B64_PAT\" ${azuredevops_git_repository.repository.remote_url} && git push -u origin --all"
        working_dir = "/path/to/working/directory/" 
      }  
    }

I am wondering if the problem is that the git commands are referencing the repo URL before the repo has completed its creation process, but I have to defer to the people who are writing this tool in order to know what is actually happening during the creation process.    
  
Alternatively, if the inability to see the https URL is due to the above not passing the `PAT` in the request, then we need to find the correct syntax for a `push` using a `pat`.  The examples we could find on the web were for `clone` operations using `PATs`, and not for `push` operations.

**Comment by AgileCloudInstitute** [comment]
@mxrss2   @xuzhang3  @nmiodice 
  
We just substantially re-wrote the preceding comment to make it easier for you to answer.  Not sure if you are messaged when we re-write a comment like that, so we are adding this brief comment to trigger the system to ping you to alert that we have a clearly stated question above.

**Comment by mxrss2** [comment]
@AgileCloudInstitute 

Lets look at some simplification before we make this too complicated 

```
variable "pat_token" {
 type = string
}


locals {
 encoded_pat_token = base64encode(var.pat_token)
 repo_url = azuredevops_git_repository.repository.remote_url
}


resource "azuredevops_git_repository" "repository" {
  project_id = azuredevops_project.project.id
  name       = "my-simple-repo"
  initialization {
    init_type = "Clean"
  }
  provisioner "local-exec" {
    command = "ls -al && git remote set-url origin http.extraHeader=\"Authorization: Bearer ${local.encoded_pat_token}\" ${local.repo_url} && git push -u origin --all"
    working_dir = "/path/to/working/directory/" 
  }      
}    
```

**Comment by xuzhang3** [comment]
@AgileCloudInstitute You can add your SSH key though portal.
[Reference Document](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page)
![image](https://user-images.githubusercontent.com/57888764/85938751-86df9080-b942-11ea-89b4-2510e6cbaeff.png)
****
