### ISSUE TITLE
Automatically include code reviewers in a git repo

### ISSUE THREAD

**Issue by ferrandinand** [microsoft/terraform-provider-azuredevops#364]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to add the possibility to configure code reviewers for a repository created in Azure Devops as it is explained in the official documentation (references bellow)

### New or Affected Resource(s)
* azuredevops_code_reviewers

### Potential Terraform Configuration

```hcl
resource "azuredevops_code_reviewers" "p" {
    required-reviewer-ids = ...  // list | required | ForceNew := false
    blocking = ..  // bool | optional | ForceNew := false | OneOf: true, false (default true)

    # can be defined 0 or many times
    scope {
        repository_id = ...  // string | required | ForceNew := false
        repository_ref = ... // string | required | ForceNew := false
        match_type = ...     // string | optional | ForceNew := false | OneOf: "Exact" (default), "Prefix"
    }
    submitter_can_approve = ... // bool | optional | ForceNew := false | OneOf: true, false (default)
}
```

### References
https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#automatically-include-code-reviewers 

https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/repos/policy/required-reviewer?view=azure-cli-latest

**Comment by C123R** [comment]
Hey @xuzhang3 👋, can I give a shot?

**Comment by xuzhang3** [comment]
Hi @C123R Sorry for reply late. Thanks for you participate. We have migrated this repository to terraform-provioder. I will transfer the issues to the new repository. But you can start your work. [New Repository Address](https://github.com/terraform-providers/terraform-provider-azuredevops)

**Comment by C123R** [comment]
> Hi @C123R Sorry for reply late. Thanks for your participate. We have migrated this repository to terraform-provioder. I will transfer the issues to the new repository. But you can start your work. [New Repository Address](https://github.com/terraform-providers/terraform-provider-azuredevops)

@xuzhang3 @nmiodice just one more question, I have another WIP pull request #306 which is currently blocked due to [AZDO GO SDK](https://github.com/microsoft/azure-devops-go-api/issues/67). Should I create (copy of)an issue in the new repo?

**Comment by xuzhang3** [comment]
Hi @C123R I will transfer the whole issues to new repo later.  You can create a new issue in the new repo too, I will handle the duplicate issues.

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#29
