### ISSUE TITLE
crlf issues with heredocs on group descriptions

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#365]
this might be my own fault, but since i never observed this behaviour with the azurerm provider i'm wondering if it's not something that needs to be handled at the provider level.  I use a heredoc for the description of a group and if i run on a windows host it'll show changes for crlf stuff, if i apply the run on ubunut in azdo pipeline it shows changes and they just fight each other.  i know i can force git to co with lf, but all my tooling on windows like crlf.  I'm *thinking* that this should be sorted out at the provider level somehow. please advise

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v0.14.7
+ provider registry.terraform.io/microsoft/azuredevops v0.1.4
```
### Affected Resource(s)

* `azuredevops_group`

### Terraform Configuration Files

```hcl
resource "azuredevops_group" "itt" {
  scope        = azuredevops_project.opsys.id
  display_name = "ITT"
  description  = <<-EOF
    ITT team for ITT contract workforce doing stuff within OpSys

    ${local.managed_by_tf_tag}
EOF

}
```

### Expected Behavior

should have no changes when i run from local windows or azdo pipeline ubuntu host

### Actual Behavior

keeps flip flopping with meaningless changes

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @drdamour  The  resource diff is detected by [Terraform core](https://github.com/hashicorp/terraform). At provider or resource level, what we can do is suppress the resource changes, Terraform will ignore the changes whenever the resource changed.

**Comment by drdamour** [comment]
i think it'll be better to just for tf to LF endings with a .gitattributes
