### ISSUE TITLE
Release version file naming format has changed between v0.1.1 and v0.1.2

### ISSUE THREAD

**Issue by russellmccloy** [microsoft/terraform-provider-azuredevops#366]
Hi, 

There was no where else to put this so it is a legitimate question.
In version v0.1.1 your naming format for the file:
terraform-provider-azuredevops_**0.1.1**_linux_amd64.tar.gz

Includes the version in the file name as you can see.

In version v.0.1.2 the file name does not include the version number:
terraform-provider-azuredevops_**???**_linux_amd64.tar.gz

This makes it hard for anyone using a variable in CI/CD to hold the version number as it is impossible to predict the format of the file names in your releases.

thanks
Russ

**Comment by xuzhang3** [comment]
@russellmccloy  I have fix this in #368 and release a new version V0.1.3.

**Comment by xuzhang3** [comment]
Closing this issue due to #368

**Comment by russellmccloy** [comment]
Thanks @xuzhang3 really fast turn around. 👍
