### ISSUE TITLE
azuredevops_group scope not set with version 0.1.4

### ISSUE THREAD

**Issue by HeikoNeblung** [microsoft/terraform-provider-azuredevops#366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.13.6
+ provider registry.terraform.io/microsoft/azuredevops v0.1.4

### Affected Resource(s)

* `azuredevops_group`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "0.1.4"
    }
  }
}

resource "azuredevops_project" "p" {
  name = "Test Project Groups"
}

resource "azuredevops_group" "g" {
  scope        = azuredevops_project.p.id
  display_name = "Test group"
  description  = "Test description"
}
```

### Expected Behavior

This should create a group named "Test group" within project "Test Project Groups" ([Test Project Groups]\Test group).

### Actual Behavior

This creates a group named "Test group" within organizations scope ([Organization]\Test group). This is only happening when creating new resources with provider verison 0.1.4. Applying the same code with version 0.1.3 of azuredevops provider will create the group within the projects scope. An upgrade of the provider from 0.1.3 to 0.1.4 with resources already managed by terraform and created with versin 0.1.3 won't recreate the resources or apply any changes to them.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by schwarzzz** [comment]
Same problem here...

**Comment by xuzhang3** [comment]
This is a bug, #369 will fix it.

**Comment by xuzhang3** [comment]
@HeikoNeblung  Please update the provider to v0.1.5.
