### ISSUE TITLE
`azuredevops_variable_group` fails when `description` is not specified

### ISSUE THREAD

**Issue by edwardwu-servian** [microsoft/terraform-provider-azuredevops#367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
```
terraform -v
Terraform v0.12.24
```

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
resource "azuredevops_variable_group" "module" {
  project_id   = var.project_id
  name         = var.variable_group_name
  allow_access = true

  variable {
    name      = "connectionName"
    value     = azuredevops_serviceendpoint_azurerm.module.service_endpoint_name
    is_secret = false
  }

  variable {
    name      = "servicePrincipalId"
    value     = var.service_principal_id
    is_secret = false
  }

  variable {
    name      = "servicePrincipalKey"
    value     = var.service_principal_key
    is_secret = true
  }

  variable {
    name      = "tenantId"
    value     = var.tenant_id
    is_secret = false
  }

  variable {
    name      = "subscriptionId"
    value     = var.subscription_id
    is_secret = false
  }
}
```

### Debug Output

https://gist.github.com/edwardwu-servian/8bf00f5e10f478c62d8d1b2f4d031ef8

### Panic Output

`panic: runtime error: invalid memory address or nil pointer dereference`
https://gist.github.com/edwardwu-servian/5c13933ee158c9f399d2732642636ec0

### Expected Behavior

`terraform apply` should complete without issue

### Actual Behavior

1. Variable group was created in Azure DevOps but `terraform apply` failed
2. When `description` was assigned with values, `terraform apply` ran successfully

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

N/A

### References

https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/variable_group.html.markdown

* #0000

**Comment by xuzhang3** [comment]
@edwardwu-servian Took a look of this issue, this is a bug. Thanks for your feedback.

**Comment by xuzhang3** [comment]
Close this issue due to #369
