### ISSUE TITLE
Transient failure for group membership acceptance tests due to AzDO server side behavior

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#37]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/174
Originally created by @nmiodice on *Thu, 31 Oct 2019 15:00:01 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_group_membership`

### Terraform Configuration Files

```hcl
// THESE ARE FROM THE ACCEPTANCE TESTS!
//    https://github.com/microsoft/terraform-provider-azuredevops/blob/0575967a20c6c37badd80c3bcdfd5295521bc93c/azuredevops/resource_group_membership_test.go#L161-L196

resource "azuredevops_project" "project" {
	project_name = "%s"
}
data "azuredevops_group" "group" {
	project_id = azuredevops_project.project.id
	name       = "%s"
}
resource "azuredevops_user_entitlement" "user" {
	principal_name       = "%s"
	account_license_type = "express"
}
resource "azuredevops_group_membership" "membership" {
	group = data.azuredevops_group.group.descriptor
	members = [azuredevops_user_entitlement.user.descriptor]
}

output "group_descriptor" {
	value = data.azuredevops_group.group.descriptor
}
output "user_descriptor" {
	value = azuredevops_user_entitlement.user.descriptor
}
```

### Debug Output

Failed builds:
 - https://dev.azure.com/terraform-azdo/terraform-provider-azuredevops/_build/results?buildId=301&view=logs&j=2097b96b-8841-582b-91af-9cbd20cca0d1
 - https://dev.azure.com/terraform-azdo/terraform-provider-azuredevops/_build/results?buildId=302&view=results

### Panic Output
N/A

### Expected Behavior
Acceptance tests for the group membership resource pass.

### Actual Behavior

Due to the delay on the server side, the acceptance tests are inconsistent and can fail transiently

### Steps to Reproduce

1. run acceptance tests with the code commentated for the azdo group membership acceptance test. If you run it 5-6 times you will probably see a failure.

### Important Factoids

Seems to be a server side issue that is present in the UI as well, leading me to believe that this is a server side issue

### References

* #0000

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/174#issuecomment-629406848
Originally created by @nmiodice on *Fri, 15 May 2020 18:16:27 GMT*

---
That's a good question. If I'm honest, my memory of the reason behind the failure is fuzzy. I'd need to dive back into it to explore.

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/174#issuecomment-628519316
Originally created by @tmeckel on *Thu, 14 May 2020 09:36:53 GMT*

---
@nmiodice  I'm a bit late here for sure :grin: but why does the acc test still fail, although we're utilizing the `WaitForState` pattern?

https://github.com/microsoft/terraform-provider-azuredevops/blob/3de82399117f659947f101707bce1fcf97094138/azuredevops/resource_group_membership.go#L82

**Comment by xuzhang3** [comment]
Close this issue. Feel free to reopen it if anyone have questions.
