### ISSUE TITLE
Implement new resource "AWS Service Endpoint"

### ISSUE THREAD

**Issue by simongottschlag** [microsoft/terraform-provider-azuredevops#370]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement AWS Service Endpoint.

### New or Affected Resource(s)

* azuredevops_serviceendpoint_aws

### References

https://github.com/aws/aws-toolkit-azure-devops

https://aws.amazon.com/vsts/

* #0000

**Comment by xuzhang3** [comment]
Potential HCL config:
```
resource "azuredevops_serviceendpoint_aws" "aws_serviceendpoint" {
  project_id            = azuredevops_project.project.id
  access_key_id         = "xxxx"
  secret_access_key     = "xxxx"
  service_endpoint_name = "aws_serviceendpoint"
  description           = "Managed by AzureDevOps"
}
```

**Comment by phillebaba** [comment]
So I implemented an AWS service endpoint resource.
https://github.com/phillebaba/terraform-provider-azuredevops/blob/aws-service-connection/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_aws.go

The only thing that does not seem to work are the confidential values. The paramters `secret_access_key` and `session_token` are not returned by the api, causing issues with the state. @xuzhang3 do you know what might cause this, or is this an issue on AWS side that needs to be fixed?

**Comment by xuzhang3** [comment]
> So I implemented an AWS service endpoint resource.
> https://github.com/phillebaba/terraform-provider-azuredevops/blob/aws-service-connection/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_aws.go
> 
> The only thing that does not seem to work are the confidential values. The paramters `secret_access_key` and `session_token` are not returned by the api, causing issues with the state. @xuzhang3 do you know what might cause this, or is this an issue on AWS side that needs to be fixed?

@phillebaba  Thanks for you contribute, wonderful work.  I'm not experience with AWS, I guess that `secret_access_key` and `session_token` can only get from AWS portal or CLI. You can reference here [Bitbucket handle password ](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_bitbucket.go#L15),  `password` won't return by API too.

**Comment by xuzhang3** [comment]
@phillebaba I assign this task to you.

**Comment by phillebaba** [comment]
I looked a bit closer at how the other resources did and realized that they do not store the secret as it is not returned by the API. Instead they use a custom diff function and a hash of the secret to detect when any changes are made.

I will change my secrets handling to it works in the same way, and I guess it should work.

**Comment by phillebaba** [comment]
@xuzhang3 I made the changes so that the state is not out of sync all the time. I am not familiar with how your testing environment looks like though. Should I go ahead and implement a test that just assumes that aws-toolkit-azure-devops is installed?

**Comment by xuzhang3** [comment]
@phillebaba  We use Terraform acceptance test framework for testing, acceptance test will create real resource and destroy it after test finished ([Acceptance Test Document](https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html)). You don't need to judge whether the organization has installed the aws-toolkit-extension. When required resource not found, service API will return an error and acceptance test failed.

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#48
