### ISSUE TITLE
Unable to build provider on Ubuntu 18.04

### ISSUE THREAD

**Issue by tmeckel** [microsoft/terraform-provider-azuredevops#371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

```sh
$ make build
```

builds provider

### Actual Behavior

```sh
$ make build
```

creates the following error

![image](https://user-images.githubusercontent.com/14177833/117451571-f6e77b80-af42-11eb-8fb2-f526372adac2.png)

### Steps to Reproduce

`make build` on 

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

### References

Change  to `GNUmakefile` introduced with:

* https://github.com/microsoft/terraform-provider-azuredevops/pull/369

**Comment by tmeckel** [comment]
@xuzhang3 can we revert to the change in the `GNUmakefile` which causes the build to fail on Ubuntu 18.04?

**Comment by tmeckel** [comment]
@xuzhang3 Another obvious option would be to set the SHELL used by make to BASH. But I don't know if this would be portable e.g. on a MAC 😁 which I don't use.

![image](https://user-images.githubusercontent.com/14177833/117452385-fe5b5480-af43-11eb-95aa-a7e08450db26.png)

**Comment by xuzhang3** [comment]
Hi @tmeckel  Looks like the make file use the `/bin/sh` not `/bin/bash`, Fixed in PR: #372 .  Tested with  wsl: unbuntu18.04, ubuntu20.04, windows git bash, mac OSX.  
The WSL ubuntu still use CRLF, you need change the git configuration:  `git config --global core.autocrlf true` otherwise `make check-vendor-vs-mod` will not pass.

**Comment by xuzhang3** [comment]
@tmeckel  Code reverted to v0.1.4,  there's something wrong with the CI

**Comment by tmeckel** [comment]
@xuzhang3 this issue with the vendor updates and the `GNUmakefile` gave me quite a hard time 😁 

had to remove the following commits from my branch:

``` 
commit fe3e06b581b72503e6118e91a50b794883cefeb2
commit 5c527aa4709587a282df51f85540813029662354
commit 8e243322b8d260e7ff202266b3529225fa4eb76e
commit 23cc7b35c691887304d12078695f11a25823c0fb
```

Build is working again, thus I'm closing the issue.
