### ISSUE TITLE
Manage SSH keys in a repo

### ISSUE THREAD

**Issue by ams0** [microsoft/terraform-provider-azuredevops#372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to be able to manage SSH keys for a user account (similar to [deploy key](https://www.terraform.io/docs/providers/github/r/repository_deploy_key.html) for Github).

### New or Affected Resource(s)

* azuredevops_ssh_key

### Potential Terraform Configuration
```hcl

resource "tls_private_key" "ssh-key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azuredevops_ssh_key" "ssh-key" {
    name = "ssh-key"
    content = tls_private_key.ssh-key.public_key_openssh
}

```

### References

This feature can come very handy when for example I want to add an SSH key generated for use by Flux controller when I use a repo in Azure DevOps for GitOps. See this [example](https://github.com/ams0/rancher-home/tree/master/terraform) how I do it with Github provider.

* #0000

Looks like the API is [undocumented](https://stackoverflow.com/questions/52658534/azure-devops-api-add-public-key).

**Comment by xuzhang3** [comment]
Hi @ams0, thank you for opening this issue. This new feature will be blocked due to SDK does not support this API. [Azuredevops API SDK](https://github.com/microsoft/azure-devops-go-api/)

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#31
