### ISSUE TITLE
Support Importing Git Repository Resources -- azuredevops_git_repository

### ISSUE THREAD

**Issue by mxrss2** [microsoft/terraform-provider-azuredevops#373]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to support importing git repos. I am dealing with a config that has been built manually and trying to get it under control with terraform. I do not want to have to blow out repos to readd to get them to work with terraform. 

### New or Affected Resource(s)

`azuredevops_git_repository`

### Potential Terraform Configuration

```hcl
terragrunt import azuredevops_git_repository.repo "azdo-config"
```

When running import you get the error message

```
azuredevops_git_repository.repo: Creating...

Error: Error creating repository in Azure DevOps: TF400948: A Git repository with the name azdo-config already exists.

  on main.tf line 1, in resource "azuredevops_git_repository" "repo":
   1: resource "azuredevops_git_repository" "repo" {


[terragrunt] 2020/06/11 22:42:09 Hit multiple errors:
exit status 1
```

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#43
