### ISSUE TITLE
Github service connection for Github enterprise

### ISSUE THREAD

**Issue by anikm1987** [microsoft/terraform-provider-azuredevops#378]
Hi,
I was trying to create service connection for GITHUB enterprise but unable to find any option to provide server url.
Is this feature planned?
Is there any other way I can do that.
Thanks

**Comment by xuzhang3** [comment]
Hi @anikm1987, `github_enterprise_service_connection` is in our future plan.  You can create the GITHUB service connection in the traditional way(use portal).
We have migrate this repo to [terraform-provider-azuredevops](https://github.com/terraform-providers/terraform-provider-azuredevops)

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#28
