### ISSUE TITLE
Service Connection for Azure China and ablity to select management group

### ISSUE THREAD

**Issue by anikm1987** [microsoft/terraform-provider-azuredevops#379]
Hi,
Currently I am not able to find any option to set azurm_enviornment while creating service connection which is kind of restricting me to use it for Azure China cloud.

Also in service azuredevops_serviceendpoint_azurerm, there is no option to provide management group as an option.

Is this planned for future release?

Thanks
Aniket

**Comment by xuzhang3** [comment]
Hi @anikm1987, We have migrate this repo to [terraform-provider-azuredevops](https://github.com/terraform-providers/terraform-provider-azuredevops)
1. In AzureRM service connection, `Environment` is not supported yet. We will add this in the future.  
2. What management group do mean? [Membership resource](https://www.terraform.io/docs/providers/azuredevops/r/group_membership.html) may help you.

**Comment by EliiseS** [comment]
Issue migrated to terraform-providers/terraform-provider-azuredevops#27
