### ISSUE TITLE
Implement new resource "Service Fabric Service Endpoint"

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#38]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/167
Originally created by @hbuckle on *Wed, 30 Oct 2019 10:42:43 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/167#issuecomment-558800386
Originally created by @nmiodice on *Tue, 26 Nov 2019 20:18:09 GMT*

---
@hbuckle you may want to look back into the existing implementation, as it has been made generic as to make extensions of service endpoints easier. 

Ex:
 - https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_dockerhub.go
 - https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_serviceendpoint_github.go

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/167#issuecomment-547840141
Originally created by @hbuckle on *Wed, 30 Oct 2019 10:43:51 GMT*

---
Would be happy to implement this myself but not sure what the design is for these - there's already a `service endpoint` resource but it references a github pat?

**Comment by hbuckle** [comment]
@EliiseS - I have started looking at this, is there any documentation on how to use the secret hashing mechanism? I think I've implemented it in the same way as the other resources, but both the raw value and the hashed value end up in the state.
