### ISSUE TITLE
azuredevops_variable_group fails to detect drift in variables with secret_value set

### ISSUE THREAD

**Issue by booyaa** [microsoft/terraform-provider-azuredevops#385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```sh
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.4
```

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

Use the example code provided in [documentation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/variable_group#example-usage)

### Debug Output

https://gist.github.com/booyaa/1e5c48ba9e1b8a600bf47a46c54daf2f

### Expected Behavior

The provider should detect the changed value for a secret variable, just like it does for plain text variables.

### Actual Behavior

The provider doesn't detect changes

### Steps to Reproduce

1. Use the example from [documentation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/variable_group#example-usage) to create a new variable group with a variable and secure variable (where secret_value and is_secret attributes are defined) 
1. Create a new variable group using
   1. `terraform plan` 
   1. `terraform apply`
1. Modify the secret variable "Account Password" in DevOps
1. Run `terraform plan` which will not detect any changes

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @booyaa  Secret value is combined with `is_secret=true` and `secret_value`, if `is_secret=false`, the variable will treated as normal text plain variable.

**Comment by booyaa** [comment]
hi @xuzhang3, the point I'm making is that if I change the value of s a secret value in the DevOps portal, I expect terraform to detect the change. At the moment it doesn't.

**Comment by xuzhang3** [comment]
@booyaa  provider cannot detect the changes when you change the value outside of Terrafrom. API response always return the secret value as `null`
![image](https://user-images.githubusercontent.com/57888764/119302010-f87ca780-bc95-11eb-910f-f9ba7951ed8b.png)

**Comment by booyaa** [comment]
That's a shame, looks like the only safe way to detect value changes is via Key Vault linked variable group.

Thanks.
