### ISSUE TITLE
Support for using Service principal to authenticate azure devops provider

### ISSUE THREAD

**Issue by bhavith** [microsoft/terraform-provider-azuredevops#395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the azure-devops provider needs a Personal Access Token (PAT) to authenticate. We use service principal with certificate for Terraform to authenticate against other Azure services. Since PAT can be generated only for a user, we had to create an AAD user for Terraform and use that to generate PAT.

It would have been great if terraform can authenticate using service principal for azure-devops provider, like it does for other providers.

**Comment by xuzhang3** [comment]
@bhavith  If I'm not wrong, SPN cannot access the devops resources. 
ref: https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops

**Comment by tmeckel** [comment]
@xuzhang3 I think the issue can be closed because AzDO definitely does not support service principal (app only) authentication and always relies on a "real" user object from Azure AD. I not sure if this feature is planned to be implemented anyway.

**Comment by tmeckel** [comment]
Related to #419 #351

**Comment by bhavith** [comment]
@tmeckel @xuzhang3 i see that now "The Azure DevOps API doesn't support non-interactive service access via service principals."

Thanks for your response. I guess this issue can be closed.
