### ISSUE TITLE
Not able to create Azure Devops Custom security groups at project level and its creating groups at organization level even we are defining scope at project level in the code

### ISSUE THREAD

**Issue by avadhut0111** [microsoft/terraform-provider-azuredevops#396]
###Create Azure DevOps Project Group at Project Level:

resource "azuredevops_group" "tf-group" {
  scope        = data.azuredevops_project.project.id
  display_name = var.group-name
  description  = var.description
}

###Using azure devops provider version: 

terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}

**Comment by xuzhang3** [comment]
@avadhut0111 This is a know issue. Fixed in #369

**Comment by xuzhang3** [comment]
@avadhut0111  Fixed in v0.1.5, please update the provider.
