### ISSUE TITLE
0.1.5 release?

### ISSUE THREAD

**Issue by hbuckle** [microsoft/terraform-provider-azuredevops#397]
Any chance of cutting a new release? I'd like to start using the service fabric service endpoint resource

**Comment by xuzhang3** [comment]
@hbuckle  Sorry for the delay, coming soon....

**Comment by xuzhang3** [comment]
@hbuckle v0.1.5 released https://registry.terraform.io/providers/microsoft/azuredevops/latest?pollNotifications=true
