### ISSUE TITLE
Changing of `init_type` doesn't have any effect

### ISSUE THREAD

**Issue by alexott** [microsoft/terraform-provider-azuredevops#406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.5
+ provider registry.terraform.io/terraform-providers/azuredevops v0.1.5
```

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

When I first declared the Git repository as not initialized like this, and run `terraform apply`:

```hcl
resource "azuredevops_git_repository" "repository2" {
  project_id = azuredevops_project.project.id
  name       = "Nutter on DevOps 2"
  initialization {
    init_type = "Uninitialized"
    source_type = "Git"
    source_url = "https://github.com/alexott/databricks-nutter-projects-demo"
  }
}
```

and then later change to "Import" then as this:

```hcl
resource "azuredevops_git_repository" "repository2" {
  project_id = azuredevops_project.project.id
  name       = "Nutter on DevOps 2"
  initialization {
    init_type = "Import"
    source_type = "Git"
    source_url = "https://github.com/alexott/databricks-nutter-projects-demo"
  }
}
```

### Expected Behavior

I would expect either:
* Git repository is imported if I still have a repository without any changes
* or report an error that you can't change the value of `init_type` after first apply is done

### Actual Behavior

the `terraform apply` goes without any problems, but it doesn't change anything:

```
  # azuredevops_git_repository.repository2 will be updated in-place
  ~ resource "azuredevops_git_repository" "repository2" {
        id         = "531c10f8-b111-4415-9eef-f738e53d6760"
        name       = "Nutter on DevOps 2"
        # (7 unchanged attributes hidden)

      ~ initialization {
          ~ init_type   = "Uninitialized" -> "Import"
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by xuzhang3** [comment]
@alexott  Thanks for open this issue.  The `init_type` should only be used once,  this configuration should only apply to repository creation not update.

**Comment by alexott** [comment]
@xuzhang3 - maybe we should throw the error when we see that people are doing update?

**Comment by xuzhang3** [comment]
@alexott  PR #407 can fix this, when `init_type` changed, terraform will recreate the repository.

**Comment by alexott** [comment]
thank you very much!
