### ISSUE TITLE
Support for certificate based service connection creation in azuredevops_serviceendpoint_azurerm

### ISSUE THREAD

**Issue by viks09** [microsoft/terraform-provider-azuredevops#409]
Currently the credentials block in this resource (azuredevops_serviceendpoint_azurerm) only support service principal's secrets for the serviceprincipalkey argument. Would like to use the certificate associated with the service principal as well.

Thanks,

**Comment by damhau** [comment]
Any news on this ?

**Comment by bwesolowskicf** [comment]
Hi, I just ran into the same issue. Is there any update here?
