### ISSUE TITLE
Authorize service connection use by pipeline via Terraform

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#41]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142
Originally created by @nmiodice on *Tue, 22 Oct 2019 23:15:33 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer provisioning new resources in AzDO, i don't want to have to manually grant access to a service endpoint to a build definition. Instead, I want to do this via Terraform.

### Acceptance criteria
 - [ ] Investigate how to grant a build definition access to a service connection via the AzDO APIs
 - [ ] Design an implementation. The implementation should cover the following items, and should be put into the body of this issue and reviewed by the core contributors on the project
   - [ ] What will the schema for the resource look like, including computed items?
   - [ ] What APIs need to be invoked?
   - [ ] What is the implementation strategy?
   - [ ] What is the testing strategy?
 - [ ] Break down the implementation into stories **after the design** is done

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-587275066
Originally created by @lachie-white on *Tue, 18 Feb 2020 04:40:31 GMT*

---
https://github.com/flynnhandley/terraform-provider-azdevops

One of the awesome engineers i was working previously started working on this 15 months ago. Our biggest reason to move away from the Microsoft one was the use of service connections missing from the provider

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-629345568
Originally created by @nmiodice on *Fri, 15 May 2020 16:09:54 GMT*

---
I think it does indeed make sense to extend the current implementation with the ability to specify a `project_id` *or* a `definition_id`

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-615841832
Originally created by @rmaziarka on *Sat, 18 Apr 2020 11:01:14 GMT*

---
I investigated these options for using TF with the creation of my personal blog. There are two endpoints:
- [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/authorizedresources/authorize%20project%20resources?view=azure-devops-rest-5.1) - to allow a service connection to be used by all builds
- [link](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/resources/authorize%20definition%20resources?view=azure-devops-rest-5.1) - to allow a particular pipeline to be accessed by the service connection.

I can take the next step of this task " Design an implementation." - are there any guidelines on how to approach it? Or any tasks finished before so I can check how there were done?

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-621595943
Originally created by @lachie-white on *Thu, 30 Apr 2020 03:48:20 GMT*

---
@rmaziarka Based on my experience using this granularity should be favoured. i.e. we should enable each pipeline to be run under a service connection. This can enable the use of a one to one mapping between whatever the deployment boundary the pipeline controls is. For example, a resource group or a subscription.

I would favour that direction

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-629352584
Originally created by @nmiodice on *Fri, 15 May 2020 16:21:03 GMT*

---
I probably won't get to this ASAP so if somebody from the OSS community would like to take a go at it, please do!

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-628704055
Originally created by @lachie-white on *Thu, 14 May 2020 15:18:20 GMT*

---
I think the `authorization` part is now covered yes! as I believe is most likely this Issue in its entirety!

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-629091105
Originally created by @rmaziarka on *Fri, 15 May 2020 07:57:54 GMT*

---
Maybe I don't see it, but is there an option to define `definitionId` in Terraform? As you can see in the [Microsoft API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/resources/authorize%20definition%20resources?view=azure-devops-rest-5.1#definitionresourcereference) related to the resource authorization you authorize resource with the particular build.

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-626149618
Originally created by @rmaziarka on *Sat, 09 May 2020 11:00:17 GMT*

---
@lachie-white I think that Terraform should support both options because both options are available in the Azure DevOps portal.

First is available in the creation of Service Connection:
![image](https://user-images.githubusercontent.com/5219374/81471791-f616ef00-91f3-11ea-9517-412be6202da0.png)
The second is available in pipeline view:
![image](https://user-images.githubusercontent.com/5219374/81471926-0380a900-91f5-11ea-92ab-c1789fdb4c21.png)

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-647045490
Originally created by @rmaziarka on *Sat, 20 Jun 2020 21:07:07 GMT*

---
Today I had some time to sit down to this issue.

`azuredevops_resource_authorization` works great if you want to add service connection to the whole project - this is a situation in service connection edit panel after running `terraform apply`:
![image](https://user-images.githubusercontent.com/5219374/85211361-a9711880-b348-11ea-9316-32fea4d6e4cf.png)

In the same time, adaptation to additionally manage authorization to the single pipeline would need to use another API:
- `azuredevops_resource_authorization` in the background uses [Authorizedresources - Authorize Project Resources API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/authorizedresources/authorize%20project%20resources?view=azure-devops-rest-5.1)
- to manage pipeline authorization you need to use Resources - [Authorize Definition Resources API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/resources/authorize%20definition%20resources?view=azure-devops-rest-5.1) - tested manually in Postman

@nmiodice how do you manage this kind of logic inside the [resource file](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/build/resource_resource_authorization.go)?
- simple if `project_id` defined then call the first API, else if `definition_id` defined the call the second API
- something more sophisticated

I would like to try to write it but I've never written a single line of code in Go 😉

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/142#issuecomment-628522109
Originally created by @tmeckel on *Thu, 14 May 2020 09:42:48 GMT*

---
Correct me ... but isn't that implemented with 

https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/resource_resource_authorization.go

https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/resource_authorization.html.markdown

```hcl 
resource "azuredevops_serviceendpoint_bitbucket" "bitbucket_account" {
  project_id = "vanilla-sky"
  username               = "xxxx"
  password               = "xxxx"
  service_endpoint_name  = "test-bitbucket"
  description            = "test"
}

resource "azuredevops_resource_authorization" "auth" {
  project_id = "phoenix-project"
  resource_id = azuredevops_serviceendpoint_bitbucket.bitbucket_account.id
  authorized = true
}
```

**Comment by xuzhang3** [comment]
Access permission  can be granted via [azuredevops_pipeline_authorization](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization)
