### ISSUE TITLE
New Resource: Pipeline general settings

### ISSUE THREAD

**Issue by LaurentLesle** [microsoft/terraform-provider-azuredevops#410]
When creating a build definition that need to access sources from a different project we are getting this error.

The current workaround is to change those 3 settings:
![image](https://user-images.githubusercontent.com/4702224/123419255-97295a80-d5ec-11eb-9e89-450ea608930d.png)

**Comment by xuzhang3** [comment]
@LaurentLesle  his feature is blocked by SDK since this feature is supported since v6.x.
API: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/general%20settings/update?view=azure-devops-rest-6.0

**Comment by richardgavel** [comment]
Has there been any update on getting the Azure DevOps GO SDK updated? This is blocking a number of issues in the Terraform provider.

**Comment by xuzhang3** [comment]
Sorry, no update.

**Comment by a2m1** [comment]
Created [azure-devops-go-api/issues/104](https://github.com/microsoft/azure-devops-go-api/issues/104). But don't think that it will help as [azure-devops-go-api](https://github.com/microsoft/azure-devops-go-api) didn't get any updates since Aug 2020.

**Comment by a2m1** [comment]
Not perfect but better than nothing
```
data "azuredevops_client_config" "current" {}

resource "null_resource" "build_general_settings" {
  triggers = {
    enforceJobAuthScope              = false
    enforceReferencedRepoScopedToken = true
    enforceSettableVar               = true
    publishPipelineMetadata          = false
    statusBadgesArePrivate           = true
    azdo_pat_token_owner_email = var.azdo_pat_token_owner_email
    azdo_pat_token             = var.azdo_pat_token
    project_url                = "${data.azuredevops_client_config.current.organization_url}/${azuredevops_project.project.name}"
  }
  provisioner "local-exec" {
    command = <<-EOT
      curl -X PATCH \
        -u "${self.triggers.azdo_pat_token_owner_email}:${self.triggers.azdo_pat_token}" \
        -H "Content-Type: application/json" \
        --data "{\"enforceJobAuthScope\":\"${self.triggers.enforceJobAuthScope}\",\"enforceReferencedRepoScopedToken\":\"${self.triggers.enforceReferencedRepoScopedToken}\",\"enforceSettableVar\":\"${self.triggers.enforceSettableVar}\",\"publishPipelineMetadata\":\"${self.triggers.publishPipelineMetadata}\",\"statusBadgesArePrivate\":\"${self.triggers.statusBadgesArePrivate}\"}" \
        "${self.triggers.project_url}/_apis/build/generalsettings?api-version=6.0-preview.1"
    EOT
  }
}
```

**Comment by favoretti** [comment]
There has been life in go-sdk-upgrade to 6.0/6.1. According to https://github.com/microsoft/azure-devops-go-api/issues/93 - coming soon™.
