### ISSUE TITLE
Artifactory Service Connection null token after user changes description, URL.

### ISSUE THREAD

**Issue by billbirchatcoles** [microsoft/terraform-provider-azuredevops#422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

v0.14.11
### Affected Resource(s)

* `azuredevops_serviceendpoint_artifactory`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_artifactory" "serviceendpoint" {
  for_each = var.artifactory_service_connections

  project_id            = azuredevops_project.this.id
  service_endpoint_name = each.value.name
  description           = format("Artifactory Service Connection (%s)", split("/", each.value.url)[2])
  url                   = each.value.url
  authentication_token {
    token = each.value.token
  }
}

```

### Debug Output
At this point Terraform has set the internal token to “null” instead of the token. Here's the proof, taken from the arguments passed into the jfrog executable in the pipeline which uses the Service Connection :

```JSON
  "args": [
    "/apps/agent/_work/_tool/jfrog/1.47.1/x64/jfrog",
    "rt",
    "u",
    "--url=https://colesgroup.jfrog.io/colesgroup",
    "--access-token=null",
    "--spec=/apps/agent/_work/27/s/uploadSpec1626257680947.json",
    "--build-name=CEFS-DevOpsOnboarding",
    "--build-number=20210714.50",
    "--fail-no-op=true",
    "--dry-run=false",
    "--insecure-tls=false",
    "--threads=3",
    "--retries=3",
    "--symlinks=false"
  ],
```

### Expected Behavior

The access token in the Service Connection should not be set to `"null"`

### Actual Behavior

The access token in the Service Connection was set to `"null"` when Terraform apply ran.

### Steps to Reproduce

This defect only appears after the following sequence of events:

1. User modifies Artifactory Service Connection via the web UI, changes the URL or description, but not the token. (Use Save without verify).

2. User runs the terraform plan and apply.  This applies a plan: 

![image](https://user-images.githubusercontent.com/75357351/125919075-f644ad0d-2a4c-42bb-893f-97422cfed9da.png)

[Notice the plan makes no mention of intent to update the secret access token.]

### Note

I will be working on a fix for this myself in the next couple of days...

**Comment by xuzhang3** [comment]
Hi @billbirchatcoles Normally, we do not recommend users change the resource configurations outside of Terraform, unpredictable. This issue might caused by the `d.Set("authentication_token", xxx)` at  https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_artifactory.go#L151

**Comment by venkatesh-thatham** [comment]
@xuzhang3, last commented was Jul 19, 2021. It's been more than an year the issue remain open. any update on the fixes. looking forward to be hearing from you

**Comment by xuzhang3** [comment]
@thatham  #656 will fix this bug. Service will return the sensitive data password/token etc. as empty string or null, this cause the second update change the token to null even user not update the HCL.

**Comment by venkatesh-thatham** [comment]
@xuzhang3 I'm still getting below error
Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.

**Comment by xuzhang3** [comment]
@thatham you need install the JFrom Artificatory extension( https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory-vsts-extension) for your ORG, this extension was not enabled by default.

**Comment by venkatesh-thatham** [comment]
@xuzhang3 we had installed JFrom Artificatory extension in our Azure DevOps, this is error

Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
│
│   with module.jfrog_service_connections["0"].azuredevops_serviceendpoint_artifactory.distribution,
│   on modules/jfrog/distribution.tf line 1, in resource "azuredevops_serviceendpoint_artifactory" "distribution":
│    1: resource "azuredevops_serviceendpoint_artifactory" "distribution" {
│
╵
╷
│ Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
│
│   with module.jfrog_service_connections["0"].azuredevops_serviceendpoint_artifactory.artifactory,
│   on modules/jfrog/main.tf line 1, in resource "azuredevops_serviceendpoint_artifactory" "artifactory":
│    1: resource "azuredevops_serviceendpoint_artifactory" "artifactory" {
│
╵
╷
│ Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
│
│   with module.jfrog_service_connections["0"].azuredevops_serviceendpoint_artifactory.platform,
│   on modules/jfrog/platform.tf line 1, in resource "azuredevops_serviceendpoint_artifactory" "platform":
│    1: resource "azuredevops_serviceendpoint_artifactory" "platform" {
│
╵
╷
│ Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
│
│   with module.jfrog_service_connections["0"].azuredevops_serviceendpoint_artifactory.xray,
│   on modules/jfrog/xray.tf line 1, in resource "azuredevops_serviceendpoint_artifactory" "xray":
│    1: resource "azuredevops_serviceendpoint_artifactory" "xray" {

**Comment by xuzhang3** [comment]
@thatham can you check that the extension correctly installed?
![image](https://user-images.githubusercontent.com/57888764/199441295-4abc0cc2-9a35-44ab-ab52-9020809c0e86.png)

**Comment by venkatesh-thatham** [comment]
@xuzhang3, we have installed this extension which has all service connection modules
![image](https://user-images.githubusercontent.com/34929590/199449078-0b9955e0-bf4f-45ac-95f1-a229f7be1a68.png)

![image](https://user-images.githubusercontent.com/34929590/199449348-8026b34b-3d54-4a1b-a162-859477349766.png)

**Comment by xuzhang3** [comment]
@thatham a bit different from my extension, 
![image](https://user-images.githubusercontent.com/57888764/199450512-6298b4bd-538a-4182-8720-f1ef2c347073.png)

you need install this extension:
![image](https://user-images.githubusercontent.com/57888764/199450738-befc4170-9b28-42cb-8ffb-0b06956d1677.png)


I will update the doc to include the requirement.

**Comment by venkatesh-thatham** [comment]
@xuzhang3 Jfrog Artifactory extension is using old version. if you refer my previous screenshots there's distinct difference between these two extension.
https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension
https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension (using V2)

**Comment by xuzhang3** [comment]
@thatham current resource only support the old version. A new resource need to added to support Artifactory v2

**Comment by venkatesh-thatham** [comment]
> @thatham current resource only support the old version. A new resource need to added to support Artifactory v2

@xuzhang3, any plan to upgrade or create a set of resources and datasources with new versions ?. Looking forward to be hearing from you.

**Comment by venkatesh-thatham** [comment]
@xuzhang3, there's a PR #705 update to Jfrog V2, could you please review and merge. Appreciate your response timely
