### ISSUE TITLE
Support for managing git branches

### ISSUE THREAD

**Issue by nikolaifa** [microsoft/terraform-provider-azuredevops#425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like an option to manage Azure DevOps branches. 

### New or Affected Resource(s)

* azuredevops_git_repository_branch

**Comment by xuzhang3** [comment]
Hi @nikolaifa   this is a duplicate issue with #383 , I will close this issue.
