### ISSUE TITLE
Import of azuredevops_git_repository forces destroying of existing resource

### ISSUE THREAD

**Issue by sikkiv** [microsoft/terraform-provider-azuredevops#428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.6

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
resource "azuredevops_git_repository" "my_repo" {
    project_id = azuredevops_project.my_project.id
    name = "my-repo"
    initialization {
        init_type = "Clean"
    }
}
```

### Expected Behavior

On importing an existing Git repository into the Terraform state it should just work without trying to recreate the repository on a new apply. 

### Actual Behavior

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azuredevops_git_repository.my_repo must be replaced
-/+ resource "azuredevops_git_repository" "my_repo" {
      ~ default_branch = "refs/heads/master" -> (known after apply)
      ~ id             = "xxxxx" -> (known after apply)
      ~ is_fork        = false -> (known after apply)
        name           = "my-repo"
      ~ remote_url     = "xxxxx" -> (known after apply)
      ~ size           = 96236 -> (known after apply)
      ~ ssh_url        = "xxxxx" -> (known after apply)
      ~ url            = "xxxxx" -> (known after apply)
      ~ web_url        = "xxxxx" -> (known after apply)
        # (1 unchanged attribute hidden)

      + initialization {
          + init_type = "Uninitialized" # forces replacement
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by xuzhang3** [comment]
Hi @sikkiv Change the `init_type` will recreate the resource. 
This is a tech-debt, this configuration is introduced by this provider and not part of the APIs, this better way is split this confutation into new resources or other configurations and deprecate this config.

**Comment by tmeckel** [comment]
@sikkiv have you tried to omit the `initialization` block? The `initialization` block will create a diff on the resource because the provider cannot know what type of initialization has been used for the Git repository in case of an import.

**Comment by sikkiv** [comment]
@tmeckel yes I did, but since it's a "required" field as stated here: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository I can't leave it empty...

**Comment by tmeckel** [comment]
@sikkiv can you check if it makes any difference when you set the `init_type` to `Uninitialized`

```hcl
resource "azuredevops_git_repository" "my_repo" {
    project_id = azuredevops_project.my_project.id
    name = "my-repo"
    initialization {
        init_type = "Uninitialized"
    }
}
```

**Comment by sikkiv** [comment]
@tmeckel that is exactly what I did already and it still wants to destroy the resource, tested with every `init_type` already :(

**Comment by xuzhang3** [comment]
@sikkiv What is the value of the `init_type` in the .tfstate file?

**Comment by sikkiv** [comment]
@xuzhang3 it's not existing, this is what's there: `"initialization": [],`

**Comment by xuzhang3** [comment]
@sikkiv   A workaround is add the `initialization` to the `.tfstate` file manually and make sure the `init_type` configuration in the TF script is same as `.tfstate`.   This is a breaking change introduced since v0.1.6.  Another workaround is downgrade the provider version to v0.1.5

**Comment by sikkiv** [comment]
@xuzhang3 thank you very much for your help, that absolutely helped 👍

**Comment by RobinS-S** [comment]
This is still an active issue on 0.1.7.

**Comment by roryprimrose** [comment]
The workaround is documented in issue #467. You need to tell the provider to ignore that attribute.
