### ISSUE TITLE
Support Importing Git Repository Resources -- azuredevops_git_repository

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#43]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/373
Originally created by @mxrss2 on *Thu, 11 Jun 2020 22:50:38 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to support importing git repos. I am dealing with a config that has been built manually and trying to get it under control with terraform. I do not want to have to blow out repos to readd to get them to work with terraform. 

### New or Affected Resource(s)

`azuredevops_git_repository`

### Potential Terraform Configuration

```hcl
terragrunt import azuredevops_git_repository.repo "azdo-config"
```

When running import you get the error message

```
azuredevops_git_repository.repo: Creating...

Error: Error creating repository in Azure DevOps: TF400948: A Git repository with the name azdo-config already exists.

  on main.tf line 1, in resource "azuredevops_git_repository" "repo":
   1: resource "azuredevops_git_repository" "repo" {


[terragrunt] 2020/06/11 22:42:09 Hit multiple errors:
exit status 1
```

**Comment by xuzhang3** [comment]
Since feature has been implemented,  close this issue.

**Comment by mxrss2** [comment]
@xuzhang3  I don't think the ref'd PR does what I intended in this ticket.

The ref'd PR does something with `import a git repo` like a template git repo.

This is to import the repo into the graph..

**Comment by xuzhang3** [comment]
@mxrss2   I see, my mistake.

**Comment by kevinmatthews-kpmg** [comment]
I too require the import of existing devops git repos in to terraform, so that I can manage all of the repos that we have manually created +1

**Comment by xuzhang3** [comment]
@kevinmatthews-kpmg  Current `Import` function support public repo import, private repo not supported yet.

**Comment by kevinmatthews-kpmg** [comment]
> @kevinmatthews-kpmg Current `Import` function support public repo import, private repo not supported yet.

Yeah, im more after private repos so like:

`terraform import my-repo-name azuredevops/repositories/my-repo-name`

Thanks

**Comment by xuzhang3** [comment]
@kevinmatthews-kpmg  Sorry, I misunderstand at first. Terraform `import` not supported yet.

**Comment by mxrss2** [comment]
@xuzhang3 

Hate to be a pest but curious if we are close to taking on this work. Really needed as I need to refactor and this is really difficult to do without import.

**Comment by mxrss2** [comment]
@kevinmatthews-kpmg i added a first stab at this, feel free to look at and look at the branch. I tested that it works for the GUIDs that get used -- I had an implementation for doing it based on the implementation of a slug uri but it needs a bit of work and tests.

**Comment by mxrss2** [comment]
Believe we can close this issue since my PR was accepted.

**Comment by kevinmatthews-kpmg** [comment]
Has the documentation on the tf been updated with the details on how to do this?

Similar to: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group#import

**Comment by mxrss2** [comment]
@kevinmatthews-kpmg it would have to be released. You can compile code from the mainline and install the provider, but the code has not been released yet.

**Comment by xuzhang3** [comment]
Close this issue as the PR has been merged.
