### ISSUE TITLE
azuredevops_variable_group doesn't allow for no variables as documented.

### ISSUE THREAD

**Issue by derekwilliamsliquidx** [microsoft/terraform-provider-azuredevops#431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

* Terraform v1.0.4 on Linux
* Azure DevOps Provider: 0.1.6

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
resource "azuredevops_variable_group" "variablegroup" {
  count        = length(local.workspace["variable_groups"])
  project_id   = azuredevops_project.project.id
  name         = "${local.workspace["project_name"]}-${local.workspace["variable_groups"][count.index]}"
  description  = "Generic environment based variable Group"
  allow_access = true

}
```

### Debug Output

Not adding for security reasons

### Panic Output

* N/A

### Expected Behavior

Variable group is created without any variables added

### Actual Behavior

╷
│ Error: Insufficient variable blocks
│
│   on ado_variable_group.tf line 1, in resource "azuredevops_variable_group" "variablegroup":
│    1: resource "azuredevops_variable_group" "variablegroup" {
│
│ At least 1 "variable" blocks are required.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

 * N/A

### References

* No

**Comment by derekwilliamsliquidx** [comment]
I have a feature branch to update the docs and mark `variable` block as optional. I'm unable to push a feature branch though.

**Comment by xuzhang3** [comment]
@derekwilliamsliquidx  You can submit a pull request to this repo.

![image](https://user-images.githubusercontent.com/57888764/128958329-a6165ab8-eef8-4c62-b328-cb16db75ea19.png)
