### ISSUE TITLE
Provider produced inconsistent final plan for azuredevops_serviceendpoint_kubernetes

### ISSUE THREAD

**Issue by allenvino1** [microsoft/terraform-provider-azuredevops#432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_serviceendpoint_kubernetes`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_kubernetes" "kubernetes_service_account" {
  project_id            = var.azure_devops_project
  service_endpoint_name = "${var.team_name}-${var.environment_name}-gke"
  apiserver_url         = "https://${google_container_cluster.primary.endpoint}"
  authorization_type    = "ServiceAccount"

  service_account {
    token   = data.kubernetes_secret.azure_devops_integration.binary_data["token"]
    ca_cert = data.kubernetes_secret.azure_devops_integration.binary_data["ca.crt"]
  }
}
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/17024847/129043552-47d6b50d-f51b-4bfd-ae07-f55ff9ae5b72.png)

### Steps to Reproduce

1. `terraform apply`

### Note

1. Im trying to do GKE + creating azure devops service connection.
2. When I applied the second time it pushed thru maybe because the gke cluster is established already. 
3. Seems like the handling of the provider seems broken with dynamic values from other terraform resources. I tried hardcoding values it works.

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @spacejam101  I cannot reproduce this error.  Which Terraform version and provider version are you use? This  seems like https://github.com/hashicorp/terraform/issues/20517

**Comment by allenvino1** [comment]
Hello @xuzhang3. I'm using terraform v1.0.3. This my provider versions:
![image](https://user-images.githubusercontent.com/17024847/129154558-17306b7b-ea02-4e66-8ad6-e08f2ed16147.png)

**Comment by allenvino1** [comment]
Is there anyway I can help inorder for you to solve this? @xuzhang3

**Comment by spacejam101** [comment]
DEBUG Log on the first run 
![image](https://user-images.githubusercontent.com/17024847/129299831-b475c0ac-512f-4d31-b095-ebdf9754c934.png)

Second run. It pushed thru to create the resource
![image](https://user-images.githubusercontent.com/17024847/129299980-9093aef8-fed8-40d5-9494-ee611d3f73d9.png)

**Comment by xuzhang3** [comment]
@spacejam101   You should mask the cert and tokens.

**Comment by xuzhang3** [comment]
Hi @spacejam101 what's the output of `terraform plan`.  Will `token` and `cert` changed during the `terraform apply`, the real value will changed by GKE?

**Comment by allenvino1** [comment]
I'm afraid my flow does not use static token and cert. I would like it to be on the fly.

The flow would be GKE is created and then I do a secret lookup on the serviceaccount to be passed to azure devops.

![image](https://user-images.githubusercontent.com/17024847/129301426-da78edac-30b8-4fc7-8dd2-2eaa2b193c49.png)

Plan output:
![image](https://user-images.githubusercontent.com/17024847/129301717-a2ad639f-3a0b-4de6-a5b9-4a65607c8bfa.png)

**Comment by xuzhang3** [comment]
@spacejam101  I create a new aks cluster and use `kubernetes_secret` to get the credentials,  all resource can be created without error.

**Comment by allenvino1** [comment]
Interesting. Sorry im new to terraform. Not sure how to debug this one. Uhmm Maybe try it with GKE cluster?

**Comment by korenlev** [comment]
same issue here (tipalti.com)

**Comment by allenvino1** [comment]
On terraform 1.2.7
<img width="939" alt="image" src="https://user-images.githubusercontent.com/17024847/225894030-89d15199-f699-4ae1-ba7d-b05f50189538.png">

**Comment by allenvino1** [comment]
This is now fixed seems like its a bug with the kubernetes_secret_v1 mutation. I used kubernetes_resource to workaround with the issue to fetch the secret details.
