### ISSUE TITLE
azuredevops_iteration_permissions doesn't work if path changes

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#441]
I initially terraformed some permissions with azuredevops_iteration_permissions  for path `/FY21/X` then we moved `/FY21` to `/Archive/FY21`  when running a terraform apply or plan i got the following error during plan phase (NOT APPLY PHASE):

`Error: Error getting classification node: VS402485: The Area/Iteration name is not recognized: FY21`

I got past it by hand modifying the state of that resource to the new path, and it worked again saying it wanted to change `/Archive/FY21/X` to `/FY21/X` (which is expected since i hand't modified my config`.

It was like the state value was being used to do a lookup somehow.

I get that the id's of iteration-permissions are a bit hacky, but it shouldn't fail a plan because of a change on server and an "outdated" value in state.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

❯ tf -v
Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.6

### Affected Resource(s)

* `azuredevops_group_membership`

### Terraform Configuration Files

```hcl
resource "azuredevops_iteration_permissions" "e" {
  project_id  = azuredevops_project.e.id
  principal   = azuredevops_group.e.id
  path = "/FY21/X"
  permissions = {
    CREATE_CHILDREN = "Allow"
    GENERIC_READ    = "Allow"
    GENERIC_WRITE   = "Allow"
    DELETE          = "Allow"
  }
}
```

### Expected Behavior

Should have gotten a plan taht said it would change the path from `/Archive/FY21/X` to `/FY21/X`, it'd be great if this was an in place change but i believe path changes force replace...which still woulda been fine.

### Actual Behavior

Error:
```
Error getting classification node: VS402485: The Area/Iteration name is not recognized: FY21
```

### Steps to Reproduce

1. `terraform apply`
2. move the path somewhere esel
3. `terraform plan`

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @drdamour It's not recommend to manage the resources with Terraform and other tools.
In your scenario, when you change the iteration path and execute `terraform apply` command, The `azuredevops_iteration_permissions` will be recreated. The  `path` is force new property,  change this value will destroy the current resource and create a new one
Terraform  will use the state value(`/FY21/X`) to destroy the `azuredevops_iteration_permissions`. But  this value has been changed to `/Archive/FY21/X`, so Terraform will raise an error that , the path `FY21` cannot be find.

**Comment by xuzhang3** [comment]
Since ADO provider does not support create iteration path. A workaround here is use [azuredevops_iteration](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/iteration) data source,  the `path` in `azuredevops_iteration_permissions` is ref from `azuredevops_iteration`, when you change the path in  https://dev.azure.com/, you change the `path` in the `azuredevops_iteration` to the latest value then apply the Terraoform command.

**Comment by drdamour** [comment]
@xuzhang3 the issue is that i cant even run a plan because the provider is incorrectly attempting to fetch based on current state file value of path and not the id.  I expected a destroy and create, but i couldn't even get that. Try it out and i think you’ll understand better the bug

**Comment by xuzhang3** [comment]
@drdamour when the iteration path changed out of Terraform, this is one result that might happen, I don't think this is a bug.  A potential workaround is remove the `azuredevops_iteration_permissions` from the `.tfstate` file manually, but you need to handle the permissions carefully since the granted permissions are not removed.
Also ADO should handle the errors gracefully, since current issue is the resource cannot be deleted and updated.

**Comment by drdamour** [comment]
@xuzhang3 why is the provider trying to fetch the iteration? Why cant it just use the id to fetch the permission?

**Comment by xuzhang3** [comment]
@drdamour Permission  configuration is based on ACL token and token is generated from the `path`

**Comment by drdamour** [comment]
Hm…i kinda get the limitation but i need to check the api docs a bit before i concede there arent any options currently.  My workaround was to modify the state to the new path, then i got the destroy and create I expected.  Again i WANT destroy and create..

compared to other providers crashing on a plan is ALWAYS a bug, even if it means a request has to be made upstream to expose an addition api service.  Crashing on a plan is devastating…even if the system has been modified outside terraform.  i havent seen that behaviour treated as “not a bug” in a long time

**Comment by drdamour** [comment]
@xuzhang3 did this actually get fixed?

**Comment by xuzhang3** [comment]
> [@xuzhang3](https://github.com/xuzhang3) did this actually get fixed?

yes,  fixed

**Comment by drdamour** [comment]
@xuzhang3 we happened to run our fiscal year archive and are still seeing this problem.  because state had an /fy25 path and that had been moved to /archive/fy25 plan failed....plan SHOULD NOT fail because of this.
