### ISSUE TITLE
How to add members to azuredevops_team_members using their email

### ISSUE THREAD

**Issue by vanmash** [microsoft/terraform-provider-azuredevops#442]
Hi,

how to add members using their email address?

Or how get to identifier like this "aad.NGJjZ***" based on email?

```hcl
resource "azuredevops_team" "team" {
  project_id     = azuredevops_project.project.id
  name           = "My Test Team"
  administrators = [
    <my ADD email>
  ]
  members = [
    <my ADD email>
  ]
}
```

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by vanmash** [comment]
Is it a correct answer to my _own_ question?

```hcl
resource "azuredevops_user_entitlement" "user" {
  principal_name = "someone@somewhere.com"
}
```

```hcl
resource "azuredevops_team_members" "team_members" {
  project_id = data.azuredevops_team.team.project_id
  team_id    = data.azuredevops_team.team.id
  mode       = "overwrite"
  members = [
    azuredevops_user_entitlement.user.descriptor,
  ]
}
```

**Comment by xuzhang3** [comment]
> Is it a correct answer to my _own_ question?
> 
> ```terraform
> resource "azuredevops_user_entitlement" "user" {
>   principal_name = "someone@somewhere.com"
> }
> ```
> 
> ```terraform
> resource "azuredevops_team_members" "team_members" {
>   project_id = data.azuredevops_team.team.project_id
>   team_id    = data.azuredevops_team.team.id
>   mode       = "overwrite"
>   members = [
>     azuredevops_user_entitlement.user.descriptor,
>   ]
> }
> ```
yes , you can use this configuration to add users to a team

**Comment by xuzhang3** [comment]
close this issue, feel free to open  another if you still have questions.
