### ISSUE TITLE
Add support for scheduled triggers in azuredevops_build_definition

### ISSUE THREAD

**Issue by Miouge1** [microsoft/terraform-provider-azuredevops#445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for scheduled triggers in `azuredevops_build_definition`

### New or Affected Resource(s)

* azuredevops_build_definition

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}
data "azuredevops_projects" "all" {
  state        = "wellFormed"
}

resource "azuredevops_build_definition" "sample_dotnetcore_app_release" {
  project_id = azuredevops_project.project.id
  name       = "Sample Build Definition"
  path       = "\\ExampleFolder"

  scheduled_trigger {
    use_yaml = true
    override {
      cron = "0 0 * * *" # cron syntax defining a schedule
      timezone = "UTC"
      always = false # only if there have been source code changes since the last successful scheduled run. The default is false.
      branch_filter {
        include = ["foo"]
        exclude = ["bar"]
      }
    }
  }

  repository {
    // ...
  }

}
```

### References

None

**Comment by xuzhang3** [comment]
@Miouge1  Did you try to handle the schedulers in `azuredevops_build_definition`？I would suggest handle it  through `yaml` file. You can manage the repo files by `azuredevops_git_repository_file` (**not released**) https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/git_repository_file.html.markdown

**Comment by Miouge1** [comment]
@xuzhang3 that might suitable for some instances, but in the use case I have the same `azure-pipelines.yml` is used by several build definitions (or pipelines) which are connected to different variable groups & triggers.

I currently adding the scheduled triggers manually, support in `azuredevops_build_definition` would appreciated.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open another is you still have questions.
