### ISSUE TITLE
Add support for imported git repos to Git Repository resource

### ISSUE THREAD

**Issue by EliiseS** [microsoft/terraform-provider-azuredevops#45]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/98
Originally created by @KeithJRome on *Fri, 11 Oct 2019 22:43:20 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for importing an existing git or tfvc repository during creation time for git_repository resources.
- See https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/git/client.go#L580

### New or Affected Resource(s)

* azuredevops_git_repository resource

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "main_project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  enable_tfvc        = False
  work_item_template = "Agile"
}

resource "azuredevops_git_repository" "main" {
  project        = azuredevops_project.main_project.id
  name           = "main-repo"
  default_branch = "master"
  initialization = {
    type         = "Import"
    type         = "GitHub"
    source       = "[repo url...]"
  }
}
```

### Acceptance Criteria

- [ ] When initialization.type = "Import", the newly created repository is initialized to a viable state using an Import Request (https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/git/client.go#L580)
- [ ] Include Unit tests for the new operation
- [ ] Acceptance (integration) test to validate repo creation/modification, following the patterns from the azuredevops_build_definition resource

### References

* Story spawned from design task #73

**Comment by edwardwu-servian** [comment]
Currently [`azuredevops_git_repository`](https://www.terraform.io/docs/providers/azuredevops/r/azure_git_repository.html) does not support importing a private git repo (one that requires authentication). Will this functionality be supported as well?

**Comment by AErmie** [comment]
Hey @EliiseS can you confirm that the initialization type of 'import' is supposed to work? 
I'm attempting to import a public repo from GitHub, but am receiving the following error

> Error: Error expanding repository resource data: Initialization strategy not implemented: Import

My code block looks like this:
```
resource "azuredevops_git_repository" "existing_repo" {
  project_id = azuredevops_project.adoproj.id
  name       = "Repo Import Test"
  initialization {
    init_type = "Import"
    source_type = "GitHub"
    source_url = "[GitHub repo URL]"
  }
}
```

NOTE: In your code example, you have 'type' set to 'GitHub' whereas the [public documentation](https://www.terraform.io/docs/providers/azuredevops/r/azure_git_repository.html) does not list 'GitHub' as a valid value option. It also does not provide an example of using 'Import' (which would be helpful). 

I have tried it using 'Git' and 'GitHub' as the Source Type.

**Comment by EliiseS** [comment]
@AErmie The import functionality has not been implemented yet. I've made a PR here to remove references to import: https://github.com/terraform-providers/terraform-provider-azuredevops/pull/108

**Comment by rswe** [comment]
@EliiseS could you confirm is this request will be implemented for Azure Repos (private)? thanks

**Comment by EliiseS** [comment]
@rswe It will eventually be added, but I'm not sure it's currently being worked on. @xuzhang3 are you working on this?

**Comment by xuzhang3** [comment]
@rswe  @EliiseS  Yes, I'm working on this feature.

**Comment by sdebruyn** [comment]
Looks like import itself is implemented, but authentication isn't

**Comment by xuzhang3** [comment]
Hi @sdebruyn   `azuredevops_resource_authorization`  is used for authorize the resources for project and pipelines.  [azuredevops_resource_authorization](https://www.terraform.io/docs/providers/azuredevops/r/resource_authorization.html), sorry for the broken page layout,  next release will fix the layout issue.

**Comment by xuzhang3** [comment]
Close this issues due to feature has been implemented.
