### ISSUE TITLE
Failure to create/update Azure DevOps service connection

### ISSUE THREAD

**Issue by ksommoxy** [microsoft/terraform-provider-azuredevops#453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.7 on windows_amd64

provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Affected Resource(s)

* `azuredevops_serviceendpoint_azuredevops`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  org_service_url            = "https://dev.azure.com/current"
  personal_access_token      = "(redacted)"
}

data "azuredevops_project" "project" {
  name = "Sample"
}

resource "azuredevops_serviceendpoint_azuredevops" "connection" {
  project_id            = data.azuredevops_project.project.id
  service_endpoint_name = "ADO-test"
  org_url               = "https://dev.azure.com/target"
  release_api_url       = "https://vsrm.dev.azure.com/target"
  personal_access_token = "(redacted)"
  description           = "Managed by Terraform"
}
```

### Debug Output

```
Terraform will perform the following actions:

  # azuredevops_serviceendpoint_azuredevops.connection will be created
  + resource "azuredevops_serviceendpoint_azuredevops" "connection" {
      + authorization              = (known after apply)
      + description                = "Managed by Terraform"
      + id                         = (known after apply)
      + org_url                    = "https://dev.azure.com/target"
      + personal_access_token      = (sensitive value)
      + personal_access_token_hash = (sensitive value)
      + project_id                 = "(REDACTED GUID)"
      + release_api_url            = "https://vsrm.dev.azure.com/target"
      + service_endpoint_name      = "ADO-test"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```
╷
│ Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'AZDOAPI' using authentication scheme 'Token'.
│
│   with azuredevops_serviceendpoint_azuredevops.connection,
│   on main.tf line 23, in resource "azuredevops_serviceendpoint_azuredevops" "connection":
│   23: resource "azuredevops_serviceendpoint_azuredevops" "connection" {
│
╵
```

### Expected Behavior

Successful apply

### Actual Behavior

Fail to apply

### Steps to Reproduce

1. `terraform init` 
2. `terraform apply`

### Important Factoids

Importing a service connection is successful. Attempting to update an existing fails with the same error.

**Comment by xuzhang3** [comment]
@ksommoxy  You need install [Configurable Pipeline Runner](https://marketplace.visualstudio.com/items?itemName=CSE-DevOps.RunPipelines) for your organization.

**Comment by ksommoxy** [comment]
Installing the extension resolved the issue. Tested both creating a new service connection and updating the created service connection. Thanks for updating the documentation.

**Comment by maxhillaert** [comment]
Hi.  Can I ask why we need this extension using the TF provider, but not when we add a connection to Azure Repos organisation via web ui?  Or is this a different service connection? 

I'm basically trying to create a service connection fit for:

    - repository: templates
      type: git
      name: foo/bar
      ref: refs/tags/v2022.3.6
      endpoint: <serviceconnection>

**Comment by xuzhang3** [comment]
@maxhillaert `azuredevops_serviceendpoint_azuredevops` is duplicate with `azuredevops_serviceendpoint_runpipeline`, I will deprecate this resource. TFS service connection is not supported, I have reopened #339
