### ISSUE TITLE
Default agent_pool_name should no longer be "Hosted Ubuntu 1604"

### ISSUE THREAD

**Issue by jstock** [microsoft/terraform-provider-azuredevops#455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ubuntu 16.04 Azure-hosted build agent pools are no longer supported as of September 20, 2021: https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-187-update#ubuntu-1604-will-be-removed-from-microsoft-hosted-pools-in-september-2021

When managing build definitions and omitting the agent pool, it defaults the build to be associated with this agent pool which is no longer supported.

### New or Affected Resource(s)

* azuredevops_agent_pool

**Comment by xuzhang3** [comment]
The default agent pool name will rename to `Azure Pipelines` 
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#default-agent-pools

**Comment by xuzhang3** [comment]
close this issue, feel free to open  another if you still have questions.
