### ISSUE TITLE
Decouple necessity of Agent Pools from Agent Queue resource

### ISSUE THREAD

**Issue by sezginceyhan** [microsoft/terraform-provider-azuredevops#456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azuredevops_agent_queue` (ADO project-level) resource is managed with the reference to the id of an agent pool. 

Agent pools on organizational level are managed on collection level with permissions like "Project Collection Administrator", security roles etc. So without these kind of permissions, we are not able to create Agent Pools and therefore also not Queue's.

The current used Azure DevOps Rest API also offers the possibility to create Agent Queue's without necessity of pre-existing Agent Pool's for Project-level Administrators (Agent Pool will be created on the fly). 

So I would like to propose to change  `azuredevops_agent_queue`  with an argument like `queue_name` to manage queues with project-level permissions only. As a queue on project-level is simply a connection to a pool on org-level, the reference is still desired for pre-existing pools, but should be optional or mutually exclusive.

### New or Affected Resource(s)

* azuredevops_agent_queue

#### Current

```hcl
resource "azuredevops_agent_queue" "queue" {
  project_id    = azuredevops_project.project.id
  agent_pool_id = data.azuredevops_agent_pool.pool.id   # <-- currently required by tf-azdo-provider,
}
```

#### Proposed
```hcl
resource "azuredevops_agent_queue" "queue" {
  project_id    = azuredevops_project.project.id
  queue_name = "name-of-the-queue-in-ado-project"
  agent_pool_id = data.azuredevops_agent_pool.pool.id   # <-- optional or mutually exclusive
}
```

Example of Restcall
```bash
curl -u :$AZURE_DEVOPS_EXT_PAT -H "Content-Type: application/json" -X POST 
https://dev.azure.com/{organization}/{project}/_apis/distributedtask/queues?api-version=5.1-preview.1 --data '{"name":"api-created-queue"}'
```

### References

ADO Rest API Refrence to [add queues](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/queues/add?view=azure-devops-rest-5.1)

[Ref to code of resource](https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/taskagent/resource_agent_queue.go#L60)

**Comment by drdamour** [comment]
ran into this recently, and totally agree the web ux lets me createa  queue and then some how magically a pool is created even though i can't create a pool directly.  would like the same in terraform.

**Comment by BHoggs** [comment]
Hi, this can be closed now as my PR has been merged
