### ISSUE TITLE
Pipeline Permissions for Service Connection

### ISSUE THREAD

**Issue by sandrom** [microsoft/terraform-provider-azuredevops#458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to be able to set individual Pipeline Permissions for Service Connections like in the UI

<img width="1273" alt="Screenshot 2021-10-04 at 15 26 24" src="https://user-images.githubusercontent.com/496479/135859566-b5b67148-c52f-4754-8ceb-81d7ca3a02a0.png">

Is this a planned feature or am I missing something existing here?

**Comment by xuzhang3** [comment]
@sandrom `azuredevops_resource_authorization` can do the authorization. 
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/resource_authorization

**Comment by drdamour** [comment]
@xuzhang3 i think this one should be closed, it has been answered
