### ISSUE TITLE
Change default from Hosted Ubuntu 1604 (unsupported as of 10/18/2021) to Azure Pipelines

### ISSUE THREAD

**Issue by gtiguy92** [microsoft/terraform-provider-azuredevops#465]
I'd like to suggest that the default agent pool name be changed from Hosted Ubuntu 1604 which is going to be retired on 10/18/2021 (https://github.com/actions/virtual-environments/issues/3287)

https://github.com/microsoft/terraform-provider-azuredevops/blob/b00f7842e49eef559addae4c3f11f6ce09356654/azuredevops/internal/service/build/resource_build_definition.go#L141

**Comment by xuzhang3** [comment]
duplicate with #455
