### ISSUE TITLE
Importing repository causes repository to be deleted on subsequent plan

### ISSUE THREAD

**Issue by roryprimrose** [microsoft/terraform-provider-azuredevops#467]
I have tried to import an existing uninitialized repository using a project name and repository name. The repository is correctly identified and put into state. A subsequent plan/apply attempts to delete the repository because the initialization.init_type is not populated in state.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0      
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```
resource "azuredevops_git_repository" "repository" {
  for_each   = { for mappedRepository in local.repositories : mappedRepository.repository.key => mappedRepository }
  project_id = azuredevops_project.project[each.value.projectKey].id
  name       = each.value.repository.name
  initialization {
    init_type = "Uninitialized"
  }
}
```

### Debug Output

```
  # azuredevops_git_repository.repository["2945c910-5fea-41dd-91c6-f1addafa75b8"] must be replaced
-/+ resource "azuredevops_git_repository" "repository" {
      + default_branch = (known after apply)
      ~ id             = "693f28c7-5a62-4ddd-92a4-70ac577cc80d" -> (known after apply)
      ~ is_fork        = false -> (known after apply)
        name           = "MyRepo"
      ~ remote_url     = "https://MyOrg@dev.azure.com/MyOrg/MyProject/_git/MyRepo" -> (known after apply)
      ~ size           = 0 -> (known after apply)
      ~ ssh_url        = "git@ssh.dev.azure.com:v3/MyOrg/MyProject/MyRepo" -> (known after apply)
      ~ url            = "https://dev.azure.com/MyOrg/2c34e648-bd1a-452c-9287-73ec7efdb1f0/_apis/git/repositories/693f28c7-5a62-4ddd-92a4-70ac577cc80d" -> (known after apply)
      ~ web_url        = "https://dev.azure.com/MyOrg/MyProject/_git/MyRepo" -> (known after apply)
        # (1 unchanged attribute hidden)

      + initialization {
          + init_type = "Uninitialized" # forces replacement
        }
    }

```

### Expected Behavior

Importing a repository should not cause the repository to then be immediate deleted on plan/apply regardless of initialization state.

I'm guessing that the solution here would be related to not including initialization state when comparing current configuration of the repository against terraform state. I have no idea if this is even possible. Essentially the comparison of initialization state on plan/apply means that you can never import an existing repository into state and then apply a configuration over the existing repository without it being deleted.

### Actual Behavior

Repository is deleted because the initialization type does not match state

### Steps to Reproduce

1. Create a repository
2. `terraform import -var-file dev.tfvars 'azuredevops_git_repository.repository[\"2945c910-5fea-41dd-91c6-f1addafa75b8\"]' "MyProject/MyRepo"`
3. `terraform plan`

### References

* #0000

**Comment by roryprimrose** [comment]
I found the solution when looking at the notes provided on plan. You can ignore changes to the initialization attribute.

```
resource "azuredevops_git_repository" "repository" {
  for_each       = { for mappedRepository in local.repositories : mappedRepository.repository.key => mappedRepository }
  project_id     = azuredevops_project.project[each.value.projectKey].id
  name           = each.value.repository.name
  default_branch = "refs/heads/main"
  initialization {
    init_type = "Uninitialized"
  }
  lifecycle {
    ignore_changes = [
      # Ignore changes to initialization to support importing existing repositories
      # Given that a repo now exists, either imported into terraform state or created by terraform,
      # we don't care for the configuration of initialization against the existing resource
      initialization,
    ]
  }
}
```

**Comment by xuzhang3** [comment]
@roryprimrose  The `initialization` is not part of the API or the service configuration. This a additional configuration introduce by ADO provider, service won't return this  configuration. This is why the import operation will force recreate the reps(`initialization` only exist in the TF script).  A workaround to ignore this error is same as you did: 
```
lifecycle {
    ignore_changes = [
      initialization,
    ]
```
