### ISSUE TITLE
azuredevops_project_permissions statefile not updated correctly on new resource creation

### ISSUE THREAD

**Issue by kjgen** [microsoft/terraform-provider-azuredevops#471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Affected Resource(s)

* `azuredevops_project_permissions`

### Terraform Configuration Files

```hcl
data "azuredevops_project" "p" {
  for_each = var.projects
  name = each.key
}

data "azuredevops_users" "my_user" {
  principal_name = "<user_email>"
}

resource "azuredevops_group" "main" {
  for_each = data.azuredevops_project.p

  scope        = each.value.id
  display_name = "Test"
  description  = "Test"

  members = [
    one(data.azuredevops_users.my_user.users).descriptor
  ]
}

resource "azuredevops_project_permissions" "view_project_info" {
  for_each = data.azuredevops_project.p

  project_id = each.value.id
  principal  = azuredevops_group.main[each.key].id
  permissions = {
    GENERIC_READ = "Allow"
  }
}
```

### Debug Output

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azuredevops_project_permissions.view_project_info["ProjectA"] has been changed
  ~ resource "azuredevops_project_permissions" "view_project_info" {
        id          = "$PROJECT:vstfs:///Classification/TeamProject/<redacted>/vssgp.<redacted>"
      ~ permissions = {
          ~ "GENERIC_READ" = "notset" -> "allow"
        }
        # (3 unchanged attributes hidden)
    }
  # azuredevops_project_permissions.view_project_info["ProjectB"] has been changed
  ~ resource "azuredevops_project_permissions" "view_project_info" {
        id          = "$PROJECT:vstfs:///Classification/TeamProject/<redacted>/vssgp.<redaced>"
      ~ permissions = {
          ~ "GENERIC_READ" = "notset" -> "allow"
        }
        # (3 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```

### Expected Behavior

State file should have the correct permission saved to it. It should already have the `GENERIC_READ = Allow`

### Actual Behavior

State file has the `GENERIC_READ` set to `notset` even though in Azure DevOps, the settings were provisioned correctly and are set to `Allow`.

### Steps to Reproduce

1. Have the resources not exist.
2. Run terraform plan & apply. 
3. Once it finishes provisioning, run terraform plan again and terraform will indicate the state file is not up-to-date.

### Important Factoids

To avoid any permission issues with PAT and permissions in Azure DevOps, we tested this with a user having full permissions.

Note: A similar issue is happening with `azuredevops_git_permissions` but isn't consistent between multiple devops projects. Might both be related to an underlying issue somewhere in the code.

**Comment by xuzhang3** [comment]
@kjgen  The `azuredevops_group.scope` is not set,  the group will be created under the organization-level by default,  this is why the permission setting failed. Set the `azuredevops_group.scope` to the project should work.

**Comment by kjgen** [comment]
@xuzhang3 In the examples I posted in the description of the bug, the scope is already defined `scope = each.value.id` which is the IDs of the projects. The configuration in azure devops is updated correctly, but if I look at the state file, the project_permissions `GENERIC_READ` is set to `not set` instead of `allow`.

**Comment by xuzhang3** [comment]
@kjgen  Thanks for the feedback.  I can randomly reproduce this error,  the root issue seems the read operation get the old value, not the latest settings.

**Comment by roryprimrose** [comment]
This may be a timing issue. Azure DevOps seems to work on eventual consistency so if you make a change to something like a permission or policy then read it from the rest api straight away, you may be returned the old value. In our experience it can be up to 10 seconds before the rest api returns the new value.

**Comment by tmeckel** [comment]
@kjgen  @roryprimrose @xuzhang3 with PR #249  I introduced code which will wait for Azure DevOps to persist changes to permissions. I hope this will fix this issue here as well.

https://github.com/microsoft/terraform-provider-azuredevops/pull/249#issuecomment-975683405

**Comment by xuzhang3** [comment]
close this issue, feel free to open  another if you still have questions.
