### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by bb-josh** [microsoft/terraform-provider-azuredevops#474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
terraform -v
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7
```

### Affected Resource(s)

`azuredevops_project`

### Terraform Configuration Files

```
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "0.1.7"
    }
  }
}

provider "azuredevops" {
  org_service_url       = "https://dev.azure.com/${var.organization}"
  personal_access_token = var.personal_access_token_full_access
}

resource "azuredevops_project" "terraform_ado_project" {
  name               = var.project_name
  description        = var.description
  visibility         = var.visibility
  version_control    = var.version_control
  work_item_template = var.work_item_template
}
```

### Debug Output

[Gist_0](https://gist.github.com/bb-josh/bf4e7c5e414f23126e6c6eed871908d1)
[Gist_1](https://gist.github.com/bb-josh/7b7707b64257d1b4c6ac3e9b107dc1cb)

### Expected Behavior

**NOTE: This issue appears inconsistently. With the same Terraform configuration and the same commands, this configuration will sometimes apply and destroy as expected. Other-times not.**

Applying this plan should consistently create a project under my organization in Azure Devops *and* consistently be tracked in the Terraform state.

### Actual Behavior

**NOTE: This issue appears inconsistently. With the same Terraform configuration and the same commands, this configuration will sometimes apply and destroy as expected. Other-times not.**

1. Applying this plan led to Terraform throwing the error: 
```Error: Provider produced inconsistent result after apply```

2. The project *is* created and viewable in the UI

3. When running `apply` a second time Terraform throws this error indicating it is not tracking the resource state: 
```Error: Error creating project: TF200019: The following project already exists on the Azure DevOps Server: TEST_PROJECT_00. You cannot create a new project with the same name as an existing project. Provide a different name.```
4. `terraform destroy` (as expected) does not have any trackable resources to destroy

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. `terraform destroy`

### References

Related issues:
* [Issue 279](https://github.com/microsoft/terraform-provider-azuredevops/issues/279)
* [Issue 266](https://github.com/microsoft/terraform-provider-azuredevops/issues/266)
* [Issue 215](https://github.com/microsoft/terraform-provider-azuredevops/issues/215)
* [Issue 145](https://github.com/microsoft/terraform-provider-azuredevops/issues/145)

Related PRs:
* [PR 273](https://github.com/microsoft/terraform-provider-azuredevops/pull/273)

**Comment by xuzhang3** [comment]
@bb-josh  Thanks for the feedback.  I can reproduce this error by manually change the service response.  The project has been created but when provider try get the project, service response indicate that this project was not found. In this scenario,  the ADO provider will set resource ID to empty string to notify Terraform that this resource should be deleted from the state file. One way to fix this issue is enhance the get project logic,  a retry logic should be helpful here.

**Comment by xuzhang3** [comment]
close this issue, feel free to open  another if you still have questions.
