### ISSUE TITLE
Renaming subscription is probably clearing or changing secret to wrong value.

### ISSUE THREAD

**Issue by mlomat** [microsoft/terraform-provider-azuredevops#476]
Hello team,

It looks like that azuredevops_serviceendpoint_azurerm has a bug, when trying to change subscription name. When I change value from "Sample Subscription" to "Sample Subscription Test", it will change value in devops, but connection service will stop working, because it looks like it's nullifying or changing value for secret.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

terraform = 1.0.9
azure devops version = "0.1.7"
### Affected Resource(s)

* `azuredevops_serviceendpoint_azurerm`

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "project" {
  name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "Sample AzureRM"
  description = "Managed by Terraform" 
  credentials {
    serviceprincipalid  = "00000000-0000-0000-0000-000000000000"
    serviceprincipalkey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
  azurerm_spn_tenantid      = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_id   = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_name = "Sample Subscription"
}
```

### Expected Behavior

1. It shouldn't touch secret value or should set it to this same value as it was on the beginning. Or 
2. It should destroy and create new object.

### Actual Behavior

When you go to Service Connection after renaming subscription name in Azure Devops and click verify it's failing. ( before rename it's working fine) 
![image](https://user-images.githubusercontent.com/7577121/138610614-e05406b5-59b1-4b3a-900f-888601fc834c.png)

### Steps to Reproduce

1. Apply terraform: 
```hcl
resource "azuredevops_project" "project" {
  name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "Sample AzureRM"
  description = "Managed by Terraform" 
  credentials {
    serviceprincipalid  = "00000000-0000-0000-0000-000000000000"
    serviceprincipalkey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
  azurerm_spn_tenantid      = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_id   = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_name = "Sample Subscription"
}
```

2. Apply terraform with renamed azurerm_subscription_name
```hck
resource "azuredevops_project" "project" {
  name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "Sample AzureRM"
  description = "Managed by Terraform" 
  credentials {
    serviceprincipalid  = "00000000-0000-0000-0000-000000000000"
    serviceprincipalkey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
  azurerm_spn_tenantid      = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_id   = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_name = "Sample Subscription TEST"
}
```

**Comment by xuzhang3** [comment]
@mlomat The subscription name is part of the credential. Since the subscription name has been changed, the credential is used to access the new subscription `Sample Subscription TEST`,  the verify will failed due the SPN does not have the permission to access the new subscription `Sample Subscription TEST`.

**Comment by mlomat** [comment]
@xuzhang3  Sorry, but you are wrong, it's not a part of credential. Subscription name is only alias. Azure does not use subscription name for anything. Credentials are Client_Id, Secret and subscription_id. You can put whatever you want in azurerm_subscription_name. From the other perspective you can assign rights to multiple subscriptions and then how you will access others?

**Comment by xuzhang3** [comment]
@mlomat The subscription name is required by ARM service connection. Normally, only clietnID, secret and subID is required, but for ARM service connection , it's different, the subscription name is required. You should create different service connection for different subscription if the SPN only have one subscription access permission.  Also, you can grant the SPN the permissions to access different subscriptions, then you can rename the subscription name, the validation should pass.

**Comment by mlomat** [comment]
@xuzhang3 I will agree that it's require, but value is not used for any interesting purpose. I tested it. If you create new service connection with valid clientId, secret and subId and with some fake subscription name it will still pass validation ;) 

E.g. You will create new service connection with clientId, secret and subId and with sub name "Sample Subscription Test" ( even you don't have such name in your tenant) Validation will work.  

If you change name from "Sample Subscription Test" to "Sample Subscription" it will fail validation, because what I am suspecting provider is also changing value for secret.

**Comment by mlomat** [comment]
+ I forget to mention, that I tested it from DevOps API, where it's working without any issue. So it's some bug in Terraform.
