### ISSUE TITLE
Add support for immediate build expiration when main branch is updated

### ISSUE THREAD

**Issue by Danielkem** [microsoft/terraform-provider-azuredevops#481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When assigning a value to `valid_duration` in [branch policy build validation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/branch_policy_build_validation) there is no way to set it to expire immediately when the main branch is updated. It would be helpful to be able to do this since it already is available as an option when defining the build expiration via the GUI.

I propose making the value -1 for `valid_duration` represent that the build expires immediately when main branch is updated since 0 already is defined to represent that the build never expires.

### New or Affected Resource(s)

* azuredevops_branch_policy_build_validation

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_build_validation" "p" {
  project_id = azuredevops_project.p.id

  settings {
    build_definition_id = azuredevops_build_definition.b.id
    valid_duration      = -1 // Let -1 represent the requested feature since 0 is defined to represent that the build never expires
    display_name        = "Don't break the build!"

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = azuredevops_git_repository.r.default_branch
      match_type     = "Exact"
    }
  }
}
```

**Comment by Danielkem** [comment]
Looks like setting `QueueOnSourceUpdateOnly` to false and then setting `valid_duration` to 0 does what this issue aimed to accomplish.

**Comment by lindhe** [comment]
I think this should be better documented.
