### ISSUE TITLE
0.1.8 release?

### ISSUE THREAD

**Issue by avgalani** [microsoft/terraform-provider-azuredevops#487]
I've looked around to see if there's a release schedule, but I haven't been able to find any. I'm starting a new terraform project for managing our Azure DevOps organisation and I need to use the `resource_git_repository_file`. I see this is available in master, but not on the latest released version of the provider. 
When could we expect the new release? I am just looking for an approximate date, so I can set expectations accordingly

Thank you!

**Comment by xuzhang3** [comment]
@avgalani   working on it #488

**Comment by roryprimrose** [comment]
Any idea when this version will be on the Terraform registry?

**Comment by xuzhang3** [comment]
Normally Terraform registry will auto-sync the latest release from GH release.   Working with the Hashicorp support team.

**Comment by xuzhang3** [comment]
@roryprimrose  Terraform registry have sync the latest release v0.1.8 now.
