### ISSUE TITLE
Unable to use two instances of the provider in the same module

### ISSUE THREAD

**Issue by panasonixme** [microsoft/terraform-provider-azuredevops#490]
Hi guys, After digging for a long time, I have no other optio but to open a bug here. I'm trying to create to instances of the provider in order to be able to create repositories in one instance and initialize the repo based on a repo content on another Azure Devops Service organization. Despite my effort, I keep receiving the plan output available below.
Could you please help ?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.26.1
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Affected Resource(s)

* `azuredevops_*`

### Terraform Configuration Files

```
terraform {
  backend "remote" {
    organization = "..."
    workspaces {
      name = "..."
    }
  }
  required_providers {
    tfe = {
      version = "~> 0.26.0"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.7"
    }
  }
}
provider "azuredevops" {
  alias                 = "Project"
  org_service_url       = local.azure_devops_org_service_url
  personal_access_token = var.azure_devops_pat
}
provider "azuredevops" {
  alias                 = "NSoIT"
  org_service_url       = "whatever"
  personal_access_token = "mypat"
}
```

### Debug Output
```Initializing Terraform configuration...

│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/microsoft/azuredevops" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
╵
╷
│ Error: the personal access token is required
│ 
│   with provider["registry.terraform.io/microsoft/azuredevops"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
╷
│ Error: invalid character '<' looking for beginning of value
│ 
│   with provider["registry.terraform.io/microsoft/azuredevops"].NSoIT,
│   on login.tf line 32, in provider "azuredevops":
│   32: provider "azuredevops" {
│ 
╵
```
------------------------------------------------------------------------
### Panic Output

###Expected behavior
The 2 instances of the provider should be up and running

### Actual Behavior
The plan doesn't even go through...

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by roryprimrose** [comment]
That error about < usually means the rest api call to azdo is returning html rather than json. Usually happens when there is an auth issue. 

Have you tried using Fiddler to see what the traffic is on the wire?

**Comment by panasonixme** [comment]
Well, after further investigations, it seems that I was having a DNS issue preventing to resolve the Devops ORG URL properly.
Closing the ticket, sorry...
