### ISSUE TITLE
Pipelines Environments

### ISSUE THREAD

**Issue by romanzdk** [microsoft/terraform-provider-azuredevops#496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

TF Resource for creating Azure DevOps Environments.

### New or Affected Resource(s)

* azuredevops_environments

### References

https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/add?view=azure-devops-rest-6.0

**Comment by avishnyakov** [comment]
Might be duplicate, there is a long discussion here -  https://github.com/microsoft/terraform-provider-azuredevops/issues/143
