### ISSUE TITLE
Provider uses case sensitive comparison on permission based resources 

### ISSUE THREAD

**Issue by roryprimrose** [microsoft/terraform-provider-azuredevops#502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8

### Affected Resource(s)

* `azuredevops_area_permissions`

Likely this impacts all permission based resources.

### Terraform Configuration Files

```hcl
resource "azuredevops_area_permissions" "project_workitemeditor" {
  for_each   = { for item in local.project_workitem_editors : format("%s|%s", item.project.key, item.member) => item }
  project_id = module.azdo_project[each.value.project.key].project.id
  principal  = local.subjects_by_lookup[lower(each.value.member)].descriptor
  replace    = false
  path       = "/"
  permissions = {
    GENERIC_READ    = "Allow"
    WORK_ITEM_READ  = "Allow"
    WORK_ITEM_WRITE = "Allow"
  }
}
```

### Debug Output

```
  # azuredevops_area_permissions.project_workitemeditor["14aae2a0-84b3-4cd6-ab6e-d20f8361893c\\<snip>"] must be replaced
-/+ resource "azuredevops_area_permissions" "project_workitemeditor" {
      ~ id          = "vstfs:///Classification/Node/<snip>MjI4MDUxMzA4NS0zMTQ2NjM4MDU3" -> (known after apply)
      ~ permissions = {
          ~ "GENERIC_READ"    = "allow" -> "Allow"
          ~ "WORK_ITEM_READ"  = "allow" -> "Allow"
          ~ "WORK_ITEM_WRITE" = "allow" -> "Allow"
        }
      ~ principal   = "vssgp.<snip>MjI4MDUxMzA4NS0zMTQ2NjM4MDU3" -> (known after apply) # forces replacement
        # (3 unchanged attributes hidden)
    }
```

### Expected Behavior

No change should have been identified in the plan.

### Actual Behavior

Existing permission is changed/destroyed.

### Steps to Reproduce

1. `terraform plan`

The results here are inconsistent. Sometimes the plan identifies no changes other times it wants to change the permissions. I suspect that sometimes the AzDO REST API returns `allow` or `Allow` but the provider is doing a case sensitive match when it should be insensitive.

### References

* #0000

**Comment by tmeckel** [comment]
@roryprimrose permissions in Azure DevOps are `bitsets` and don't use the `allow`, `deny` or `notset` strings. Those strings are only used inside the provider. We're already using a case insensitive match to compare the permission settings:

![image](https://user-images.githubusercontent.com/14177833/147086982-815c5900-ab6a-4ca9-bd17-d722020975d2.png)
 
In addition the acceptances tests for the `azuredevops_area_permissions` resource are using the capital letter notation as in your example and they pass without any errors:

![image](https://user-images.githubusercontent.com/14177833/147088260-ad87519c-97d4-4fe4-8be1-1740e44afcac.png)

![image](https://user-images.githubusercontent.com/14177833/147088389-6f67ed75-4428-4594-9550-4568346578a6.png)

I'm therefore a bit surprised that you are experiencing the problem described.
