### ISSUE TITLE
Add support for ServiceHook permission namespace

### ISSUE THREAD

**Issue by larsmaesmosadexehealth** [microsoft/terraform-provider-azuredevops#504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I would like to set permissions in de ServiceHooks namespace with terraform

### New or Affected Resource(s)

None

### Potential Terraform Configuration

```hcl
resource "azuredevops_servicehook_permissions" "servicehook_permissions" {
  project_id = var.project_id
  principal  = var.principal_id
  permissions = {
    VIEW_SUBSCRIPTIONS = "allow"
    EDIT_SUBSCRIPTIONS = "allow"
    DELETE_SUBSCRIPTIONS = "allow"
    PUBLISH_EVENTS = "allow"
  }
}
```

**Comment by tmeckel** [comment]
@xuzhang3 very low hanging fruit 😁 Implemented with PR #506

**Comment by tmeckel** [comment]
@martenvd I saw you files a PR for this new resources as well. You're missing the required acceptance tests. If you like you can copy those from my PR. I can close my own PR then 😀

**Comment by martenvd** [comment]
@tmeckel I didn't see your PR yet, but thank you for the test file! I have included it in my own PR now.

**Comment by tmeckel** [comment]
@martenvd This is my PR -> #506

**Comment by martenvd** [comment]
@tmeckel Thank you! The tests were succesful in my PR [#505](https://github.com/microsoft/terraform-provider-azuredevops/pull/505) 😊
