### ISSUE TITLE
Can not create fork repository

### ISSUE THREAD

**Issue by patr00n** [microsoft/terraform-provider-azuredevops#52]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.28
provider.azuredevops 0.0.1

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

data "azuredevops_project" "test" {
  project_name = "Test Project"
}

resource "azuredevops_git_repository" "repo" {
  project_id = data.azuredevops_project.test.id
  name       = "test-repo"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_git_repository" "fork-repo" {
  project_id = data.azuredevops_project.test.id
  name       = "fork-test-repo"
  parent_id  = azuredevops_git_repository.repo.id
}
```

### Debug Output
https://gist.github.com/patr00n/f2f7e1057d90d70b411c02148d12ef03

### Expected Behavior
New repo was created

### Actual Behavior
Error

### Steps to Reproduce

1. `terraform plan`

**Comment by xuzhang3** [comment]
Hi @patr00n  Thanks for your feed back. You  can change you config like this :
```
provider "azuredevops" {
  version = ">= 0.0.1"
}

data "azuredevops_project" "test" {
  project_name = "Test Project"
}

resource "azuredevops_git_repository" "repo" {
  project_id = data.azuredevops_project.test.id
  name       = "test-repo"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_git_repository" "fork-repo" {
  project_id = data.azuredevops_project.test.id
  name       = "fork-test-repo"
  parent_repository_id  = azuredevops_git_repository.repo.id
  initialization {
    init_type = "Clean"
  }
}
```

`parent_id  ` is not a valid configure in `azuredevops_git_repository`. 
**Attention**
You need specify the `initialization`  configuration in `azuredevops_git_repository`, otherwise  Terraform may crash. This is a know issue in azuredevops, we will fix this soon.

**Comment by patr00n** [comment]
Thanks for your quick reply!
It works with `parent_repository_id`. But [documentation](https://www.terraform.io/docs/providers/azuredevops/r/azure_git_repository.html#create-fork-of-another-azure-devops-git-repository) says `parent_id`. It would be nice to fix.

**Comment by EliiseS** [comment]
I've fixed the docs here: https://github.com/terraform-providers/terraform-provider-azuredevops/pull/55
