### ISSUE TITLE
Error when trying to import existing git repo

### ISSUE THREAD

**Issue by patr00n** [microsoft/terraform-provider-azuredevops#53]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v0.12.28
provider.azuredevops 0.0.1

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

data "azuredevops_project" "test" {
  project_name = "ADO Migration Test"
}

data "azuredevops_git_repositories" "repo" {
  project_id = data.azuredevops_project.test.id
  name       = "test-repo"
}

resource "azuredevops_git_repository" "repo-tf" {
  project_id = data.azuredevops_project.test.id
  name       = "test-repo-tf"
  initialization {
    init_type = "Import"
    source_url = data.azuredevops_git_repositories.repo.repositories[0].remote_url
  }
}
```

### Debug Output
```
2020/07/03 14:45:33 [DEBUG] azuredevops_git_repository.repo-tf: applying the planned Create change
2020-07-03T14:45:33.246+0300 [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 2020/07/03 14:45:33 [DEBUG] expandGitRepository: ID is empty (not set)
2020/07/03 14:45:33 [DEBUG] azuredevops_git_repository.repo-tf: apply errored, but we're indicating that via the Error pointer rather than returning it: Error expanding repository resource data: Initialization strategy not implemented: Import
2020/07/03 14:45:33 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error expanding repository resource data: Initialization strategy not implemented: Import
2020/07/03 14:45:33 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error expanding repository resource data: Initialization strategy not implemented: Import

Error: Error expanding repository resource data: Initialization strategy not implemented: Import

  on main.tf line 14, in resource "azuredevops_git_repository" "repo-tf":
  14: resource "azuredevops_git_repository" "repo-tf" {
```

### Expected Behavior
Creating new repo from an existing source repo

### Actual Behavior
Error

### Steps to Reproduce

1. `terraform apply`

**Comment by xuzhang3** [comment]
Hi @patr00n Thanks for opening this issue.  Import Git repository has not been implemented yet. Sorry the document mislead you.  I will close this issue as this issue has been opened in #45
