### ISSUE TITLE
unable to resolve UUID's when using for_each

### ISSUE THREAD

**Issue by smholvoet** [microsoft/terraform-provider-azuredevops#533]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8
```
### Affected Resource(s)

* `azuredevops_git_permissions`

### Terraform Configuration Files

```hcl
resource "azuredevops_git_permissions" "git-permissions-test" {
  for_each = toset( ["repo1","repo2","repo3"] )
  project_id    = "azuredevops_git_repository.${each.value}.project_id"
  repository_id = "azuredevops_git_repository.${each.value}.id"
  principal     = azuredevops_group.my-group.id
  permissions   = {
    PullRequestBypassPolicy = "NotSet"
    PolicyExempt            = "NotSet"
    GenericContribute       = "Allow"
    PullRequestContribute   = "Allow"
    CreateBranch            = "NotSet"
    CreateTag               = "Allow"
    DeleteRepository        = "NotSet"
    EditPolicies            = "NotSet"
    ForcePush               = "Allow"
    ManageNote              = "Allow"
    ManagePermissions       = "NotSet"
    GenericRead             = "Allow"
    RemoveOthersLocks       = "Allow"
    RenameRepository        = "NotSet"
  }
}
```

### Expected Behavior

Assign the specified permissions to each repository mentioned in the `for_each = toset( ["repo1","repo2","repo3"] )` section and create 3 new resources.

Doing the exact same thing (with the `for_each` element) with a different resource (e.g. `azuredevops_branch_policy_work_item_linking` works without any issues:

```hcl
resource "azuredevops_branch_policy_work_item_linking" "work-item-link-test" {
  for_each = toset( ["repo1","repo2","repo3"] )
  project_id = azuredevops_project.project.id

  enabled  = true
  blocking = true

  settings {

    scope {
      repository_id  = "azuredevops_git_repository.${each.value}.id"
      repository_ref = "azuredevops_git_repository.${each.value}.default_branch"
      match_type     = "Exact"
    }
  }
}
```

### Actual Behavior

It loops through all repo's but fails to resolve the `project_id` and `repository_id` properties when using `${each.value}` instead of a literal value:

```
│ Error: expected "project_id" to be a valid UUID, got azuredevops_git_repository.repo1.project_id
│
│   with azuredevops_git_permissions.git-permissions-test["repo1"],
│   on git-permissions.tf line 1, in resource "azuredevops_git_permissions" "git-permissions-test":
│    1: resource "azuredevops_git_permissions" "git-permissions-test": {
│
╵
╷
│ Error: expected "repository_id" to be a valid UUID, got azuredevops_git_repository.repo1.id
│
│   with azuredevops_git_permissions.git-permissions-test["repo1"],
│   on git-permissions.tf line 1, in resource "azuredevops_git_permissions" "git-permissions-test":
│    1: resource "azuredevops_git_permissions" "git-permissions-test": {
```

### Steps to Reproduce

1. `terraform plan`

**Comment by xuzhang3** [comment]
@smholvoet  You should use the `project ID/repo ID` not there names.

**Comment by smholvoet** [comment]
@xuzhang3 I'm not sure what you mean?

The `azuredevops_git_permissions` resource expects the `project_id` and `repository_id` [attributes](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_permissions#argument-reference) of a git repo.

Using the name of a repo (e.g. `my-repository-name`) works just fine when I declare the resource like this:

```hcl
resource "azuredevops_git_permissions" "git-permissions-test" {
  project_id    = azuredevops_git_repository.my-repository-name.project_id
  repository_id = azuredevops_git_repository.my-repository-name.id
  principal     = azuredevops_group.my-group.id
  permissions   = {
    PullRequestBypassPolicy = "NotSet"
    PolicyExempt            = "NotSet"
    GenericContribute       = "Allow"
    PullRequestContribute   = "Allow"
    CreateBranch            = "NotSet"
    CreateTag               = "Allow"
    DeleteRepository        = "NotSet"
    EditPolicies            = "NotSet"
    ForcePush               = "Allow"
    ManageNote              = "Allow"
    ManagePermissions       = "NotSet"
    GenericRead             = "Allow"
    RemoveOthersLocks       = "Allow"
    RenameRepository        = "NotSet"
  }
}
```

But when I try to the same for multiple repo's in a `for_each`, it fails. 

My guess is that is has to do with the quotation marks. The above example which doesn't use `for_each` will also fail when I place the attributes in between quotation marks (which I need in order for the `for_each` block to get the value of `${each.value}`).

✅

```hcl
  project_id    = azuredevops_git_repository.my-repository-name.project_id
  repository_id = azuredevops_git_repository.my-repository-name.id
```


❌

```hcl
  project_id    = "azuredevops_git_repository.my-repository-name.project_id"
  repository_id = "azuredevops_git_repository.my-repository-name.id"
```

**Comment by xuzhang3** [comment]
@smholvoet   my bad, I misunderstand at first.  Maybe you can construct an IDs set first then use `for_each` to iterate all the ids?

**Comment by smholvoet** [comment]
@xuzhang3 That's actually a great idea🤯, thank you.

The below code did work:

```hcl
resource "azuredevops_git_permissions" "test" {
    for_each = toset( ["repo1-GUID","repo2-GUID","repo3-GUID"] )
  project_id    = azuredevops_project.project.id
  repository_id = each.value
  principal     = azuredevops_group.my-group.id
  permissions   = {
    PullRequestBypassPolicy = "NotSet"
    PolicyExempt            = "NotSet"
    GenericContribute       = "Allow"
    PullRequestContribute   = "Allow"
    CreateBranch            = "NotSet"
    CreateTag               = "Allow"
    DeleteRepository        = "NotSet"
    EditPolicies            = "NotSet"
    ForcePush               = "Allow"
    ManageNote              = "Allow"
    ManagePermissions       = "NotSet"
    GenericRead             = "Allow"
    RemoveOthersLocks       = "Allow"
    RenameRepository        = "NotSet"
  }
}
```

Now I'm able to use `each.value` and don't need any quotation marks to interpolate the `repository_id` ("`azuredevops_git_repository.${each.value}.id"`).

Even though this works, having the repo names instead of the GUID's makes things more readable. Also note that the `azuredevops_branch_policy_work_item_linking` resource _is_ able to handle the quotation marks (see the example in the original issue at the very top) but for some reason the `azuredevops_git_permissions` resource can't. 

I think this can be considered a bug, as both resources reference the exact same attributes?

- `project_id`
- `repository_id`

EDIT: I originally thought `azuredevops_branch_policy_work_item_linking` is able to handle properties which are placed in between quotation marks. Even though `terraform plan` works... `terraform apply` fails:

```text
│ Error: Error creating policy in Azure DevOps: TF402457: The settings for this policy are not correctly formatted. Error: Error converting value "azuredevops_git_repository.my-repo-name.id" to type 'System.Nullable`1[System.Guid]'. Path 'repositoryId', line 6, position 68.
```

 How can I loop through all of my repositories without using any quotation marks?

```hcl
resource "azuredevops_branch_policy_work_item_linking" "work-item-link-test" {
  for_each = toset( ["repo1","repo2","repo3"] )
  project_id = azuredevops_project.project.id

  enabled  = true
  blocking = true

  settings {

    scope {
      repository_id  = "azuredevops_git_repository.${each.value}.id" 👈
      repository_ref = "azuredevops_git_repository.${each.value}.default_branch" 👈
      match_type     = "Exact"
    }
  }
}
```

**Comment by xuzhang3** [comment]
@smholvoet  You can  construct the repo object in a map then iterate the repo object to get the `id` and `default_branch`

```hcl
data azuredevops_project "project" {
  name = "test"
}

data azuredevops_git_repository "repo" {
  for_each = toset( ["repo1", "repo2"])
  project_id = data.azuredevops_project.project.id
  name = "${each.value}"
}

#
#output "repos" {
#  value = data.azuredevops_git_repository.repo.*[0]
#}

resource "azuredevops_branch_policy_work_item_linking" "work-item-link-test" {
  for_each = tomap(data.azuredevops_git_repository.repo.*[0])
  project_id = data.azuredevops_project.project.id

  enabled  = true
  blocking = true

  settings {

    scope {
      repository_id  = "${each.value}".id
      repository_ref = "${each.value}".default_branch
      match_type     = "Exact"
    }
  }
}
```

**Comment by smholvoet** [comment]
This works like a charm, thank you @xuzhang3 👏
