### ISSUE TITLE
scaleset agent pool support

### ISSUE THREAD

**Issue by davidaughey** [microsoft/terraform-provider-azuredevops#537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to configure "Azure virtual machine scale set" Agent Pools using the `azuredevops` provider.

### New or Affected Resource(s)

* azuredevops_agent_pool

### Potential Terraform Configuration

```hcl

resource "azuredevops_agent_pool" "pool" {
  name                   = "scalesetpool"
  description            = "Scale set agent pool"
  pool_type              = "scaleset"
  scaleset_configuration = {
    service_connection_project = azuredevops_project.project.name
    service_connection_id      = azuredevops_serviceendpoint_azurerm.endpoint.id
    azure_scaleset_name        = "vmss"
    automatically_tear_down    = true
    max_agents                 = 10
    min_agents                 = 2
    delete_excess_agents_delay = 30
  }
}

```

**Comment by tmeckel** [comment]
I think it's a duplicate of #368

**Comment by davidaughey** [comment]
You're right.  I did a search with the word scaleset and nothing got flagged.  Pity.  Would have saved everyone a bit of time.
