### ISSUE TITLE
azuredevops_resource_authorization for azuredevops_environment 

### ISSUE THREAD

**Issue by tobiasz-gleba** [microsoft/terraform-provider-azuredevops#540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

1.1.6 - terraform
0.2.0 - provider 

### Affected Resource(s)

azuredevops_resource_authorization 

### Terraform Configuration Files

```hcl
resource "azuredevops_environment" "environment" {
  project_id = data.azuredevops_project.devops_project.id
  name       = data.azurerm_subscription.current.display_name
}

resource "azuredevops_resource_authorization" "auth_for_environment" {
  project_id  = data.azuredevops_project.devops_project.id
  resource_id = azuredevops_environment.environment.id
  authorized  = true
}
```
### Debug Output
```hcl
2022-02-23T09:25:03.486Z [INFO]  Starting apply for module.azuredevops_enviroment[0].azuredevops_resource_authorization.auth_for_environment
2022-02-23T09:25:03.486Z [DEBUG] module.azuredevops_enviroment[0].azuredevops_resource_authorization.auth_for_environment: applying the planned Create change
2022-02-23T09:25:03.846Z [DEBUG] provider.terraform-provider-azuredevops_v0.2.0: 2022/02/23 09:25:03 [WARN] The authorization with ID '27' no longer exists. Setting Id to empty 
2022-02-23T09:25:03.846Z [ERROR] vertex "module.azuredevops_enviroment[0].azuredevops_resource_authorization.auth_for_environment" error: Provider produced inconsistent result after apply
```
### Panic Output

```
[ERROR] vertex "module.azuredevops_enviroment[0].azuredevops_resource_authorization.auth_for_environment" error: error creating authorized resource: TF400898: An Internal Error Occurred. Activity Id:
```
```hcl
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.azuredevops_enviroment[1].azuredevops_resource_authorization.auth_for_environment,
│ provider "provider[\"registry.terraform.io/microsoft/azuredevops\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Expected Behavior

successfully created azuredevops_resource_authorization,
My pipelines should have permissions for creating apps in the environment. 

#### In my env:
![image](https://user-images.githubusercontent.com/26468905/155292927-fd796cdc-c5ad-428e-bce3-2726751ce24a.png)
![image](https://user-images.githubusercontent.com/26468905/155292985-78c3a87a-b470-4e72-ac3e-dfb8549f1dd8.png)

### Actual Behavior

terraform provider crash

### Steps to Reproduce

create ```azuredevops_resource_authorization``` resource for ```azuredevops_environment.id```

**Comment by tobiasz-gleba** [comment]
This is a bug in the provider

**Comment by xuzhang3** [comment]
@tobiase-gleba  `azuredevops_resource_authorization` support: `endpoint, queue, variablegroup`.  `environment` not supported by now.
Doc: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/resource_authorization#type

**Comment by tobiasz-gleba** [comment]
When can we expect implementation? Is it in a plan at all?

**Comment by xuzhang3** [comment]
@tobiasz-gleba  This API is not included in the latest SDK(v6 API) release. https://docs.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.1

**Comment by Christian-Schmid** [comment]
Hi, 

Azure DevOps changed the default behaviour for new environments in the december update from "permit access to all pipelines" to "permit to none".
See: https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-213-update#prevent-granting-all-pipelines-access-to-protected-resources

This now leads to the issue that we have to manually add the permissions after we create the environment. 

In the REST api 7.0 it looks like it is possible to configure those permissions: 
https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.0&tabs=HTTP#examples

I guess this would it now make possible to integrate this feature into the terraform provider.

**Comment by Christian-Schmid** [comment]
Hi @tobiasz-gleba 
I saw you closed this issue. Is this by now implemented or did you find a work around? If so I (and maybe some others) would be interested in the solution :-) Thanks!

**Comment by avishnyakov** [comment]
This should be re-opened.

**Comment by xuzhang3** [comment]
API : https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.0&tabs=HTTP
