### ISSUE TITLE
azuredevops_variable_group error : 401 Unauthorized, since 0.2.0

### ISSUE THREAD

**Issue by mivica** [microsoft/terraform-provider-azuredevops#541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- Terraform version is v1.1.6
- azuredevops provider version is 0.2.0

### Affected Resource(s)

* `azuredevops_variable_group `

### Terraform Configuration Files

```
resource "azuredevops_variable_group" "environment-resources" {
  project_id   = data.azuredevops_project.devops_project.id
  name         = "Environment"

  variable {
    name  = "ResourceGroupName"
    value = module.resource_group.name
  }
 }
```
### Expected Behavior

azuredevops_variable_group resource is created.

### Actual Behaviour

Error: creating variable group in Azure DevOps: Request returned status: 401 Unauthorized

1. `terraform apply`

### Important Factoids

- The error was introduced with version 0.2.0 of the provider
- Version 0.1.8 of the provider works fine

### References

* #0000

**Comment by xuzhang3** [comment]
SDK skip the project name from the request URL which result in create new variable group at organization level

**Comment by xuzhang3** [comment]
SDK issue: https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/525,  @mivica workaround for this issue is grant the PAT full access permission.

**Comment by xuzhang3** [comment]
Looks like service bug: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-pats-with-policies-for-administrators?view=azure-devops#restrict-creation-of-full-scoped-pats

**Comment by mivica** [comment]
@xuzhang3 , Thank you for the feedback.
This is a security concern. We don't want to have to give full permission just to create a variable group in DevOps.
Can you switch back to the old API endpoint until Microsoft have updated the new one to support non-full-scoped PATs?

**Comment by xuzhang3** [comment]
@mivica I was considering pull out a private SDK client and add the project constraint manually to make sure the VG is create at project level.

**Comment by xuzhang3** [comment]
@mivica #554  will fix the permission, downgrade the VG API from v6 to v5

**Comment by mivica** [comment]
@xuzhang3 , thank you for fixing this. When is the next release planned?

**Comment by xuzhang3** [comment]
@mivica  next release  will  be in a few weeks.
