### ISSUE TITLE
service endpoint project_id regression

### ISSUE THREAD

**Issue by croemmich** [microsoft/terraform-provider-azuredevops#545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.1.6
on darwin_amd64

provider registry.terraform.io/microsoft/azuredevops v0.2.0

### Affected Resource(s)

* `azuredevops_serviceendpoint_dockerregistry` (and probably all `azuredevops_serviceendpoint`)

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "example" {
  name               = "Example"
}

resource "azuredevops_serviceendpoint_dockerregistry" "example" {
  project_id            = azuredevops_project.example.name
  service_endpoint_name = "Example"

  docker_username = "_json_key"
  docker_password = "***"
  docker_registry = "***"
  registry_type   = "Others"
}
```

### Description

`azuredevops_serviceendpoint_*` resources created under versions prior to 0.2.0 accepted the project UUID OR name.
In #494, the project_id state is now always parsed to be a UUID (https://github.com/microsoft/terraform-provider-azuredevops/pull/494/commits/8ea873647dfacf778d69157cdf44cd4c8caf8c18#diff-b4329baf6162807ac4d1e75a35ba9d8f88ea877272d87cfe7ae3d4347e00611fR189) so it's no longer possible to use project name. Additionally, any previously created resources cannot be modified since the issue happens when reading the current state .
 
### Workaround

Use a version prior to `0.2.0` to switch all instances of project_id to use the UUID reference rather than project name.

**Comment by xuzhang3** [comment]
@croemmich for v5 API ,  project ID and name are mixed, both of them can be used to mange the service endpoint. After upgrade the API to v6,  some of the API separate ID and name, only ID is allowed,  so we add the constraint that only ID is allowed.

**Comment by croemmich** [comment]
Hi @xuzhang3, that makes sense. We did work around it by updating our existing resources using a prior provider version, but there should probably be a call-out for this in the docs for 0.2.0. Additionally the usage documentation still says "The project ID or project name." : https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_dockerregistry#project_id

**Comment by xuzhang3** [comment]
@croemmich  Thanks for pointing this out, document updated #548 . Registry document will updated after next release.

**Comment by croemmich** [comment]
Thanks @xuzhang3!
