### ISSUE TITLE
AZDO_GITHUB_SERVICE_CONNECTION_PAT env var not being read as expected 

### ISSUE THREAD

**Issue by AdamSir2** [microsoft/terraform-provider-azuredevops#546]
AZDO_GITHUB_SERVICE_CONNECTION_PAT environment variable not being read as highlighted.

My code works if i manually add in the github pat to the auth_personal block 

https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_github

```
resource "azuredevops_serviceendpoint_github" "serviceendpoint_gh_1" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "Sample GithHub Personal Access Token"

  auth_personal {
    # Also can be set with AZDO_GITHUB_SERVICE_CONNECTION_PAT environment variable
    personal_access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

Error - 

```
│ Error: Error creating service endpoint in Azure DevOps: Github Apps must be created on Github and then can be imported
│
│   with azuredevops_serviceendpoint_github.serviceendpoint_github,
│   on service_endpoint.tf line 13, in resource "azuredevops_serviceendpoint_github" "serviceendpoint_github":
│   13: resource "azuredevops_serviceendpoint_github" "serviceendpoint_github" {
```

**Comment by xuzhang3** [comment]
@AdamSir2  I cannot reproduce your error. How do u set `AZDO_GITHUB_SERVICE_CONNECTION_PAT` for ENV? I teste in local and pipeline, all works.

**Comment by AzySir** [comment]
@xuzhang3 `export AZDO_GITHUB_SERVICE_CONNECTION_PAT=ghp_123akjlshdalkjhd` this is on OS X

Can you try this in a docker container? 

Could you also share your code for me please?

**Comment by AdamSir2** [comment]
@xuzhang3  export AZDO_GITHUB_SERVICE_CONNECTION_PAT=xxxx this is on OS X

Can you try this in a docker container?

Could you also share your code for me please?

**Comment by AdamSir2** [comment]
I've tried in a docker image getting this error while the variable is set


```
azuredevops_serviceendpoint_github.serviceendpoint_github: Modifying... [id=82a7603b-c420-47c9-bd23-f63830071c48]
╷
│ Error: Error updating service endpoint in Azure DevOps: Github Apps can not be updated must match imported values exactly
│
│   with azuredevops_serviceendpoint_github.serviceendpoint_github,
│   on service_endpoint.tf line 3, in resource "azuredevops_serviceendpoint_github" "serviceendpoint_github":
│    3: resource "azuredevops_serviceendpoint_github" "serviceendpoint_github" {
│
```

**Comment by xuzhang3** [comment]
@AdamSir2  u should export the ENV variable for docker:
```
docker run --env AZDO_GITHUB_SERVICE_CONNECTION_PAT=xxxx  
```

**Comment by AdamSir2** [comment]
@xuzhang3  i've tried it already mate - have you tried it? 

It does not work - I keep getting above error

**Comment by xuzhang3** [comment]
@AdamSir2  Can you check if the EVN variables has been injected? I can set the ENV variables for docker.
![image](https://user-images.githubusercontent.com/57888764/156111926-99dbde57-2d50-4f17-a5a9-510dff5501f5.png)

**Comment by AdamSir2** [comment]
@xuzhang3  yes i know how to use docker mate - it's set. I did /bin/sh and could find all the environment variables set. 

All you're doing is showing me how to use docker. I know how to use docker.

I'd like to see a screenshot of you actually running the working scenario above... can you please provide?

**Comment by xuzhang3** [comment]
@AdamSir2  I see, you have export the env variables for docker but Terraform cannot get it. Which docker image are u use?

**Comment by xuzhang3** [comment]
@AdamSir2  I can apply the Terraform command and get the injected ENV variables. 
Test:
TF scripet
```hcl
terraform {
 required_providers {
   azuredevops = {
     source  = "microsoft/azuredevops"
     version = "=0.2.0"
   }
 }
}

data "azuredevops_project" "example" {
  name = "ADOTest"
}

resource "azuredevops_serviceendpoint_github" "serviceendpoint_gh_1" {
  project_id            = data.azuredevops_project.example.id
  service_endpoint_name = "Sample GithHub Personal Access Token"

  auth_personal {
    # Also can be set with AZDO_GITHUB_SERVICE_CONNECTION_PAT environment variable
#    personal_access_token = ""
  }
}
```

Apply command (powershell):
```powershell
docker run --rm -it --name terraform --env AZDO_GITHUB_SERVICE_CONNECTION_PAT=123 --env AZDO_ORG_SERVICE_URL=https://dev.azure.com/123/ --env AZDO_PERSONAL_ACCESS_TOKEN=123 -v ${pwd}:/workspace -w /workspace hashicorp/terraform:light apply --auto-approve=true
```
Result:
```log
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # azuredevops_serviceendpoint_github.serviceendpoint_gh_1 will be created
  + resource "azuredevops_serviceendpoint_github" "serviceendpoint_gh_1" {
      + authorization         = (known after apply)
      + description           = "Managed by Terraform"
      + id                    = (known after apply)
      + project_id            = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      + service_endpoint_name = "Sample GithHub Personal Access Token"

      + auth_personal {
          + personal_access_token      = (sensitive value)
          + personal_access_token_hash = (sensitive value)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
azuredevops_serviceendpoint_github.serviceendpoint_gh_1: Creating...
azuredevops_serviceendpoint_github.serviceendpoint_gh_1: Still creating... [10s elapsed]
azuredevops_serviceendpoint_github.serviceendpoint_gh_1: Creation complete after 12s [id=xxxxxxxxxxxxxxxxxxxxxxxxxx]
```

**Comment by AdamSir2** [comment]
@xuzhang3 this worked! We must update the documentation. This does not work if you don't have the below code in the service endpoint.

```
auth_personal {

}
```

In the documentation it says:

```
NOTE: Github Apps can not be created or updated via terraform. You must install and configure the app on Github and then import it. You must also set the description to "" explicitly."
```

But it does not say anything about leaving an empty `auth_personal { }` block!! Once I added this in - everything started working!

**Comment by AdamSir2** [comment]
Tried to do PR - but have no permissions to create a branch sorry

**Comment by xuzhang3** [comment]
@AdamSir2 you should fork this repo first then submit  a PR to this repo, you cannot create branch from this repo directly

**Comment by xuzhang3** [comment]
> AdamSir2
Than example is for GitHub APP, you can find this kind of connection at : `Project settings -> Boards -> GitHub connections`.

**Comment by xuzhang3** [comment]
Close this issue, feel free to open new issue if you have questions.
