### ISSUE TITLE
New azure devops service connection using Terraform - The identity with type 'Microsoft.IdentityModel.Claims.ClaimsIdentity' could not be found

### ISSUE THREAD

**Issue by raviumishra** [microsoft/terraform-provider-azuredevops#563]
$ terraform -v
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.19.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

```
data "azuredevops_project" "project" {
  name = "DevOps"
}

# azure container registry service connection
resource "azuredevops_serviceendpoint_azurecr" "azurecr" {
  for_each                   = var.acr
  project_id                 = data.azuredevops_project.project.id
  service_endpoint_name      = azurerm_container_registry.acr[each.key].name
  resource_group             = azurerm_resource_group.acr.name
  azurecr_spn_tenantid       = data.azurerm_client_config.current.tenant_id
  azurecr_name               = azurerm_container_registry.acr[each.key].name
  azurecr_subscription_id    = data.azurerm_client_config.current.client_id
  azurecr_subscription_name  = data.azurerm_subscription.subscription_current.display_name
}
```
`terraform plan`

    Terraform will perform the following actions:
    
      module.azure-acr.azuredevops_serviceendpoint_azurecr.azurecr["devops"] will be created
      + resource "azuredevops_serviceendpoint_azurecr" "azurecr" {
          + app_object_id               = (known after apply)
          + authorization               = (known after apply)
          + az_spn_role_assignment_id   = (known after apply)
          + az_spn_role_permissions     = (known after apply)
          + azurecr_name                = "acrname"
          + azurecr_spn_tenantid        = "xxxxxx"
          + azurecr_subscription_id     = "xxxxxx"
          + azurecr_subscription_name   = "dev"
          + description                 = "Managed by Terraform"
          + id                          = (known after apply)
          + project_id                  = "xxxxxx"
          + resource_group              = "rg"
          + service_endpoint_name       = "acrname"
          + service_principal_id        = (known after apply)
          + spn_object_id               = (known after apply)
        }
    
    Plan: 1 to add, 0 to change, 0 to destroy.

`terraform apply`

module.azure-acr.azuredevops_serviceendpoint_azurecr.azurecr["devops"]: Creating...
module.azure-acr.azuredevops_serviceendpoint_azurecr.azurecr["devops"]: Still creating... [10s elapsed]
module.azure-acr.azuredevops_serviceendpoint_azurecr.azurecr["devops"]: Still creating... [20s elapsed]
╷
│ Error:  waiting for service endpoint ready. Error looking up service endpoint given ID (xxxxxxxx) and project ID (xxxxxxxxx): map[state:Failed statusMessage:TF14045: The identity with type 'Microsoft.IdentityModel.Claims.ClaimsIdentity' could not be found.]
│
│   with module.azure-acr.azuredevops_serviceendpoint_azurecr.azurecr["devops"],
│   on modules\acr\acr.tf line 171, in resource "azuredevops_serviceendpoint_azurecr" "azurecr":
│  171: resource "azuredevops_serviceendpoint_azurecr" "azurecr" {
│
╵

**Comment by xuzhang3** [comment]
@raviumishra   `azuredevops_serviceendpoint_azurecr.azurecr` will auto create a new SPN in the directory your ORG connected,  the permission is related you account. Can  check your in the AAD that you have enough permission?

**Comment by pavelpikatamcs** [comment]
I am getting the same error, but I have permissions to create SPNs or App registrations manually in my tenant

```
│ Error:  waiting for service endpoint ready. Error looking up service endpoint given ID (xxx) and project ID (xxx): map[state:Failed statusMessage:TF14045: The ident
ity with type 'Microsoft.IdentityModel.Claims.ClaimsIdentity' could not be found.]
```

Here's my configuration slice:

```
resource "azuredevops_serviceendpoint_azurecr" "acr" {
  for_each                  = var.acr
  project_id                = data.azuredevops_project.project.id
  service_endpoint_name     = azurerm_container_registry.acr[each.key].name
  resource_group            = azurerm_container_registry.acr[each.key].resource_group_name
  azurecr_spn_tenantid      = data.azurerm_client_config.current.tenant_id
  azurecr_name              = azurerm_container_registry.acr[each.key].name
  azurecr_subscription_id   = data.azurerm_client_config.current.subscription_id
  azurecr_subscription_name = data.azurerm_subscription.current.display_name
}
```

**Comment by pavelpikatamcs** [comment]
It appears that the issue was with PAT I used for the provider - it lacked permissions to create service connections

**Comment by raviumishra** [comment]
@xuzhang3 Thanks for responce. We can archive this issue.

**Comment by xuzhang3** [comment]
good to see this issue been resolved.
