### ISSUE TITLE
add repository status in azuredevops_git_repository

### ISSUE THREAD

**Issue by ceciliasharp** [microsoft/terraform-provider-azuredevops#564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I need to be able to determine if a repository is disabled or not.

### New or Affected Resource(s)

* azuredevops_git_repository
* azuredevops_git_repositories

### Potential Terraform Configuration

```hcl
data "azuredevops_git_repository" "r" {
  project_id = <id>
  name       = <repoName>
}

output "name" {
  value = data.azuredevops_git_repository.r.status
}
```

**Comment by xuzhang3** [comment]
SDK missing property `isDisabled`: https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/v6/git/models.go#L1938

Response example:
```
{
    "id": "",
    "name": "test",
    "url": "",
    "project": {},
    "size": 0,
    "remoteUrl": "",
    "sshUrl": "",
    "webUrl": "https://dev.azure.com/test/test/_git/test",
    "_links": {    },
    "isDisabled": false
}
```

**Comment by aristosvo** [comment]
Please vote on this issue: https://developercommunity.visualstudio.com/t/Update-of-the-Go-SDK-to-include-new-feat/10186787

**Comment by matthewtckr** [comment]
Is this unblocked by #774?

**Comment by ceciliasharp** [comment]
The go api now includes the IsDisabled propery on the struct

**Comment by ceciliasharp** [comment]
[xuzhang3](https://github.com/xuzhang3) please remove the blocked tag (https://github.com/microsoft/azure-devops-go-api/blob/c9e5fa06da2c96efdb063352524aa458e7733bb6/azuredevops/v7/git/models.go#L1933)
