### ISSUE TITLE
Why is "Configurable Pipeline Runner" required for azuredevops_serviceendpoint_azuredevops ?

### ISSUE THREAD

**Issue by maxhillaert** [microsoft/terraform-provider-azuredevops#565]
I'm assuming this service endpoint matches the "New Azure Repos/Team Foundation Server service connection" from the Settings on the  Azure DevOps web ui?

**Comment by xuzhang3** [comment]
@maxhillaert  Checked the resources, this resource is duplicate with `azuredevops_serviceendpoint_runpipeline`, and this is a community supported extension: https://marketplace.visualstudio.com/items?itemName=CSE-DevOps.RunPipelines. Wrong resource implemented, I will deprecate this resource.

**Comment by xuzhang3** [comment]
I have reopen issue #339 . Feel free to open a new issue if you have questions.
