### ISSUE TITLE
Provider Checksum Error

### ISSUE THREAD

**Issue by indranil-chakraborty** [microsoft/terraform-provider-azuredevops#578]
Hey,
Looks like the releases are broken. When I try to run a `terraform init` using this provider, I get the below.

```text
│ Error: Failed to install provider │ │ Error while installing microsoft/azuredevops v0.2.1: archive has incorrect │ checksum │ zh:67f794f75714d3ab8307d411a9e908ce3d6bb83c6e96a07830572ff85246681a │ (expected │ zh:f12de8c46a0bf557d0a11e26b4253d3bc73e63a19d0caa24e1bafd1c8bb4e09c)
```

If I compare the release artifact available here vs. the artifact at https://releases.hashicorp.com/terraform-provider-azuredevops/0.2.1/, I can see that the sha256sum of the artifact here is indeed invalid.

This seems to be affecting all release versions across all platforms.

**Comment by xuzhang3** [comment]
@indranil-chakraborty  I cannot reproduce your (win/osx) .  Can you check where you download the providers? . I checked the checksums both in  https://releases.hashicorp.com/terraform-provider-azuredevops/0.2.1/, and https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v0.2.1 , they are the same and not changed.

**Comment by indranil-chakraborty** [comment]
@xuzhang3 I can confirm that this works when I try now. I was earlier trying using a work laptop and that failed. I am guessing that my work laptop / network is performing some sort of MITM that is changing the downloaded file which is causing the issue. Closing this issue.
