### ISSUE TITLE
Add ability to add a resource under an Environment - Kubernetes / Virtual Machine

### ISSUE THREAD

**Issue by Phil1972** [microsoft/terraform-provider-azuredevops#584]
Hi,

I am not able to find the functionality, maybe I have it wrong, but is there a way to create a resource under an environment?  ie: either add a kubernetes namespace or a virtual machine.

We are presently stuck at creating a functioning environment because this is missing (or we are not able to find out how to do it).

The missing piece is supposed to under-the-hood call MS azure devops REST API:
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/kubernetes/add?view=azure-devops-rest-6.0

POST https://dev.azure.com/{organization}/{project}/_apis/distributedtask/environments/{environmentId}/providers/kubernetes?api-version=6.0-preview.1

We are using the pulumi devops provider which derives from the terraform provider.

Thanks for your time,

**Comment by Phil1972** [comment]
<img width="872" alt="Environments - Pipelines - Issue" src="https://user-images.githubusercontent.com/40364427/167660115-564a98fc-17c2-4561-a9f5-d3e5c72af0fc.png">

Here is an image for better understanding of what we would need.

**Comment by croemmich** [comment]
@Phil1972 I implemented this a few months ago in https://github.com/microsoft/terraform-provider-azuredevops/pull/553. Unfortunately it's blocked by an upstream issue no one seems to care much about... which pretty much describes my entire experience with the https://github.com/microsoft/azure-devops-go-api team. @xuzhang3 any chance you could poke them again?

**Comment by xuzhang3** [comment]
@croemmich  Sorry, no update 😞

**Comment by venkatesh-thatham** [comment]
@croemmich, @xuzhang3 any update on this PR, we really need this enhancement to be merged for our use case also. Appreciate your help.

**Comment by tiwarishrijan** [comment]
Any Update on this PR ? I see upstream bug is also closed.

**Comment by xuzhang3** [comment]
#553 is working on this feature. Hope @croemmich has time to update the PR.

**Comment by SDohle** [comment]
Hi @croemmich,
any plans to update/complete this?

Best regards

**Comment by croemmich** [comment]
Apologies, I don't have time to complete this. Anyone is welcome to fork it and take it to completion.
