### ISSUE TITLE
azuredevops_repository_policy_check_credentials can't create policy

### ISSUE THREAD

**Issue by klecouvey** [microsoft/terraform-provider-azuredevops#585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1

### Affected Resource(s)

* `azuredevops_repository_policy_check_credentials`

### Terraform Configuration Files

[This is the example from the documentation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/repository_policy_check_credentials#example-usage).

```hcl
terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = "0.2.1"
    }
  }
}

resource "azuredevops_project" "example" {
  name               = "Example Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
  description        = "Managed by Terraform"
}

resource "azuredevops_git_repository" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Repository"
  initialization {
    init_type = "Clean"
  }
}

resource "azuredevops_repository_policy_check_credentials" "example" {
  project_id     = azuredevops_project.example.id
  enabled        = true
  blocking       = true
  repository_ids = [azuredevops_git_repository.example.id]
}
```

### Debug Output

```shell
...
azuredevops_repository_policy_check_credentials.example: Creating...
2022-04-29T15:59:03.514-0400 [INFO]  Starting apply for azuredevops_repository_policy_check_credentials.example
2022-04-29T15:59:03.515-0400 [DEBUG] azuredevops_repository_policy_check_credentials.example: applying the planned Create change
2022-04-29T15:59:03.736-0400 [ERROR] vertex "azuredevops_repository_policy_check_credentials.example" error: Error creating policy in Azure DevOps: Type with id 'e67ae10f-cf9a-40bc-8e66-6b3a8216956e' does not exist.
╷
│ Error: Error creating policy in Azure DevOps: Type with id 'e67ae10f-cf9a-40bc-8e66-6b3a8216956e' does not exist.
│
│   with azuredevops_repository_policy_check_credentials.example,
│   on toto.tf line 26, in resource "azuredevops_repository_policy_check_credentials" "example":
│   26: resource "azuredevops_repository_policy_check_credentials" "example" {
│
╵
2022-04-29T15:59:03.747-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-29T15:59:04.040-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/microsoft/azuredevops/0.2.1/windows_amd64/terraform-provider-azuredevops_v0.2.1 pid=38552
2022-04-29T15:59:04.040-0400 [DEBUG] provider: plugin exited
```

### Expected Behavior

Credentials check repository policy created!

### Actual Behavior

Credentials check repository policy not created with error!

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

"Personal" Azure DevOps Services organization. Free tier.

### References

* #0000

**Comment by xuzhang3** [comment]
@Maetis This feature is not available by default,  supported by extension: https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview.
If your ORG has this extension enabled, you will find the configuration at `project -> Settings -> Repositories -> Policies`:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/57888764/166879582-64c0b973-caa4-4ecc-9641-06f6f248d402.png">

**Comment by klecouvey** [comment]
Thanks @xuzhang3 for clarifying this point.

Maybe a note in the documentation would be useful.
