### ISSUE TITLE
`azuredevops_serviceendpoint_aws` does not support 'shared' service connections

### ISSUE THREAD

**Issue by kal-el** [microsoft/terraform-provider-azuredevops#586]
In Azure DevOps, one can share a service connection across various projects within the same AzDo org. When you enable this through the console, the service connection shows up with a tag 'Shared' next to it.

If you create a new service connection using this provider and then make it shared via the console, or try to import an existing service connection which is shared - although the import works fine and the resource gets created in the terraform state file, it picks up the configuration of the service connection before it was shared. 

For example, if I manually create a service connection and give it a description of "test description", and import the service connection in my state file, it works fine. Next, I go into the AzDo console, share this service connection with another project (which makes it tagged as Shared) and update the description of this connection to "shared description". I then go into my terraform state file, remove the service connection and reimport it to update the reference, it will get imported with the description of "test description". This will keep on happening on until all the shared connections are deleted by going to the respective AzDo projects where the connection is shared and deleting them there. After only the primary project's service connection remains, you can make changes and import the latest updates. 

This means to update any service connection managed by this provider, you first have to (manually) stop sharing, work on the resource, and then (manually) share it again.

**Comment by xuzhang3** [comment]
@kal-el ,  `shared` is currently not supported. Modifications outside of Terraform may not be handled correctly. https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/update-service-endpoint?view=azure-devops-rest-6.0

**Comment by xuzhang3** [comment]
If the description is  changed after sharing, the shared project will get the old description, this is service behavior not a bug.
Original:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/57888764/166886225-0d5e14bc-15ff-43ff-8e2a-fdcb3b82f62d.png">
Shared connection:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/57888764/166886079-43ba2fb9-23ca-4ae2-a971-ad52e4a2fa1f.png">

**Comment by kal-el** [comment]
Hello @xuzhang3  - thanks for your response. The issue we have is that when we use the primary connection as the service connection resource via the azure devops provider, it doesn't pick up these changes. Once the primary connection is shared, we don't import or use those shared connections in terraform - as they are managed by other projects. And yes, through the console those don't sync up. 

As for the example your provided, if I change the description of primary connection through the console, the console does show those changes (import through TF provider doesn't). The shared connections don't pick those - which is fine, since we don't import or use the shared connections through TF.

But our main concern is with the primary connection - i.e. description changes not recognized by the provider for the primary connection until all the shared connections are severed. 

It sounds like we will have to wait for the provider to support shared connections. Is that on the roadmap, or any timelines associated with it?

**Comment by xuzhang3** [comment]
@kal-el this looks like a bug, the import operations should read the latest changes.
