### ISSUE TITLE
I have python wheel files in Azure Artifacts. How Can I install these wheel files on a databricks cluster using terraform?

### ISSUE THREAD

**Issue by MADHBHAR** [microsoft/terraform-provider-azuredevops#588]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by xuzhang3** [comment]
@MADHBHAR you can use ` local-exec` or `remote-exec` invoke the install command after databricks cluster created https://www.terraform.io/language/resources/provisioners/local-exec
