### ISSUE TITLE
Documentation for import of service endpoints is missing

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#59]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation for how to import the following service endpoints are missing, but the code to do the import is working and tested:
* https://www.terraform.io/docs/providers/azuredevops/r/serviceendpoint_azurerm.html
* https://www.terraform.io/docs/providers/azuredevops/r/serviceendpoint_dockerregistry.html
* https://www.terraform.io/docs/providers/azuredevops/r/serviceendpoint_kubernetes.html

### New or Affected Resource(s)

* azuredevops_serviceendpoint_azurerm
* azuredevops_serviceendpoint_dockerregistry
* azuredevops_serviceendpoint_kubernetes

### Potential Terraform Configuration

N/A

### References

N/A

**Comment by xuzhang3** [comment]
@nmiodice  I think that all of this resources contains sensitives data,  and the service always returns these variables with empty string. If these resource can be imported, there will be a diff during the plan stage, customers need to  handle the diffs manually. Support for importing resources containing sensitive configuration is inappropriate.
