### ISSUE TITLE
[New Resource] Release Definition Resource

### ISSUE THREAD

**Issue by straubt1** [microsoft/terraform-provider-azuredevops#6]
### Description

Currently the ability to create .yml based build pipelines exists, however there is no resource to create release pipelines.

### New or Affected Resource(s)

* azuredevops_release_definition

### Potential Terraform Configuration

azuredevops_release_definition

```hcl
resource "azuredevops_release_definition" "release" {
  project_id = azuredevops_project.project.id
  name       = "Sample Release Definition"

  ci_trigger {
    use_yaml = true
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = azuredevops_git_repository.repository.id
    branch_name = azuredevops_git_repository.repository.default_branch
    yml_path    = "azure-pipelines.yml"
  }
  ...
}
```

### References

* [Release Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by marekaf** [comment]
Hi 👋 I'm interested in working on this. I see however a draft PR https://github.com/microsoft/terraform-provider-azuredevops/pull/178 already. Should I work on it / join forces / leave it as it is?:)

**Comment by federicomidaglia** [comment]
It's a basic function, I can't believe I don't have it

**Comment by movergan** [comment]
At least something IaC for releases is highly desirable.  +1

**Comment by florianfirmenich** [comment]
@EliiseS @xuzhang3 shouldn't this be merged with this issue: https://github.com/microsoft/terraform-provider-azuredevops/issues/49 ?

**Comment by xuzhang3** [comment]
dup of #49
