### ISSUE TITLE
Git repository with the name exists when importing private repo into newly created project

### ISSUE THREAD

**Issue by VincentVerweij** [microsoft/terraform-provider-azuredevops#601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.2.1
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}

provider "azuredevops" {
  org_service_url       = "https://dev.azure.com/target-org"
  personal_access_token = "****"
}

resource "azuredevops_project" "New-Project-1" {
  name               = "MyProject"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
  description        = ""
  features = {
    "boards"    = "disabled"
    "testplans" = "disabled"
    "artifacts" = "disabled"
  }
}

resource "azuredevops_serviceendpoint_generic_git" "example-serviceendpoint" {
  project_id            = azuredevops_project.New-Project-1.id
  repository_url        = "https://source-org@dev.azure.com/source-org/MyProject/_git/MyProject"
  username              = var.username
  password              = var.pat
  service_endpoint_name = "Example Generic Git"
  description           = "Managed by Terraform"
}

resource "azuredevops_git_repository" "New-Project-1-repo-import-sp-0" {
  project_id = azuredevops_project.New-Project-1.id
  name       = "MyProject"
  initialization {
    init_type             = "Import"
    source_type           = "Git"
    source_url            = "https://source-org@dev.azure.com/source-org/MyProject/_git/MyProject"
    service_connection_id = azuredevops_serviceendpoint_generic_git.example-serviceendpoint.id
  }
}
```

### Expected Behavior

The project is created, the service endpoint is created and the source-org repository is imported into the newly created project (as project creation causes repo to be created with the same name as the project).

### Actual Behavior

The project is created, the service endpoint is created but the repository is not imported. The following output is being shown:
```
azuredevops_project.New-Project-1: Creating...
azuredevops_project.New-Project-1: Still creating... [10s elapsed]
azuredevops_project.New-Project-1: Creation complete after 16s [id=c16c2c7c-b38e-44f1-abe9-fbadf5bb9a27]
azuredevops_serviceendpoint_generic_git.example-serviceendpoint: Creating...
azuredevops_serviceendpoint_generic_git.example-serviceendpoint: Still creating... [10s elapsed]
azuredevops_serviceendpoint_generic_git.example-serviceendpoint: Creation complete after 11s [id=0fcd4c04-9bc7-4aa4-80d3-4e2c55d2c483]
azuredevops_git_repository.New-Project-1-repo-import-sp-0: Creating...
╷
│ Error: Error creating repository in Azure DevOps: TF400948: A Git repository with the name MyProject already exists.
│
│   with azuredevops_git_repository.New-Project-1-repo-import-sp-0,
│   on main.tf line 29, in resource "azuredevops_git_repository" "New-Project-1-repo-import-sp-0":
│   29: resource "azuredevops_git_repository" "New-Project-1-repo-import-sp-0" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

### References

* none

So I did take this page's code as an example: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository#import-from-a-private-repository  

In there we have another resource "azuredevops_git_repository" "example" which I did use as well but it gave me the same outcome.
For the repository_url and the source_url, I did go to the source organization, went to the repo and clicked the clone button where I did copy the URL from.  

If I try to do this import manually in the UI, also copying that same URL and enabling the authentication checkbox it all works properly. The PAT that I generated is "All accessible organizations" so works for both the source and target organization.

I am not sure whether this is an actual bug or me doing something wrong, or the documentation which is missing something crucial.

To avoid anyone coming up with this, I don't want to have a second created repo next to the existing one, which was created during project creation. I am saying this as this could be a workaround.

**Comment by sjackson0109** [comment]
It's my experience the azuredevops provider isn't currently able to:
 - replace the default repository using the azuredevops_git_repository resource
 - initialise the default repository using an external uri/url and or credential using the azuredevops provider
 - update the default_repository_name inside azuredevops_proejct resources
 - delete a repository with a property on the azuredevops_project resource

**Comment by sjackson0109** [comment]
@VincentVerweij  don't forget to include the lifecycle to ignore the initialization state changes discovered via API calls that the azuredevops provider discovers.
```
resource "azuredevops_git_repository" "New-Project-1-repo-import-sp-0" {
  # all existing lines above remain
  lifecycle { ignore_changes = [ initialization ] }
}
```

**Comment by xuzhang3** [comment]
This is by design. A default repository will be created once a project created, this is controlled by service(at least one project per project).

**Comment by xuzhang3** [comment]
One potential configuration is to use the default repository (not initialized by default) as the source repository and initialize it
Potential config:
```hcl
resource "azuredevops_project" "New-Project-1" {
  name               = "MyProject"
}

resource "azuredevops_serviceendpoint_generic_git" "example-serviceendpoint" {
  project_id            = azuredevops_project.New-Project-1.id
  repository_url        = "<url>"
  username              = ""
  password              = ""
  service_endpoint_name = "Example Generic Git"
  description           = "Managed by Terraform"
}

data "azuredevops_git_repository" "repo" {
  project_id = azuredevops_project.New-Project-1.id
  name = azuredevops_project.New-Project-1.name
}

resource "azuredevops_git_repository" "New-Project-1-repo-import-sp-0" {
  project_id = azuredevops_project.New-Project-1.id
  name       = "MyProject"
  initialization {
    init_type             = "Import"
    source_type           = "Git"
    source_url            = "<url>"
    service_connection_id = azuredevops_serviceendpoint_generic_git.example-serviceendpoint.id
  }
}

import {
  id = "${azuredevops_project.New-Project-1.id}/${data.azuredevops_git_repository.repo.id}"
  to = azuredevops_git_repository.New-Project-1-repo-import-sp-0
}
```
