### ISSUE TITLE
azuredevops_serviceendpoint_kubernetes - using an old version of Azure AKS API

### ISSUE THREAD

**Issue by robobrown** [microsoft/terraform-provider-azuredevops#602]
When deploying a DevOps service connection for AKS we are getting an error stating that the API version 2018-03-31 is invalid

Error:  waiting for service endpoint ready. Error looking up service endpoint given ID ({ID}) and project ID ({PROJECTID}): map[state:Failed statusMessage:An error occured while fetching the AKS cluster. Internal error: Failed to query service connection API: 'https://management.azure.com/subscriptions/{SUBID}/resourcegroups/subscriptions/{SUBID}/resourceGroups/{RESOURCEGROUP}/providers/Microsoft.ContainerService/managedClusters/{CLUESTERNAME}?api-version=2018-03-31'. Status Code: 'BadRequest', Response from server: '{"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2018-03-31' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}']

**Comment by xuzhang3** [comment]
@robobrown can you share your TF script, this can help reproduce the error

**Comment by robobrown** [comment]
Sorry for the delay, below are the key points for keeping it brief. nothing too fancy.

Versions in Use

terraform version          
Terraform v1.2.3
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.17.0
+ provider registry.terraform.io/hashicorp/azuread v2.24.0
+ provider registry.terraform.io/hashicorp/azurerm v3.10.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/mastercard/restapi v1.16.2
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1
+ provider registry.terraform.io/sullivtr/graphql v2.4.0


######################################################################################
DEVOPS
######################################################################################
```
data "azuredevops_project" "project" {
  name = "devopsPojectName"
}
data "azurerm_subscription" "current" {
}

resource "azuredevops_serviceendpoint_kubernetes" "devopsconnection" {
  project_id            = data.azuredevops_project.project.id
  service_endpoint_name = azurerm_kubernetes_cluster.default.name
  apiserver_url         = "${azurerm_kubernetes_cluster.default.kube_config.0.host}"
  authorization_type    = "AzureSubscription"

  azure_subscription {
    subscription_id   = var.azure_subscription_id
    subscription_name = data.azurerm_subscription.current.display_name
    tenant_id         = var.azure_tenant_id
    resourcegroup_id  = azurerm_resource_group.rg-default.id
    namespace         = var.kub_namespace
    cluster_name      = azurerm_kubernetes_cluster.default.name
  }
}
```

################################################################
Kub Cluster
###############################################################
```
resource "azurerm_resource_group" "rg-default" {
  name     = "rg-name-here"
  location = var.region_location
}
resource "azurerm_kubernetes_cluster" "default" {
    name                = "aks-name-here"
    location            = azurerm_resource_group.rg-default.location
    resource_group_name = azurerm_resource_group.rg-default.name
    dns_prefix          = "aks-name-here-dns"

    # custom
    role_based_access_control_enabled   = false
    local_account_disabled              = false
    oidc_issuer_enabled                 = false
    open_service_mesh_enabled           = false
    private_cluster_enabled             = false
    api_server_authorized_ip_ranges     = []
    azure_policy_enabled                = true
    enable_pod_security_policy          = false
    http_application_routing_enabled    = false
    sku_tier                            = "Paid"
    node_resource_group                 = "rg-name-here-aks-managed"
  
    network_profile{
        network_plugin = "azure"
        service_cidr  = "172.16.0.0/16"
        docker_bridge_cidr = "172.17.0.1/16"
        dns_service_ip = "172.16.0.10"
    }

    default_node_pool {
        name       = "agentpool"
        node_count = var.agent_pool_nodecount
        vm_size    = var.agent_pool_vmsize

        # custom
        enable_auto_scaling          = false
        enable_host_encryption       = false
        enable_node_public_ip        = false
        fips_enabled                 = false
        node_taints                  = []
        only_critical_addons_enabled = false
        kubelet_disk_type            = "OS"
        max_pods                     = 110
        node_labels                  = {}
        os_disk_size_gb              = 128
        os_sku                       = "Ubuntu"
        vnet_subnet_id               = module.vnet-default.subnet_map["subnet-name-here"].id

        zones                        = [
              "1",
              "2",
              "3",
        ]

        tags     = local.default_tags
    }

    identity {
        type = "UserAssigned"
        identity_ids =[ azurerm_user_assigned_identity.aks.id ]
    }

    key_vault_secrets_provider {
        secret_rotation_enabled = false
     }

    oms_agent {
        log_analytics_workspace_id = data.azurerm_log_analytics_workspace.log-grtenant.id
    }
       
}

```

**Comment by robobrown** [comment]
One thing I have noticed is that the Cluster does not have the Resource Group in the name on DevOps - This is while it is trying to create the connection

LEFT - Manually Created
RIGHT - Terraform Created (in progress, it fails with the connection error)

<img width="899" alt="image" src="https://user-images.githubusercontent.com/37118647/174822312-2e35dfeb-8844-4945-a1f1-3544d2b6a68c.png">

**Comment by robobrown** [comment]
I managed to get it working, the parameter **resourcegroup_id** is actually expecting the **resource group name** and not the resource Id as per Azure, you may want to think about renaming the field to resourcegroup_name
