### ISSUE TITLE
azuredevops_serviceendpoint_dockerregistry doesn't update password

### ISSUE THREAD

**Issue by derhally** [microsoft/terraform-provider-azuredevops#603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.23.0
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_dockerregistry`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_dockerregistry" "prod" {
  project_id            = "xxx"
  service_endpoint_name = ""xxx-prod"
  docker_registry       = "https://us-docker.pkg.dev/xxx-xxx"
  docker_username       = "_json_key"
  docker_password       = data.google_secret_manager_secret_version.ado_prod_svc_account_key.secret_data
  registry_type         = "Others"
}

```

### Panic Output

None

### Expected Behavior

When the docker_password changes, it should update the password in the service_connection

### Actual Behavior

Terraform reports no changes.

### Steps to Reproduce

1. `terraform apply`
2. change the password
3. terraform plan

### Important Factoids

None

**Comment by xuzhang3** [comment]
@derhally  one `password` changed and run `terraform plan`, you will see the diffs:
![image](https://user-images.githubusercontent.com/57888764/173507816-29414eb9-a367-4d59-b451-de091abd706d.png)



Can you check if `data.google_secret_manager_secret_version.ado_prod_svc_account_key.secret_data` has been chagned?

**Comment by derhally** [comment]
@xuzhang3 I went back and tried manually changing the password and it generated the plan.   Not sure why it didn't last time.  Sorry about that.

**Comment by eval-on-point** [comment]
I just reproduced this bug on our system. If you are setting `docker_password` using a sensitive value, when the serviceendpoint's `docker_password` is already sensitive, then Terraform will not change the resource (even though the plan says the change will be made). @derhally accidentally resolved his issue by setting the password to a non-sensitive value, which causes Terraform to apply the change.

**Comment by xuzhang3** [comment]
@eval-on-point  This is a bug of the hash function. More details in the fix PRs:: #708 #664

**Comment by eval-on-point** [comment]
Thanks for the additional context, @xuzhang3. I am having some trouble understanding. 

1. Does #708 fix this bug? I am on version `0.5.0` of this provider, which I believe includes the merged PR, and I am still seeing this bug. 
2. It is unclear to me what the feature request in #664 has to do with this.

Sorry for wasting your time if this should all be clear.

**Comment by xuzhang3** [comment]
@eval-on-point  
 1. #708 fix the bug in resource `azuredevops_serviceendpoint_npm`, not `azuredevops_serviceendpoint_dockerregistry`
 2. My mistake, should be #619 not #664.

**Comment by eval-on-point** [comment]
Thank you for clarifying! This isn't a blocker for my team, but it might make sense to re-open this issue so that others do not unknowingly hit the same roadblock.
