### ISSUE TITLE
Modifying a repository with init_type as Uninitialized fails on apply

### ISSUE THREAD

**Issue by Jolton** [microsoft/terraform-provider-azuredevops#605]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.1.5
Installed microsoft/azuredevops v0.2.1

### Affected Resource(s)

* azuredevops_git_repository`

### Terraform Configuration Files

Partial configuration
```hcl
resource "azuredevops_git_repository" "git_repos" {
    for_each 		= {for repo in local.repos: repo.repo_key => repo }

    name                   = each.value.repo_name
    project_id            = data.azuredevops_project.project.id

    initialization {
        init_type = "Uninitialized"
    }
    lifecycle {	
        ignore_changes 	= [
            initialization,
            size
        ]
        prevent_destroy = true
    }
}
```

### Debug Output

Output from Plan
```
# azuredevops_git_repository.git_repos["DotnetAPI.ContentEditor.User"] will be updated in-place
  ~ resource "azuredevops_git_repository" "git_repos" {
        id             = "35136b8d-001e-48aa-8ef0-4caa230eed37"
      ~ name           = "DotnetAPI.ContentEditor.User" -> "DotnetAPI.ContentEditor.WebApi"
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Expected Behavior

The repo gets renamed

### Actual Behavior

```
azuredevops_git_repository.git_repos["DotnetAPI.ContentEditor.User"]: Modifying... [id=35136b8d-001e-48aa-8ef0-4caa230eed37]
╷
│ Error: Error converting terraform data model to AzDO project reference:  Repository 'initialization.init_type = Uninitialized', there will be no branches, 'default_branch' cannt not be set.
│ 
│   with azuredevops_git_repository.git_repos["DotnetAPI.ContentEditor.User"],
│   on repos.tf line 2, in resource "azuredevops_git_repository" "git_repos":
│    2: resource "azuredevops_git_repository" "git_repos" {
│ 
╵
```
### Steps to Reproduce

1. `terraform apply`

### References

* This seems to be related to the fix for https://github.com/microsoft/terraform-provider-azuredevops/issues/498

### Notes
This was working with microsoft/azuredevops v0.1.8

**Comment by xuzhang3** [comment]
@Jolton This a conflict setting  between `initialization.init_type=Uninitialized` and `default_branch`.  This error message is a bit confuse, you need remove the `default_branch` when set `initialization.init_type=Uninitialized`.  More context, `initialization` was originally introduce from ADO provider, it combines different API and features which should be separated into different resources like `git_init`, `git_import etc.`

**Comment by Jolton** [comment]
Hi @xuzhang3 thanks for responding

How would I remove the default branch as I'm not setting that in terraform?

**Comment by JennaFriesen** [comment]
@xuzhang3 For some more clarification:

* We are setting the init_type=Unitialized, and adding Initialization to the ignore_changes lifecycle as the documentation suggests (https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository#import)
* We are _not_ setting the default_branch in terraform.  That seems to get set in the state once the repo is initialized manually later.

The issue is that modifying an existing repo is no longer possible if that repo was initially created Uninitialized, even if it has since been initialized.  This used to be possible.
