### ISSUE TITLE
Upload a Wiki to a newly created Project for Standardized Guidance

### ISSUE THREAD

**Issue by JeffLeite** [microsoft/terraform-provider-azuredevops#606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would like to be able to use the Terraform provider to add a wiki to the newly created project as the Azure DevOps CLI `az devops wiki create` or the VSTeam PowerShell module with  `Add-VSTeamWiki`.  Is this something that is going to be considered for the future of the `azuredevops` provider?   The IT/DevOps groups are asking if this could be automated through Terraform to allow to provide consistent guidance based on the newly created project instead of having store the guidance outside of the newly created project.

### New or Affected Resource(s)

* azuredevops_project_wiki 

### Potential Terraform Configuration

```hcl
resource "azuredevops_project_wiki" "project-wiki" {
  project_id = azuredevops_project.project.id
  name = "${azuredevops_project.project.name} Wiki"
  type = "project" # code for code wiki  
}
```

**Comment by xuzhang3** [comment]
API: https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/wikis/create?view=azure-devops-rest-6.0

**Comment by xuzhang3** [comment]
Supported: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/wiki
