### ISSUE TITLE
Resources destroying and recreating when switching from PAT to System.Access.Token when running terraform in azure devops pipelines

### ISSUE THREAD

**Issue by mickmorse** [microsoft/terraform-provider-azuredevops#607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform: 1.0.11
azuredevops: 0.2.1

### Affected Resource(s)

* `azuredevops_branch_policy_build_validation`
* `azuredevops_git_repository`
* `azuredevops_branch_policy*`
* `azuredevops_build_definition`
* `azuredevops_git_permissions`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0.11"
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.2.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">=3.74.0"
    }
  }
}

provider "azuredevops" {
  org_service_url = var.ado_organisation_url
}

provider "aws" {
}

```

### Debug Output
https://gist.githubusercontent.com/mickmorse/6f9e0e6b7958192224f1b27fdc0ef2d4/raw/977fbbf89153bc9d6b3b1f739bcfbe608c4151d1/gistfile1.txt

### Panic Output
na
### Expected Behavior

`No changes. Infrastructure is up-to-date."`

### Actual Behavior
`Note: Objects have changed outside of Terraform` 
Destroying and recreating of the above impacted resources 

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Using terragrunt
Creating terraform ado resources in ADO pipeline.

Original resources in state created by setting `AZDO_PERSONAL_ACCESS_TOKEN` to a user's PAT in pipeline yaml - the above behaviour is happening when changing the `AZDO_PERSONAL_ACCESS_TOKEN` to the `$(System.AccessToken)`, e.g:

```yaml
- script: |
              set -e
              terragrunt plan --input=false \
                -out=$(TERRAFORM_PLAN_FILENAME)
            displayName: "Terraform init & plan"
            workingDirectory: infrastructure
            env:
              TF_IN_AUTOMATION: true
              TF_LOG: DEBUG
              AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
```

Interesting things to note from debug:

```
azuredevops_branch_policy_build_validation.ado_infra_falcon_policy: Refreshing state... [id=18222]
2022-06-22T13:06:56.917Z [WARN]  Provider "registry.terraform.io/microsoft/azuredevops" produced an invalid plan for azuredevops_branch_policy_build_validation.ado_infra_design_policy, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .settings[0].manual_queue_only: planned value cty.False for a non-computed attribute
      - .settings[0].queue_on_source_update_only: planned value cty.True for a non-computed attribute
```

```
2022-06-22T13:06:57.834Z [DEBUG] ReferenceTransformer: "azuredevops_build_definition_permissions.permissions[\"superfleet_infra_tf_module_iam_domain_accounts_np\"]" references: []
2022-06-22T13:06:57.834Z [INFO]  ReferenceTransformer: reference not found: "azuredevops_build_definition.ado_pipeline"
2022-06-22T13:06:57.834Z [INFO]  ReferenceTransformer: reference not found: "azuredevops_build_definition.pipelines"
2022-06-22T13:06:57.834Z [INFO]  ReferenceTransformer: reference not found: "var.ado_repositories"
2022-06-22T13:06:57.834Z [INFO]  ReferenceTransformer: reference not found: "azuredevops_build_definition.pipelines"
2022-06-22T13:06:57.834Z [INFO]  ReferenceTransformer: reference not found: "each.value"
``` 

### References
na

**Comment by mickmorse** [comment]
Any update on this?

**Comment by xuzhang3** [comment]
Ref doc:  https://github.com/microsoft/terraform-provider-azuredevops/blob/main/website/docs/guides/authenticating_using_the_personal_access_token.html.md#azure-devops-provider-authenticating-using-the-personal-access-token
