### ISSUE TITLE
Lost data during resource force replacement when ADO api gets an error

### ISSUE THREAD

**Issue by patr00n** [microsoft/terraform-provider-azuredevops#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_branch_policy_build_validation`

### Terraform Configuration Files

```hcl
resource "azuredevops_branch_policy_build_validation" "bp" {
    blocking   = true
    enabled    = true
    project_id = "5713a29b-a24c-4358-bfb5-51781344f423"

    settings {
        build_definition_id         = 1161
        display_name                = "tf_test_policy"
        manual_queue_only           = false
        queue_on_source_update_only = true
        valid_duration              = 720

        scope {
            match_type     = "Exact"
            repository_id  = "105bb7b9-1d25-48ff-ae9f-d6062e306200"
            repository_ref = "refs/heads/master"
        }
    }
}
```

### Debug Output
```
Terraform will perform the following actions:

  # azuredevops_branch_policy_build_validation.bp must be replaced
-/+ resource "azuredevops_branch_policy_build_validation" "bp" {
        blocking   = true
        enabled    = true
      ~ id         = "1473" -> (known after apply)
      ~ project_id = "5713a29b-a24c-4358-bfb5-51781344f423" -> "c8ace00e-03cf-46f5-9d24-5e448f352df8" # forces replacement

      ~ settings {
            build_definition_id         = 1161
            display_name                = "tf_test_policy"
            manual_queue_only           = false
            queue_on_source_update_only = true
            valid_duration              = 720

          ~ scope {
                match_type     = "Exact"
              ~ repository_id  = "105bb7b9-1d25-48ff-ae9f-d6062e306200" -> "0a14d67f-03b0-4045-9609-f2f79e0447d5"
                repository_ref = "refs/heads/master"
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azuredevops_branch_policy_build_validation.bp: Destroying... [id=1473]
azuredevops_branch_policy_build_validation.bp: Destruction complete after 0s
azuredevops_branch_policy_build_validation.bp: Creating...

Error: Error creating policy in Azure DevOps: TF402457: The settings for this policy are not correctly formatted. Error: The build pipeline 1161 was not found.

  on main.tf line 68, in resource "azuredevops_branch_policy_build_validation" "uv-devops":
  68: resource "azuredevops_branch_policy_build_validation" "uv-devops" {
```

### Expected Behavior

Original branch policy steel available

### Actual Behavior

Original branch policy has been deleted, but the new policy didn't create. And we lost the data

### Steps to Reproduce

1. Import or create a resource
1. Change `repository_id` and `project_id`
1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @patr00n , The branch policy is bind with a  project. If you change the project ID. In Terraform's perspective, the branch policy is not longer needed and should be destroyed. After the old branch policy destroyed, a new one will be created.
If you want create multiple projects, you can use [foreach](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/)

**Comment by patr00n** [comment]
I think provider should restore destroyable resources when creating a new one is failed, or maybe it should check creation compliances during the `plan`, isn't it?

**Comment by xuzhang3** [comment]
> I think provider should restore destroyable resources when creating a new one is failed, or maybe it should check creation compliances during the `plan`, isn't it?

You create a new resource with a different name, after you create the new resource successful, then you can delete the old one.

**Comment by xuzhang3** [comment]
@patr00n  [resource lifecycle](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations) may help you.

**Comment by patr00n** [comment]
> @patr00n  [resource lifecycle](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations) may help you.

I didn't know about that functionality. Thanks
