### ISSUE TITLE
Not able to understand how user_entitlement is being used in azure_devops

### ISSUE THREAD

**Issue by omkarsrcm** [microsoft/terraform-provider-azuredevops#611]
Hello Team,
i have been trying to automate and manage complete azure devops via terraform.I have following issue.
1. i could not understand why we have to use user_entitlement.Did not understand it.Doc just say it used to managed users in azure devops and there permission
2. My doubt is suppose i already have set of users added in azure devops organisation along with proper lic(basic).
3. Now i want to fetch user's id so i can use them in the auto-reviewer-add option.
4. But when i use Data Source: azuredevops_users.It does not output the correct the user-id.
5. My point is if i already have user present.How can i fetch there correct user id rather again going and running azuredevops_user_entitlement
6. As per my understand i see azuredevops_user_entitlement is technically adding/creating the user in organisation. Correct me if i am wrong?
Requesting for please help on this.As its blocking me out.

**Comment by xuzhang3** [comment]
@omkarsrcm   Not all API returns the user  ID, in some scenario, ADO return  `descriptor` as the use ID and it can be convert to ID with API(API: https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/storage-keys/get?view=azure-devops-rest-6.0). 
data source `azuredevops_users` support  convert the `descriptor` to ID, Example:
```hcl
data "azuredevops_users" "example" {
  principal_name = "test@test.com"
}

output "ddd" {
  value =tolist(data.azuredevops_users.example.users)[0].id
}

```

**Comment by dtap001** [comment]
It works!! Thanks @xuzhang3 !! <3
