### ISSUE TITLE
Deleting project outside of terraform causes apply to fail

### ISSUE THREAD

**Issue by larsmaes-sogeti** [microsoft/terraform-provider-azuredevops#614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.25.0
+ provider registry.terraform.io/hashicorp/azurerm v3.11.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/microsoft/azuredevops v0.2.1

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl

terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "~>0.2"
    }
  }
}

provider "azuredevops" {
  # Configuration options
}

resource "azuredevops_project" "project a" {
  name               = "project a"
  work_item_template = "Scrum"
  description        = "Project A"
  version_control    = "Git"
  visibility         = "private"
}
```

### Debug Output

(https://gist.github.com/larsmaes-sogeti/beaf737506280aa0200dcab67af087c5)

### Expected Behavior

the deletion of the project should be recognized, and a recreation should be triggered

### Actual Behavior

apply fails with an error during refreshing state:

Error: Error looking up project with ID e51a88cb-8024-48b7-a797-45b7c9cdb1e2 and Name project a

### Steps to Reproduce

1. `terraform apply`
2. in azure devops, remove the created project
3. `terraform apply`

**Comment by xuzhang3** [comment]
`404` should be handled  as special error.
