### ISSUE TITLE
Add "Path filter" support for repository build policy

### ISSUE THREAD

**Issue by patr00n** [microsoft/terraform-provider-azuredevops#62]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add missing `filenamePatterns` arguments block 
https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/create?view=azure-devops-rest-5.1
### New or Affected Resource(s)
* azuredevops_branch_policy_build_validation

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_build_validation" "p" {
  project_id = azuredevops_project.p.id

  settings {
    display_name        = "Don't break the build!"
    build_definition_id = azuredevops_build_definition.b.id

    scope {
      repository_id  = azuredevops_git_repository.r.id
      repository_ref = azuredevops_git_repository.r.default_branch
      match_type     = "Exact"
    }

    filename_patterns [
      "/WebApp/*",
      "!/WebApp/Tests/*",
      "*.cs",
    ]
  }
}
```

**Comment by cmielke** [comment]
I see that this issue has been merged and closed. How do I get a version of the provider that includes this change?

**Comment by EliiseS** [comment]
@cmielke You'd need to build and install the provider from the source code. The instructions can be found here: https://github.com/microsoft/terraform-provider-azuredevops/blob/master/docs/contributing.md#3-build--install-provider
