### ISSUE TITLE
Handle Service Connection access tokens correctly

### ISSUE THREAD

**Issue by awkwardindustries** [microsoft/terraform-provider-azuredevops#62]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.9
(unreleased) Azure DevOps Provider v0.0.1

### Affected Resource(s)

* `resource_serviceendpoint.go`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_project" "project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_pipeline" "pipeline" {
  project_id    = azuredevops_project.project.id
  pipeline_name = "Test Pipeline"

  repository {
    repo_type             = "GitHub"
    repo_name             = "nmiodice/terraform-azure-devops-hack"
    branch_name           = "master"
    yml_path              = "azdo-api-samples/azure-pipeline.yml"
    service_connection_id = azuredevops_serviceendpoint.github_serviceendpoint.id
  }
}

resource "azuredevops_serviceendpoint" "github_serviceendpoint" {
  project_id             = azuredevops_project.project.id
  service_endpoint_name  = "GitHub Service Connection"
  service_endpoint_type  = "github"
  service_endpoint_url   = "http://github.com"
  service_endpoint_owner = "Library"
}
```

### Debug Output

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azuredevops_project.project: Refreshing state... [id=XXX]
azuredevops_serviceendpoint.github_serviceendpoint: Refreshing state... [id=XXX]
azuredevops_pipeline.pipeline: Refreshing state... [id=XXX]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azuredevops_serviceendpoint.github_serviceendpoint will be updated in-place
  ~ resource "azuredevops_serviceendpoint" "github_serviceendpoint" {
      + github_service_endpoint_pat = (sensitive value)
        id                          = "XXX"
        project_id                  = "XXX"
        service_endpoint_name       = "GitHub Service Connection"
        service_endpoint_owner      = "Library"
        service_endpoint_type       = "github"
        service_endpoint_url        = "http://github.com"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

### Expected Behavior

When executing a `terraform apply` followed immediately by a `terraform plan`, there should be no changes to the `azuredevops_serviceendpoint.github_serviceendpoint` resource as nothing has changed.

### Actual Behavior

Because the Azure DevOps Go API's reads against a service endpoint never return the accessToken value, Terraform believes that value has changed and will attempt to update the resource. This should be handled differently so that Terraform does not always attempt to modify the resource.

Example response for the authorization section of a Service Connection created with a valid PAT:
```json
  "authorization": {
    "parameters": {
      "accessToken": null
    },
    "scheme": "PersonalAccessToken"
  },
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #4 (Read)
* #5 (Update)

**Comment by nmiodice** [comment]
Some thoughts (from a non-security guru)...

Cryptographic salt (https://www.terraform.io/docs/providers/random/r/string.html, https://www.terraform.io/docs/providers/random/r/password.html) could be used along with a hash...

https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/

**Comment by ThePhen** [comment]
Here's the approach I'd like to try @nmiodice : 

### Goal

To compare inbound state changes against
 previously stored bcyrpted hashed secrets. If 
 secret values aren't changing, help TF to see
 it that way.
 
### See: 
* [Customized Diff](https://www.terraform.io/docs/extend/resources/customizing-differences.html)
* [Resource Diff](https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#ResourceDiff)

### Narrative
The code change will use diff handling features of TF schema to
signal a secret change only when: 
* there is a secret specified, and
* either of:
    * there is no previously stored hash for that secret
    * the previously stored hash doesn't equal a hash of an inbound secret value

Upon creating/updating (writing) a secret to a resource, a hash of the secret is retained in tfstate.

**Comment by nmiodice** [comment]
Neat! In the approach, do we ever store the raw secret to state?

**Comment by nmiodice** [comment]
And do you forsee the need to add a salt? I'm not super well versed in the security around all this, would love to hear your thoughts

**Comment by KeithJRome** [comment]
You would only store the hash and salt in state, otherwise it would be a major security flaw. Never store a raw authentication credential unless you're using something designed especially for that purpose.

For sure, salting would add some measure of protection from dictionary-based cracks and probably _should_ be done, but this might not be secure enough depending on how much of a risk the exposed secret would pose. At the point when you consider upgrading further from a simple salted hash you should probably get input from a security pro because it's a very easy thing to mess up.

It's great to be thinking about these things early though! Better to handle it properly now, than to fail a sec audit later.

**Comment by ThePhen** [comment]
We would not store a secret in persistent state. We'd store a bcrypt (one-way) hash of the secret. bcrypt uses salt, so a salt value is required.

The salt would be selected at random and stored with the hash in state.

**Comment by nmiodice** [comment]
This sounds great. I think we can go forward with writing this up into a doc of some kind and adding it to `./docs` and linking from the contributing document so that it can be easily found.

Great approach!
