### ISSUE TITLE
azuredevops_serviceendpoint_aws - secret_access_key appears empty in state file

### ISSUE THREAD

**Issue by alexMagicBeans** [microsoft/terraform-provider-azuredevops#629]
Hello, I'm having issues with the resource : **azuredevops_serviceendpoint_aws**

Basically, I'm creating a IAM user and associate his credentials with a service connection in Azure Devops all using terraform.

The problem is: In state file: 
            "type": "aws_iam_access_key" has the access key and secret access key values correct.

But, on type:
            "type": "azuredevops_serviceendpoint_aws"
the secret key is empty like this:
    "secret_access_key": ""
The Access key appears correctly;

Sample code:
resource "aws_iam_access_key" "key" {
  user = aws_iam_user.iamuser.name
}

resource "azuredevops_serviceendpoint_aws" "sc" {
  project_id            = data.azuredevops_project.repo.id
  service_endpoint_name = var.endpointname
  access_key_id         = aws_iam_access_key.key.id
  secret_access_key     = aws_iam_access_key.key.secret
  description           = var.descriptionEndpoint
}

Any ideia why the secret key appears empty in the Endpoint resource of the state file but shows the real value on the access key side type?

I noticie something was wrong because I was getting AWS errors related with lacked of permissions while using the service connection

**Comment by tiagoarrulo** [comment]
I'm having the same issue

**Comment by xuzhang3** [comment]
@alexMagicBeans this is by design, the `secret_access_key` is encoded and stored in `secret_access_key_hash`
