### ISSUE TITLE
`azuredevops_build_definition` does not report build status to Bitbucket by default

### ISSUE THREAD

**Issue by edwardwu-servian** [microsoft/terraform-provider-azuredevops#63]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

terraform 0.12.28
azuredevops 0.0.1

### Affected Resource(s)

* `azuredevops_build_definition`

### Terraform Configuration Files

```hcl
resource "azuredevops_build_definition" "example" {
  project_id      = azuredevops_project.module.id
  name            = "${var.pipeline_name}"
  path            = "\\"
  agent_pool_name = var.agent_pool_name

  ci_trigger {
    use_yaml = true
  }

  pull_request_trigger {
    use_yaml = true

    forks {
      enabled       = false
      share_secrets = false
    }
  }

  repository {
    repo_id               = "${bitbucket_repository.module.owner}/${bitbucket_repository.module.name}"
    repo_type             = "Bitbucket"
    branch_name           = "master"
    service_connection_id = azuredevops_serviceendpoint_bitbucket.bitbucket.id
    yml_path              = "/azure-pipeline.yml"
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The pipeline should be created with "Report build status" enabled, this is the behavior if pipeline is created on the web frontend.

### Actual Behavior

Pipeline is created, however, "Report build status" is not enabled. 
![image](https://user-images.githubusercontent.com/65932538/86857894-dc662b00-c102-11ea-9fdc-9ade7813d680.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

- https://www.terraform.io/docs/providers/azuredevops/r/build_definition.html

* #0000

**Comment by xuzhang3** [comment]
Hi @edwardwu-servian Thanks for your suggestion, We will put this in our backlog.

**Comment by xuzhang3** [comment]
Closing this issue. Feel free to reopen it if anyone have questions

**Comment by dperezro-ins** [comment]
@xuzhang3 what about `az pipeline create` command? the default is unchecked. Is this something that can be changed as well? Thanks!

Edit: oh sorry, this is the terraform provider. Do you know who could work it for the `az` CLI? thank you

**Comment by xuzhang3** [comment]
@dperezro-ins   you can open issue at https://github.com/Azure/azure-devops-cli-extension
