### ISSUE TITLE
azuredevops_variable_group - can't datasource secret value

### ISSUE THREAD

**Issue by dza89** [microsoft/terraform-provider-azuredevops#630]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  org_service_url = "https://dev.azure.com/my-org/"
}

terraform {
  required_providers {
    azuredevops = {
      source = "microsoft/azuredevops"
      version = ">=0.2.2"
    }
  }
}

data "azuredevops_project" "my_project" {
  name = "my-project"
}

data "azuredevops_variable_group" "test_credentials" {
  project_id = data.azuredevops_project.my_project.id
  name       = "test-group"
}

output "test_credentials" {
   value = data.azuredevops_variable_group.test_credentials.variable
}
```

### Debug Output

https://gist.github.com/dza89/372e24c46f51bbf8d590d448d8e62662

### Expected Behavior

Should have retrieved the secret value

### Actual Behavior

Secret value is empty

### Steps to Reproduce

1. Create a variable group with a secret_value.
2. Use hcl above.
3. `terraform apply`

### References

* #0000

**Comment by dza89** [comment]
Variable group layout:
![afbeelding](https://user-images.githubusercontent.com/20373984/184832531-250f6b6f-024d-4c06-8be1-3ec09398eee5.png)

**Comment by xuzhang3** [comment]
@dza89 this is service behavior, sensitive data like secret, password etc. cannot be get though API

**Comment by dza89** [comment]
Shouldnt this be in the docs then? Why is this provider then capable of outputting the secret value at all then?

**Comment by dza89** [comment]
Thanks, closing this.
