### ISSUE TITLE
azuredevops_serviceendpoint_azurerm - support for environment

### ISSUE THREAD

**Issue by bnchou** [microsoft/terraform-provider-azuredevops#636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azuredevops_serviceendpoint_azurerm doesn't allow to create an azurerm service endpoint for gov cloud, can we have the environment accessible to the provider

### New or Affected Resource(s)

* azuredevops_serviceendpoint_azurerm

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_azurerm" "config" {
  project_id             = var.project.id
  service_endpoint_name = var.service_endpoint_name
  environment         = "AzureUSGovernment"
  description           = "Managed by Terraform"

  credentials {
    serviceprincipalid  = var.service_principal_id
    serviceprincipalkey = var.service_principal_key
  }

  azurerm_spn_tenantid      = data.azurerm_subscription.current.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.current.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.current.display_name
}
```

### References

* #600 
* #527

**Comment by miaooss** [comment]
This seems to be fix using `azuredevops_serviceendpoint_azurerm`

**Comment by xuzhang3** [comment]
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_azurerm#environment
