### ISSUE TITLE
0.2.3 Release Schedule / Preparation

### ISSUE THREAD

**Issue by bobmhong** [microsoft/terraform-provider-azuredevops#637]
@xuzhang3 - Is there a tentative schedule for the next release of the provider? Are there any tasks that could be done by community members to help prepare for the release? I'm able to assist if needed.

**Comment by xuzhang3** [comment]
@bobmhong sorry for the delay, there's not too much new resources/enhance/bug fix since last release,  v0.2.3 will be pending
