### ISSUE TITLE
Error: error creating resource Build Definition: Agent pool Azure Pipelines was not found.

### ISSUE THREAD

**Issue by alinuxguru70** [microsoft/terraform-provider-azuredevops#647]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azuredevops_build_definition

### Terraform Configuration Files

```hcl
# Create a pipeline from the new fork
resource "azuredevops_build_definition" "build" {
  project_id      = data.azuredevops_project.ado_project.id
  name            = data.azurerm_subscription.current.display_name
  agent_pool_name = var.ADO_AGENT_POOL
  path            = "\\${var.target}\\${var.apm_id}"

  ci_trigger {
    use_yaml = true
  }

  repository {
    repo_type           = "TfsGit"
    repo_id             = azuredevops_git_repository.repo.id
    branch_name         = azuredevops_git_repository.repo.default_branch
    yml_path            = "azure-pipelines.yaml"
    report_build_status = true
  }
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```log
Error: error creating resource Build Definition: Agent pool tf-vmss-agent-pool-test was not found.

  with azuredevops_build_definition.build,
  on main.tf line 77, in resource "azuredevops_build_definition" "build":
  77: resource "azuredevops_build_definition" "build" {

```
### Expected Behavior

The yml pipeline should be created, yet errors out with the latest azuredevops provider

### Actual Behavior
```log
Error: error creating resource Build Definition: Agent pool tf-vmss-agent-pool-test was not found.

  with azuredevops_build_definition.build,
  on main.tf line 77, in resource "azuredevops_build_definition" "build":
  77: resource "azuredevops_build_definition" "build" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@alinuxguru70  `Azure Pipelines` is the default agent pool for free.  To restrict the pipeline running in the specific agent pool, you should create an agent pool the this pipeline.  You can manage the agent pool at `Project settings -> Agent pools`

**Comment by alinuxguru70** [comment]
> @alinuxguru70 `Azure Pipelines` is the default agent pool for free. To restrict the pipeline running in the specific agent pool, you should create an agent pool the this pipeline. You can manage the agent pool at `Project settings -> Agent pools`

The issue is not the choice of agent pools.   The issue is I cannot create an azuredevops_build_definition resource using **ANY** agent pool.   I have a self hosted agent which also fails.      If I send azuredevops_agent_pools information to outputs, it returns null data.

2022-10-11T12:37:01.4823299Z   "resources": [
2022-10-11T12:37:01.4823591Z     {
2022-10-11T12:37:01.4823827Z       "mode": "data",
2022-10-11T12:37:01.4824197Z       "type": "azuredevops_agent_pools",
2022-10-11T12:37:01.4824519Z       "name": "agent_pools",
2022-10-11T12:37:01.4824981Z       "provider": "provider[\"registry.terraform.io/microsoft/azuredevops\"]",
2022-10-11T12:37:01.4825418Z       "instances": [
2022-10-11T12:37:01.4825663Z         {
2022-10-11T12:37:01.4826187Z           "schema_version": 0,
2022-10-11T12:37:01.4826479Z           "attributes": {
2022-10-11T12:37:01.4826829Z             "agent_pools": [],
2022-10-11T12:37:01.4827419Z             "id": "2022-10-10 17:43:38.47807163 +0000 UTC"
2022-10-11T12:37:01.4827820Z           },
2022-10-11T12:37:01.4828093Z           "sensitive_attributes": []
2022-10-11T12:37:01.4828429Z         }
2022-10-11T12:37:01.4828644Z       ]
2022-10-11T12:37:01.4828920Z     },

**Comment by xuzhang3** [comment]
@alinuxguru70 how do you create agent pool with `azuredevops_agent_pools`, you need set `auto_provision = true` otherwise the agent pool will only be available to ORG not project.

**Comment by alinuxguru70** [comment]
Thank you.    The issue was that the build agent account did not have Build Administrators permissions to the project.   Once that was resolved, the issue was resolved
