### ISSUE TITLE
Cannot add Azure AD group to team members or administrators

### ISSUE THREAD

**Issue by Ahzekri** [microsoft/terraform-provider-azuredevops#649]

**Comment by xuzhang3** [comment]
@Ahzekri can you share your script? This can help us reproduce and solve this issue.

**Comment by xuzhang3** [comment]
To add the group as a team's members or administrators, you need the group's `dfescriptor` which is not support in v0.2.2. #648 will export the `descriptor` then you can add the group as the team member
