### ISSUE TITLE
Azure devops pipeline is failing to create "azuredevops_serviceendpoint_kubernetes"

### ISSUE THREAD

**Issue by pdarji-bakkt** [microsoft/terraform-provider-azuredevops#652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops = >=0.1.0`
* `terraform = v1.0.10` 
*  `terraform = v1.2.2` # with azure devops pipeline

### Terraform Configuration Files

```hcl
# azdo_provider.tf
provider "azuredevops" {
  org_service_url       = var.org_service_url
  personal_access_token = var.AZDO_PERSONAL_ACCESS_TOKEN
}

# versions.tf
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    google = {
      source = "hashicorp/google"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
    restapi = {
      source  = "fmontezuma/restapi"
      version = "1.14.1"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.82.0"
    }
  }
}

# azdo.tf
resource "azuredevops_serviceendpoint_kubernetes" "svc_conn" {
  for_each              = resource.kubernetes_namespace.namespaces
  project_id            = var.azdo_project_id
  service_endpoint_name = "${each.key}-sc"
  apiserver_url         = "https://${resource.google_container_cluster.primary.endpoint}"
  authorization_type    = "ServiceAccount"

  service_account {
    token   = resource.kubernetes_secret.k8s_secrets[resource.kubernetes_namespace.namespaces[each.key]].data.token
    ca_cert = resource.kubernetes_secret.k8s_secrets[resource.kubernetes_namespace.namespaces[each.key]].data["ca.crt"]    
  }
}
```

### Steps to Reproduce

1. `terraform plan` or
2. Running Azure devops yml pipeline

### Important Factoids

I'm trying to create 'azuredevops_serviceendpoint_kubernetes' to connect to GKE cluster using devops pipeline and/or terraform plan.

ERROR:
[ERROR] vertex "provider[\"registry.terraform.io/microsoft/azuredevops\"]" error: The resource cannot be found.
Error: The resource cannot be found.

  with provider["registry.terraform.io/microsoft/azuredevops"],
  on azdo_provider.tf line 1, in provider "azuredevops":
   1: provider "azuredevops" {

**Comment by xuzhang3** [comment]
@pdarji-bakkt  I cannot reproduce this error. Any other  error messages?  Can you successfully  run `terraform plan` with HCL: 
```hcl

data "azuredevops_project" "test" {
  name = "ADDTest"
}

# azdo.tf
resource "azuredevops_serviceendpoint_kubernetes" "svc_conn" {
  project_id            = data.azuredevops_project.test.id
  service_endpoint_name = "xz3-sc"
  apiserver_url         = "https://www.google.com"
  authorization_type    = "ServiceAccount"


  service_account {
    token   = "test"
    ca_cert = "test"
  }
}
```

**Comment by pdarji-bakkt** [comment]
@xuzhang3 Thanks for looking into this issue.
I've made suggested changes, however, I'm still seeing the same error. Here is the file layout:
- Env
  - dev
     - myapp
        - myapp-gke (folder)
   	    backend.tf
   	    outputs.tf
   	    variables.tf
   	    terraorm.tfvars
   	    azdo_provider.tf
- Module
   - gke-private-cluster (folder)
 	  azdo_provider.tf
 	  azdo.tf
 	  variables.tf
 	  versions.tf	# Terraform version and other providers are here
 	  other GKE .tf files

I tried to remove azdo_provider.tf files from each location at a time, and tried with both location. Still no luck.

**Comment by xuzhang3** [comment]
@pdarji-bakkt  Can you share your script?  I also tried the script at https://github.com/microsoft/terraform-provider-azuredevops/issues/449#issuecomment-1130100678, but no errors.

**Comment by pdarji-bakkt** [comment]
> @pdarji-bakkt Can you share your script? I also tried the script at [#449 (comment)](https://github.com/microsoft/terraform-provider-azuredevops/issues/449#issuecomment-1130100678), but no errors.

Here is the code
[https://github.com/pdarji-bakkt/azdo_gcp](url)

**Comment by pdarji-bakkt** [comment]
> 

The issue is resolved. I'll update the code

**Comment by xuzhang3** [comment]
good to see this issue resolved.
