### ISSUE TITLE
Plugin crashed!

### ISSUE THREAD

**Issue by AndrewHuddleston** [microsoft/terraform-provider-azuredevops#655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hitting the below error from Azure China. This is working from all our America regions.

│ Error: Plugin did not respond
│ 
│   with module.shared-cluster.azuredevops_serviceendpoint_kubernetes.se_azure_sub,
│   on ../../../pipeline-lib/terraform/azure/shared-cluster/shared-cluster.tf line 261, in resource "azuredevops_serviceendpoint_kubernetes" "se_azure_sub":
│  261: resource "azuredevops_serviceendpoint_kubernetes" "se_azure_sub" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.5
azuredevops =0.1.8

(yes I tried upgrading both to latest same error)

### Affected Resource(s)

* azuredevops_serviceendpoint_kubernetes

### Panic Output

```panic: interface conversion: interface {} is nil, not []interface {}

goroutine 53 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.expandServiceEndpointKubernetes(0xc0008482a0, 0x7000100, 0x0, 0xffffffffffffffff, 0xc0006b97e0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_kubernetes.go:211 +0x197f
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointUpdateFunc.func1(0xc0008482a0, 0x1bdd7e0, 0xc0003dc000, 0x0, 0x0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:219 +0x51
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000366500, 0xc000225ea0, 0xc0008920c0, 0x1bdd7e0, 0xc0003dc000, 0x1c6b301, 0xc00020ef88, 0xc00058a090)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:326 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00005cd80, 0xc0006b9a38, 0xc000225ea0, 0xc0008920c0, 0xc00054fdd8, 0xc0008eb601, 0x1c6da40)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000116b10, 0x1fd59b0, 0xc000a5e9c0, 0xc000848460, 0xc000116b10, 0xc000a5e9c0, 0xc00016aba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1d8d040, 0xc000116b10, 0x1fd59b0, 0xc000a5e9c0, 0xc000268a20, 0x0, 0x1fd59b0, 0xc000a5e9c0, 0xc000aa0000, 0x9ff0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00063c1c0, 0x1fe3918, 0xc0005c3500, 0xc00011c700, 0xc000426570, 0x25ce580, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00063c1c0, 0x1fe3918, 0xc0005c3500, 0xc00011c700, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000038250, 0xc00063c1c0, 0x1fe3918, 0xc0005c3500, 0xc00011c700)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-azuredevops_v0.1.8 plugin crashed!
```

### Expected Behavior

For the plugin not to crash

### Actual Behavior

Crashes with this error every time from Azure China region

### Steps to Reproduce

1. `terraform apply from Azure China Region`

### Important Factoids

Running in a Azure China but ADO is in AMAP region

### References

https://github.com/microsoft/terraform-provider-azuredevops/issues/460

**Comment by xuzhang3** [comment]
@AndrewHuddleston #638 have fixed this issue, but not released.

**Comment by diegolagospagopa** [comment]
People it would be very helpful if we could have this issue released, we are having a lot of colleagues who are stuck with plugin crashes.

Thank you for the work you have put into it

**Comment by xuzhang3** [comment]
@diegolagospagopa [v0.3.0](https://registry.terraform.io/providers/microsoft/azuredevops/0.3.0)  has been released
