### ISSUE TITLE
Add support for the SonarCloud service endpoint

### ISSUE THREAD

**Issue by martenvd** [microsoft/terraform-provider-azuredevops#657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to roll out my SonarCloud service endpoints through terraform, for I need to have it implemented on multiple projects and don't want to do so by hand.

### New or Affected Resource(s)

New resource: #658 

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_sonarcloud" "example" {
  project_id = var.project_id
  service_endpoint_name  = "Example SonarCloud"
  token = "XXXXXXXXXXXXXXXX"
  description = "Managed by Terraform"
}
```

**Comment by xuzhang3** [comment]
@martenvd got error when run Acctests:
```log
Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'sonarcloud' using authentication scheme 'UsernamePassword'.
```

**Comment by martenvd** [comment]
The resource has been merged, I'll close this issue, thanks!
