### ISSUE TITLE
Add Work Item Resource

### ISSUE THREAD

**Issue by IronMania** [microsoft/terraform-provider-azuredevops#660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to track workitems for an Azure Devops project with Terraform.

### New or Affected Resource(s)

* azuredevops_workitem

### Potential Terraform Configuration

```hcl
resource "azuredevops_workitem" "example" {
  title = "Testing Terraform with"
  project = "9a6ec7fd-a679-4b11-af60-0b1fc8cae540"
  type = "Issue"
  custom_fields = {
    foo = "SomeCustomField"
  } 
  state = "To Do"
  tags = ["tag1"]
}

```

### References

I created a pull request
https://github.com/microsoft/terraform-provider-azuredevops/pull/659

**Comment by IronMania** [comment]
I am thinking. Could it be better to have a desired state for a ticket?
This way one could track that the ticket is correctly created, when it is done as example.

In our case we have a ticket workflow and I want to create a ticket and I want that the Ticket went to done.
So that the read is only accepting it as complete when desired value matches the actual state of the Ticket.
Something like this:
```
resource "azuredevops_workitem" "example" {
  title = "Testing Terraform with"
  project = "9a6ec7fd-a679-4b11-af60-0b1fc8cae540"
  type = "Issue"
  custom_fields = {
    foo = "SomeCustomField"
  } 
 state = {
     value = "To Do"
     desired = true
    }
}
```

What do you think about this?

**Comment by taljundi** [comment]
How can you add a description to the workItem?

**Comment by IronMania** [comment]
actually you can't
not implemented. but should be easy to implement

**Comment by xuzhang3** [comment]
Supported: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/workitem
