### ISSUE TITLE
Add support for the SNYK service endpoint

### ISSUE THREAD

**Issue by JoshStead** [microsoft/terraform-provider-azuredevops#664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to create a SYNK service connection using Terraform. Currently there is no resource in the latest provider. 

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_snyk" "example" {
  project_id = var.project_id
  service_endpoint_name  = "Example SNYK"
  api_token = "XXXXXXXXXXXXXXXX"
  description = "Managed by Terraform"
}
```

**Comment by xuzhang3** [comment]
@JoshStead   Is the extension already installed by default or users need to install the extension before using it? 
Is this the  resource https://marketplace.visualstudio.com/items?itemName=synker.synker-tools?

**Comment by JoshStead** [comment]
Hello @xuzhang3 

Sorry, i spelt it wrong! - it's this: https://marketplace.visualstudio.com/items?itemName=Snyk.snyk-security-scan

**Comment by grimmxsleeper** [comment]
+1 this would be highly useful for me
