### ISSUE TITLE
"Default" project-named Repo deletion by terraform in code

### ISSUE THREAD

**Issue by UnlimitedValue** [microsoft/terraform-provider-azuredevops#665]
Dear all,

I would like to have only my "defined" repository **with resource "azuredevops_git_repository"** and not have the system generated one uninitalized with project name, is it possible on code level somehow? 

Could you please help me to find this answer ?

Thank you in advance,

**Comment by xuzhang3** [comment]
@UnlimitedValue The default repo was created by service not Terraform.

**Comment by xuzhang3** [comment]
Every newly created project requires at least one repository, this is by design. Therefore, you can manage the default repository through the data source, or delete the default repository after creating a new repository.
