### ISSUE TITLE
Add minimum number of reviewers to azuredevops_branch_policy_auto_reviewers 

### ISSUE THREAD

**Issue by jan-mrm** [microsoft/terraform-provider-azuredevops#667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to set the minimum number of required reviewers in a `azuredevops_branch_policy_auto_reviewers` resource.

The interesting point is that, at least using the Azure DevOps WebUI, setting the minimum number is only possible when `reviewers` is exactly set to one group. This behavior is described in the WebUI and at https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#automatically-include-code-reviewers

>"If only one group is required, the minimum number of members you specify approve the changes."

*Note*: I'm aware of the `azuredevops_branch_policy_min_reviewers` resource, but I would like to only set two required reviewers for changes under certain paths, thus having to use the `azuredevops_branch_policy_auto_reviewers` resource (as far as I know).

### New or Affected Resource(s)

* azuredevops_branch_policy_auto_reviewers

### Potential Terraform Configuration

copied from the current example code and added `minimum_reviewers` and changed to reference a group (https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/branch_policy_auto_reviewers)
```hcl
resource "azuredevops_branch_policy_auto_reviewers" "example" {
  project_id = azuredevops_project.example.id

  enabled  = true
  blocking = true

  settings {
    auto_reviewer_ids  = [azuredevops_group.example.origin_id]
    submitter_can_vote = false
    message            = "Auto reviewer"
    path_filters       = ["*/src/*.ts"]
    minimum_reviewers  = 2

    scope {
      repository_id  = azuredevops_git_repository.example.id
      repository_ref = azuredevops_git_repository.example.default_branch
      match_type     = "Exact"
    }
  }
}
```

### References

* https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#automatically-include-code-reviewers

**Comment by xuzhang3** [comment]
Config the minimum number of required reviewers is only available when the reviews is set to a group.
