### ISSUE TITLE
Unit test names do not follow the recommended structure from HashiCorp

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#67]
The unit test structure, while valid, does not follow the structure recommended by Hashicorp.

As we will soon need to integrate with Hashicorp's CI/CD process, we need to move more towards their approach to ensure consistency across the providers.

The convention is described here: https://www.terraform.io/docs/extend/testing/unit-testing.html

## Acceptance criteria
 - [ ] Re-name tests to match the recommended structure

**Comment by ThePhen** [comment]
It looks like this work is mostly:
- [ ] renaming `go` files, as needed (this seems to be OK with the current test files that I see), and
- [ ] renaming test functions to match the `Test<Provider>_<Test Name>` idoim.
