### ISSUE TITLE
Project repositories setting for default branch is superseded

### ISSUE THREAD

**Issue by jandias** [microsoft/terraform-provider-azuredevops#678]
With [this code](https://github.com/microsoft/terraform-provider-azuredevops/blob/369a53b24013ca15e6a2afb3fb12767f1d25d869/azuredevops/internal/service/git/resource_git_repository.go#L284), the value set for a project as a default branch on new repositories is lost and replaced by this hard coded value "master".

See setting help here:
https://learn.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops&tabs=browser#default-branch-name

**Comment by MaxAnderson95** [comment]
Any updates on this? It would be nice if this could be specified as part of the initialization block for a repo.

**Comment by rw-hardin** [comment]
Yes, this is an issue when the Organization/Project define "main" as the default branch, but the provider creates a "master" branch anyway. Expected behavior is that the provider respects the "Default branch for new repositories" setting when enabled.

**Comment by xuzhang3** [comment]
Latest release will honor the configuration instead of being set by the project-repository settings
