### ISSUE TITLE
Crash report when creating service connection with service account type

### ISSUE THREAD

**Issue by rena0157** [microsoft/terraform-provider-azuredevops#682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.31.0
+ provider registry.terraform.io/hashicorp/azurerm v3.37.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/microsoft/azuredevops v0.3.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.1
```

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurecr`

### Panic Output

[Panic Gist](https://gist.github.com/rena0157/466d3d42f3590d29e1bb0352c5b36dcb)

### Expected Behavior

Create a new azure aks service endpoint using the service account auth type.

### Actual Behavior

Crashed on `terraform apply`

**Comment by xuzhang3** [comment]
similar issue #679
