### ISSUE TITLE
Issue when destroying an ADO group with a linked ADO Group

### ISSUE THREAD

**Issue by Tolbin10088** [microsoft/terraform-provider-azuredevops#685]
Hi @xuzhang3   - @josh-barker-coles  has an example of how to do that in issue #51 

This successfully links an AAD group to an Azure DevOps team.

We found in tetsing that subsequent removal of the resource removes ALL references to the group in the Org. This seems to be because you can't set both a scope and an origin_id ( based on this comment ) :

[https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group]

scope - (Optional) The scope of the group. A descriptor referencing the scope (collection, project) in which the group should be created. **If omitted, will be created in the scope of the enclosing account or organization.x**

origin_id - (Optional) The OriginID as a reference to a group from an external AD or AAD backed provider. The scope, mail and display_name arguments cannot be used simultaneously with origin_id.

This seems to be an API limitation.
For now we are using a lifecycle block to stop this from causing damage!

_Originally posted by @a30000931 in https://github.com/microsoft/terraform-provider-azuredevops/issues/417#issuecomment-915040004_

**Comment by xuzhang3** [comment]
@Tolbin10088  Create new Group without `scope`, the group will be created at the organization level. To manage the AAD group without effect the other project groups you can add a new group in the ADO organization as a shadow of the AAD group, then you can add project groups and add the shadow group to the members.

Example:
```hcl
# organization level group, the shadow group of the AAD group
resource "azuredevops_group" "org_group" {
  origin_id = local.aad_id
  description = "For test"
}

# project 1 start
resource "azuredevops_project" "terraform_ado_project1" {
  name               = "project1"
  description        =  "project1"
}

resource "azuredevops_group" "ado_group_linked_to_ad_group1" {
  scope = azuredevops_project.terraform_ado_project1.id
  display_name = "proj1 group"
  members = [
    azuredevops_group.org_group.descriptor
  ]
}
# project 1 end

# project 2 start
resource "azuredevops_project" "terraform_ado_project2" {
  name               = "project2"
  description        =  "project2"
}

resource "azuredevops_group" "ado_group_linked_to_ad_group2" {
  scope = azuredevops_project.terraform_ado_project2.id
  display_name = "proj2 group"
  members = [
    azuredevops_group.org_group.descriptor
  ]
}
# project 2 end
```
