### ISSUE TITLE
Resource for AWS service connections from Azure DevOps

### ISSUE THREAD

**Issue by coffeedome** [microsoft/terraform-provider-azuredevops#69]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Feature request: Currently using AWS service connections from Azure DevOps. It would be great if we could provision AWS service connections via this provider. It can get tough to provision these connections consistently and scalably.

### New or Affected Resource(s)

Net new resource similar to existing service endpoints that terraform-provider-azuredevops has.

* azuredevops_0.0.1

### Potential Terraform Configuration

```hcl
resource "azuredevops_serviceendpoint_aws" "serviceendpoint" {
  access_key_id               = "aws_access_key_id"
  secret_access_key_id    = "aws_secret_access_key_id"
  session_token               = "aws_session_token" (optional)
  role_to_assume             = "aws_arn_iam_role_to_assume"  (optional)
  external_id                    = "external_id" (optional)
  service_connection_name = "service_connection_name"
  description           = "test" (optional)
  grant_access_all_pipelines  = boolean (default true)
}
```

### References
Screenshot below of Azure DevOps AWS Service Connection:
![image](https://user-images.githubusercontent.com/51391611/87115569-497bdc80-c239-11ea-9495-3577d01a594b.png)

* #0000

**Comment by xuzhang3** [comment]
Hi @estebanes22 `aws_service_connection` has been implemented by @phillebaba. You can find the [PR](https://github.com/terraform-providers/terraform-provider-azuredevops/pull/58) and [issue](https://github.com/terraform-providers/terraform-provider-azuredevops/issues/48) here. I closing this issue as this is a duplicate issue.
