### ISSUE TITLE
azuredevops_git_repository should check on repo name not UUID

### ISSUE THREAD

**Issue by slzmruepp** [microsoft/terraform-provider-azuredevops#694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When we develop with the provider, we want to test out certain things. If we manually delete the repo, the tf run fails because it says, the Repo ID no longer exists. Which means we have manually either prune the resource from the tf state ( terraform state rm) which is only feasable when using terraform cli and not from a forward fixing pipeline. Usually if working with the azurerm provider, if deleting a resource from azure platform, the tf run tries to recreate it. 

Considering, the identification of the azuredevops_git_repository is by the devops_org/devops_project/repo_name (because not two same named repos can exist in the same devops project, this would be much more convinient for developing.

So if I would delete the repo in the azure devops web gui, tf should create a new one and initialize it as long as its in the tf config.

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by xuzhang3** [comment]
@slzmruepp  I cannot reproduce this error. If the repo has been deleted, service will return a 404 error code which has been handled by this provider.  Can you provider the error logs?

**Comment by xuzhang3** [comment]
This issue has been fixed, please update to the latest released version
