### ISSUE TITLE
Please add within azuredevops_build_definition support for azuredevops_serviceendpoint_azurerm (and other azure service endpoints)

### ISSUE THREAD

**Issue by bgmonroe** [microsoft/terraform-provider-azuredevops#704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, the `azuredevops_build_definition` resource only supports GitHub and GitHubEnterprise service connections.
The azuredevops provider, however, can create numerous other service endpoints so I'm surprised that the azuredevops_build_definition resource only supports two of them. 
Please add additional support for at least the azurerm service endpoints, but ideally any others that are supported too.

### New or Affected Resource(s)
This would affect the azuredevops_build_definition resource.

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
resource "azuredevops_build_definition" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Build Definition"
  repository { 
   repo_type              = "TfsGit"
    repo_id               = data.azuredevops_git_repository.id
    branch_name           = azuredevops_git_repository.example.default_branch
    yml_path              = "azure-pipelines.yml"
    service_connection_id = azuredevops_serviceendpoint_azurerm.example.id
    ...  
  }
  ...
}
```

### References

* #0000

**Comment by xuzhang3** [comment]
@bgmonroe   `service_connection_id ` in repository block is used for repository importing.  Can you be more specific about your requirement?

**Comment by bgmonroe** [comment]
I misread the documentation.  Apologies.
