### ISSUE TITLE
error on on-prem Azure Devops Server 2022

### ISSUE THREAD

**Issue by yavasura** [microsoft/terraform-provider-azuredevops#709]
code:
data "azuredevops_group" "Contributors" {
  project_id = azuredevops_project.project.id
  name       = "Contributors"
}

gives error:

Error: Error finding descriptor for project with ID <guid>. Error: API resource location <guid> is not registered on https://<on-prem link to collection>

any ideas?

**Comment by xuzhang3** [comment]
@NorkeviciusThis provider is tested against https://dev.azure.com/ APIS,  not for on-prem Azure DevOps Server. There may be some difference between the same API.

**Comment by mrweiland** [comment]
@xuzhang3 - When are on-premise fully supported? Would really like to have this functionality 👍

**Comment by xuzhang3** [comment]
@mrweiland no plan to provide on-premise support in the near feature
