### ISSUE TITLE
`azuredevops_build_folder_permissions` - microsoft/azuredevops 0.3.0 provider crashed

### ISSUE THREAD

**Issue by george-lloyd** [microsoft/terraform-provider-azuredevops#710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.0.4
hashicorp/azuread: v2.31.0
hashicorp/azurerm: v2.72.0
microsoft/azuredevops: v0.3.0

### Affected Resource(s)

* `azuredevops_project`
* `azuredevops_project_group`
* `azuredevops_project_permissions`
* `azuredevops_build_folder`
* `azuredevops_build_folder_permissions`

### Terraform Configuration Files

```hcl
Provider.tf
terraform {
  required_version = ">= 1.0.4"
  backend "azurerm" {
    resource_group_name  = "xxxx"
    subscription_id      = "xxxx"
    storage_account_name = "xxxx"
    container_name       = "terraformstate"
    key                  = "xxxx"
    access_key           = "xxxx"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.72.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.31.0"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "~> 0.3.0"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = "true"
  features {}
}

provider "azuredevops" {
  org_service_url       = "xxxx"
}

Example sub-module Main.tf

resource "azuredevops_build_folder" "project-build-folder" {
  project_id  = var.project-group-project-id
  path        = var.project-build-folder-path
  description = var.project-build-folder-description
}

module "project-build-folder-permissions" {
  source                          = "./modules/project-build-folder-permissions"
  count                           = length(toset(var.project-groups))
  project-group-project-id        = var.project-group-project-id
  project-build-folder-path       = var.project-build-folder-path
  project-group-name              = "${var.project-name} ${var.project-groups[count.index].project-group-name}"
  project-group-build-permissions = var.project-groups[count.index].project-group-build-permissions
}

```

### Debug Output

https://gist.github.com/george-lloyd-nbs/170964327ff38644838203ea760005e5

### Expected Behavior

terraform destroy should have output a plan to destroy the 109 resources created.

### Actual Behavior

The microsoft/azuredevops plugin crashed, see files.

### Steps to Reproduce
Create full access PAT token, export to env variable as described in docs.

terraform destroy --var-file something.tfvars
Apply TF Config to create Azure DevOps Services organisation level groups linked to AAD.
Apply TF Config to create projects, for each project the same project level groups (linked to organisation scoped groups) and assign permissions. 
Apply TF Config to create azuredevops_build_folder and azuredevops_build_folder_permissions for each project.

### Important Factoids

Full access PAT token is being used.

### References

* #0000

**Comment by xuzhang3** [comment]
@george-lloyd-nb I cannot reproduce this error. Error occurred in `azuredevops_build_folder_permissions`, can you share the module  `project-build-folder-permissions` configuration?

**Comment by george-lloyd** [comment]
@xuzhang3 Please review the latest files added to the gist above, they should aid you in reproducing the issue. Thanks.

**Comment by george-lloyd** [comment]
@xuzhang3 Have I provided enough of the code for you to reproduce?

**Comment by xuzhang3** [comment]
@george-lloyd-nbs still cannot reproduce this error.   Can you remove the `build_permission` and verify if the folder has been created successfully and the path need to grant the permission is exists?

**Comment by george-lloyd** [comment]
@xuzhang3 Given the build folder config for GeorgeTest3 project:

    project-build-folders = [
      {
        project-build-folder-path        = "\\GeorgeTest3_build1"
        project-build-folder-description = "GeorgeTest3 build definitions folder 1"
      },
      {
        project-build-folder-path        = "\\GeorgeTest3_build2"
        project-build-folder-description = "GeorgeTest3 build definitions folder 2"
      },

Only GeorgeTest3_build2 build folder has been created, GeorgeTest3_build1 does not exist.

Within GeorgeTest2 project, both build folders were created.

When trying to reproduce the error yesterday, I created a third test project (GeorgeTest4) and the same behaviour occurred in that only one of the defined build folders was created.

**Comment by shekharshams** [comment]
@xuzhang3 

Hello,

I'm Sharath from the Azure DevOps team.

Can you please prioritize the request as couple of production tasks are pending for George as the above issue is a roadblock.

If you can look into this. It would be helpful :)

Thank you so much for your support so far.

**Comment by xuzhang3** [comment]
@george-lloyd-nbs @shekharshams  I can reproduce and encountered this error when destroying. The permission resource should be destroyed before the folder.   You need add `depends_on = [azuredevops_build_folder.project-build-folder]` in `module "project-build-folder-permissions"`

**Comment by xuzhang3** [comment]
Create:
![image](https://user-images.githubusercontent.com/57888764/219319047-2613c4de-8859-4340-b1b2-6f529aaeddea.png)
Destroy:
![image](https://user-images.githubusercontent.com/57888764/219319196-01beba58-5af6-446d-91c0-cad07f28af37.png)

**Comment by george-lloyd** [comment]
@xuzhang3 I will make the changes and let you know the outcome. Thanks for your support.
I'm surprised Terraform can't implicitly determine this dependency.

**Comment by george-lloyd** [comment]
@xuzhang3 that's fixed the issue. Thank you very much :)

**Comment by shekharshams** [comment]
@xuzhang3 Thank you so much for the help and taking action immediately.

Have a wonderful rest of the day. :)
