### ISSUE TITLE
azuredevops_serviceendpoint_azurerm fails when using $(System.AccessToken) in DevOps pipeline

### ISSUE THREAD

**Issue by y6vmeq** [microsoft/terraform-provider-azuredevops#723]
We create terraform resources (including azuredevops resources) by running Terrafom jobs in DevOps build pipelines. But the azuredevops_serviceendpoint_azurerm resource is not created and crashes with the following error:

```
│ Error: Error creating service endpoint in Azure DevOps: You do not have permission to create a service connection. You need to be a Creator for service connections in this project.
│ 
│ with module.vmss["general"].module.access.azuredevops_serviceendpoint_azurerm.default,
│ on modules/submodules/access/main.tf line 25, in resource "azuredevops_serviceendpoint_azurerm" "default":
│ 25: resource "azuredevops_serviceendpoint_azurerm" "default" {
```
![image](https://user-images.githubusercontent.com/46869350/222564858-06711351-6570-4e5a-847c-430abc9e12ca.png)

We use a system token to connect to azure devops $(System.AccessToken) via yaml pipelines.
The system user (Project Collection Build Service) has (in my opinion) all the necessary rights, and is in all the necessary groups.

![image](https://user-images.githubusercontent.com/46869350/222565974-d4baaabb-49c0-4b29-a6fb-4076ba005478.png)
![image](https://user-images.githubusercontent.com/46869350/222566031-e09fe8f2-1a45-48fa-a7ca-d6acea79a988.png)

This is happening on terraform **1.3.9**, azuredevops provider **0.3.0**.

### **Community Note**

- Please vote on this issue by adding a 👍 response to the original issue to help the community and maintainers prioritize this request.
- Please do not leave "+1" or "me too" comments, they create unnecessary noise for followers of the issue and do not help prioritize the query.
- If you are interested in working on this issue or have submitted a fix request, please leave a comment

**Comment by xuzhang3** [comment]
@y6vmeq `System.AccessToken` has  restricted access permission. Generally recommend run with a custom permissions or full access PAT as there are some permission issue in the backend service. In this case,  you can go `Project Settings -> Service connections ->  3 dots" (top right) -> Security` , add `Project Collection Build Service` the access permissions.
