### ISSUE TITLE
Identify and document a strategy for supporting Azure Repos

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#73]
Currently we have no support for Azure Repos. We need to deep dive into how we can support this with TF. 

# Acceptance criteria
 - [x] Deep dive into the relevant APIs - you need to define these as there may be many - in AzDO to understand what metadata needs to be tracked by Terraform in order to manage repos
 - [x] Break down the implementation into granular stories that can be implemented in 2 days max (ideally 1). Each story should contain relevant findings from this story. For example, if you have a story for "create schema for resource" you should define what that schema is based on your findings. Each implementation story should also include any relevant unit tests and acceptance tests for that piece of functionality

# Related APIs
 - [Git Repos](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/repositories?view=azure-devops-rest-5.0)

**Comment by KeithJRome** [comment]
Breaking this work down into multiple phases:

1. Minor change to existing Project resource's handling of versioncontrol type
2. Define new resource type for git repository
  - Stubs for create/read/update/delete ops
  - Simple schema
3. Stories for implementation of basic CRUD ops
4. Stories for advanced creation scenarios (imported/forked/parented repos)

**Comment by KeithJRome** [comment]
@nmiodice Please review the story breakdown for this and prioritize accordingly. All spawned stories should be showing above as referencing this design task.

**Comment by nmiodice** [comment]
Thanks @KeithJRome !

Some comments:
 - For https://github.com/microsoft/terraform-provider-azuredevops/issues/92 can we add an AC to test that the behavior for defaulting to Git vs TFVC works properly?
 - https://github.com/microsoft/terraform-provider-azuredevops/issues/93 is the `default_branch` optional? if so, what should it default to?
 - https://github.com/microsoft/terraform-provider-azuredevops/issues/95, https://github.com/microsoft/terraform-provider-azuredevops/issues/94, https://github.com/microsoft/terraform-provider-azuredevops/issues/96, https://github.com/microsoft/terraform-provider-azuredevops/issues/99, https://github.com/microsoft/terraform-provider-azuredevops/issues/98, https://github.com/microsoft/terraform-provider-azuredevops/issues/100 Can you call out the testing criteria as AC? I would think that we want the following:
   - Unit test to see what happens if the service fails
   - Acceptance (integration) test to validate that the repo can be created, following the patterns from the `azuredevops_build_definition` resource
 - I like the suggestion of adding a data source - can you write this story as well?

**Comment by KeithJRome** [comment]
Regarding #93, it is optional. If omitted, then git will decide what to do. Almost always this means the default value will be `master`
