### ISSUE TITLE
azuredevops_branch_policy_auto_reviewers add minimumApproverCount support

### ISSUE THREAD

**Issue by Dirnei** [microsoft/terraform-provider-azuredevops#731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was playing arround with the branch policies and the `minimumApproverCout` is missing for the azuredevops_branch_policy_auto_reviewers. In the API docs i can find it: https://learn.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/create?view=azure-devops-rest-6.0&tabs=HTTP

### New or Affected Resource(s)

* azuredevops_branch_policy_auto_reviewers

### Potential Terraform Configuration

```hcl
resource "azuredevops_branch_policy_auto_reviewers" "default_development" {
  project_id = data.azuredevops_project.example.id

  enabled  = true
  blocking = true

  settings {
    auto_reviewer_ids  = [
        azuredevops_group.dev_code_reviewer.origin_id
    ]

    minimum_approver_count = 3 # this property is missing currently
    submitter_can_vote = false
    message            = "Code Reviewer"

    scope {
      repository_ref = "refs/heads/development"
      match_type     = "Exact"
    }
  }
}
```

**Comment by xuzhang3** [comment]
@Dirnei this property has be supported in #672 , will be available in the next version

**Comment by Dirnei** [comment]
Any plans when it will be released?

**Comment by xuzhang3** [comment]
@Dirnei working on it, coming soon.

**Comment by xuzhang3** [comment]
@Dirnei  v0.4.0 https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v0.4.0
