### ISSUE TITLE
Incorrect description for project_id argument in azuredevops_variable_group documentation

### ISSUE THREAD

**Issue by stijnherreman** [microsoft/terraform-provider-azuredevops#736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

microsoft/azuredevops v0.4.0

### Affected Resource(s)

* `azuredevops_variable_group`

### Terraform Configuration Files

```hcl
resource "azuredevops_variable_group" "example" {
	project_id = "ExampleProject"
	# ...
}
```

### Expected Behavior

The variable group is created.

### Actual Behavior

An error is thrown:
> Error: expected "project_id" to be a valid UUID, got ExampleProject

Commit https://github.com/microsoft/terraform-provider-azuredevops/commit/4ff6702e87b1a07029d32667d889ad7c4dfb4bed standardized the documentation of `project_id` parameters in multiple places.

> [project_id](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/variable_group#project_id) - (Required) The project ID or project name.

Either the `project_id` parameter never supported anything other than a UUID, or support was removed at some point. I have only tried the `azuredevops_variable_group` resource, other resources may also be documented incorrectly.

**Comment by xuzhang3** [comment]
Fix in #739
