### ISSUE TITLE
Support AzDO Group Membership

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#74]
As a maintainer of an AzDO organization and/or project, I want to have the ability to add users from my companies AD group and/or GitHub and add them to groups within the org/project. 

More specifically, I want to support the following actions:
 - [x] Import and remove a user from AAD/GitHub to AzDO org - https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users?view=azure-devops-rest-5.0
 - [x] Entitle and un-entitle user after they are in the AzDO org - https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlements/add?view=azure-devops-rest-5.0
 - [x] Assign and remove user to org and project groups https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/add?view=azure-devops-rest-5.0
 - [x] Remove user from org projects/groups https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/remove%20membership?view=azure-devops-rest-5.0

The acceptance criteria for this story are to design the implementation strategy and breakdown the user stories for implementation.

 - [x] Review design
 - [x] Write stories for design

**Comment by nmiodice** [comment]
# Some notes on some relevant API calls...

### Given a group name, find the names of all members
```bash
AZDO_PAT=<...>
ORG=<...>
GROUP=<...>

# Lookup Group
GROUP_DESCRIPTOR=$(
    curl -u ":$AZDO_PAT" https://vssps.dev.azure.com/$ORG/_apis/graph/groups | \
    jq -r ".value | .[] | select(.displayName == \"$GROUP\") | .descriptor"
)
echo "Found Group Descriptor: $GROUP_DESCRIPTOR"

# Query Group Members
MEMBER_DESCRIPTORS=$(
    curl -u ":$AZDO_PAT" "https://vssps.dev.azure.com/$ORG/_apis/graph/memberships/$GROUP_DESCRIPTOR?direction=Down&api-version=5.0-preview.1" | \
    jq -r '.value | .[].memberDescriptor'
)
echo -e "Found Member Descriptors:\n$MEMBER_DESCRIPTORS"
```

**Comment by nmiodice** [comment]
https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/create?view=azure-devops-rest-5.0

**Comment by nmiodice** [comment]
https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlements/add?view=azure-devops-rest-5.0

**Comment by nmiodice** [comment]
* Validate that we can add users from GH and AAD

**Comment by nmiodice** [comment]
Working flow using AAD member. Current tenant does not allow importing from GH. More on that later...

```bash
$ cat .env
export AZDO_PAT=...
export AZDO_ORG=...
export GROUP_SCOPE=...
export GROUP_NAME="Project Collection Administrators"
```

```bash
source .env

echo $AZDO_ORG
echo $AZDO_PAT

USER_RESPONSE=$(
    curl -s -u ":$AZDO_PAT" \
        -X POST \
        -H "Content-Type: application/json" \
        https://vsaex.dev.azure.com/$AZDO_ORG/_apis/userentitlements?api-version=5.1-preview.2 -d @add_user_entitlements.json
)

USER_DESCRIPTOR=$(echo $USER_RESPONSE | jq -r ".operationResult.result.user.descriptor")
USER_ID=$(echo $USER_RESPONSE | jq -r ".operationResult.userId")


echo "Imported AAD user. "
echo -e "\tdescriptor: $USER_DESCRIPTOR"
echo -e "\tid: $USER_ID"

GROUP_DESCRIPTOR=$(
    GROUP_PRINCIPAL_NAME="[$GROUP_SCOPE]\\\\$GROUP_NAME"
    curl -s -u ":$AZDO_PAT" https://vssps.dev.azure.com/$AZDO_ORG/_apis/graph/groups | \
    jq -r ".value | .[] | select(.principalName == \"$GROUP_PRINCIPAL_NAME\") | .descriptor"
)
echo "Queried group"
echo -e "\tdescriptor: $GROUP_DESCRIPTOR"

curl -s -X PUT \
    -u ":$AZDO_PAT" \
    -H "Content-Type: application/json" \
    https://vssps.dev.azure.com/$AZDO_ORG/_apis/graph/memberships/$USER_DESCRIPTOR/$GROUP_DESCRIPTOR?api-version=5.0-preview.1 -d '{}' \
    > /dev/null

echo "Member added to group!"

curl -s -X DELETE \
    -u ":$AZDO_PAT" \
    https://vssps.dev.azure.com/$AZDO_ORG/_apis/graph/memberships/$USER_DESCRIPTOR/$GROUP_DESCRIPTOR?api-version=5.0-preview.1


echo "Member deleted from group!"

curl -s -u ":$AZDO_PAT" \
    -X DELETE \
     https://vsaex.dev.azure.com/$AZDO_ORG/_apis/userentitlements/$USER_ID?api-version=5.1-preview.2 |
    jq #-r ".value | .[] | .principalName"

echo "Member un-imported from AAD"

```

**Comment by nmiodice** [comment]
The JSON file used for the initial user import are the following:

### AAD user
```json
{
    "accessLevel": {
      "accountLicenseType": "express"
    },
    "extensions": [],
    "user": {
      "principalName": "<USER EMAIL ADDRESS>",
      "subjectKind": "user"
    },
    "projectEntitlements": []
}
```

### GitHub user
Note: the GH user ID can be rendered using the following command:
`curl -s https://api.github.com/users/$GH_USER_NAME| jq -r .id`
```json
{
    "accessLevel": {
      "accountLicenseType": "express"
    },
    "extensions": [],
    "user": {
      "origin": "ghb",
      "originId": "$GH_USER_ID",
      "principalName": "$GH_USER_NAME",
      "subjectKind": "user"
    },
    "projectEntitlements": []
}
```

**Comment by nmiodice** [comment]
@KeithJRome @ThePhen @TsuyoshiUshio please have a look when you get a chance

# Design for Azure AD Group Membership

The scope of this document is to identify an implementation strategy for the following features:
 - Add entitlements to users that exist in AAD and GitHub. This materializes a user into the AzDO organization; without it, you cannot interact with the user within AzDO.
 - Add users to organization and project groups. This allows users to be added into pre-existing groups that have permission-sets already associated with them.

Out of scope:
 - Add entitlements to groups that exist in AAD. The pattern for this will be similar to the above, but it is not in scope for our V1 milestone and therefore is omitted from this design. While out of scope, the implementation of this would fit nicely with the proposed implementation of `azuredevops_group_membership`


### High level data flow
In order to achieve the acceptance criteria, outside of the realm of terraform, the followign sequence of events must occur:

1. `HTTP POST: https://vsaex.dev.azure.com/$AZDO_ORG/_apis/userentitlements` [API Docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user%20entitlements/add?view=azure-devops-rest-5.0). See the appendix for the HTTP body.
   - This is the equivelant of inviting a user to an organization. The UI-based version of [inviting AAD members to an AzDO org](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-organization-users?view=azure-devops&tabs=browser#add-users-to-your-organization) or [inviting GitHub members to an AzDO org](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-github-authentication?view=azure-devops). Without invoking this API, either programatically or through the UI, a member cannot be added to any group within the AzDO. The underlying API call is mostly the same for AAD and GitHub users aside from the addition of the `origin` and `originId` fields. See the appendix for more information. 
2. `HTTP GET: https://vssps.dev.azure.com/$AZDO_ORG/_apis/graph/groups` [API Docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/groups/list?view=azure-devops-rest-5.0)
   - This call lists organization and project groups. The API can be used to find the primary ID, called a `descriptor`, of the group into which we want to add users. The selectors that enables identification of the intended group is (1) `scope`, which defines the organization and/or project that the group lives in, and (2) `name` which describes the name of the group. Together, these define the `principal_name`. An example of an organization group `principal_name` is `[terraform-azdo]\\Project Collection Administrators`
3. `HTTP POST: https://vssps.dev.azure.com/$AZDO_ORG/_apis/graph/memberships/$USER_DESCRIPTOR/$GROUP_DESCRIPTOR` [API Docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/add?view=azure-devops-rest-5.0)
    - This API adds a user into a group. The metadata needed to construct this call is formed from the API calls noted above.

Similar calls to (1) - (3) exist to undo these operations, and can be used during the terraform destroy/apply phase where needed. Update semantics are meaningless here, as the operations are really only create/remove and not modify. I.e., it does not make sense to "update a membership" except for add/remove as there are no other properties to change!

### Resource breakdown
The above data flow calls for a handful of resources to be created:

##### Resource: `azuredevops_member_entitlement`
 - Need to support `CREATE`, `DELETE`, `READ`
```hcl
// outputs: id, descriptor
resource "azuredevops_member_entitlement" "member" {
    // ex AAD: foobar@microsoft.com
    // ex GH: foobar
    // note: a change here forces a delete/create - update not supported
    principal_name = string, required

    // values: "aad" (default), "ghb"
    // note: a change here forces a delete/create - update not supported
    origin = string, optional
}
```

##### Datasource: `azuredevops_group`
 - Need to support `READ`
```hcl
// outputs: id, descriptor
data "azuredevops_group" "group" {
    // ex for Project Group: Release Administrators
    // ex for Org Group: Security Service Group 
    // note: a change here forces a delete/create - update not supported
    name = string, required

    // Name of the entity in which the group resides (org or project name)
    // note: a change here forces a delete/create - update not supported
    scope = string, required
}
```

##### Resource: `azuredevops_group_membership`
 - Need to support `CREATE`, `DELETE`, `READ`
```hcl
// outputs: n/a
resource "azuredevops_group_membership" "membership" {
    // ex azuredevops_group.group.descriptor
    // note: a change here forces a delete/create - update not supported
    container_descriptor = string, required

    // ex azuredevops_member_entitlement.member.descriptor
    // note: a change here forces a delete/create - update not supported
    subject_descriptor = string, required
}
```


### Appendix:
**Artifact 1**: `HTTP POST` payload for adding entitlement to AAD backed user:
```json
{
    "accessLevel": {
      "accountLicenseType": "express"
    },
    "extensions": [],
    "user": {
      "principalName": "<USER EMAIL ADDRESS>",
      "subjectKind": "user"
    },
    "projectEntitlements": []
}
```

**Artifact 2**: `HTTP POST` payload for adding entitlement to GitHub backed user:
Note: GH user ID can be rendered using the following command: `curl -s https://api.github.com/users/$GH_USER_NAME| jq -r .id`
```json
{
    "accessLevel": {
      "accountLicenseType": "express"
    },
    "extensions": [],
    "user": {
      "origin": "ghb",
      "originId": "$GH_USER_ID",
      "principalName": "$GH_USER_NAME",
      "subjectKind": "user"
    },
    "projectEntitlements": []
}
```

**Comment by TsuyoshiUshio** [comment]
It looks very well designed! Awesome job!. Only question is this part. https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/create?view=azure-devops-rest-5.0    
In this case which scenario do you support? usually we can use principalName however, OID scenario, requires OID. OID one means BtoB multi-tenant scenario. If it requires for users, we might need to consider it.

**Comment by nmiodice** [comment]
@TsuyoshiUshio I am targeting the `Add an AAD user by UPN` scenario, however, you make a great point. It will be relatively straight forward to support more use cases.

What are your thoughts on the following proposal that would allow for more flexibility? It involves adding an `origin_id` field and making both `origin_id` and `principal_name` optional:

 - If `origin_id` is provided, it will be used. If `principal_name` is also supplied, an error will be reported
 - if `origin_id` is `""` and `principal_name` is supplied, the `principal_name` will be used
 - if `origin_id` is `""` and `principal_name` is `""`, an error will be reported

Thoughts?

**Comment by TsuyoshiUshio** [comment]
Looks cool to me. :)

**Comment by nmiodice** [comment]
Great -- I'll go ahead and update the original comment based on your feedback. I'll be leaving this open a day or 2 to collect more feedback prior to breaking it into stories

**Comment by nmiodice** [comment]
Note - make out of scope the definition of the group/role

**Comment by rguthriemsft** [comment]
org level groups are in a different rest api than project groups.

https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/group%20entitlements?view=azure-devops-rest-5.1

**Comment by rguthriemsft** [comment]
In playing around with the REST API's tonight, I would consider limiting the Group Membership to project level groups.  I would also put out of scope dealing with group entitlements for now.  So you only entitle users and you can create project level groups maybe but not deal with org.  The same group API is used for both org / project but the params are slightly different.  I think a lot more testing would be needed to support org groups and without a solid understanding I would be concerned that the resources would not be correct in TF.

**Comment by nmiodice** [comment]
@rguthriemsft Ill model the resource generically, but i'll model it slightly differently so that (1) the same data source can be used for orgs **once we deep dive into the right way** and (2) we can validate that its only used for project groups for now:
```
// outputs: id, descriptor
data "azuredevops_group" "group" {
    // ex for Project Group: Release Administrators
    // note: a change here forces a delete/create - update not supported
    name = string, required

    // Name of the project in which the group resides. Required for now, optional once org groups are supported
    project_name = string, required
}
```
