### ISSUE TITLE
Panic crash at terraform apply

### ISSUE THREAD

**Issue by gregbaleyy** [microsoft/terraform-provider-azuredevops#741]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.36.0
+ provider registry.terraform.io/hashicorp/azurerm v3.49.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/microsoft/azuredevops v0.4.0

### Affected Resource(s)

We are creating full azure devops project with:
- azuredevops_project
- azuredevops_git_repository
- azuredevops_variable_group
- azuredevops_serviceendpoint_azurerm
- azuredevops_serviceendpoint_sonarqube
- azuredevops_resource_authorization
- azuredevops_agent_pool
- azuredevops_agent_queue
- azuredevops_resource_authorization
Crash can happen at any time during the creation and doesn't seem to be linked to a specific resource.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

The error message indicates that a runtime error occurred in the terraform-provider-azuredevops plugin, specifically in the function flattenVariables() of the resource_variable_group.go file. The error is due to an invalid memory address or a nil pointer dereference, which could be caused by trying to access an unallocated or uninitialized memory address.

### Panic Output

Stack trace from the terraform-provider-azuredevops_v0.4.0 plugin:

 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc2fcd9]

 

goroutine 97 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariables(0xc000173800?, 0xc0000801e0)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:447 +0x39
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.flattenVariableGroup(0xc0001da840?, 0xc0000801e0, 0xc0001401f0?)
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:413 +0x12e
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.resourceVariableGroupRead(0xc000173800?, {0xcaa580?, 0xc000384500})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:225 +0x158
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent.resourceVariableGroupCreate(0x0?, {0xcaa580?, 0xc000384500})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/taskagent/resource_variable_group.go:195 +0x273
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf9c200?, {0xf9c200?, 0xc0002448d0?}, 0xd?, {0xcaa580?, 0xc000384500?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003aab60, {0xf9c200, 0xc0002448d0}, 0xc000735a00, 0xc000172d80, {0xcaa580, 0xc000384500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00037e918, {0xf9c200?, 0xc0002447b0?}, 0xc000278a50)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000358fa0, {0xf9c200?, 0xc000244180?}, 0xc000368070)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe06e20?, 0xc000358fa0}, {0xf9c200, 0xc000244180}, 0xc000368000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002641e0, {0xf9ee60, 0xc000003860}, 0xc0006e2000, 0xc0003e8960, 0x14c4880, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0002641e0, {0xf9ee60, 0xc000003860}, 0xc0006e2000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

 

Error: The terraform-provider-azuredevops_v0.4.0 plugin crashed!

### Expected Behavior

Smooth creation of resources on first apply

### Actual Behavior

The first apply crashes. After several applies and naming conflict fixes, the resources are created.
No change is done to the code between the applies.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@gregbaleyy can you share yore TF script? VG requires at least one variable for every VG by default. From the error log, the VG seems empty without any variables.

**Comment by gregbaleyy** [comment]
# .tf
```hcl
resource "azuredevops_variable_group" "variable_group" {
  for_each = var.azure_devops.variable_groups

  project_id   = azuredevops_project.project.id
  name         = each.value.name
  description  = try(each.value.description, null)
  allow_access = try(each.value.allow_access, false)

  dynamic "variable" {
    for_each = {
      for key, variable in try(each.value.variables, {}) : key => {
        name  = key == "name" ? variable : key
        value = key == "name" ? null : variable
      }
      if try(each.value.remote_objects, false) == false
    }

    content {
      name  = variable.value.name
      value = variable.value.value
    }
  }                          
}
```

# .tfvars structure. 
We are creating 6 VG this way. The variables block is never empty:
```hcl
 azure_devops = {
  variable_groups = {
    dev-front = {
      project_key  = "lab"
      name         = "infra-front-dev" 
      allow_access = true
      variables = {
        environment          = "dev"
        AppService_Name      = "asp-front-01"
        Appsvc_RGName        = "rg-shared-asp01-front"
        Location             = "westeurope"
        RG_Name              = "rg-dev01"
        Service_Co           = "Dev01"
        WebApp_Name          = "dev01-app-webapp-templ-front"
        webapp_vnet_name     = "vnet-dev01-weu-front"
      }
    }
    dev-back = {
      ...
    }
  }
}
```

**Comment by gregbaleyy** [comment]
Hello, 
do you have any feedback on this issue ?
thank you

**Comment by xuzhang3** [comment]
@gregbaleyy cannot reproduce this error based on the .tf script shared.  Any more infos like a .tf can reproduce this error every time?

**Comment by gregbaleyy** [comment]
@xuzhang3, the error happens each time on my prod azdo but never happens on my dev tenant one (which is almost empty).
Could it be linked to the load on the azdo or to a timeout causing the error ? On my prod tenant azdo I have plenty of organization with plenty of repo and vg each time.

**Comment by xuzhang3** [comment]
@gregbaleyy  What permissions are granted by your PAT? This could be a permission issues preventing the provider getting VG variables.

**Comment by gregbaleyy** [comment]
@xuzhang3, PAT is full access. If this was permission issue, it should fail each time I think. In my case it always manage to create all my resources after several applies.

**Comment by xuzhang3** [comment]
@gregbaleyy  Is it possible to share the full script and error logs? From what I can get, I can't locate the issue but this should be a bug, VG is forbidden to create without variables.

**Comment by gregbaleyy** [comment]
@xuzhang3, you can find the full script in https://tf.orange.com/f/0c553d03e043442c8a5e/?dl=1 
Please be aware the link is only available for 24h

**Comment by gregbaleyy** [comment]
@xuzhang3, you can find the full script in https://tf.orange.com/f/efc102d0b0624b11ab5f/?dl=1
Please be aware the link is only available for 48h

**Comment by gregbaleyy** [comment]
@xuzhang3, any feedback ?

**Comment by xuzhang3** [comment]
@gregbaleyy can you share the full script again? I was on a vacation last days

**Comment by gregbaleyy** [comment]
@xuzhang3, here you go https://tf.orange.com/f/8b414f83590841b99f33/?dl=1

**Comment by gregbaleyy** [comment]
Hi @xuzhang3, thank you for your work! Things seems to work better with state management on VG.

Yet, I guess it could be applied to azuredevops.project resource as well. It sometimes get created but end up in error nevertheless (we are still on the same project)
![image](https://user-images.githubusercontent.com/111118056/234869930-7afb3d29-b63a-4f92-8f5c-43c0f913fefd.png)

**Comment by xuzhang3** [comment]
@gregbaleyy   Does this error happen every time or randomly?

**Comment by gregbaleyy** [comment]
@xuzhang3 almost every time. When it happens I need to delete the azdo project manually then recreate it again with code. After multiple attempts, it goes through and everything get created. I couldn't find what trigger the error or why it works sometimes.

**Comment by xuzhang3** [comment]
@gregbaleyy terraform keyword  `depends_on` may help solve part of this issue

**Comment by gregbaleyy** [comment]
@xuzhang3 I'm fine with creating explicit dependency but as any azdo resource reference the azdo project, implicit dependency is already in place. Maybe I'm missing a point here so please enlighten me on which resources I should add dependency and to which resource.
I also tried to add delay using terraform time provider with no luck so far. 
Is there a way to get a more verbose log on azdo provider error?

**Comment by xuzhang3** [comment]
@gregbaleyy Some  resources have same parent but they have dependencies that Terraform doesn't recognize.  Need to set explicit dependencies, you can check the relationship with `terraform graph`.
To get a more verbose log:
```
export TF_LOG=TRACE
export TF_LOG_PATH=<log file path>

```

**Comment by gregbaleyy** [comment]
Hi @xuzhang3, I faced the same issue again 2 days ago. I captured the logs, you can find them in:
https://tf.orange.com/f/f35da6421ddc460e8d14/?dl=1

**Comment by xuzhang3** [comment]
@gregbaleyy thanks for providing the error log.  The difference I found was that the target state changed during the state refresh.  The project should have successfully created.
```log
2023-06-13T17:54:08.645+0200 [INFO]  provider.terraform-provider-azuredevops_v0.4.0: 2023/06/13 17:54:08 [DEBUG] Waiting for state to become: [failed succeeded cancelled]: timestamp=2023-06-13T17:54:08.645+0200
2023-06-13T17:54:13.671+0200 [INFO]  provider.terraform-provider-azuredevops_v0.4.0: 2023/06/13 17:54:13 [DEBUG] Waiting for state to become: [success]: timestamp=2023-06-13T17:54:13.671+0200

```

**Comment by xuzhang3** [comment]
The get API is unstable,   this seems to be the issue causing this error.

**Comment by gregbaleyy** [comment]
Indeed, the project is created. On the next apply I get an error because of a name conflict between the project "to be created" according to Terraform and the one that was actually created before the error.
Is there a way to cope with API unstability?
