### ISSUE TITLE
Unable to set default timeout on azuredevops_check_branch_control or azuredevops_check_business_hours

### ISSUE THREAD

**Issue by Scott-Emberson** [microsoft/terraform-provider-azuredevops#752]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azuredevops_check_branch_control 
* azuredevops_check_business_hours

### Terraform Configuration Files

```hcl
resource "azuredevops_check_branch_control" "example" {
  project_id           = data.azuredevops_project.example.id
  display_name         = "Branch Control \n**Managed by Terraform**"
  target_resource_id   = azuredevops_environment.env.id
  target_resource_type = "environment"
  allowed_branches     = "refs/heads/main, refs/heads/master"
  timeouts {
    Default  = "10"
  }
}
```

### Expected Behavior

The default should be accepted as the code allows it.
In the resource_timeout.go function DefaultTimeout
https://github.com/microsoft/terraform-provider-azuredevops/blob/50d9dd8913dd8a4e7e7d1d162af8d51a82417d37/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_timeout.go#L36

The genBseCheckResource looks to be missing the default option.
https://github.com/microsoft/terraform-provider-azuredevops/blob/50d9dd8913dd8a4e7e7d1d162af8d51a82417d37/azuredevops/internal/service/approvalsandchecks/common_check.go#L31

### Actual Behavior

Error is given

### Steps to Reproduce

1. `terraform apply`

**Comment by xuzhang3** [comment]
@Scott-Emberson   `azuredevops_check_branch_control` and `azuredevops_check_business_hours` have customed timeout for `create/read/update/delete` so we skip the default timeout.

Refs: https://github.com/microsoft/terraform-provider-azuredevops/blob/50d9dd8913dd8a4e7e7d1d162af8d51a82417d37/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go#L411
