### ISSUE TITLE
azuredevops_project data source doesn't export id?

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/terraform-provider-azuredevops#755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- [`azuredevops_project`](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/project)

### Terraform Configuration Files

N/A

### Debug Output

Intellisense doesn't show `id` or `project_id` as attributes exported by data source `azuredevops_project`.
![image](https://user-images.githubusercontent.com/36889813/234294508-2cc15f2c-743b-4f58-952f-5e993af1550d.png)

The documentation (linked above) doesn't list `id` or `project_id` as attribute exports for `azuredevops_project`. How am I supposed to get the ID of a project, for example to create an `azuredevops_serviceendpoint_azurerm` ?

### Panic Output

N/A

### Expected Behavior

`azuredevops_project` data source should make the `project_id` or `id` attribute available, and [document it](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/project#attributes-reference)

### Actual Behavior

What's weird to me is that the `azuredevops_projects` data source does export ids as `project_id`.. or at least [the documentation for it](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/projects#attributes-reference) says so
`azuredevops_project` data source should make the `project_id` or `id` attribute available.

### Steps to Reproduce

Found with Intellisense in VS Code..

### Important Factoids

N/A

### References

I'm trying to use [`serviceendpoint_azurerm`](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_azurerm)

**Comment by xuzhang3** [comment]
@ncook-hxgn you can ref the project ID with  `azuredevops_project.project_id` or `azuredevops_project.id`
