### ISSUE TITLE
Updating Kubernetes service endpoint does not update the resource

### ISSUE THREAD

**Issue by rpeltola** [microsoft/terraform-provider-azuredevops#76]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- Terraform v0.12.28
- provider.azuredevops v0.0.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_kubernetes`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version               = ">= 0.0.1"
  org_service_url       = "https://tfs.foobar.com/tfs/DefaultCollection"
  personal_access_token = "redacted"
}

data "azuredevops_project" "expert_project" {
  project_name = "Expert"
}

locals {
  kubernetes_apiserver_url = "redacted"
}

resource "azuredevops_serviceendpoint_kubernetes" "imagebank_prod_service_account" {
  project_id            = data.azuredevops_project.expert_project.id
  apiserver_url         = local.kubernetes_apiserver_url
  service_endpoint_name = "Imagebank - Prod"
  authorization_type    = "ServiceAccount"

  service_account {
    token   = "redacted"
    ca_cert = "redacted"
  }
}

```

### Debug Output

Running `terraform apply` for the second time after those changes should have already been made

- https://gist.github.com/rpeltola/cc53a35701fd049703987c6c46d90f32

### Expected Behavior

- Updating service_account token and ca_cert values with `terraform apply` works correctly and `terraform plan` doesn't find any more changes

### Actual Behavior

- `terraform apply` is completed successfully but running `terraform plan` still shows the changes

```hcl
Terraform will perform the following actions:

  # azuredevops_serviceendpoint_kubernetes.imagebank_prod_service_account will be updated in-place
  ~ resource "azuredevops_serviceendpoint_kubernetes" "imagebank_prod_service_account" {
        apiserver_url         = "https://nooslopenshiftpocm01.expert.local:8443"
        authorization         = {
            "scheme" = "Token"
        }
        authorization_type    = "ServiceAccount"
        description           = "Managed by Terraform"
        id                    = "ab913e3f-d150-4e22-834d-daf50df80434"
        project_id            = "3c6bdd93-8760-451b-8488-239ad2c4e793"
        service_endpoint_name = "Imagebank - Dev"

      + service_account {
          + ca_cert      = (sensitive value)
          + ca_cert_hash = (sensitive value)
          + token        = (sensitive value)
          + token_hash   = (sensitive value)
        }
        service_account {
            ca_cert      = (sensitive value)
            ca_cert_hash = (sensitive value)
            token        = (sensitive value)
            token_hash   = (sensitive value)
        }
    }
```

### Steps to Reproduce

1. `terraform apply`
2. Change service_account values
3. `terraform apply`
4. `terraform plan`

### Important Factoids

- Running on onprem Azure DevOps Server Version Dev17.M153.3

**Comment by xuzhang3** [comment]
Hi @rpeltola , Thank you for your feedback. Just checked this issue, this has been fixed, you can waiting for our next release.

**Comment by xuzhang3** [comment]
Closing this issue.  Feel free to reopen it if you have questions.

**Comment by avishnyakov** [comment]
Happens with `0.1.8` with Azure DevOps online.
What was the issue and fix for this?
