### ISSUE TITLE
Failure to create branch + file within that branch

### ISSUE THREAD

**Issue by Sebast1aan** [microsoft/terraform-provider-azuredevops#764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.0.4 (on windows_amd64)
provider registry.terraform.io/microsoft/azuredevops v0.5.0

### Affected Resource(s)

* `azuredevops_azuredevops_git_repository_branch`
* `azuredevops_git_repository_file`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.4.0"
    }
  }
}

# get the project
data "azuredevops_project" "myProject" {
  name = "test_project"
}

# get the repo that is inside the project
data "azuredevops_git_repository" "myRepo" {
  project_id = data.azuredevops_project.myProject.id
  name       = "test_repo"
}

# create a new branch within the repo
resource "azuredevops_git_repository_branch" "new_branch" {
  repository_id = data.azuredevops_git_repository.myRepo.id
  name          = "refs/test/develop"
  ref_branch    = data.azuredevops_git_repository.myRepo.default_branch
}

# within the newly created branch, add a test.yml file
resource "azuredevops_git_repository_file" "default_pipeline" {
  repository_id       = data.azuredevops_git_repository.myRepo.id
  file                = "test.yml"
  content             = file("${path.module}/assets/test.yml")
  branch              = azuredevops_git_repository_branch.new_branch.name
  commit_message      = "Add yml file via terraform"
  overwrite_on_create = false
}
```

### Expected Behavior

- Branch 'ref/test/develop' should be created within repo 'test_repo' of project 'test_project'
- file 'test.yml' should be created within branch 'ref/test/develop' within repo 'test_repo' of project 'test_project'

### Actual Behavior
- Branch ref/test/develop gets correctly created
- When creating the file using the resource 'azuredevops_git_repository_file', following error is returned:
Error: Create repositroy file failed, repositoryID: 8249e650-45aa-4242-9bf5-a269cff844e7, branch: refs/test/develop, file: test.yml. Error:  TF401028: The reference 'refs/test/develop' has already been updated by another client, so you cannot update it. Please try again.

Note that I'm the only one working on the repository.

When using branch name 'develop' instead of 'refs/test/develop', I'm running into this error as well:
Error: Create repositroy file failed, repositoryID: 8249e650-45aa-4242-9bf5-a269cff844e7, branch: develop, file: test.yml. Error: TF401021: 'develop' is not a valid name for a Git ref. Visit https://go.microsoft.com/fwlink/?LinkId=800646 for more information on Git ref naming. │ Parameter name: newPush

Is there any reason why such 'simple' branch names are causing an issue?

### Steps to Reproduce

1. `terraform apply`

**Comment by xuzhang3** [comment]
@Sebast1aan  The branch you created is `refs/test/develop`, the real path is `refs/heads/refs/test/develop`. You need set the  `  branch= format("refs/heads/%s", azuredevops_git_repository_branch.new_branch.name)` 

Example:
```hcl
resource "azuredevops_git_repository_file" "default_pipeline" {
  repository_id       = data.azuredevops_git_repository.myRepo.id
  file                = "test.yml"
  content             = "test"
  branch              = format("refs/heads/%s", azuredevops_git_repository_branch.new_branch.name)
  commit_message      = "Add yml file via terraform"
  overwrite_on_create = false
}
```

**Comment by Sebast1aan** [comment]
> ```terraform
> format("refs/heads/%s", azuredevops_git_repository_branch.new_branch.name)
> ```

@xuzhang3 Thanks, that seems to do the trick
