### ISSUE TITLE
Service endpoint import crashes

### ISSUE THREAD

**Issue by rpeltola** [microsoft/terraform-provider-azuredevops#77]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

- Terraform v0.12.28
- provider.azuredevops v0.0.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_dockerregistry`
* `azuredevops_serviceendpoint_kubernetes` (also crashes similarly but not part of the debug logs here)

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version               = ">= 0.0.1"
  org_service_url       = "https://tfs.foobar.com/tfs/DefaultCollection"
  personal_access_token = "redacted"
}

data "azuredevops_project" "expert_project" {
  project_name = "Expert"
}

# harbor docker registry service connection
resource "azuredevops_serviceendpoint_dockerregistry" "harbor_registry" {

}
```

### Debug Output

Running `terraform import azuredevops_serviceendpoint_dockerregistry.harbor_registry 3c6bdd93-8760-451b-8488-239ad2c4e793/9ca54a9f-3d40-4551-a919-41656e82b24f`, where `3c6bdd93-8760-451b-8488-239ad2c4e793` is the id of the project and `9ca54a9f-3d40-4551-a919-41656e82b24f` is the id of an existing docker registry connection

- https://gist.github.com/rpeltola/f22caf86923163f206310aa46b020171

### Panic Output

- https://gist.github.com/rpeltola/c98ece030c646bc182553e74ec9d24b2

### Expected Behavior

- Resource is imported succesfully

### Actual Behavior

- Resource import crashes

### Steps to Reproduce

1. `terraform import azuredevops_serviceendpoint_dockerregistry.harbor_registry 3c6bdd93-8760-451b-8488-239ad2c4e793/9ca54a9f-3d40-4551-a919-41656e82b24f`

### Important Factoids

- Running on onprem Azure DevOps Server Version Dev17.M153.3

### References

* #59

**Comment by xuzhang3** [comment]
Hi @rpeltola   Thank you for opening this issue.   ADO provider doesn't support  on-premise Azure DevOps Server.  We will put this in our backlog.

**Comment by xuzhang3** [comment]
Close this issue. Feel free to reopen it if you have questions.
