### ISSUE TITLE
Provider produced inconsistent result after apply - azuredevops_project

### ISSUE THREAD

**Issue by kvakulo** [microsoft/terraform-provider-azuredevops#771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.5.0

### Affected Resource(s)

azuredevops_project

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "ado_project" {
  name               = "tf-test-project-1234"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Basic"
  description        = "Project created as part of Terraform module test"
}
```

### Debug Output

https://gist.github.com/kvakulo/ff068f2caf0a3c37583a618e8def7fac

### Expected Behavior

The project is created and added to the Terraform state

### Actual Behavior

The project is created, but Terraform exists with the following error and the project is not added to the state:

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to azuredevops_project.ado_project, provider
│ "provider[\"registry.terraform.io/microsoft/azuredevops\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The user only has the `Create new projects` permission on the organization

**Comment by kvakulo** [comment]
When the user is added to the `Project Collection Administrators` group it works as expected. Perhaps it takes some time before the user has access to the new project when only granting the `Create new projects` permission?

**Comment by xuzhang3** [comment]
`azuredevops_project` requires permissions like `project mange`, `work item template read` etc. It seems user can get partial resources and end up with this error.
