### ISSUE TITLE
git import from onpremise Bitbucket server

### ISSUE THREAD

**Issue by omichels** [microsoft/terraform-provider-azuredevops#772]
Hi

i have got a question regarding the import of git repos via "azuredevops_git_repository":
if the source_url is unreachable for AZDO in the cloud 
(e.g. http://nl012001:7990/scm/project/example.git),
but only from the workstation running terraform, is the import still possible?

BR, Oliver

**Comment by xuzhang3** [comment]
@omichels  The repository cannot be imported into the ADO repository if it is unreachable for ADO
