### ISSUE TITLE
`azuredevops_branch_policy_min_reviewers` - on_push_reset_all_votes not setting resetOnSourcePush to true

### ISSUE THREAD

**Issue by kristiangleeson** [microsoft/terraform-provider-azuredevops#783]
Using azuredevops_branch_policy_min_reviewers (latest v0.5.0) when you set on_push_reset_all_votes = true it sets reset of rejection votes (resetRejectionsOnSourcePush) to true  but approvals to false (resetOnSourcePush).

Since only one of on_push_reset_all_votes and on_push_reset_approved_votes can be provided it is currently impossible to set both to true.

Note that when this issue occurs the AzureDevops UI shows the correct "Reset all code reviewer votes" radio button being selected, but does not reset approved votes on push. Toggling to another option and back via UI does correctly set resetOnSourcePush=true.

JSON extract of a policy (using az cli -> az repos policy list --project xxx) where this was used:

~~~
{
    "createdBy": {
        ....
    },
    "createdDate": "2023-05-23T22:24:23.662228+00:00",
    "isBlocking": true,
    "isDeleted": false,
    "isEnabled": true,
    "isEnterpriseManaged": false,
    "revision": 5,
    "settings": {
      "allowDownvotes": false,
      "blockLastPusherVote": false,
      "creatorVoteCounts": false,
      "minimumApproverCount": 1,
      "requireVoteOnLastIteration": false,
      "resetOnSourcePush": false,
      "resetRejectionsOnSourcePush": true,
      "scope": [
        {
          ....
        }
      ]
    },
    "type": {
      "displayName": "Minimum number of reviewers",
      ......
    }
  }
~~~

**Comment by xuzhang3** [comment]
@kristiangleeson `on_push_reset_all_votes` and `on_push_reset_approved_votes` conflict with each is they cannot set both from  UI. But from API perspective, they can be both to true.   This looks like a service bug.

**Comment by kristiangleeson** [comment]
Forgive me if I'm misunderstanding your comment, but the UI is wrapping up multiple bools under a single radio button (resetOnSourcePush, resetRejectionsOnSourcePush) and you can correctly set both to true via UI by selecting "Reset all code reviewer votes".
My go isn't great but it seems like the issue is [here](https://github.com/microsoft/terraform-provider-azuredevops/blob/fbb84c3ada5996634038b5acd84c0b523ccc8f7b/azuredevops/internal/service/policy/branch/resource_branchpolicy_min_reviewers.go#LL21C21-L21C21), the mapping to json property is limited to a single one, but this needs/should be to both properties.

**Comment by xuzhang3** [comment]
@kristiangleeson  I see. Tested though the UI. I got three potential configuration:
1. resetOnSourcePush=true, resetRejectionsOnSourcePush=false
2. resetOnSourcePush=true, resetRejectionsOnSourcePush=true
3. resetOnSourcePush=false, resetRejectionsOnSourcePush=false

**Comment by kristiangleeson** [comment]
Exactly. So from UI true/true is possible, but not via provider.
