### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by MathKlim** [microsoft/terraform-provider-azuredevops#788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.5.0
```

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.4.6"

  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.5.0"
    }
  }
}

provider "azuredevops" {}

variable "project_name" {
  type        = string
  description = "Name of the project"
  default     = "terraform-test"
}

variable "project_description" {
  type        = string
  description = "Description of the project"
  default     = "Test project created via Terraform"
}

resource "azuredevops_project" "current" {
  name               = "datascience-${var.project_name}"
  description        = "${var.project_description}. Managed by Terraform"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}


```

### Debug Output

https://gist.github.com/MathKlim/b012173392fa63866ed554f7953aa0f0

### Expected Behavior

The project is created and Terraform ends with an exit code 0.

### What actually happened? 

I get this error when I try to create a project, after the `terraform apply`, I have this error. Terraform exits with an exit code 1. **BUT** the project is created in my azure devops organization.

### Steps to Reproduce

```
# I stored my credentials in a .env file using AZDO_ORG_SERVICE_URL and AZDO_PERSONAL_ACCESS_TOKEN
source .env 
terraform init
terraform plan -out=tfplan
terraform apply tfplan
```

### Important Factoids

Nothing special.

### References

None

**Comment by xuzhang3** [comment]
@MathKlim  cannot reproduce, does this error always happened or randomly?  
```log
azuredevops_project.current encountered an error during creation, so it is now marked as tainted","@timestamp":"2023-06-08T14:48:56.017724+02:00"}
```
Error log shows something wrong during the creation but the error details not printed.

**Comment by MathKlim** [comment]
I've started using the devops provider yesterday, but yes every time  I've tried to provision a project I've had this error. I've just tried again and I have the same error.

* Init

![tf_init](https://github.com/microsoft/terraform-provider-azuredevops/assets/48051974/c4796ae1-ddd2-41ee-98a6-0fbffb47c415)

* Plan 

![tf_plan](https://github.com/microsoft/terraform-provider-azuredevops/assets/48051974/b68c5302-1246-4f7c-8052-1879300ec862)

* Apply with exit code 1

![tf_apply](https://github.com/microsoft/terraform-provider-azuredevops/assets/48051974/90c8dcbc-4443-488c-b1e5-7d6acad7ae14)

* Project still created

![tf_project](https://github.com/microsoft/terraform-provider-azuredevops/assets/48051974/b207434c-9780-4678-b0d1-832d48076208)

**Comment by xuzhang3** [comment]
@MathKlim which permissions does PAT have, I try reproduce this error in my dev env.

**Comment by MathKlim** [comment]
I've tried with one with the permissions defined in the doc, ie **Project & Team**: Read, Write, & Manage. Then with one with full access, the screens come from a full access PAT.

**Comment by jessedietrich** [comment]
I recieved the same error .  Happens on version 0.4.0 as well.

[#790](https://github.com/microsoft/terraform-provider-azuredevops/issues/790)
