### ISSUE TITLE
Provider returns misleading error when organization service URL is incorrect

### ISSUE THREAD

**Issue by msl0** [microsoft/terraform-provider-azuredevops#789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.4.5
on linux_amd64
provider registry.terraform.io/microsoft/azuredevops v0.5.0

### Affected Resource(s)

* `azuredevops_*`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.2.0"
    }
  }
}

provider "azuredevops" {
  org_service_url = "https://dev.azure.com/dummy-org"   
  personal_access_token = "correct-pat" 
}

data "azuredevops_project" "test" {
    name = "Test"
}

```

### Expected Behavior
It would be good to see information that there is a problem with URL or organization name when problem occur. The current error message is misleading.

```
╷
│ Error: The organization "dummy-org" does not exist.
│ 
│   with provider["registry.terraform.io/microsoft/azuredevops"],
│   on main.tf line 1, in provider "azuredevops":
│    1: provider "azuredevops" {
│ 
```

### Actual Behavior
Provider returns misleading error when organization service URL is incorrect.
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: The resource cannot be found.
│ 
│   with provider["registry.terraform.io/microsoft/azuredevops"],
│   on main.tf line 1, in provider "azuredevops":
│    1: provider "azuredevops" {
│ 
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by xuzhang3** [comment]
@msl0  If URL/PAT not correct, an 401 Unauthorized. This is more like an initialization error, the provider not initialized.

**Comment by msl0** [comment]
I don't quite understand what you mean. I got the mentioned error, not 401 Unauthorized. When I corrected URL it started working. What I noticed is an error that does not indicate the cause

**Comment by xuzhang3** [comment]
@msl0   What permission does you PAT granted, full permission or custom permissions?

**Comment by msl0** [comment]
I don't remember, but I know that with the correct address the problem didn't occur

**Comment by xuzhang3** [comment]
I added a custom error message in #1207 which should help
