### ISSUE TITLE
importing OR refreshing team with many team members fails

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_team`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

team imports successfully

### Actual Behavior

fails to import because 

### Steps to Reproduce

Have an existing team with a lot of members (mine had 50) and try to import it into terraform state
a reqeust is made out to https://simplot.vssps.visualstudio.com/_apis/Identities?descriptors=<descriptor per member>

but that request fails because it's too big/large for the http server on the azdo side 

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/1514496/fb43474f-99af-4baf-807d-2533b957fa91)

**Comment by xuzhang3** [comment]
Too many `descriptors` requested when resolve `descriptors` to `SubjectDescriptors`

**Comment by luki95** [comment]
The **data.azuredevops_team** resource is also affected. Successful up to 44 members, breaks on 45 members

```tf
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.3.0, < 1.0.0"
    }
  }
  required_version = ">=1.3.0, < 2.0.0"
}

provider "azuredevops" {
  org_service_url = "REPLACE_ME"
}

data "azuredevops_project" "main" {
  name = "Example"
}

data "azuredevops_team" "main" {
  project_id = data.azuredevops_project.main.id
  name       = "Example Team"
}
```
Error:
```
data.azuredevops_team.main: Reading...
╷
│ Error: Request returned status: 404 Not Found
│ 
│   with data.azuredevops_team.main,
```
With registry.terraform.io/microsoft/azuredevops version 0.6.0

**Comment by AleksanderTolstopyatov** [comment]
I also encountered this problem on the latest version of the provider

**Comment by jmoersch-sgi** [comment]
We are also encountering this error. Groups don't seem to suffer from the same issue.

I dug in a bit, and the teams resources seem to be built on top of the identity API endpoints whereas groups use the graph API endpoints. Could teams also use the graph endpoints?

**Comment by JohannesMoersch** [comment]
We are also encountering this error. Groups don't seem to suffer from the same issue.

I dug in a bit, and the teams resources seem to be built on top of the identity API endpoints whereas groups use the graph API endpoints. Could teams also use the graph endpoints?

**Comment by drdamour** [comment]
@xuzhang3 any chance this has been prioritized, we keep hitting up against it in our org

**Comment by xuzhang3** [comment]
@drdamour #1014 should help fix this issue

**Comment by DaniRieker** [comment]
I can confirm that the Issue is fixed with https://github.com/microsoft/terraform-provider-azuredevops/pull/1014 which made it into the last Release [v1.1.0](https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v1.1.0). 👍
Thanks @xuzhang3
