### ISSUE TITLE
Using "azuredevops_pipeline_authorization" instead of "azuredevops_resource_authorization" for endpoints recreates each time by not adding optional pipeline_id

### ISSUE THREAD

**Issue by pmatthews05** [microsoft/terraform-provider-azuredevops#808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.4.4 on windows_amd64
DevOps Provider - 0.6.0

### Affected Resource(s)

* `azuredevops_pipeline_authorization`

### Terraform Configuration Files

When running the "azuredevops_pipeline_authorization" for endpoints, and not including the optional pipeline_id, each time the terraform is run, it destroys and creates the authorize. This wasn't a problem when using "azuredevops_resource_authorization" 

Used to run 
```hcl
resource "azuredevops_resource_authorization" "authorize" {
  project_id  = var.project_id
  resource_id = azuredevops_serviceendpoint_azurerm.subscription.id
  authorized  = true
}
```
Now using the updated version because above is being depreciated. 
_Note: Below is example as I cannot supply the actual code, hence bad practice of servicePrincipalId and secret_
```hcl
locals {
 subscription_id            = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
 project_name              = "example"
 serviceprincipalid        = "xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxx"
 serviceprincipalsecret = "password-here"
}

data "azurerm_subscription" "azurerm_scope_resource_group_subscription" {
  subscription_id = local.subscription_id
}

data "azuredevops_project" "ado_project" {
  name = local.project_name
}

resource "azuredevops_serviceendpoint_azurerm" "subscription" {
  project_id                       = data.azuredevops_project.ado_project.id
  service_endpoint_name = "example-sub"
  description           = "Managed by Terraform"
  credentials {
    serviceprincipalid  = local.serviceprincipalid
    serviceprincipalkey = local.serviceprincipalid
  }
  azurerm_spn_tenantid      = data.azurerm_subscription.azurerm_scope_subscription.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.azurerm_scope_subscription.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.azurerm_scope_subscription.display_name
}

resource "azuredevops_pipeline_authorization" "authorize" {
  project_id =  data.azuredevops_project.ado_project.id
  resource_id =azuredevops_serviceendpoint_azurerm.subscription.id
  type = "endpoint"
} 
```

I have discovered I can work around the issue for now, by adding lifecycle to azuredevops_pipeline_authorization like below:
```hcl
resource "azuredevops_pipeline_authorization" "authorize" {
  project_id =  data.azuredevops_project.ado_project.id
  resource_id =azuredevops_serviceendpoint_azurerm.subscription.id
  type = "endpoint"
  lifecycle {
    ignore_changes = [
      pipeline_id //If not added, it destroys and creates every run.
     ]
 }
```

### Debug Output

```txt
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:


  # module.devops_azurerm_service_connection_mg.azuredevops_pipeline_authorization.authorize must be replaced
-/+ resource "azuredevops_pipeline_authorization" "authorize" {
      ~ id          = "a9438b9c-99c5-436a-9d0b-a63e282b7d77" -> (known after apply)
      - pipeline_id = 837 -> null # forces replacement
        # (3 unchanged attributes hidden)
    }
```

### Expected Behavior

Shouldn't need pipeline_id if it's optional, or I need a way to get the pipeline_id.

### Actual Behavior

Deletes and recreates the authorization.

### Steps to Reproduce

1. Use the hcl example shown in the Configuration files.
2. Need to set your PAT and URL of DevOps.
```ps1
    $Env:AZDO_PERSONAL_ACCESS_TOKEN = $PersonalAccessToken
    $Env:AZDO_ORG_SERVICE_URL = $TeamFoundationCollectionUri
```
4. `terraform apply`

**Comment by xuzhang3** [comment]
@pmatthews05 does the `azuredevops_pipeline_authorization` new created or migrate from a `.state` file? If `pipeline_id` not configured, the `pipeline_id` will be null but the debug log shows the `pipeline_id=837`.

**Comment by pmatthews05** [comment]
Hi @xuzhang3, thanks for coming back to me.

The creation is brand new of the `azuredevops_pipeline_authorization`.

 What I probably didn't explain clearly, is that you run it once (brand new) and it creates the authorization. However, if you run the same terraform again, instead of saying there are no changes, it sets the `pipeline_id` to null, causing the resource to be destroyed and recreated again.

**Comment by xuzhang3** [comment]
@pmatthews0  Does there any other tools or HCL manage the same pipeline authorization? `pipeline_id` set to 'null' means there's no authorizations. Run `terraform apply` multi times will not change the `pipeline_id`.

**Comment by pmatthews05** [comment]
Hi @xuzhang3 ,
 I've just logged in to give you some more information and I have noticed you have merged a check in, does that mean you have found the bug?

Anyway, I've worked a bit more on this. I believe the issue is after I have created the service connection between DevOps and Azure Subscription, we hand the project site over to our other developers. They then create pipelines using that service connection manually in the portal.  It is after that, running the terraform again the pipeline_id is no longer null. 

Because I'm not creating the pipelines in terraform, I assume this is why the issue? Although this wasn't a problem with the original `azuredevops_resource_authorization`.

I have put the example project and walkthrough of replicating the issue in a project:
https://github.com/pmatthews05/tf_pipeline_authorization/blob/main/README.md

**Comment by xuzhang3** [comment]
@pmatthews05   #809  will fix the bug. Before that, `azuredevops_pipeline_authorization` will set the `pipeline_id ` to the first authorized pipeline.  One scenario, custom authorization to a pipeline and authorize for all pipeline(can set at the same time but auth to all pipeline has high priority), authorize to all pipeline trigger a force create operation(` - pipeline_id = 123-> null # forces replacement`) because the `pipeline_id` not configured but it has a value which is belong to the custom pipeline authorization.

**Comment by drdamour** [comment]
@xuzhang3  will that also fix the problem where two pipelines cannot be authorized ?

i've noticed if i try to authorize two pipelines they fight each other each thinking they should be the first (and only) one

**Comment by xuzhang3** [comment]
> @xuzhang3 will that also fix the problem where two pipelines cannot be authorized ?
> 
> i've noticed if i try to authorize two pipelines they fight each other each thinking they should be the first (and only) one

yes, this issue will alse be fixed.
