### ISSUE TITLE
Error: azuredevops_serviceendpoint_aws not supported by azuredevops provider

### ISSUE THREAD

**Issue by coffeedome** [microsoft/terraform-provider-azuredevops#81]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.24
Azuredevops 0.0.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_aws`

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_aws" "create" {
  project_id            = "<my project id>"
  service_endpoint_name = var.AWS_CONN_NAME
  description           = var.AWS_CONN_DESCRIPTION

  access_key_id         = aws_iam_access_key.ado_svc_conn_iam_user.id
  secret_access_key     = aws_iam_access_key.ado_svc_conn_iam_user.secret

  role_to_assume        = var.AWS_CONN_ROLE_TO_ASSUME
  role_session_names    = var.AWS_CONN_ROLE_SESSION_NAMES
}
```

### Expected Behavior

Resource gets provisioned successfully

### Actual Behavior

Error: The provider provider.azuredevops does not support resource type
"azuredevops_serviceendpoint_aws"

### Steps to Reproduce

1. `terraform validate`

### References

I'm following the instructions on this link https://github.com/terraform-providers/terraform-provider-azuredevops/blob/master/website/docs/r/serviceendpoint_aws.html.markdown

* #0000

**Comment by xuzhang3** [comment]
Hi @estebanes22   We have not release the new ADO provider version.

**Comment by coffeedome** [comment]
I see. Any idea when we can expect release? or if there is a beta/pre-release version we can use?

**Comment by xuzhang3** [comment]
Hi @estebanes22  We don't have any beta/pre-release. But you can build a binary file for yourself.
Make you have golang  installed.
1. check out this repository.
2. open `cmd` or `bash` terminal and go to the root directory and 
3. use command `go build -gcflags="-N -l" -o terraform-provider-azuredevops` to build a provider , you will find the binary file in the same root directory.  If you use Terraform in  windows environment you need add `.exe` suffix for the provider.

**Comment by xuzhang3** [comment]
Closing this issue. Feel free reopen it if you still  have question.
