### ISSUE TITLE
add group_id attribute to azuredevops_team

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Creating a team always creates a group as well.  It's this group's id that is then leverage to grant permissions in the other resources like `azuredevops_git_permissions`, `azuredevops_workitemquery_permissions`, `azuredevops_iteration_permissions`, etc

this will most certainly require another call to fetch the group info by the teams descriptor to fill in this attribute's on referesh.  this should also be supported in the data source for a team

### New or Affected Resource(s)

* azuredevops_team

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "example" {
  name               = "Example Project"
  work_item_template = "Agile"
  version_control    = "Git"
  visibility         = "private"
  description        = "Managed by Terraform"
}

resource "azuredevops_team" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Team"
}

resource "azuredevops_git_permissions" "example-permissions" {
  project_id = azuredevops_project.example.id
  principal  = azuredevops_team.example.group_id
  permissions = {
    CreateRepository = "Deny"
    DeleteRepository = "Deny"
    RenameRepository = "NotSet"
  }
}
```

### References

* #343 added teams support, and this WAS requested there but wasn't included.  Some workarounds are discussed and their drawbacks.  having natural support like this is a fundamental need to make teams work effectively in AzDO terraform.

**Comment by xuzhang3** [comment]
@drdamour is `descriptor` the property  you want to be returned with the team?

**Comment by drdamour** [comment]
@xuzhang3 yeah i think that would be fine..seems like group's id and descriptor are the same value?  i suggested group_id because that is what the example in https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_permissions uses, but maybe that example should use descriptor instead

**Comment by xuzhang3** [comment]
@drdamour the `group_id` not returned by service but `descriptor` does.

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/57888764/4eb97f7d-8739-4b19-b3b8-0a15cce79383)

**Comment by drdamour** [comment]
Ah yeah i see now theyre the dame for group from https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/group

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/1514496/6c32f8a3-f12d-41fe-9718-078cf98e5672)

so group_descriptor would be great!

**Comment by xuzhang3** [comment]
@drdamour   Checked the Group and Team API. Current `descriptor` in `azuredevops_team` can be used as the group descriptor.  The `descriptor` here was converted from team ID to descriptor by  [Descriptors API](https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/descriptors/get?view=azure-devops-rest-7.1&tabs=HTTP) and it is same to the group `descriptor`

**Comment by drdamour** [comment]
@xuzhang3 u are of course correct.

also found that team,id is also the group's origin_id that was needed for PR auto reviewer config.

so all my fault.
