### ISSUE TITLE
"azurerm_subscription_id": conflicts with azurerm_management_group_id

### ISSUE THREAD

**Issue by IntergalacticBVBA** [microsoft/terraform-provider-azuredevops#833]
### Error
When deploying different azuredevops_serviceendpoint_azurerm resources (one ManagementGroup Scoped, one Subscription Scoped), I run into the following error when deploying these resources via Azure DevOps pipelines. When deploying this manually, it deploys correctly and no error is given. 

This is the error I get for deploying an azurerm service connection pointing towards a management group.

```
│ Error: Conflicting configuration arguments
│ 
│   with azuredevops_serviceendpoint_azurerm.mg_service_connection,
│   on azdevops.tf line 131, in resource "azuredevops_serviceendpoint_azurerm" "mg_service_connection":
│  131: resource "azuredevops_serviceendpoint_azurerm" "mg_service_connection" {
│ 
│ "azurerm_subscription_id": conflicts with azurerm_management_group_id

```

When looking at the code, I did not specify the "azurerm_subscription_id"
```tf
resource "azuredevops_serviceendpoint_azurerm" "mg_service_connection" {
  project_id            = data.azuredevops_project.project.id
  service_endpoint_name = "${data.azurerm_management_group.management_group.display_name} - ${azuread_application.mg_service_connection.display_name}"
  description           = "Managed by Terraform"
  credentials {
    serviceprincipalid  = azuread_service_principal.mg_service_connection.application_id
    serviceprincipalkey = azuread_application_password.mg_service_connection.value
  }
  azurerm_spn_tenantid          = data.azurerm_client_config.current.tenant_id
  azurerm_management_group_id   = data.azurerm_management_group.management_group.name
  azurerm_management_group_name = data.azurerm_management_group.management_group.display_name
}

```

The code for the Subscription Scoped service connection :
```tf
resource "azuredevops_serviceendpoint_azurerm" "sub_service_connection" {
  project_id            = data.azuredevops_project.project.id
  service_endpoint_name = "${data.azurerm_subscription.current.display_name} - ${azuread_application.sub_service_connection.display_name}"
  description           = "Managed by Terraform"
  credentials {
    serviceprincipalid  = azuread_service_principal.sub_service_connection.application_id
    serviceprincipalkey = azuread_application_password.sub_service_connection.value
  }
  azurerm_spn_tenantid      = data.azurerm_client_config.current.tenant_id
  azurerm_subscription_id   = data.azurerm_client_config.current.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.current.display_name

}
```

### Terraform (and Azure DevOps Provider) Version
Running on
Terraform v1.5.3
microsoft/azuredevops v0.6.0

I also tried downgrading towards the following versions, but the same result.
Terraform v1.5.2
microsoft/azuredevops v0.5.0

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xuzhang3** [comment]
@IntergalacticBVBA  Cannot reproduce this error. Does there any other configuration in that pipeline?  Apply the Terraform command with same configuration should have the same result.

**Comment by Vykistwo** [comment]
getting the same error as well

**Comment by xuzhang3** [comment]
@Vykistwo `azurerm_subscription_id` and `azurerm_management_group_id` are conflicts with each other.  They will not conflict unless you configure it.

**Comment by jaredfholgate** [comment]
Is it possible you have the `ARM_SUBSCRIPTION_ID` env var set? That could cause the conflict I think, even if you don't have the variable explicitly set in the code. See here: https://github.com/microsoft/terraform-provider-azuredevops/blob/f569dfc9830926ae365cb87733a0a843612d60e8/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go#L55C41-L55C60

**Comment by xuzhang3** [comment]
@IntergalacticBVBA as @jaredfholgate mentioned, do you have an environment setup?

**Comment by kvakulo** [comment]
I have run into this issue having the `ARM_SUBSCRIPTION_ID` environment variable set (for the `azurerm` provider). However, I'd still like to create the specific service connection on a management group scope using the `azuredevops` provider.

Would it be possible? (Perhaps in a future version of the `azuredevops` provider)

**Comment by xuzhang3** [comment]
@kvakulo It is a constraint in the `azuredevops_serviceendpoint_azurerm` resource(hard coded).  And it can be removed to fix the compatibility with the AzurRM.

**Comment by kvakulo** [comment]
@xuzhang3 Yes, I imagined that was the case. It would be great if the hard-coded fallback on `ARM_SUBSCRIPTION_ID` could be removed. Maybe only in cases where a value for `azurerm_management_group_id` is provided to keep backwards compatibility.
