### ISSUE TITLE
Elastic Pool Resource needs Project ID Parameter 

### ISSUE THREAD

**Issue by DevOpsBoondoggles** [microsoft/terraform-provider-azuredevops#843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[](https://github.com/microsoft/terraform-provider-azuredevops/pull/835) thank you @xuzhang3 !   but it is missing the Project ID parameter that allows a Task Agent Queue to be created within that project. 
https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools/create?view=azure-devops-rest-7.1
It looks to me like it's in the SDK but I'm not very good at Go so I could be misreading. I'm hoping this is a really easy addition as we need the pools to be available at the Project level. 

### New or Affected Resource(s)

azuredevops_elastic_pool

### Potential Terraform Configuration

```hcl
resource "azuredevops_elastic_pool" "example" {
  name                   = "Example Elastic Pool"
  project_id             = "49"  <<<<<<
  service_endpoint_id    = azuredevops_serviceendpoint_azurerm.example.id
  service_endpoint_scope = azuredevops_project.example.id
  desired_idle           = 2
  max_capacity           = 3
  azure_resource_id      = "/subscriptions/<Subscription Id>/resourceGroups/<Resource Name>/providers/Microsoft.Compute/virtualMachineScaleSets/<VMSS Name>"
}
```

### References

* #835  #368  #204

**Comment by xuzhang3** [comment]
@gabrielmccoll   elastic pool is a special agent pool,  `azuredevops_agent_queue` can be used to create the elastic pool with in project
```hcl
data "azuredevops_project" "example" {
  name = "ADDTest"
}

data "azuredevops_agent_pool" "example" {
  name = "vmss"
}

resource "azuredevops_agent_queue" "example" {
  project_id    = data.azuredevops_project.example.id
  agent_pool_id = data.azuredevops_agent_pool.example.id
}
```

**Comment by DevOpsBoondoggles** [comment]
amazing thank you
