### ISSUE TITLE
Error creating service endpoint in Azure DevOps: Unable to find service connection type 'azurerm' using authentication scheme 'WorkloadIdentityFederation'

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/terraform-provider-azuredevops#845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

terraform - 1.3.7
azure devops - 0.7.0

### Affected Resource(s)

azuredevops_serviceendpoint_azurerm

### Terraform Configuration Files

```hcl
resource "azuredevops_serviceendpoint_azurerm" "sc" {
  project_id                             = data.azuredevops_project.project.id
  service_endpoint_name                  = var.sc_name
  description                            = var.sc_desc
  service_endpoint_authentication_scheme = var.umi == null ? "ServicePrincipal" : "WorkloadIdentityFederation"
  credentials {
    serviceprincipalid  = var.umi == null ? var.sp_app_id : var.umi.client_id
    serviceprincipalkey = var.sp_password
  }
  azurerm_spn_tenantid      = data.azurerm_subscription.current.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.current.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.current.display_name
}
```

### Debug Output

https://gist.githubusercontent.com/MarkKharitonov/d04c0dacf6771581602702f28696fafa/raw/4b780e885691d1b741c3f0bf784f458fa3cdac1a/tf.log

### Expected Behavior

A service connection wrapping the given managed identity is created

### Actual Behavior

```
│ Error: Error creating service endpoint in Azure DevOps: Unable to find service connection type 'azurerm' using authentication scheme 'WorkloadIdentityFederation'.
│ 
│   with module.ado_service_connection.azuredevops_serviceendpoint_azurerm.sc,
│   on .terraform/modules/ado_service_connection/main.tf line 27, in resource "azuredevops_serviceendpoint_azurerm" "sc":
│   27: resource "azuredevops_serviceendpoint_azurerm" "sc" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by xuzhang3** [comment]
@MarkKharitonov  `WorkloadIdentityFederation`  is a preview feature, currently only available in some ORGs.
https://github.com/microsoft/azure-pipelines-tasks/blob/users/geekzter/oidc-preview-docs/docs/service-connections/azure-oidc/README.md
