### ISSUE TITLE
Inconsistent results in version 0.7.0 azuredevops_resource_authorization to azuredevops_pipeline_authorization

### ISSUE THREAD

**Issue by mgapp12** [microsoft/terraform-provider-azuredevops#847]
We are seeing results are the upgrade and change of this resource where the azure devops pipelines are no longer running due to permissions. I feel this may be due to the removal of authorization = true. This greatly impacts us when we upgrade and since this will be removed in future versions is it possible to know where we are going wrong with this implementation if it is not due to authorized = true? 

resource "azuredevops_resource_authorization" "example" {
  project_id  = var.project_id
  resource_id = var.resource_id
  authorized  = true
}

to

resource "azuredevops_pipeline_authorization" "example" {
  project_id  = var.project_id
  resource_id = var.resource_id
  type        = "endpoint"
}

**Comment by xuzhang3** [comment]
@mgapp12  These two resources have the same behavior but use different API.  To do a authorization you need create a new `azuredevops_pipeline_authorization`  resource.   
```hcl
resource "azuredevops_resource_authorization" "example" {
project_id = var.project_id
resource_id = var.resource_id
authorized = true
}
```
and 

```hcl
resource "azuredevops_pipeline_authorization" "example" {
project_id = var.project_id
resource_id = var.resource_id
type = "endpoint"
}
```
have the same behavior. Authorize the resource to all pipelines.

**Comment by mgapp12** [comment]
we are seeing pipelines be inaccessible after switching to this new resource.

**Comment by mgapp12** [comment]
hi, any information?

**Comment by A30001546** [comment]
> we are seeing pipelines be inaccessible after switching to this new resource.

Yes are seeing the same results after switching to the new resource as the new resource is not enabling the access to the pipelines
![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/49295494/3443514b-3b37-461d-ba38-320dff5321e8)

**Comment by lahiruperamune** [comment]
Any update? I got the same outcome. "Grant access permission to all pipelines" is disabled after moving to the `azuredevops_pipeline_authorization` even though the [documentation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization#pipeline_id) said that all pipelines will be authorized.

**Comment by mgapp12** [comment]
@xuzhang3 are there are updates for this? It should not be labelled a question given other people are experiencing the issue.

**Comment by xuzhang3** [comment]
@lahiruperamune  @mgapp12   this is bug,  `azuredevops_pipeline_authorization` not detect the authorization has been revoked. Current workaround remove  the `azuredevops_pipeline_authorization` then apply the changes then add `azuredevops_pipeline_authorization` back and apply again to enable the authorization

**Comment by xuzhang3** [comment]
#986 will fix this issue, since the `azuredevops_resource_authorization` and `azuredevops_pipeline_authorization` was used to manage the same resource, the change may not detected at the first apply when `azuredevops_resource_authorization` removed, but you will get a new resource to be added when you run `terraform plan`
