### ISSUE TITLE
azuredevops_team_members - Error reading team memberships(404)

### ISSUE THREAD

**Issue by bsuchorowski** [microsoft/terraform-provider-azuredevops#848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform version: 1.5.2
+ provider registry.terraform.io/microsoft/azuredevops v0.7.0

### Affected Resource(s)

azuredevops_team_members

### Terraform Configuration Files

```hcl
resource "azuredevops_team_members" "default_team_members" {
  project_id = azuredevops_project.project.id
  team_id    = data.azuredevops_team.default_team.id
  mode       = "overwrite"
  members    = jsondecode(data.external.manufacturo_team_members.result.manufacturo_members)
}
```

### Debug Output
```
2023-07-28T15:09:49.749+0200 [INFO]  provider.terraform-provider-azuredevops_v0.7.0: 2023/07/28 15:09:49 [TRACE] Adding member 03082d21-850c-6597-9908-012a6272fea1 to team Test8 Team: timestamp=2023-07-28T15:09:49.749+0200
2023-07-28T15:09:49.978+0200 [INFO]  provider.terraform-provider-azuredevops_v0.7.0: 2023/07/28 15:09:49 [DEBUG] Waiting for state to become: [Synched]: timestamp=2023-07-28T15:09:49.978+0200
2023-07-28T15:09:55.184+0200 [ERROR] provider.terraform-provider-azuredevops_v0.7.0: Response contains error diagnostic: diagnostic_detail= tf_proto_version=5.3 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_summary=" waiting for distribution of member list update. Error reading team memberships: Request returned status: 404 Not Found " tf_provider_addr=registry.terraform.io/microsoft/azuredevops tf_req_id=e2438c92-5708-e109-1a2a-7a53d528bd21 tf_resource_type=azuredevops_team_members tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_severity=ERROR timestamp=2023-07-28T15:09:55.183+0200
2023-07-28T15:09:55.185+0200 [ERROR] vertex "azuredevops_team_members.default_team_members" error:  waiting for distribution of member list update. Error reading team memberships: Request returned status: 404 Not Found
```
### Expected Behavior

azuredevops_team_members  works without issues

### Actual Behavior

azuredevops_team_members returns 404 when team has more than 45 members

### Steps to Reproduce

1. Terraform apply azuredevops_team_members  with large number of members (at least 46)

### Important Factoids

1. Number of members in the team

### References

* #0000

**Comment by Nataliia5722** [comment]
@xuzhang3 all the teams resources and data are affected. Any suggestions/recommendations how it can be resolved? 
Currently a blocker for our team.

**Comment by xuzhang3** [comment]
@Nataliia5722  this seems to be the read operation called too early before the members updated.  The team members still updating or update failed then the GET returns the 404 error code.

**Comment by Nataliia5722** [comment]
@xuzhang3 thanks a lot for the quick response! 
I was trying to update the response value from string to struct [here](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/v7/identity/client.go#L897), thinking maybe it can't handle a long response (cause for 42 users works as expected in my case, but fails while adding 43d user). 
After this update to struct, the 404 has gone, but now getting `json: cannot unmarshal string into Go struct field .Value of type identity.Team`
The struct I was using:
```
type Team struct {
    Value []struct {
        Identity struct {
            DisplayName string `json:"displayName"`
			Url string `json:"url"`
			Id string `json:"id"`
			Descriptor string `json:"descriptor"`
        } `json:"identity"`
    } `json:"value"`
}
```
[ReadMembers](https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/v7/identity/client.go#L880) then:
```
func (client *ClientImpl) ReadMembers(ctx context.Context, args ReadMembersArgs) (*[]Team, error) {
	routeValues := make(map[string]string)
	if args.ContainerId == nil || *args.ContainerId == "" {
		return nil, &azuredevops.ArgumentNilOrEmptyError{ArgumentName: "args.ContainerId"}
	}
	routeValues["containerId"] = *args.ContainerId

	queryParams := url.Values{}
	if args.QueryMembership != nil {
		queryParams.Add("queryMembership", string(*args.QueryMembership))
	}
	locationId, _ := uuid.Parse("8ba35978-138e-41f8-8963-7b1ea2c5f775")
	resp, err := client.Client.Send(ctx, http.MethodGet, locationId, "7.1-preview.1", routeValues, queryParams, nil, "", "application/json", nil)
	if err != nil {
		return nil, err
	}

	var responseValue []Team
	err = client.Client.UnmarshalCollectionBody(resp, &responseValue)
	return &responseValue, err
}
```
And updates in _**terraform-provider-azuredevops**_, in [readTeamMembers](https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/core/resource_team.go#L356) to iterate through struct:
```
func readTeamMembers(clients *client.AggregatedClient, team *core.WebApiTeam) (*schema.Set, error) {
	membersList, err := clients.IdentityClient.ReadMembers(clients.Ctx, identity.ReadMembersArgs{
		ContainerId: converter.String(team.Id.String()),
	})
	if err != nil {
		return nil, err
	}

	set := schema.NewSet(schema.HashString, nil)
	for _, member := range *membersList {
		for _, value := range member.Value {
			set.Add(value.Identity.Descriptor)
		}
	}

	return set, nil
}
```
Not sure this information will be helpful, cause I'm new to Go, but thought would be better to share :)

Thank you!

**Comment by xuzhang3** [comment]
@Nataliia5722 thanks for sharing the details,  I need to do some testing to locate this error

**Comment by Nataliia5722** [comment]
Hi @xuzhang3! Any updates on this?

**Comment by xuzhang3** [comment]
@Nataliia5722 sorry for the delay response, the root issue here is that the query string is too long for the API which resulted in 404 error. We are working on to fix this issue.
