### ISSUE TITLE
Branch policy at folder level is not applied using Terraform

### ISSUE THREAD

**Issue by hari-budd** [microsoft/terraform-provider-azuredevops#855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform version - 1.5.5
+ provider registry.terraform.io/databricks/databricks v1.2.1
+ provider registry.terraform.io/hashicorp/azuread v2.41.0
+ provider registry.terraform.io/hashicorp/azurerm v3.69.0
+ provider registry.terraform.io/microsoft/azuredevops v0.7.0

### Terraform Configuration Files
```hcl
data "azuredevops_project" "project_name" {
  name = "name-of-project"
}

data "azuredevops_git_repository" "repo_name" {
  project_id = data.azuredevops_project.project_name.id
  name       = "repo-name"
}

data "azuredevops_group" "admin" {
  project_id = data.azuredevops_project.project_name.id
  name       = "ADO group name"
}

resource "azuredevops_branch_policy_auto_reviewers" "azuredevops_projectid" {
  project_id = data.azuredevops_project.project_name.id

  enabled  = true
  blocking = true

  settings {
    auto_reviewer_ids  = [data.azuredevops_group.admin.origin_id]
    submitter_can_vote = false
    message            = "Auto reviewer"
    path_filters       = ["path/*"]

    scope {
      repository_id  = "repo id"
      repository_ref = "refs/features/PR_trigger"
      match_type     = "Exact"
    }
  }
}
```
### Output

            ]
          + submitter_can_vote          = false

          + scope {
              + match_type     = "Exact"
              + repository_id  = "repo id"
              + repository_ref = "refs/features/PR_trigger_edit"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

### Expected Behavior

<img width="719" alt="image" src="https://github.com/microsoft/terraform-provider-azuredevops/assets/61681776/7f24cc3f-bb96-4be0-a16f-2fa1a5347df7">

### Actual Behavior

<img width="728" alt="image" src="https://github.com/microsoft/terraform-provider-azuredevops/assets/61681776/32c6e886-4095-4899-b787-2476c711a204">

### Steps to Reproduce

1. `terraform apply`

**Comment by xuzhang3** [comment]
@hari-budd  The `path_filters       = ["path/*"]` will not match the ` repository_ref = "refs/features/PR_trigger_edit"`,  you need change the filters.

**Comment by hari-budd** [comment]
Hello @xuzhang3 thank you for the response. I am able to apply the required path filter on the branch. 
But one thing which i am unable to get is , I need to apply the policy on multiple folders .

This is what i tried doing for multiple folders ,
path_filters       = ["/folderA/abc/*;/FolderA/123/*;/FolderB/*"]

It isnt applying the branch policy when a PR is created . 

But when i just use on path in the path filters it is working fine. Can you help please. 

The code for this is written as 

resource "azuredevops_branch_policy_auto_reviewers" "azuredevops_projectid" {
  project_id = data.azuredevops_project.project_name.id

  enabled  = true
  blocking = true

  settings {
    auto_reviewer_ids  = [data.azuredevops_group.admin.origin_id]
    submitter_can_vote = false
    message            = "Auto reviewer"
    path_filters       = ["/pipelines/ci/*;/pipelines/cd/*;/mlops/*"]

    scope {
      repository_id  = data.azuredevops_git_repository.repo_name.id
      repository_ref = "refs/heads/Staging"
      match_type     = "Exact"
    }
  }
}

**Comment by hari-budd** [comment]
The path filters folder mutliple sub folders are achieved using this format 
path_filters = ["/pipelines/ci/*", "/pipelines/cd/*" ,"/mlops/*"]
