### ISSUE TITLE
Error: Creating user entitlement: Adding user entitlement: (5032) Access Denied: rundeck svcacct needs the following permission(s) on the resource Users to perform this action: Add Users

### ISSUE THREAD

**Issue by anikm1987** [microsoft/terraform-provider-azuredevops#86]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v0.12.24
+ provider.azuredevops v0.1.3

### Affected Resource(s)

azuredevops_user_entitlement

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

# Make sure to set the following environment variables:
#   AZDO_PERSONAL_ACCESS_TOKEN
#   AZDO_ORG_SERVICE_URL
```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_project" "project" {
  project_name = "aniket-test-tf"
  description  = "Devops pipeline to ADO TF"
}


// This section configures an Azure DevOps Variable Group
resource "azuredevops_variable_group" "tf-provider" {
  project_id   = azuredevops_project.project.id
  name         = "tf-provider"
  description  = "Azure TF providers"
  allow_access = true

  variable {
    name      = "ARM_CLIENT_ID"
    value     = "abc"
    is_secret = true
  }
}

// This section configures an Azure DevOps Variable Group
resource "azuredevops_variable_group" "tf-backend" {
  project_id   = azuredevops_project.project.id
  name         = "tf-backend"
  description  = "Variable to keep all details about tfstate storage"
  allow_access = true

  variable {
    name = "container_name"
    value = "tfstate"
    is_secret = true
  }
  
}

resource "azuredevops_user_entitlement" "user" {
  principal_name = "nick.kar@gmail.com"
}

data "azuredevops_group" "group" {
  project_id = azuredevops_project.project.id
  name       = "Build Administrators"
}

resource "azuredevops_group_membership" "membership" {
  group = data.azuredevops_group.group.descriptor
  members = [
    azuredevops_user_entitlement.user.descriptor
  ]
}
```

### Expected Behavior

User should be added to the group in the project.

### Actual Behavior

Error: Creating user entitlement: Adding user entitlement: (5032) Access Denied: rundeck svcacct needs the following permission(s) on the resource Users to perform this action: Add Users

  on main.tf line 94, in resource "azuredevops_user_entitlement" "user":
  94: resource "azuredevops_user_entitlement" "user" {

### Steps to Reproduce
terraform apply

1. `terraform apply`

### Important Factoids

No
### References

* #0000

**Comment by anikm1987** [comment]
With same user account I am able to add the user in a newly created project using user interface. Unable to do it using terraform code

**Comment by xuzhang3** [comment]
Hi @anikm1987 ADO provider get access permissions from personal access token.  You can change the permission configuration though portal:  `usersettings-> personal access-tokens`, select the token you use and change the permission configuration.
![image](https://user-images.githubusercontent.com/57888764/87910114-0bce4d80-ca9c-11ea-9fbe-f7d65912fbdd.png)

**Comment by anikm1987** [comment]
Hi xuzhang3,
I have tried with full access for the token but still getting the same error.

I don't see anything as Add Users access while creating the token.

**Comment by xuzhang3** [comment]
@anikm1987 `rundeck ` is not managed by ADO provider. Can you check your HCL that the project configure is correct?

**Comment by anikm1987** [comment]
Hi,

Rundeck is just the functional account name, similar to my name anikm1987 using which I logged in to the Azure Devops org. If you see the terraform code I am not doing anything with Rundeck. Sorry if the functional account cause any confusion.


I am simply trying to create project and add members to it when it is throwing error - 
needs the following permission(s) on the resource Users to perform this action: Add Users 


How to provide this permission to this account? I have already given full access to the token

**Comment by xuzhang3** [comment]
I cannot reproduce your error. Can you provider more logs which have more context information.

**Comment by xuzhang3** [comment]
Close this issue, feel free to reopen it if you have questions.

**Comment by vastnight** [comment]
You have enough permissions to add a user to a project, but you don't have enough permissions to create a user entitlement. (you can check in your azure devops organization page > organization settings > users ; and you probably dont have enough rights to create / add a user)

you need the rights Member Entitlement Management: Read & Write
