### ISSUE TITLE
azuredevops_build_folder_permissions set permissions on "root" in pipelines

### ISSUE THREAD

**Issue by MariusStorhaug** [microsoft/terraform-provider-azuredevops#860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v1.5.5
on windows_amd64

azuredevops provider version: 0.7.0
```

### Affected Resource(s)

* `azuredevops_build_folder_permissions`

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "example" {
  name               = "Example Project"
  work_item_template = "Agile"
  version_control    = "Git"
  visibility         = "private"
  description        = "Managed by Terraform"
}

resource "azuredevops_group" "edit_build_definitions" {
  project_id = azuredevops_project.example.id
  name       = "EditBuildDefinitions"
}

resource "azuredevops_build_folder_permissions" "example" {
  project_id = azuredevops_project.example.id
  path       = "\\"
  principal  = azuredevops_group.edit_build_definitions.id

  permissions = {
    "EditBuildDefinition" : "allow"
  }
}
```

Have also tested with path set to `"."` `"\\"` `""` and `".\\"` with no change in behaviour.

### Expected Behavior

Set permissions on a group on the "root"

### Actual Behavior

No permission actually set in the pipeline view on "root" via "Manage security".

### Steps to Reproduce

1. `terraform apply`
2. Review the security/permissions set on "pipelines" view on root (not under another folder).

### References

* #0000

**Comment by xuzhang3** [comment]
Similar to #842
