### ISSUE TITLE
azuredevops build definition - first run flag

### ISSUE THREAD

**Issue by Mabog10** [microsoft/terraform-provider-azuredevops#862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When automating the infrastructure deployment using azure devops provider, sometimes there is a need to **create a pipeline build definition and trigger the newly created pipeline automatically**. When creating the pipelines using azure cli command "az pipelines create" - this will create a new build definition and the new pipeline will be triggered automatically **(it is possible to change this using --skip-first-run flag)**. It would be great to have a similar flag in **"azuredevops_build_definition"** resource.

### New or Affected Resource(s)

* azuredevops_build_definition

### Potential Terraform Configuration

```hcl
resource "azuredevops_build_definition" "example" {
  project_id = data.azuredevops_project.this.id
  name       = "test-pipeline"
  path       = "\\"

  repository {
    repo_type   = "TfsGit"
    repo_id     = azuredevops_git_repository.this.id
    branch_name = azuredevops_git_repository.this.default_branch
    yml_path    = "example.yaml"
    skip_first_run = false
  }
}
```

**Comment by xuzhang3** [comment]
Run pipeline: https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run-pipeline?view=azure-devops-rest-7.0

**Comment by Mabog10** [comment]
> Run pipeline: https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run-pipeline?view=azure-devops-rest-7.0

I am aware that we can use REST API call to run the pipeline, but having the possibility to run the pipeline inside azuredevops provider would make the pipeline development much more simple.

**Comment by xuzhang3** [comment]
@Mabog10 I have a dev branch working this features and the first run will only available on create.

**Comment by Mabog10** [comment]
That's great, thank you!
I believe below page needs to be updated as well 😉
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/build_definition

**Comment by xuzhang3** [comment]
@Mabog10 The documentation is updated along with the code. Not sure why the document updates aren't showing up.https://github.com/microsoft/terraform-provider-azuredevops/blob/main/website/docs/r/build_definition.html.markdown

**Comment by arkoc** [comment]
@xuzhang3 I bealive the proposed solution is going to work ONLY for projects that are using DevOps Git Repositories. The code is using `clients.GitReposClient` which I bealive is working only with DevOps Git Repos.

When I pass `repoId` in GitHub format (`gitOrg/repoName`), it's throwing error "Page not found".

As far as I can see from the code, we need the branch information for passing `commitId` to `version` property in `RunPipeline` request. Is the `version` required there? Because from UI I can trigger without passing the commit id.

**Comment by arkoc** [comment]
Just tested it with API, version is not required, will create a PR soon.

I removed all references using `GitReposClient` and removed the `version` property from request body. Tested this with API as well as DevOps UI works like a charm. :)
