### ISSUE TITLE
Tag azure devops project

### ISSUE THREAD

**Issue by gregbaleyy** [microsoft/terraform-provider-azuredevops#868]
I would like to tag my azure devops project using terraform but I can't see tags as a parameter of azuredevops_project resource
![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/111118056/cf8c409b-2fea-4e49-a8d4-aa8d85872a07)

Is there another way to do that?

**Comment by xuzhang3** [comment]
Original project does not support tags. Is this feature enabled by some extension?

**Comment by gregbaleyy** [comment]
There is no extension that seems link to it in my organization. To me it is default behavior.
You can add tags by clicking on  "Edit project information" on Overwiew/Summary page.
It is visible in MS documentation: https://learn.microsoft.com/en-us/azure/devops/organizations/projects/project-vision-status?view=azure-devops#update-the-page

**Comment by gregbaleyy** [comment]
We can also see tags using API
![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/111118056/9786820d-cc79-4e19-83f6-ec717e7fd5bd)

I managed to create one using API: https://learn.microsoft.com/en-us/rest/api/azure/devops/core/projects/set-project-properties?tabs=HTTP

Example of body (create a tag "test"):
```json
[
    {
        "op": "add",
        "path": "/Microsoft.TeamFoundation.Project.Tag.test",
        "value": "true"
    }
]
```
