### ISSUE TITLE
New Data Source - `azuredevops_environment` List all environments

### ISSUE THREAD

**Issue by ghs** [microsoft/terraform-provider-azuredevops#886]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add possibility to list environments within a project.
https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/list?view=azure-devops-rest-7.0
Requesting this because currently in order to get specific environment is by providing an ID: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/environment
Around other resources, when an environment ID is needed, a reference from https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/environment can be used, but that makes no sense of the current data source implementation.

### New or Affected Resource(s)

* azuredevops_environment: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/data-sources/environment

### Potential Terraform Configuration

```hcl
resource "azuredevops_environment" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Environment"
}

resource "azuredevops_check_approval" "example" {
  project_id           = azuredevops_project.example.id
  target_resource_id   = azuredevops_environment.example.id # <-- HERE WE USE THE ID FROM ABOVE,  WHICH MAKES THE DATA SOURCE USELESS. IN ADDITION, IF DON'T HAVE THE ID, WE CAN'T RETRIEVE IT.
  target_resource_type = "environment"

  requester_can_approve = true
  approvers = [
    azuredevops_group.example.origin_id,
  ]
}
```

### References

* #0000

**Comment by xuzhang3** [comment]
API: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/list?view=azure-devops-rest-7.0
