### ISSUE TITLE
datasource azuredevops_project - Error looking up template by ID

### ISSUE THREAD

**Issue by ncastrocosta** [microsoft/terraform-provider-azuredevops#892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.5.4
on linux_amd64

azuredevops provider version: 0.9.1

### Affected Resource(s)

* `azuredevops_project`

### Terraform Configuration Files

```hcl
data "azuredevops_project" "myproject" {
  name = "myproject"
}
```

### Expected Behavior

On plan execution, it was expected the data source to be able to read the project details.

### Actual Behavior

The following error message:

Error: Error flattening project: Error looking up template by ID: Request returned status: 401 Unauthorized

Although it has the "401 Unauthorized" message, I'm able to read the project using the `azuredevops_projects` data source.

### Steps to Reproduce

1. `terraform plan`

### References

* looks like something similar happened months ago #755

**Comment by xuzhang3** [comment]
@ncastrocosta  The PAT need the permissions to work item template.

**Comment by browol** [comment]
Adding read permission to the PAT at the `Work Items` scope works for me.
