### ISSUE TITLE
Add these settings authorizeAllPipelines and autoProvisionProjectPools when we create a new elastic pool using azuredevops_elastic_pool

### ISSUE THREAD

**Issue by Khayoann2** [microsoft/terraform-provider-azuredevops#894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of today when we create a new azure devops elastic pool, the pool will remains at the organization level.
Even if you enable the autoprovision later, it seems to be not enough because the auto-provisioning setting is only for new project.
So if you want to spread your agent pool into your existing project, this is set by autoProvisionProjectsPools setting when you create the new elastic pool in devops.

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/95438464/aabc1e82-abc8-4b4d-a91c-fbc942c1d05c)

### New or Affected Resource(s)

azuredevops_elastic_pool

### Potential Terraform Configuration

```hcl

resource "azuredevops_elastic_pool" "agents" {
  name                   = "agents"
  service_endpoint_id    = data.azuredevops_serviceendpoint_azurerm.serviceendpoint.id
  service_endpoint_scope = data.azuredevops_project.test.id
  desired_idle           = 0
  max_capacity           = 30
  azure_resource_id      = azurerm_linux_virtual_machine_scale_set.agents.id
  auto_provision   = true # for new projects
  time_to_live_minutes   = 60
  authorize_all_pipelines_after_creation = true
  auto_provision_projects_after_creation = true # for all existing projects after creation
}
```

### References

* #0000

**Comment by Khayoann2** [comment]
I find a workaround.... Maybe it is the normal way to deal with that but it's a little bit tricky

Adding this did the trick 


``` hcl
resource "azuredevops_agent_queue" "example" {
  project_id    = data.azuredevops_project.test.id
  agent_pool_id = azuredevops_elastic_pool.agents.id
}

resource "azuredevops_pipeline_authorization" "test" {
  project_id  = data.azuredevops_project.test.id
  resource_id = azuredevops_agent_queue.example.id
  type        = "queue"
}
```

**Comment by xuzhang3** [comment]
pipeline authorization has been supported by resource [azuredevops_pipeline_authorization](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/pipeline_authorization)
