### ISSUE TITLE
401 while trying to get project details using datasource

### ISSUE THREAD

**Issue by s4ntos** [microsoft/terraform-provider-azuredevops#897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.5.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.50.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/microsoft/azuredevops v0.9.1

### Affected Resource(s)

* `data.azuredevops_project`

### Terraform Configuration Files

Provider is configured to ask for the PAT as a variable

```hcl
provider "azuredevops" {
  personal_access_token = var.azuredevops_pat
  org_service_url = "${var.azuredevops_url}${var.azuredevops_org}"
}
```
I have tried using "static values" but the problem remains the same.

The request is very simple and asks for the details for a certain project from a variable, but the error is around.

```hcl
data "azuredevops_project" "project" {
  name = var.azuredevops_project
}
```

### Debug Output

The Output doesn't provide much information . 
I believe the problem may occur because I have more than one Org on my profile. But that doesn't make sense based 

```powershell
C:\azure_agent > terraform apply -var-file .\env\variables.tfvars -target data.azuredevops_project.project
var.azuredevops_pat
  Token to add agent to devops azure

  Enter a value: PAT

data.azuredevops_project.project: Reading...
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵
╷
│ Error: Error flattening project: Error looking up template by ID: Request returned status: 401 Unauthorized
│
│   with data.azuredevops_project.project,
│   on azuredevops.tf line 11, in data "azuredevops_project" "project":
│   11: data "azuredevops_project" "project" {
│
╵
``` 
### Expected Behavior

I should get the details of the project

### Actual Behavior

I get a 401 error 

│ Error: Error flattening project: Error looking up template by ID: Request returned status: 401 Unauthorized

### Steps to Reproduce

See above

### Important Factoids

I belong to 2 separate organizations.

If I make the same request using the API with the same TOKEN the reply is succesfull.
```powershell
curl -s -u user:$env:AZDO_PERSONAL_ACCESS_TOKEN $env:AZDO_ORG_SERVICE_URL/_apis/projects?api-version=2.0 
```

The PAT created as the normal privileges for a azure agent + full manage access to projects (I would also like to restrict this to read only)

### References

N/A

**Comment by xuzhang3** [comment]
@s4ntos 1. How do you set the PAT used by `var.azuredevops_pat`
2. The project template will be fetched by the project data source, so you need the permission to mange the template.

**Comment by s4ntos** [comment]
@xuzhang3 not sure why I didn't receive any notification on your answer.

Any way the PAT is created on the azure devops console, if I use the exact same PAT on the curl it works and I get the reply.
In fact my current work around is to perform the HTTP request and parse the JSON myself. 

Code bellow for reference.

```
data "http" "project_id" {
  url = "${var.azuredevops_url}${var.azuredevops_org}/_apis/projects/${var.azuredevops_project}?api-version=2.0"
  request_headers = {
    Accept = "application/json"
    Authorization = "Basic ${base64encode("bogus:${var.azuredevops_pat}")}"
  }
}

resource "azuredevops_agent_queue" "project-queue" {
  project_id    = jsondecode(data.http.project_id.response_body).id
  agent_pool_id = azuredevops_agent_pool.project-pool.id
}
```

**Comment by xuzhang3** [comment]
@s4ntos  curl request will only get the project info but ADO provider will try to get the work item template infos so the PAT used needs to have the permissions on the work items as well.

**Comment by s4ntos** [comment]
Can confirm,  adding read permissions to the work item does resolve the issue
