### ISSUE TITLE
TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.

### ISSUE THREAD

**Issue by jceval** [microsoft/terraform-provider-azuredevops#901]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.5.7
on windows_386
+ provider registry.terraform.io/hashicorp/azuread v2.43.0
+ provider registry.terraform.io/hashicorp/azurerm v3.75.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/microsoft/azuredevops v0.9.1

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurerm`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.3.0"
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.7.0"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}

provider "azuredevops" {
  # Configuration options
  org_service_url       = var.org_service_url
  personal_access_token = var.personal_access_token
}

resource "azuredevops_serviceendpoint_azurerm" "service_connection" {

  project_id                = var.devops_project_id
  service_endpoint_name     = "spn-${var.environment}"
  azurerm_spn_tenantid      = var.azurerm_provider_tenant_id
  azurerm_subscription_id   = var.subscription_id
  azurerm_subscription_name = var.subscription_name

  credentials {
    serviceprincipalid  = var.application_id
    serviceprincipalkey = var.application_password
  }
}
```

### Expected Behavior

Im passing in the variables for the PAT token and the project ID through an Azure DevOps Variable Group. The pipeline is then running  Terraform CLI and passing in the values as -var to the CLI. Expecting that the provider is able to log in and deploy the Service Connection resource in the Azure DevOps project. The PAT token has Full Access on the ADO project.

### Actual Behavior

Error: TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.
│ 
│   with provider["registry.terraform.io/microsoft/azuredevops"],
│   on providers.tf line 9, in provider "azuredevops":
│    9: provider "azuredevops" {

### Steps to Reproduce

1. `Create PAT Token from Azure DevOps User Settings`
2. `Create variable group in Azure DevOps Pipelines`
3. `Add Variable PAT_Token`
4. `Pass variable into Terraform runtime using -var flag`
5. `Register Azure DevOps Provider using the PAT_token variable`
6. `Create azuredevops_serviceendpoint_azurerm resource in terraform configuration`

**Comment by jaredfholgate** [comment]
Hi. This error would usually indicate an issue with the PAT, the PAT scope or the organization url being supplied.

**Comment by jceval** [comment]
I had seen some suggestion in other threads around that. But I'm trying to test out this functionallity and am using a pretty broad scope for this PAT.

![image](https://github.com/microsoft/terraform-provider-azuredevops/assets/45887246/9220b9ad-e5a0-4a21-99d5-c2593840b140)

Any other suggestions on what I should check?

**Comment by jaredfholgate** [comment]
@jceval  Could it be that your variable is called `personal_access_token`, but you are supplying it as `PAT_Token`?

If you can share a snippet of your pipeline or contact me directly, I can help further. Feel free to find me on LinkedIn and message me https://www.linkedin.com/in/jaredfholgate.

**Comment by jceval** [comment]
Thanks for the attention to detail @jaredfholgate !
I was using PAT_Token as my own test PAT, and personal_access_token as the enterprise PAT token used for the automation.

Thanks for noticing my mix up !
