### ISSUE TITLE
Support for federated authentication instead of PAT?

### ISSUE THREAD

**Issue by jackmtpt** [microsoft/terraform-provider-azuredevops#903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure DevOps now supports authenticating to its API via Managed Identity or Service Principal credentials instead of requiring a PAT. This would greatly simplify deployments because typically you will already have such credentials available when running Terraform to store your state file in an Azure Storage account.

This already kind-of works if you manually obtain a token via `az account get-access-token --resource=499b84ac-1321-427f-aa17-267ca6975798` and put that into the `AZDO_PERSONAL_ACCESS_TOKEN` env var instead of an actual PAT, so there hopefully aren't too many changes required to the actual API calling code - the provider just needs to do the equivalent library call to get a token.

### Potential Terraform Configuration

Ideally the provider would try and obtain a token via the azure identity library automatically, and only _then_ check the environment variable for a PAT.

### References

https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-228-update#managed-identity-and-service-principal-support-for-azure-devops-now-in-general-availability-ga

* #0000

**Comment by xuzhang3** [comment]
@jackmtpt  #865 will support auth with SPN

**Comment by jackmtpt** [comment]
Did you mean #747 ? I suppose this can be closed

**Comment by xuzhang3** [comment]
@jackmtpt  yes, #747 will support auth with SPN.
