### ISSUE TITLE
Why is the subscription ID and name required to create an azurerm service connection?

### ISSUE THREAD

**Issue by jackmtpt** [microsoft/terraform-provider-azuredevops#904]
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_azurerm

Subscription names are mutable and not globally unique, and can be looked up from the subscription ID (which _is_ globally unique). Why doesn't the provider do this, instead of requiring them both?

**Comment by xuzhang3** [comment]
@jackmtpt The subscription APIs is managed by **Azure**. ADO provider focus on  mange the **Azure DevOps** resources. You can use `AzureRM` to get the subscription ID 
Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/subscription

**Comment by jackmtpt** [comment]
Yeah that's exactly what I've done in the end. Do you know why ADO requires the sub name in the first place?

**Comment by xuzhang3** [comment]
@jackmtpt  This is an API constraint, the sub name is required when creating new AzureRm service connection manually.
