### ISSUE TITLE
Move the service connection ID out of the repository block for the build_definition resource

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#91]
As of now the service connection ID lives within the repository block for the  `build_definition` resource. Logically this should be moved into the top level definition of the resource, as it is not an attribute of the repository.

**Comment by stevenfranks** [comment]
PR added, could this be reviewed please?

**Comment by nmiodice** [comment]
Need to re-visit this issue. I may have mis-understood how the service connection auth works for pipelines, making this an invalid story. 

Please hold! I'll re-visit this today.

**Comment by nmiodice** [comment]
@stevenfranks apologies for a mistake that I made with regards to https://github.com/microsoft/terraform-provider-azuredevops/issues/91 - I misunderstood how the service connection configuration works for build definitions and mistakenly thought that this ID was used to configure the service connection that the *whole* build runs under. However, this property only configures the service connection needed to connect to GitHub.

For this reason, the current implementation is correct and nothing needs to change here. Sorry to waste your time, and I really do appreciate the time it took you to implement.

I'll do better at validating my assumptions moving forward.

Based on this, I'll go ahead and close out the PR and issue since there is no need for change. Feel free to re-open if you'd like to continue the discussion.
