### ISSUE TITLE
azuredevops_serviceendpoint_azurerm is not supported in Azure US Gov Cloud???

### ISSUE THREAD

**Issue by dsavciuc** [microsoft/terraform-provider-azuredevops#919]
I work with the Azure US Government Cloud, and I need to add a few service connections using the service principals. However, I am not able to select the Azure US Government using the terraform. In the docs, https://registry.terraform.io/providers/microsoft/azuredevops/0.10.0/docs/resources/serviceendpoint_azurerm It is suggested that possible values are Azure Cloud and Azure China Cloud. Is that a defect? 
Thank you

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@dsavciuc current supported clouds are `AzureCloud` and `AzureChinaCloud`
