### ISSUE TITLE
Modify Project resource handling of git/tfvc repositories during creation

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/terraform-provider-azuredevops#92]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Perform minor modifications to the existing Project resource in preparation for implementation of support for non-trivial repository creation:
- Change `version_control` schema property to boolean `enable_tfvc`
- If `enable_tfvc` then set capability during project create for `versioncontrol:sourceControlType` = "Tfvc"
- If not `enable_tfvc` then set capability to "Git"
- (you can always add Git repos to a project individually)

### New or Affected Resource(s)

* azuredevops_project resource
  - Remove `version_control` schema property
  - Add `enable_tfvc` schema property

### Potential Terraform Configuration

Old configuration fragment:
```hcl
resource "azuredevops_project" "project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}
```

New configuration fragment:
```hcl
resource "azuredevops_project" "project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  enable_tfvc        = False
  work_item_template = "Agile"
}
```

### Acceptance Criteria

- [ ] Selecting `enable_tfvc` when creating a new project will create a TFVC repository, and no additional git repositories
- [ ] Not selecting `enable_tfvc` when creating a new project will NOT create a TFVC repository, and will instead create a single git repository
- [ ] Regardless of which option is selected at creation, it should still be possible to manually add additional git repositories to the project directly from AzDO portal
- [ ] If `enable_tfvc` is not selected during project creation, it should still be possible to manually add a single TFVC repository to the project directly from AzDO portal

### References

* Story spawned from design task #73

**Comment by nmiodice** [comment]
No plan to fix
