### ISSUE TITLE
Error when attempting to destroy a DevOps project with Tfvc version control and an additional Git repository.

### ISSUE THREAD

**Issue by januscgi** [microsoft/terraform-provider-azuredevops#922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
> terraform -v
Terraform v1.6.3
on windows_386
+ provider registry.terraform.io/microsoft/azuredevops v0.10.0
```

### Affected Resource(s)

* `azuredevops_project`
* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.10.0"
    }
  }
}

resource "azuredevops_project" "this" {
    name               = "TestProject"
    description        = "Test"
    visibility         = "private"
    version_control    = "Tfvc"
    work_item_template = "Agile"
}

resource "azuredevops_git_repository" "this" {
  project_id = azuredevops_project.this.id
  name       = "TestGitRepo"

  initialization {
    init_type = "Uninitialized"
  }
}
```

### Debug Output

https://gist.github.com/januscgi/2b2326fc8ac012d7c4e24162345e10fe

### Expected Behavior

When running `terraform apply .\main.destroy.tfplan` the project is destroyed.

### Actual Behavior

Terraform fails with the error message `Error: There must always be at least one repository per Team Project.`

### Steps to Reproduce

1. Create a module that creates a DevOps project with version control type "Tfvc" and a Git repository in the same project.
2. Run `terraform init`, `terraform plan -out main.tfplan`, and `terraform apply main.tfplan` to create the DevOps project.
3. Attempt to destroy the project with:
4. `terraform plan -destroy -out main.destroy.tfplan`
5. `terraform apply .\main.destroy.tfplan`

### Important Factoids

If I create a DevOps project with version control type Tfvs and no Git repository, destruction of the project works as expected. The error only occurs when there is an additional Git repository. 

### References

* #0000

**Comment by xuzhang3** [comment]
@januscgi This a service issue.  One workaround it remove the repository(`terraform state rm azuredevops_git_repository.this` )  from the state and destroy the project.

More info: https://learn.microsoft.com/en-us/azure/devops/repos/git/delete-existing-repo?view=azure-devops&viewFallbackFrom=vsts&tabs=browser

**Comment by januscgi** [comment]
I can confirm that the workaround works. Thank you!

**Comment by januscgi** [comment]
I can confirm that the workaround works. Thank you!
