### ISSUE TITLE
Allow creation of project scope elastic pool

### ISSUE THREAD

**Issue by rcomanne** [microsoft/terraform-provider-azuredevops#930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to Microsofts' Azure DevOps REST API documentation:
* If a project id is provided, this will create a new TaskAgentQueue in the specified project.
However, we do not have that option for the resource, meaning that the authenticated user needs to have permission on the organisational level it seems. By allowing the resource to be created on a project basis, we can use lesser scoped authorisation.

### New or Affected Resource(s)

* azuredevops_elastic_pool

### Potential Terraform Configuration

```hcl
resource "azuredevops_elastic_pool" "example" {
  name                   = "Example Elastic Pool"
  service_endpoint_id    = azuredevops_serviceendpoint_azurerm.example.id
  service_endpoint_scope = azuredevops_project.example.id
  project_id             = azuredevops_project.example.id
  desired_idle           = 2
  max_capacity           = 3
  azure_resource_id      = "/subscriptions/<Subscription Id>/resourceGroups/<Resource Name>/providers/Microsoft.Compute/virtualMachineScaleSets/<VMSS Name>"
}
```

**Comment by xuzhang3** [comment]
@rcomanne you create the agent pool at project level with [azuredevops_agent_queue](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/agent_queue)

```hcl
resource "azuredevops_elastic_pool" "example" {
  name                   = "Example Elastic Pool"
  service_endpoint_id    = azuredevops_serviceendpoint_azurerm.example.id
  service_endpoint_scope = azuredevops_project.example.id
  desired_idle           = 2
  max_capacity           = 3
  azure_resource_id      = "/subscriptions/<Subscription Id>/resourceGroups/<Resource Name>/providers/Microsoft.Compute/virtualMachineScaleSets/<VMSS Name>"
}

resource "azuredevops_agent_queue" "example" {
  project_id    = azuredevops_project.example.id
  agent_pool_id = azuredevops_elastic_pool.example.id
}
```

**Comment by rcomanne** [comment]
@xuzhang3 I understand what you're saying, but that does not solve my issue; as the user we've been given by our organisation does not have permission to create the initial pool definition on the Organizational scope.
So while this will work to add an agent pool that's been created to a project, it will not work to create the initial pool inside that project scope.

**Comment by xuzhang3** [comment]
@rcomanne   we can add this feature, but as I know the default behavior of create a new elastic pool will create a organization level pool too.

**Comment by rcomanne** [comment]
@xuzhang3 yes, it does also create it on the org scope, but somehow there is something strange in the rights of Azure DevOps, where creating it in the project scope is allowed (even though they'll also be created on the org) while directly creating it as an organization agent pool is *not* allowed.
