### ISSUE TITLE
data azuredevops_teams: return 404

### ISSUE THREAD

**Issue by jaysson1710** [microsoft/terraform-provider-azuredevops#933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

terraform: 1.6.4
provider:  registry.terraform.io/microsoft/azuredevops v0.10.0

### Affected Resource(s)

data azuredevops_teams

### Terraform Configuration Files

```hcl
data "azuredevops_teams" "teams_project2" {
  project_id = "7f7f7f32-94f6-42c0-9611-cfa0bba90c9d"
}

output "teamsout" {
  value = data.azuredevops_teams.teams_project2.teams
}
```

### Debug Output
https://gist.github.com/jaysson1710/753218d2b0bb79219de893b037eed812

### Expected Behavior

get information about existing teams in selected projects. 

### Actual Behavior

error while terraform plan is running.
the error doesn't happen for all projects, and I already verified that the ID project passed is right, but the error lock other steps on my general flow

```HCL
 Error: Request returned status: 404 Not Found
│
│   with module.devops.data.azuredevops_teams.teams_project2,
│   on modules\devops\devops.tf line 115, in data "azuredevops_teams" "teams_project2":
│  115: data "azuredevops_teams" "teams_project2" {
```
I really appreciate you help with this situation!

**Comment by AleksanderTolstopyatov** [comment]
I think this is a repeat of the [problem](https://github.com/microsoft/terraform-provider-azuredevops/issues/805)

**Comment by xuzhang3** [comment]
@jaysson1710 Can't reproduce. Can you share detailed logs? The log only shows 404 error and I can't find which part is produce this error(code side)
