### ISSUE TITLE
reading azuredevops_group: Error: Request returned status: 401 Unauthorized, using specific PAT permissions

### ISSUE THREAD

**Issue by rob-zz** [microsoft/terraform-provider-azuredevops#934]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.41.0
+ provider registry.terraform.io/hashicorp/azurerm v3.77.0
+ provider registry.terraform.io/microsoft/azuredevops v0.10.0

### Affected Resource(s)

* `azuredevops_group`

### Terraform Configuration Files

```hcl
data "azuredevops_group" "contributors" {
  project_id = azuredevops_project.project.id
  name       = "Contributors"
}
```

### Expected Behavior

The group is read successfully.

### Actual Behavior

Error: Error finding descriptor for project with ID 00000000-0000-0000-0000-000000000000. Error: Request returned status: 401 Unauthorized

### Steps to Reproduce

1. Create a PAT with the 'Project & Team: Read, Write, & Manage' permission
2. Create a DevOps group and try to read it's built-in Contributors group using `terraform plan`

### Important Factoids

This is using a PAT having specific permissions (see above). Using a Full Access PAT this works without error. However that is not an option for us. We would like to only allow specific permissions here. According to the documentation, "Project & Team: Read, Write, & Manage" should be enough permission to use `azuredevops_group`, but that seems false.

### References

* #0000

**Comment by rob-zz** [comment]
@xuzhang3 Fonud out that 'Graph - Read' is required for this. It's probably a good idea to add this to the documentation of the `azuredevops_group` data source. Similarly, the resource needs 'Graph - Read & Manage'. The documentation is wrong, or at least incomplete, at this point.

**Comment by xuzhang3** [comment]
@robbert-nlo sorry for the inconvenience. The PAT permissions are not documented as required for all resource.
