### ISSUE TITLE
azuredevops_pipeline_authorization: Usign Type: "repository" is impossible to create an auth for github

### ISSUE THREAD

**Issue by diegolagospagopa** [microsoft/terraform-provider-azuredevops#954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```hcl
terraform {
  required_version = ">= 1.3.5"
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "<= 0.11.0"
    }
    azurerm = {
      version = "<= 3.85.0"
    }
  }
  backend "azurerm" {}
}
``` 

### Affected Resource(s)

* azuredevops_pipeline_authorization

### Terraform Configuration Files

```hcl
resource "azuredevops_pipeline_authorization" "github_service_connection_authorization" {
  depends_on = [azuredevops_build_definition.pipeline, time_sleep.wait]

  project_id  = var.project_id
  resource_id = var.github_service_connection_id
  pipeline_id = azuredevops_build_definition.pipeline.id
  type        = "repository"
}
```

### Expected Behavior

The authorization is created, if i use "endpoint" as type everything work as expected

### Actual Behavior

```
│ Error:  creating authorized resource: The resource doesn't exist or the user doesn't have use permission.
│ 
│   with module.pagopa-ecommerce-transactions-service_code_review[0].azuredevops_pipeline_authorization.github_service_connection_authorization,
│   on .terraform/modules/pagopa-ecommerce-transactions-service_code_review/azuredevops_build_definition_code_review/main.tf line 90, in resource "azuredevops_pipeline_authorization" "github_service_connection_authorization":
│   90: resource "azuredevops_pipeline_authorization" "github_service_connection_authorization" {
│ 
``` 

### Steps to Reproduce

1. Create service connection `Github`
2. Create a resource: `azuredevops_build_definition`
3. create a azuredevops_pipeline_authorization linked to the pipeline, and to a github's service connection. The type must be "repository"
4. `terraform apply` 

### References

* #0000

**Comment by xuzhang3** [comment]
@diegolagospagopa  `endpoint` is the right type for service connection. `repository` is for  Azure DevOps repository.  The authorization resource can only authorize the resource in Azure DevOps.

**Comment by diegolagospagopa** [comment]
Ok thx, but please can you put this info into the documentation. I was not able to find anything about that

**Comment by xuzhang3** [comment]
@diegolagospagopa  document updated #960
