### ISSUE TITLE
Optional arguments in `azuredevops_serviceendpoint_azurerm` aren't optional

### ISSUE THREAD

**Issue by rob-zz** [microsoft/terraform-provider-azuredevops#955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
+ provider registry.terraform.io/hashicorp/azurerm v3.83.0
+ provider registry.terraform.io/microsoft/azuredevops v0.11.0

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurerm`

### Terraform Configuration Files

```hcl
resource "azuredevops_project" "example" {
  name               = "Example Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
  description        = "Managed by Terraform"
}

resource "azuredevops_serviceendpoint_azurerm" "example" {
  project_id                             = azuredevops_project.example.id
  service_endpoint_name                  = "Example AzureRM"
  description                            = "Managed by Terraform"
  service_endpoint_authentication_scheme = "ServicePrincipal"
  credentials {
    serviceprincipalid  = "00000000-0000-0000-0000-000000000000"
    serviceprincipalkey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
  azurerm_spn_tenantid      = "00000000-0000-0000-0000-000000000000"
  azurerm_subscription_id   = "00000000-0000-0000-0000-000000000000"
  #azurerm_subscription_name = "Example Subscription Name"
}
```

Note that I used the example from the documentation and commented out `azurerm_subscription_name` as it should be optional.

### Expected Behavior

According to the documentation, `azurerm_subscription_id` and `azurerm_subscription_name` are optional, however that does not seem true. Also note that setting `azurerm_subscription_name` to any random non-empty string also seems to correctly create the service endpoint, so I am unsure why this parameter is actually required.

### Actual Behavior

On `terraform apply`:
`Error: Error reading terraform configuration: azurerm_subscription_id and azurerm_subscription_name must be provided`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
@robbert-nlo  The require constraint is based on the `service_endpoint_authentication_scheme` and  not all of the constraint added, this will be fixed. 
`random non-empty string also seems to correctly` :
Default service connection creation will not do the validation,  `azurerm_subscription_id` and `azurerm_subscription_name` can be anything,  you set 
```hcl
features {
   validation = true
}
``` 
the creation will do the validation based on the configuration and you will get an error if anything goes wrong.

**Comment by rob-zz** [comment]
@xuzhang3 Thanks for clarifying. I can understand `azurerm_subscription_id` being required, but what still puzzles me is why `azurerm_subscription_name` is also required. When I set `azurerm_subscription_id` to the correct id and `azurerm_subscription_name` to a "dummy" string, the service endpoint still works. Do you know what the subscription name is actually needed for?

**Comment by xuzhang3** [comment]
@robbert-nlo  Initially, this follows the same parameters as required for web configuration.

**Comment by rob-zz** [comment]
@xuzhang3 Yeah, I asked myself this question for the web conf as well :) IMO it would make the configuration simpler if the sub name wasn't required, but I can understand following the web conf.

**Comment by xuzhang3** [comment]
The subName is required by the service, cannot ignore.
