### ISSUE TITLE
Add in data. azuredevops_environment the attribute for the resource id to use into pipelines authorization

### ISSUE THREAD

**Issue by diegolagospagopa** [microsoft/terraform-provider-azuredevops#964]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to allow pipelines to be linked/allow to use an environment, using the `pipeline_authorization` but i not able to use the id of the env, so the link is impossible.

And i must enable via UI, that isn't so good

thx so much

### New or Affected Resource(s)

* data.azuredevops_environment

### Potential Terraform Configuration

```hcl
data.azuredevops_environment.resource_id
```

### References

* #0000

**Comment by xuzhang3** [comment]
@diegolagospagopa `data. azuredevops_environment.id` is the resource ID, you can use this ID to do the authorization.

**Comment by diegolagospagopa** [comment]
Hi,

this is the code snippet

```hcl
data.azuredevops_environment.dev_env.id
``` 


```hcl 
+ resource "azuredevops_pipeline_authorization" "service_connection_ids_authorization" {
      + id          = (known after apply)
      + pipeline_id = 1687
      + project_id  = "1dae636d-3310-4108-8a85-2a2a9007ed1e"
      + resource_id = "80"
      + type        = "endpoint"
    }
```

and this is the error

```hcl
 Error:  creating authorized resource: Invalid resource id. Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
Parameter name: resource.Id
   with module.idpay-mock_code_review[0].azuredevops_pipeline_authorization.service_connection_ids_authorization[2],
   on .terraform/modules/idpay-mock_code_review/azuredevops_build_definition_code_review/main.tf line 110, in resource "azuredevops_pipeline_authorization" "service_connection_ids_authorization":
  110: resource "azuredevops_pipeline_authorization" "service_connection_ids_authorization" {

```

so i can't use this info

**Comment by xuzhang3** [comment]
@diegolagospagopa  the auth `type` is `environment` not `endpoint`, `endpoint` ID is in UUID type while `environment` is simple integer
