### ISSUE TITLE
failed to respond to the plugin.(*GRPCProvider).ReadResource call

### ISSUE THREAD

**Issue by stevanovic-milan** [microsoft/terraform-provider-azuredevops#969]
Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azuredevops_project.project,
│   on project.tf line 1, in resource "azuredevops_project" "project":
│    1: resource "azuredevops_project" "project" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azuredevops_v0.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1045b92]

goroutine 100 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.resourceServiceEndpointAzureCRRead(0x0?, {0x10fa9e0?, 0xc00053d760})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurecr.go:127 +0xb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x13fe5c0?, {0x13fe5c0?, 0xc0007b0a80?}, 0xd?, {0x10fa9e0?, 0xc00053d760?})        
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003fb340, {0x13fe5c0, 0xc0007b0a80}, 0xc0004469c0, {0x10fa9e0, 0xc00053d760})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003c6660, {0x13fe5c0?, 0xc0007b0960?}, 0xc000212500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003790e0, {0x13fe5c0?, 0xc0007b0360?}, 0xc00060e180)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x125f3e0?, 0xc0003790e0}, {0x13fe5c0, 0xc0007b0360}, 0xc0002ba000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x14012c0, 0xc00029e1a0}, 0xc0007c6120, 0xc000442330, 0x193f8d0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x14012c0, 0xc00029e1a0}, 0xc0007c6120, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v0.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

NOTE: The issue is also present on provider version 0.10.

**Comment by xuzhang3** [comment]
@stevanovic-milan  can

**Comment by stevanovic-milan** [comment]
Hey @xuzhang3  I see that you merged this issue with an azuredevops_serviceendpoint_azurecr issue, while the error I got seems to be related to the azuredevops_project resource:

│ Error: Plugin did not respond
│
│ with azuredevops_project.project,

Am I looking at the right thing here?

**Comment by xuzhang3** [comment]
@stevanovic-milancan you share the error details?
