### ISSUE TITLE
Can the provider be used without a PAT token now? 

### ISSUE THREAD

**Issue by jblaaa-codes** [microsoft/terraform-provider-azuredevops#975]
I see in the provider.go file that these parameters I think are available but there isn't an example indicating how to use them.

https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/provider.go

`
func Provider() *schema.Provider {
	servicePrincipalAuthFields := []string{"use_msi", "use_oidc", "client_certificate_path", "client_certificate", "client_secret", "client_secret_path"}
	allAuthFields := append([]string{"personal_access_token"}, servicePrincipalAuthFields...)

`

Is there any documentation on how to setup a Terraform Cloud Agent to authenticate to AzureDevops without a PAT token?

**Comment by mathewpeterson** [comment]
I believe this feature will be included in the next release.

**Comment by xuzhang3** [comment]
@jblaaa-codes  this feature will be available in the next release

**Comment by xuzhang3** [comment]
v1.0.1 support auth with SPN/ identity etc. ### 
More details: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/guides/authenticating_service_principal_using_a_client_secret
