### ISSUE TITLE
Service Connection creation succeeds but cannot be "read" afterwards from a different pipeline

### ISSUE THREAD

**Issue by achilles-portarinos** [microsoft/terraform-provider-azuredevops#985]
I am using this code snippez to create a service connection in Azure devops:

````
# create the service connection
resource "azuredevops_serviceendpoint_azurerm" "connection" {
  for_each = data.azuredevops_project.projects

  project_id                             = each.value.id
  service_endpoint_name                  = "'${each.value.name}' service connection to - '${data.azurerm_resource_group.resource_group.name}'"
  description                            = "Service Connection between project '${each.value.name}' and '${data.azurerm_resource_group.resource_group.name}' - Managed by Terraform"
  service_endpoint_authentication_scheme = "WorkloadIdentityFederation"
  credentials {
    serviceprincipalid = azurerm_user_assigned_identity.identity.client_id
  }
  azurerm_spn_tenantid      = data.azurerm_subscription.current.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.current.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.current.display_name
}

````

The code works. I am using devops provider 0.10.0 and terraform v1.7.4. 

The problem is, I have 2 different execution scenarios. The local CLI and the pipeline.
Locally, I use a PAT (personal access token) with full-access to login. (AZDO_PERSONAL_ACCESS_TOKEN). Via the pipeline, I use the System.AccessToken, which does not have full-access.

The code works both in the pipeline and locally. They use the same remote state. BUT:

Dependent on where it first created the service connection, it stops working on the other end. This means:
If I apply the terraform script from my laptop, it works, but then the pipeline throws this error (seem that it cannot "read" the service connection):

````
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-azuredevops_v0.10.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1823292]

goroutine 87 [running]:
github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.resourceServiceEndpointAzureRMRead(0x0?, {0x18ce9e0?, 0xc00027c160})
        github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go:189 +0xb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1bca840?, {0x1bca840?, 0xc0003a7350?}, 0xd?, {0x18ce9e0?, 0xc00027c160?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003c0380, {0x1bca840, 0xc0003a7350}, 0xc00010a9c0, {0x18ce9e0, 0xc00027c160})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00028b338, {0x1bca840?, 0xc0003a7230?}, 0xc000220040)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00034eaa0, {0x1bca840?, 0xc000150d80?}, 0xc000502240)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1a309c0?, 0xc00034eaa0}, {0x1bca840, 0xc000150d80}, 0xc000224070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00039a000, {0x1bcd5c0, 0xc0003d7ba0}, 0xc00037e6c0, 0xc00040e060, 0x210aa10, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc00039a000, {0x1bcd5c0, 0xc0003d7ba0}, 0xc00037e6c0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-azuredevops_v0.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

`````
On the same environment (CLI for example), the script still works, and the service connection is "read" normally.

I then need to use the same execution environment to destroy the service connection, cannot do that from the other environment (pipeline).

And if I first execute the terraform script via the pipeline (setting the System.AccessToken as AZDO PAT), it works but then the local execution throws the error above.

Expected behaviour:
Both the pipeline and the local deployment can work independently, since they share a common terraform state file.

 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_0.10.0`

**Comment by achilles-portarinos** [comment]
I managed to figure this out.

The problem was not the PAT, but the "Project Collection Build Service (organisation)" not being set as an admin in the project. Setting that fixed the pipeline access problems that I faced. 
 
The "Project Collection Build Service (organisation)" is the "[Job Access Token"-identity](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/guides/authenticating_using_the_personal_access_token) that terraform uses internally within the pipeline (by using the System.AccessToken to set the AZDO_PERSONAL_ACCESS_TOKEN variable.

**Comment by xuzhang3** [comment]
@achilles-portarinos `System.AccessToken` permission is managed by the ADO service.
More details:  https://github.com/microsoft/terraform-provider-azuredevops/blob/main/website/docs/guides/authenticating_using_the_personal_access_token.html.md#azure-devops-provider-authenticating-using-the-personal-access-token
