### ISSUE TITLE
cant change timeout for existing azuredevops_check_approval

### ISSUE THREAD

**Issue by drdamour** [microsoft/terraform-provider-azuredevops#995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.7.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.37.2
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/microsoft/azuredevops v0.11.0

### Affected Resource(s)

* `azuredevops_check_approval`

### Terraform Configuration Files

```hcl
resource "azuredevops_check_approval" "require_iac_mergers_approval_for" {
  project_id           = azuredevops_project.ex.id
  target_resource_id   = exid
  target_resource_type = "environment"

  requester_can_approve = true
  approvers = [
    azuredevops_group.example.origin_id,
  ]

  instructions = "Check the 'Plan Summary' task of the 'plan' job to ensure changes are expected and valid.  Approving will apply the respective plan!"

  # this is in minutes, IaC plans go stale fast so we timeout in a day, but we may find even smaller windows is better
  timeout = 60 * 24
}
```

### Actual Behavior
value that was set to 30 days 43200 changed to 1440

got an error:
Error: Specified argument was out of the range of valid values.
│ Parameter name: Version
│
│   with azuredevops_check_approval.require_iac_mergers_approval_for["az-abp01"],
│   on app-infra-cloud.tf line 26, in resource "azuredevops_check_approval" "require_iac_mergers_approval_for":
│   26: resource "azuredevops_check_approval" "require_iac_mergers_approval_for" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

if i delete the check in azdo web ux and reapply it creates fine...it just seems to be the update that fails

### References

* n/a

**Comment by xuzhang3** [comment]
@drdamour   cannot reproduce this error.  From the logs this issue was brought into this provider by #977 .  The int type value should be 0 by default, so not sure what the invalid values is.
